### ISSUE TITLE
Improve consistency of API across Carbon

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1005]
This would be a breaking change

Propositions:

* Booleans are defined across the components, things like `border`, `open`, `visible` and such like are defined and prefixed with `is` or `has`
* `as` and `theme` are separated correctly and nicely named - currently they're used interchangeably for a base colour set and a `primary` and `secondary` definition (could be conflated) - suggest the colour set is simply called `colour` and the primary and secondary definitions are defined as contrast (as they seem to be used for light on dark and dark on light, vice versa) - any colouring is made consistent
* `align` is used consistently for the binary choice of left and right and `position` is used for the quaternary `top`, `bottom`, `left` and `right`
* `name`, `title`, `text` etc are checked over for consistency (for example, titles and sub-titles collectively are referred to as 'title', 'heading' and 'header' in various props - I'd suggest using 'title' across the board)
* look at `href`, `link` (as a suffix), `to` etc.
* problems with inherited properties across dialogs, for example, `onCancel` and `showCloseIcon` being used for the same purpose in two different descendants of modal.

**Comment by abramin** [comment]
Related issue https://github.com/Sage/carbon/issues/1205
