### ISSUE TITLE
How can we improve the experience of using Immutable.js?

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1016]
Immutable constantly requires us to convert this way and that and when a developer doesn't remember to do this exactly right then the errors can be hard to place.

A really good tool for this would abstract away all the conversion so the developer just used an array or object as they are used to in JS while the library does the rest.

This would speed up development and clean up the code (Immutable fills code up with a lot of cruft)

It might not need to be as complex, it seems we only ever need to get and set data in it.

I'm suggesting replacement of ImmutableJS with something that brings the same benefits with a better API (Like Enzyme replacing TestUtils), not suggesting that immutability should be removed

**Comment by andrewjtait** [comment]
Closing as we're not updating ImmutableJS. We need to recommend that developers learn how to use the library.

**Comment by toni-leigh** [comment]
For the record, I've been applying with success the use of simplifying by using arrays and also applying the pattern of stateful views (fits in with the end-point matching pattern we've been looking at recently).

ImmutableJS is here to stay though by the looks of it, I think there'd need to be a fundamental change to the way JS works to make it redundant!
