### ISSUE TITLE
Pod applies `align-title` prop to the entire Pod

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1102]
There are two related issues:

* `Pod` takes an `align-title` prop applies it's css by applying a modifier to the top level of the component and applying `text-align: center;` to it. This should either:

* Be applied on to the title in the css
* Be applied to the Pod, but still only on the content area to avoid effects of text align on layout

**Comment by SeanArmstrong** [comment]
This requires another look

**Comment by ianforster-sage** [comment]
Fixed in PR #1103
