### ISSUE TITLE
Radio Button Controlled

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#1193]
In our application the Radio Button seems to lend itself more to a uncontrolled component where you let the DOM emit the value when it changes, store that value but not pass it back down to the component. 

If you wanted to radio button to be a controlled component you would need to use the checked property however this gets a little awkward

Noisy Implementation
```
<RadioButton name='options' value='option-1' checked={ this.props.checkedValue == 'option-1' }/>
<RadioButton name='options' value='option-2' checked={ this.props.checkedValue == 'option-2' }/>
<RadioButton name='options' value='option-3' checked={ this.props.checkedValue == 'option-3' }/>
```
OR

Holding a value in the store for each and having to track all the booleans
```
<RadioButton name='options' value='option-1' checked={ this.props.option1Checked }/>
<RadioButton name='options' value='option-2' checked={ this.props.option2Checked } />
<RadioButton name='options' value='option-3' checked={ this.props.option3Checked } />
```
I propose that we introduce a RadioButton wrapper that deals with this logic simplifying the implementation for the developer
```
<RadioButtonWrapper checked={ this.props.checkedValue } >
  <RadioButton name='options' value='option-1' />
  <RadioButton name='options' value='option-2' />
  <RadioButton name='options' value='option-3' />
</RadioButtonWrapper> 
```

**Comment by abramin** [comment]
https://github.com/Sage/carbon/issues/337

**Comment by SeanArmstrong** [comment]
Perhaps this is not needed. Mostly Radio Buttons would be created within a loop which would clean the code up alot.

**Comment by ianforster-sage** [comment]
{{RadioButtonGroup}} is now a Carbon component.
