### ISSUE TITLE
Validation on componentWillReceiveProps does not pass correct data

### ISSUE THREAD

**Issue by liam-lagay-14** [Sage/carbon#1195]
The `validate` function in the Presence validator https://github.com/Sage/carbon/blob/master/src/utils/validations/presence/presence.js#L78-L90 no longer uses the `value`, and instead gets it's value from the props passed into it via the 2nd arg. This could maybe be refactored to validate using the value if that's all it needs to do (ie when there is no other props configured in the validator)

Secondly, in the validation decorator, this call https://github.com/Sage/carbon/blob/master/src/utils/decorators/input-validation/input-validation.js#L164 needs to pass `nextProps`, otherwise it sends `this.props` which is not correct, and gives us false results.

**Comment by SeanArmstrong** [comment]
The first issue has been resolved. The second issue may still be a problem where this.props. is being passed.

**Comment by ianforster-sage** [comment]
Fixed in PR #1218
