### ISSUE TITLE
Make prop types consistent across components

### ISSUE THREAD

**Issue by ianoxley** [Sage/carbon#1205]
Some components take number props as numbers, others accept them as strings.

Should we make changes to make all components consistent in how they accept number props?

(See https://github.com/Sage/carbon/pull/1194#discussion_r113456973)

**Comment by SeanArmstrong** [comment]
We can decide to make them all Strings from now on

**Comment by ianoxley** [comment]
Not sure about this.

> As your app grows, you can catch a lot of bugs with typechecking
-- from https://facebook.github.io/react/docs/typechecking-with-proptypes.html

Why would we **not** use typechecking on prop types in favour of using strings for everything?
