### ISSUE TITLE
Flux: unit or integration testing and what tools?

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1220]
In React and Flux we unit test the components, checking that props `x` render HTML `y` and that a state change re-renders HTML `z` - then we check an action calls the correct AJAX or store function and we check a store adds `foo` to `data`, etc, with each bit tested in isolation as unit tests should be.

It seems that it is also possible to test integrations, i.e. clicking on button `x` causes `y` to be sent round to the store and for re-render to `z` to occur - this for me is an integration test, testing a feature made up of a collection of units

Where is the best place to test this?

1. Just in the unit tests.
2. In the store connecting view layer, as an integration test written separately, but still with the JS framework.
3. In automation suites, such as Selenium.

Personally, I think there is value in integration tests at this level as they would provide fast iteration for developers, but I don't think these should be all mushed up with unit tests. We should be able to run units on every save, then make an integration test to check on the user interactions with a set of components.

Perhaps a different framework exists for testing this?

Thoughts?

**Comment by SeanArmstrong** [comment]
I think we can correctly assume that this is covered by automation
