### ISSUE TITLE
Use automation tags for in component unit testing

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1235]
I think when we write unit tests we should use the data tags added to Carbon for automation testing and that this should be the best practice for hooking tests into Carbon / app code.

As these things will never change and will specifically target the sorts of things we want to test it seems logical to use them. 

We see the same sort of problems as identified by automation in unit tests when the DOM selectors change for some reason - at the moment classes are recommended, but they are still somewhat volatile.

It will also provide a tidy description of the components contents and succinct tags for Enzyme.

We can also get rid of a lot of cruft from tests as the usage of these tags will replace the tests for existence.

Thoughts?

**Comment by andrewjtait** [comment]
It’s probably useful rather than using classes that are added just for testing, however I think it'll become a non-issue once we start using Jest's snapshot testing. No reason we couldn't use them until we get Jest setup properly though.

**Comment by adamgeorgeson** [comment]
Jest or not, I think this is still valid as I imagine the automation team will still want to have an element of end to end testing driven by Selenium.

**Comment by andrewjtait** [comment]
@adamgeorgeson true, I'm just cautious of littering the UI with too many tags.

**Comment by toni-leigh** [comment]
The automation team are still going to want them so if they're well thought through they'll be useful (we're both facing the same problem)

**Comment by abramin** [comment]
We'll encourage people to do this - pending further info on the impact of Jest.
