### ISSUE TITLE
Dialog Headers

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1342]
Currently we assign the dialog header using props on the dialog component:

```
<Dialog title="My Dialog">
  ...
</Dialog>
```

This is a useful quick way to add a title, however we have found that developers are continually wanting more control of the header.

We could keep this existing functionality, but if a developer does not provide a `title` prop then we could render nothing.

Instead we could pull the header code out into it's own component allowing developers to provide their own customised version:

```
<Dialog>
  <DialogHeader>
    My title
  </DialogHeader>
</Dialog>
```

We could either have a separate component for `DialogFullScreen`, or just apply contextual CSS to the heading to style it differently.

**Comment by SeanArmstrong** [comment]
I like the idea of de-coupling the header from the dialog and making it more flexible/composable

**Comment by ianoxley** [comment]
We'd need to link the heading element to the dialog element via `aria-labelledby`, and any description too if that is deemed part of `<DialogHeader>`:

```
<div role="dialog" aria-labelledby="dialog-header" aria-describedby="dialog-description">
  <header>
    <h1 id="dialog-header">Dialog header</h1>
    <p id="dialog-description">Description of what the dialog is for / allows you to do</p>
  </header>
  ...
</div>
```

**Comment by SeanArmstrong** [comment]
This should change the actual dialog so it uses the header component under the hood as default. Or we deprecate the inbuilt dialog header and make the devs implement it if they want one

**Comment by alandomiel** [comment]
I am going to start working on this as part of https://jira-sage.valiantyscloud.net/browse/SE-2333
