### ISSUE TITLE
Paginated Content Component

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1343]
There is a requirement to build a paginated `DialogFullScreen`. I suggest we build a reusable paginated component (similar to the `Carousel` component). It is important however that the inactive pages are not rendered to the DOM until required (they could be complex interfaces unlike a carousel).

Switching between pages would trigger an animation (sliding by default, but we could add additional transitions in the future).

```
<Pagination currentPage="1">
  <Page id="1">
    ...
  </Page>

  <Page id="2">
    ...
  </Page>
</Pagination>
```

In combination with the [change to the Dialog component](https://github.com/Sage/carbon/issues/1342) we could use a structure such as:

```
<DialogFullScreen>
  <Pagination currentPage="1">
    <Page id="1">
      <DialogHeader>Page One</DialogHeader>
      <PageOne />
    </Page>

    <Page id="2">
      <DialogHeader>Page One</DialogHeader>
      <PageTwo />
    </Page>
  </Pagination>
</DialogFullScreen>
```

**Comment by SeanArmstrong** [comment]
The Carousel component with some minor tweaks may satisfy the Pagination work however if it needs too much change perhaps its better being its own component.

**Comment by andrewjtait** [comment]
@SeanArmstrong Good point. As I see it will need the following tweaks:

* Ability to turn the dots off.
* Ability to turn the back/forward arrows off.
* Ability to manually control the active index, outside of the internal state.

**Comment by alandomiel** [comment]
I am going to start working on this as part of https://jira-sage.valiantyscloud.net/browse/SE-2333
