### ISSUE TITLE
Presence validator

### ISSUE THREAD

**Issue by abramin** [Sage/carbon#1346]
The presence validator had additional functionality added to check for the presence of multiple props (rather than just a value). 
This has introduced the following code https://github.com/Sage/carbon/blob/master/src/utils/validations/presence/presence.js#L87-L97 which currently is not doing anything (see discussion here https://github.com/Sage/carbon/pull/1332)
 We should fix this and consider creating a new validator for this specific use case.

**Comment by andrewjtait** [comment]
Creating a new validator would be a breaking change, so tagged this as v2.

**Comment by SeanArmstrong** [comment]
We should split the presence validator into two. The simple presence validator which is how it was originally implemented (only handling the presence of value).

The second one should be `MultiPropsValidator`/`PropsSetValidator`. This should take an array of props that should all be presence. We will also need to carry across the `requireAll` functionality.

**Comment by ianforster-sage** [comment]
Fixed in PR #1571
