### ISSUE TITLE
Mis-matched border radii on Table component

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1375]
The below close up images show this, it looks like the internal border radii are less sharp than the external ones:

![image](https://user-images.githubusercontent.com/10499070/27637009-0132c5de-5c06-11e7-8d2d-a491d66f975d.png)

![image](https://user-images.githubusercontent.com/10499070/27637001-fa2900aa-5c05-11e7-9d43-010400f5eaf9.png)

This is reproducible on the demo site, [please view here](https://carbon.sage.com/components/table)

**Comment by toni-leigh** [comment]
Looks to be fixed on the latest master version of Carbon

The live demo site still exhibits this but is on v1.1.4

**Comment by ianforster-sage** [comment]
The demo site has been retired in favour of Storybook and the Table now reflects the latest DLS design.
