### ISSUE TITLE
Mis-matched paddings on outer table cells

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1376]
When a table's contents are aligned left in the left-most column and right in the right-most column, the paddings in from table edge to data are mis-matched:

![image](https://user-images.githubusercontent.com/10499070/27637183-b341fef2-5c06-11e7-95af-1c4dd34c3be3.png)

![image](https://user-images.githubusercontent.com/10499070/27637193-c2f22764-5c06-11e7-8eb9-ca29800f78da.png)

You'll need to create a table with correctly aligned data in the right columns to reproduce this as the demo site data is all left aligned

**Comment by ianforster-sage** [comment]
The demo site has been retired in favour of Storybook and the Table now reflects the latest DLS design.
