### ISSUE TITLE
Unable to tab in full screen dialog in order to use keyboard for navigating	

### ISSUE THREAD

**Issue by msinga** [Sage/carbon#1387]
I’m testing some components `full screen dialog` is an example for drill work we have - I can’t tab or access buttons functionality via the keyboard yet escape key works to close dialogs etc
Expected behaviour
To be able to tab around the dialog in order to use the keyboard for button selection etc

**Comment by ianoxley** [comment]
See #1340 for how this works in the `Alert` component.

**Comment by andrewjtait** [comment]
I think a fix has been applied to dialogs now to resolve this (so that the dialog gets focus) need to test if this is also resolved on full screen dialogs.

**Comment by andrewjtait** [comment]
Appears that this is not fixed yet for full screen dialogs.

**Comment by ianforster-sage** [comment]
Tested in v14.11.0, Full Screen Dialog now gets focus and keyboard navigation works.
