### ISSUE TITLE
Button rendered as Link functionality is not on the demo site

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1388]
## Problem

Currently the `Button` component can be rendered as a link. This screen grab from the inspector shows this:

![image](https://user-images.githubusercontent.com/10499070/27795779-4f0d7342-5fff-11e7-8f77-f7edeba58f8f.png)

This refers to the following buttons on the demo-site:

![image](https://user-images.githubusercontent.com/10499070/27795790-5c956cb8-5fff-11e7-8c4c-2abaefbe2fab.png)

The [code here](https://github.com/Sage/carbon/blob/master/src/components/button/button.js#L99-L117  actually does the check, but it also looks like the prop type is missing too)

The readme details this, but it can't be checked easily for QA.

**Comment by andrewjtait** [comment]
Needs `href` prop type available on demo site

**Comment by ianforster-sage** [comment]
v14.11.0 Button now complies with latest DLS designs and Storybook contains all valid examples.
