### ISSUE TITLE
Table Summary Row

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1418]
The following enhancement to the Carbon `Table` component is proposed:

## Graphics

![image](https://user-images.githubusercontent.com/10499070/28319295-66108aa8-6bc5-11e7-9bc7-9164d2e7c946.png)

## Proposed Solution

* A `TableSummary` section is added as a child component of Table.
* This component is further divided into `TableSummaryRow`s.
* Summary rows are free style, anything can be added into the label `Summary Row` or the value `Data`.
* The final row will just be another `TableSummaryRow` but a prop will be provided to the `TableSummary` component that would mark it up as in the designs, with bold text and a border break-line.

## Proposed Usage Mark-up

```
<TableSummary markLastRow={ true }>
  <TableSummaryRow
    label='Summary Row'
    value='Data'
  />
  <TableSummaryRow
    label='Summary Row'
    value='Data'
  />
  <TableSummaryRow
    label='Main Summary Row'
    value='£Data'
  />
</TableSummary>
```

## Done Means

- [ ] Component and specs are written / edited.
- [ ] Definition and demo site example works and is sense checked.
- [ ] Demo site text is added to.
- [ ] Component is QA'd on the demo-site across browsers

**Comment by SeanArmstrong** [comment]
Would the separator be defined as a separate component or just a style on the TableSummaryRow

```
<TableSummary markLastRow={ true }>
  <TableSummaryRow
    label='Summary Row'
    value='Data'
  />
  <TableSummaryDivider /> (basically a styled HR)
  <TableSummaryRow
    label='Main Summary Row'
    value='£Data'
  />
</TableSummary>
```

```
<TableSummary markLastRow={ true }>
  <TableSummaryRow
    label='Summary Row'
    value='Data'
    divider={ true }
  />
  <TableSummaryRow
    label='Main Summary Row'
    value='£Data'
  />
</TableSummary>
```

**Comment by toni-leigh** [comment]
@SeanArmstrong could be useful, as it could be re-used across the set of lines

I'd leave only the bottom one bold however (though maybe, a repeating pattern could be established with a `<TableSummarySection>`

**Comment by andrewjtait** [comment]
Is this a design from UX?

**Comment by toni-leigh** [comment]
Yes @kylemayne can elaborate

**Comment by toni-leigh** [comment]
FYI, I won't let stuff get to the issue stage without being signed off by UX

**Comment by ianforster-sage** [comment]
Table now follows more recent DLS designs.
