### ISSUE TITLE
Sticky footer in Dialog doesn't align correctly in Safari

### ISSUE THREAD

**Issue by tomajwinter** [Sage/carbon#1432]
The issue is being caused by the left pixels that are calculated and inlined for the Dialog styles being applied differently to the CSS that fixes the footer. So as the `left:` value of the dialog container alters, the CSS doesn't follow.

**Comment by andrewjtait** [comment]
Issue stems from this line https://github.com/Sage/carbon/blob/master/src/components/dialog/dialog.js#L213
