### ISSUE TITLE
Remove ReactShallowRenderer from I18n

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1445]
We currently have a dependency on React Test Renderer, it looks as though we only use this on a single spec at the moment (The I18n component).

Is it worth keeping this dependency or should we refactor this test to use Enzyme instead?

They both offer shallow rendering, but it would be good to maintain a consistent approach.

**Comment by SeanArmstrong** [comment]
ReactShallowRenderer should be removed

**Comment by ianforster-sage** [comment]
Fixed in PR #1532
