### ISSUE TITLE
Escape key for a dialog on a dialog

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1448]
Currently we are building with a pattern where a full screen dialog appears and then based on the user's actions within that dialog, a second dialog can appear over the top.

This pattern is allowable from UX, but we've noticed that when we hit `esc` on the second dialog the full screen dialog is also escaped.

It looks like Carbon needs to block the escape key from affecting anything apart from the current dialog, though UX can advise on exactly how this should work

**Comment by benwilsonsage** [comment]
Sounds good - I'd agree... in a situation where a dialog is open on top of a full-screen dialog, 'Esc' should kill the single dialog 'on top', but leave the dialog below open, so the user can step back one level at a time, and not lose their context. Of course, if a full-screen dialog has no further dialog open on top of it, 'Esc' is OK to close it straight away.

**Comment by toni-leigh** [comment]
@benwilsonsage how does `esc` behave when the user might be several pages into a set of full screen dialogs, i.e. drilling down into complex data?

**Comment by SeanArmstrong** [comment]
There may be a temp solution where you can use the same flag that determines if the second dialog is open to all determine the disableEscKey prop on the first dialog. 

Another solution is that we should stopPropagation of the event and this may stop the bubbling. However i don't know which dialog would be hit first and if it is consistent

**Comment by toni-leigh** [comment]
I think also @SeanArmstrong and @benwilsonsage there is a consideration with the pattern that involves drilling down between different full screen dialogs

**Comment by ianoxley** [comment]
Given that the `Esc` key merely triggers the [calling of `this.props.onCancel`](https://github.com/Sage/carbon/blob/master/src/components/modal/modal.js#L172) isn't guarding against this more of a job for the parent component?

**Comment by SeanArmstrong** [comment]
It may be an implementation detail as the store / parent component would likely know if its children or the child dialog is open and could block the first dialog from closing.

**Comment by andrewjtait** [comment]
It could be handled by the parent component, but there may be many different dialogs (or even other elements - dropdown lists for example) that we need to guard against. I know we had a similar issue in SOP components, it may be worth checking what we did there first. If there is a solution that will work as expected then it could be useful.
