### ISSUE TITLE
Icon for Carbon Dialog close needs to be more specifically fixed in position

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1450]
## Problem

This problem is not apparent on the demo site, but given that we can't be sure which order the CSS will be compiled in a live situation we need the position defined on the dialog close to over-ride any positioning on the icon itself

### Screen-shot
![screen shot 2017-07-31 at 11 53 19](https://user-images.githubusercontent.com/10499070/28774783-f01d7442-75e6-11e7-9319-3a4fe5f0ca68.png)

### CSS Order loading differently
![screen shot 2017-07-31 at 11 54 20](https://user-images.githubusercontent.com/10499070/28774798-00ed40f4-75e7-11e7-87f0-69c5d15c67ca.png)

## Solution

Add extra specificity to the [Dialog close icon css](https://github.com/Sage/carbon/blob/master/src/components/dialog/dialog.scss#L97)

```
.carbon-dialog__close {
  &.carbon-icon {
    position: absolute;
  }
}
```

## Done means

- [ ] No problems are found in the demo site after change
- [x] Tested in the application where the problem has been observed

**Comment by andrewjtait** [comment]
Merged and released
