### ISSUE TITLE
SettingsRow doesn't look right on demo site

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1455]
Please see this image:

![image](https://user-images.githubusercontent.com/10499070/28864572-e1eb660c-7764-11e7-8a5e-fbe758468653.png)

**Comment by andrewjtait** [comment]
<img width="1077" alt="screen shot 2017-08-29 at 11 09 19" src="https://user-images.githubusercontent.com/1668080/29815998-77bac948-8caa-11e7-8249-18f60853fadb.png">

Currently looks like this, can you please clarify if this is still an issue?

**Comment by toni-leigh** [comment]
I can't see this currently on the live demo site, closing
