### ISSUE TITLE
Dropdown loses it's arrow icon

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1458]
## Problem

`z-index` on `.common-input__input--error, &:hover` is set to `1` while the drop-down icon here `.carbon-dropdown .icon-dropdown` has no `z-index` set.

![image](https://user-images.githubusercontent.com/10499070/28873560-1daddcc6-7786-11e7-94ef-c271b0caf537.png)

## Solution

#1461 

## Done means

- [x] Specs are written and component edited accordingly. N/A CSS change
- [ ] Definition and demo site example works.
- [x] Demo site text is added to. N/A

## Related Issues
https://github.com/Sage/carbon/issues/1459

**Comment by andrewjtait** [comment]
Merged and released
