### ISSUE TITLE
No validations on the demo site

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1459]
We can't trigger validations on the demo site which means validation related changes can't be QA'd.

This led to problems like this [z-index issue with drop down icons](https://github.com/Sage/carbon/issues/1458) being missed until apps use the validations.

**Comment by SeanArmstrong** [comment]
There was an attempt here however i don't believe the approach was quite right - https://github.com/Sage/carbon/pull/1423

**Comment by ianforster-sage** [comment]
The demo site has been removed in favour of Storybook.
