### ISSUE TITLE
Overflow and validations on small dialogs

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1515]
## Problem

When the Carbon Dialog is small enough _not_ to trigger any sort of fixing or internal scrollability properties applied for this purpose effect validations.

![screen shot 2017-08-31 at 10 00 59](https://user-images.githubusercontent.com/10499070/29915623-45c2b190-8e34-11e7-8cd6-e9d30fe43b13.png)

## Solution

Three potential solutions:

* A quick and easy extra prop to switch overflow on and off inside the dialog.
* Something that makes this judgement based on the size of the screen and the size of the dialog.
* A reconsideration of what CSS properties are used to position validations: `fixed` and relative to the screen position of the control might work well (with onScroll hiding them).

## Done means

- [ ] Specs are written and component edited accordingly.
- [ ] Definition and demo site example works.
- [ ] Demo site text is added to.

**Comment by andrewjtait** [comment]
A solution for this is already in development in our current sprint, which links back to this issue https://github.com/Sage/carbon/issues/328#issuecomment-323764522

**Comment by toni-leigh** [comment]
@andrewjtait what's the expected TOA / version for this?

**Comment by andrewjtait** [comment]
@toni-leigh it depends how long development takes, at the moment we're investigating the solution, but if it is viable and simple then it could be as quick as `1.6.0`. But I cannot say for certain.

**Comment by adamgeorgeson** [comment]
Has this been resolved?

**Comment by andrewjtait** [comment]
Not yet. Though progress has been made. Would expect a fix in the next couple of weeks.

**Comment by andrewjtait** [comment]
Fixed as of `v3.1.0` https://github.com/Sage/carbon/pull/1678
