### ISSUE TITLE
BigNumber helper

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1529]
`BigNumber` has an issue when it's used in conjunction with user entry fields where it can't handle when the user starts a number with a `-` (less than 0).

`-` is as valid a number character as `.` or any digit as the first char typed of a number.

As `new BigNumber(-)` is an error, this pops up in the browser and the component created appears not to work.

It would useful to provide some helper to handle this. Propose creating a `NumberHelper` and starting with this function:

```
  /**
   * @param {String} number
   * @return {Number}
   */
  processNumberEntry = (number) => {
    return parseInt(number, 10) >= 0 ? number : 0;
  }
```

**Comment by andrewjtait** [comment]
Sounds like a factory function may be useful in this case, for example:

```js
import BigNumberClass from 'bignumber.js';

const BigNumber = (n, b) => {
  n = isNaN(n) ? 0 : n;
  return new BigNumberClass(n, b);
}

export default BigNumber;
```

so in an application you can do:

```js
import BigNumber from 'carbon/lib/utils/big-number';

const n = BigNumber('-');
n.toString(); // "0"
```

**Comment by SeanArmstrong** [comment]
That or a simple helper function in Carbon. In a similar way we have our own Immutable helper

**Comment by ianforster-sage** [comment]
Decimal component is working correctly. Closing.
