### ISSUE TITLE
ActionToolbar Refactor

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#1539]
Move from
```
<ActionToolbar action={ [ array of actions ] } />
```
to
```
<ActionToolbar>
  <ActionToolbarIcon type='foo' onClick={ () => {} } />
  <ActionToolbarIcon type='bar' onClick={ () => {} } />
  <ActionToolbarIcon type='baz' onClick={ () => {} } />
</ActionToolbar>
```

This allows for more future flexibility of more ActionToolbar things

The complexity comes with knowing context of what is selected with the table

```
<ActionToolbar>
  <ActionToolbarIcon type='foo' onClick={ () => {} } />
  <ActionToolbarIcon type='bar' onClick={ () => {} } />
  <ActionToolbarIcon type='baz' onClick={ () => {} } />
  <ActionToolbarStatusBar />
  <ActionToolbarMultiActionButton />
</ActionToolbar>
```

We also want to be careful that we are not writing a ActionToolbarX for all our X components. Is there a way we could decorate some component with ActionToolbarDecorator to provide the functionality we need. Maybe not

**Comment by andrewjtait** [comment]
We have since gone with the idea of a child function:

```
<ActionToolbar>
{
  (context) => {
    return (
      <Icon onClick={} disabled={ context.disabled } />
    );
  }
}
</ActionToolbar>
```

We have implemented this for buttons and multi action buttons, but not yet for icons. We should look to refactor for this, and deprecate the `actions` prop.
