### ISSUE TITLE
Review CSS !important rules

### ISSUE THREAD

**Issue by ianoxley** [Sage/carbon#1549]
There are a few instances of `!important` being used in CSS to prevent application code accidentally overwriting certain styles.

Is this the correct approach?

**Comment by toni-leigh** [comment]
In some cases it's acceptable, namely the instances where certain styles are applied to something that we want to always be true, a good example being warning and error states. It's a good defensive practice IMO.

However, there are some I question, for example, there's [one on a DateInput width](https://github.com/Sage/carbon/blob/6415926e35a11b36fe73feadafadf4cca777a96f/src/components/date/date.scss#L165) that should be removed. I expect this will be over-ridden in apps

**Comment by ianforster-sage** [comment]
Components have now been restyled to follow the latest DLS with CSS-in-JS provided by styled-components
