### ISSUE TITLE
Add support for skeleton/placeholder/preview

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1557]
Some components could benefit from rendering some skeletal content before the component has a chance to collect information from a server, giving a user a sense that the page is loading faster.

Adding control over this via a prop is a useful idea, please see https://medium.com/dev-channel/treebo-a-react-and-preact-progressive-web-app-performance-case-study-5e4f450d5299#bee4

**Comment by DipperTheDan** [comment]
Closed due to marked as `stale` in April 2020 and no reply since.

**Comment by ianforster-sage** [comment]
FE-3276

**Comment by sjohnson-sage** [comment]
Closed due to marked as stale in April 2020 and no reply since.
