### ISSUE TITLE
Date Picker inline is not aligned correctly

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1580]
## Problem

![date-picker](https://user-images.githubusercontent.com/10499070/31223533-888cec8a-a9c2-11e7-87ad-50bd74677493.gif)

We can see that the date picker has no concept of it's parent field in different responsive states when arranged inline. There seems to be no fixed values to keep it in place

**Comment by andrewjtait** [comment]
![screen shot 2017-10-18 at 14 01 51](https://user-images.githubusercontent.com/1668080/31719910-e2cbc820-b40c-11e7-93b0-04150cb613a7.png)

fixed as of v2.2.0
