### ISSUE TITLE
Presence validator asterisk addition breaks component labels

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1583]
If an input label is provided in component form for a field with a `PresenceValidator`, perhaps if it's more complex then basic text, the addition of an asterisk to the label converts it to a string, which for anything other than a string is `Object Object`.

https://github.com/Sage/carbon/blob/master/src/utils/decorators/input-label/input-label.js#L197-L200

**Suggested fix**

1. We could convert the label contents to be a component always, by converting a string label to a component and prepending a validation marker component to that within the parent

2. I don't think retrospectively enforcing a string Proptype on `label` would be good as it would be a breaking change

I'm sending this to the label:

```
<div className='amount-label'>
  <span data-element='amount-label__label'>
    { props.label }
  </span>
  <span className='amount-label__extra'>
    { props.labelExtra }
  </span>
</div>
```

**Comment by andrewjtait** [comment]
Just for clarity, what are you sending to `label`?

**Comment by toni-leigh** [comment]
@andrewjtait updated

**Comment by ianforster-sage** [comment]
Formik & Yup will replace validators. Closing.
