### ISSUE TITLE
Icon is mis-aligned on message component

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1588]
Found in IE11 on Win7

![image](https://user-images.githubusercontent.com/10499070/31551950-ffad3286-b02d-11e7-81e2-da4487bcdc7f.png)

![image](https://user-images.githubusercontent.com/10499070/31551983-1a0d44f4-b02e-11e7-8b5c-3a43a0b21ef3.png)

This will be flex, that will need tweaking for IE11

**Comment by ianforster-sage** [comment]
Fixed in PR https://github.com/Sage/carbon/pull/1657
