### ISSUE TITLE
Allow Alert to have a Button

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1597]
UPDATE:

We're going to add two props to `Alert` which will make a button appear. The props will be the button action and the text for the button.

=======

We've hit a requirement in our app where we need a Dialog that presents information and has a single button that will do something, so we can say 'this is the case' to the user, and allow them to close (with the icon) or follow the button with an action. In some cases we might want this just to say OK which is actually the same close action as the icon, but sometimes it might be a link to another page / action.

Need to chat through with @kylemayne exactly what needs to happen UX wise, so expect this issue to update and become more clear

**Comment by andrewjtait** [comment]
Is this an issue with `Alert`? The component can receive any child components. Maybe we should instead supply an `Actions` component which knows how to arrange child buttons for dialogs and forms etc (right aligned etc), then you could have

```js
<Alert>
  My content for alert.

  <Actions>
    <Button>My Action</Button>
  </Actions>
</Alert>
```

**Comment by toni-leigh** [comment]
Not Alert per-se, just the clutch dialogesque components didn't cover our use case

**Comment by toni-leigh** [comment]
`Alert` did seem the most logical place to put it though

**Comment by toni-leigh** [comment]
I think if you did something like what you propose with an `Actions` component then you could probably get rid of all the different types of dialogs and just let users do as they please
