### ISSUE TITLE
DropdownFilter Create Hover

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1603]
When hovering over the "create" link on a `DropdownFilter` we should ensure none of the list items are highlighted.

![31943779-d28b1c92-b897-11e7-91fa-705791b045f7](https://user-images.githubusercontent.com/1668080/31944996-cbce83de-b8c5-11e7-8697-e50490e43a67.gif)

**Comment by ianforster-sage** [comment]
resolved in PR https://github.com/Sage/carbon/pull/1602
