### ISSUE TITLE
form summary translation interpolation

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1607]
Our form summary translations use JS interpolation, but should use I18n's method
https://github.com/Sage/carbon/blob/master/src/components/form/form-summary/form-summary.js#L51-L52

eg. instead of

```
value: `there are ${count} errors`
```

we should use

```
value: 'there are %{count} errors'
```

**Comment by ianforster-sage** [comment]
Form Summary has been deprecated
https://github.com/Sage/carbon/blob/master/src/__deprecated__/components/form/form-summary/form-summary.component.js
