### ISSUE TITLE
Dropdown should handle undefined

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1608]
Currently the Dropdown does not handle `undefined`, meaning if you preload a component which will be populated on some API call the user _may_ make (and therefore you don't necessarily want to do straight away) you get a console warning.

const displayedAsToName = option => option.set('name', option.get('displayed_as'));

```
const loadOptions = (options) => {
  return typeof options === 'undefined' ? ImmutableHelper.parseJSON([{}]) : options;
};
```

**Comment by ianforster-sage** [comment]
This component has been rewritten to comply with the latest DLS requirements and thoroughly retested.
