### ISSUE TITLE
Consider using HOC to connect React components to flux stores and deprecating the existing connect function

### ISSUE THREAD

**Issue by casparrolfe** [Sage/carbon#1611]
The existing `connect` function looks pretty similar to the `flux` libraries' container. This method of connecting stores to components is obtrusive and should be considered an antipattern, because it hijacks the existing component through inheritance to inject stores as part of component state.

A better method would be to use [higher order components](https://reactjs.org/docs/higher-order-components.html) to provide store state through props. This would encourage better practices around the [container/presenter](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) pattern and would encourage composability.

This could be implemented in some form similar to below (ignoring obvious required enhancements to make it usable in anger):

```javascript
import React from 'react'

const connect = (...args) => (Component) => {
  const stores = args.slice(0, args.length - 1)
  const mapToProps = args[args.length - 1]

  return class ConnectedComponent extends React.Component {
    componentDidMount() {
      stores.forEach((store) => store.addChangeListener(() => this.forceUpdate() ))
    }

    render() {
      const states = stores.map((store) => store.getState())

      return (
        <Component
          {...mapToProps(...states)}
          {...this.props}
        />
      )
    }
  }
}

export default connect
```

To be consumed similarly to below:

```javascript
test('It connects stores to props', () => {
  const UPDATE_A = 'UPDATE_A'
  const updateA = (value) => ({
    actionType: UPDATE_A,
    value
  })

  const UPDATE_B = 'UPDATE_B'
  const updateB = (value) => ({
    actionType: UPDATE_B,
    value
  })

  class TestStoreA extends Store {
    [UPDATE_A]({ value }) {
      this.data = value
    }
  }

  class TestStoreB extends Store {
    [UPDATE_B]({ value }) {
      this.data = value
    }
  }

  const testStoreA = new TestStoreA('A', 1)
  const testStoreB = new TestStoreB('B', 2)

  function Presenter({ one, two }) {
    return (
      <ul>
        <li>{one}</li>
        <li>{two}</li>
      </ul>
    )
  }

  const ConnectedComponent = connect(
    testStoreA,
    testStoreB,
    (testStateA, testStateB) => ({
      one: testStateA,
      two: testStateB
    })
  )(Presenter)

  const $ = mount(<ConnectedComponent />)
  expect($.find(Presenter).props()).toEqual({ one: 1, two: 2 })

  Dispatcher.dispatch(updateA(42))
  expect($.find(Presenter).props()).toEqual({ one: 42, two: 2 })

  Dispatcher.dispatch(updateB(44))
  expect($.find(Presenter).props()).toEqual({ one: 42, two: 44 })
})
```

**Comment by andrewjtait** [comment]
👍  we have long term plans to convert this to use a higher order component, as well as the the rest of the decorators in https://github.com/Sage/carbon/tree/master/src/utils/decorators as well as a few components which are currently using inheritance such as `Dialog`, `DropdownFilter` and `TableAjax`.

Thanks for raising the issue, I'll make sure to add issues for the others as well so they're visibly logged.

**Comment by andrewjtait** [comment]
✅  https://github.com/Sage/carbon/pull/1615
