### ISSUE TITLE
Cli install gives error .npm/_cacache/tmp/git-clone-d39c741f/.git: Permission denied

### ISSUE THREAD

**Issue by banstola** [Sage/carbon#1649]
I have been following the `getting started` document and been getting the following error.
`.npm/_cacache/tmp/git-clone-d39c741f/.git: Permission denied` 

Comman I ran : `sudo npm install -g sage/carbon-factory`

**Comment by andrewjtait** [comment]
Thanks @banstola - looks like our documentation is out of date here.

Instead could you try `npm install -g carbon-factory` (without the `sage/` prefix).

To be honest the CLI is a little out of date and may not work fully, all it does is provide a scaffold for a React project. You can download a zip of the [same scaffold here](https://github.com/Sage/carbon-factory/raw/master/docs/carbon-app.zip).
