### ISSUE TITLE
Dropdown lists should allow the options to be wider than the dropdown

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1653]
This is how it currently is:

![screen shot 2017-12-20 at 12 04 42](https://user-images.githubusercontent.com/10499070/34206347-175fe01a-e57e-11e7-9d2d-9309aa07de71.png)

This, however, would be nice:

![image](https://user-images.githubusercontent.com/10499070/34206381-3d66b7c0-e57e-11e7-91e7-074783484a29.png)

(Note the above was achieved with fixed width hacking in the browser console

**Comment by ianforster-sage** [comment]
This component has now been restyled to follow the latest DLS.
