### ISSUE TITLE
XSS Validation Support on Inputs by Default

### ISSUE THREAD

**Issue by halezmo** [Sage/carbon#1664]
We should have XSS character validation and show an input error **invalid_chars**  when there are invalid characters in input.

Not sure if it should be default validations for text inputs or maybe we can create new validator for this which can be added to inputs where its required

**Comment by andrewjtait** [comment]
It would probably be most useful for us to have this validator enabled by default, much like how `Date` has a date validator on by default. If so, then you should be able to disable it on specific inputs if you need to.

Alternatively we could maybe set up a static method on the validation class, that can enable an application to apply some configuration of default validators across all instances of the class.

**Comment by ianoxley** [comment]
Nice idea, but it sounds a bit like blacklist filtering. [Whitelist filtering is often the better approach](https://www.owasp.org/index.php/Input_Validation_Cheat_Sheet#Whitelisting_vs_blacklisting), which should already be possible using the existing validators e.g. [RegexValidator](https://github.com/Sage/carbon/blob/master/src/utils/validations/regex/regex.js), [NumeralValidator](https://github.com/Sage/carbon/blob/master/src/utils/validations/numeral/numeral.js)

Unless there's something missing from the existing validators?

**Comment by ianforster-sage** [comment]
Carbon's form and validation functionality will be replaced with Formik 2.0.
https://github.com/Sage/carbon/blob/master/rfcs/text/formik.md
Our recommendation is to use Yup to validate your inputs.
