### ISSUE TITLE
DropdownFilterAjax query params are not suitable for all endpoints

### ISSUE THREAD

**Issue by adamgeorgeson** [Sage/carbon#1666]
Currently the DropdownFilterAjax query params for `rows`, `page` and `value` are not suitable unless the endpoint being used supports those query params. It is possible that a developer would like to use an existing endpoint which have their own versions of these query params but named differently.

For example, the Sage One API uses `items_per_page`, `page` and `search`.

https://github.com/Sage/carbon/blob/v3.0.0-rc1/src/components/dropdown-filter-ajax/dropdown-filter-ajax.js#L217-L221

Would it be suitable to have these as defaults, overwritten by props?

**Comment by abramin** [comment]
It is possible to send additional params 
https://github.com/Sage/carbon/blob/v3.0.0-rc1/src/components/dropdown-filter-ajax/dropdown-filter-ajax.js#L108

Would that solve problem? Or would your appoint not appreciate the extraneous params it wasn't using?

**Comment by adamgeorgeson** [comment]
Yeah I think that will be fine now I've had another look.

I hadn't looked too hard but figured the rest of the component behaviour would rely on the props used in those query params. I guess in the use case I suggested above, would have to send multiple params for the same thing. For example, `items_per_page` as an additional param as part of `this.props.additionalRequestParams`, as well as the prop for `rowsPerRequest` for usage [here](https://github.com/Sage/carbon/blob/v3.0.0-rc1/src/components/dropdown-filter-ajax/dropdown-filter-ajax.js#L254).

The endpoints that made me question this though are fine with sending `rows` and `value`, they'll just be ignored.
