### ISSUE TITLE
Render HTML code in the Flash component.

### ISSUE THREAD

**Issue by darioajmu** [Sage/carbon#1668]
At this time, it is not possible to render HTML in the Flash component.

If you go to https://carbon.sage.com/components/flash and put 'This is some information from the Flash Component. \<a href="foo">bar</a>\' as message, the flash returns something like this:

![image](https://user-images.githubusercontent.com/15021125/34940602-6583fd04-f9f0-11e7-8f68-aed5a1e65fa0.png)

For example, it would be perfect if we could add a link to some error explanation in the same message.

**Comment by ianforster-sage** [comment]
FE-1789

**Comment by sjohnson-sage** [comment]
Closing because the Flash component was removed from Carbon v50.0.0
