### ISSUE TITLE
min-width causes horizontal scroll bar in IE

### ISSUE THREAD

**Issue by melaniesmith29** [Sage/carbon#1704]
We have noticed a horizontal scroll bar appear when using IE11/Microsoft edge. This is caused by a min-width being set on `.carbon-app-wrapper` on this line: https://github.com/Sage/carbon/blob/624b6da159a1ebc3223f34cace7ece12d1fee8fd/src/components/app-wrapper/app-wrapper.scss#L5

To fix this we should make the min-width a configurable property. 
The following example would prevent it being applied to any widths below the min app width:
The suggested approach would be:
```
@media (min-width: $app-width) {
  min-width: $app-width;
}
```

**Comment by toni-leigh** [comment]
Note, the suggested approach is just a way of making sure the scroll bar doesn't happen, rather than the configurability, however, it might be a good thing to add also

**Comment by ianforster-sage** [comment]
Edge legacy is no longer available. Checked in Edge(Chromium) in Carbon v35.1.1. There are no longer scroll bars in Edge browser. It behaves much the same as Chrome now. Issue resolved.
