### ISSUE TITLE
Add non-editable state to ShowEditPod

### ISSUE THREAD

**Issue by patrickmelvin** [Sage/carbon#1719]
We have a requirement in several places in our app to make a Show Edit Pod uneditable conditionally. In this case we do not want to display the edit button or be able to open the edit state of the Pod. 

This can be accomplished by displaying a Pod or Show Edit Pod conditionally, but it would be useful to have an attribute to remove the edit button. In this case, the Show Edit Pod would resemble a regular Pod.

<img width="133" alt="screen shot 2018-04-11 at 10 14 42" src="https://user-images.githubusercontent.com/8832592/38605021-6efbf7a4-3d72-11e8-85b9-e6a2d9a0e5b6.png">

<img width="100" alt="screen shot 2018-04-11 at 10 17 53" src="https://user-images.githubusercontent.com/8832592/38605029-726bda1c-3d72-11e8-843c-75d1b1ec5868.png">

**Comment by toni-leigh** [comment]
We really need to reconfigure components like Pod to be more composable as they're already complicated with Boolean props and conditionals. I think this is the last thing we need, to add a prop to the editable prop to make it uneditable, we really ought to think of `Pod 2.0` or some such with a more modern, componentised approach

**Comment by toni-leigh** [comment]
What about doing something like this:

```
props = { ... }

shouldBeEditable ? <EditPod { ...props } /> : <Pod { ...props } />
```

**Comment by patrickmelvin** [comment]
It's an option. I just wanted to suggest this because as it is I'm going to be implementing that in 7+ places.

**Comment by patrickmelvin** [comment]
Closing this issue down following discussions. This is not something that we want to do.
