### ISSUE TITLE
Padding is wrong when ondismiss is not provided to message

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1751]
We see `50px` of padding on the right of the message when there's no `onDismiss` prop provided which means wide content is mis-padded on the right.

Here we see a button to the right of the message content which is out of line due to the extra space provided for the close button which doesn't exist.

![image](https://user-images.githubusercontent.com/10499070/40362476-8d33748c-5dc4-11e8-8ea6-939b105b3d5f.png)

**Comment by ianforster-sage** [comment]
Will revisit once styled components are implemented

**Comment by ianforster-sage** [comment]
Tested in v16.7.0. Closing
