### ISSUE TITLE
Button as a Link accessibility

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1756]
`<Button href="/">My Link</Button>` will look like a button but render an `<a>` tag.

This pen demonstrates how the interactions are different:

https://codepen.io/tonileigh303/pen/LrVbmK

A link doesn't respond to a space bar so using it as the tag under something that looks like a button is an accessibility issue.

There's also some further stuff about how links should navigate and buttons should cause events, so some UX input here might be good to make sure we're not facilitating unexpected accessibility issues with our design.

**Comment by andrewjtait** [comment]
Accessibility wise though, does it necessarily matter what it looks like? For screen readers or other things that parse the HTML it will recognise it for it is, not what it looks like.

Also as we move to more dialog based UI, or "single page app" style, we will have less page navigation from clicking buttons and they will trigger events instead. Having the `Button` seamlessly transition from an anchor to a button but still looking the same could help us by not providing an unfamiliar interface when it changes, but providing the correct accessibility when it changes.

**Comment by toni-leigh** [comment]
I think it matters for keyboard users, who could assume that the thing that looks like a button will respond to the same keypresses as the other thing that looks like a button (this was raised at FENE conference as part of a general 'think about your HTML' message).

A solution would probably be to make anything that looks like a button respond to the `space` bar like a `<button>`

**Comment by andrewjtait** [comment]
> A solution would probably be to make anything that looks like a button respond to the space bar like a <button>

👍 

From [MDN's docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role#Keyboard_and_focus)

> Warning: Be careful when marking up links with the button role. Buttons are expected to be triggered using the Space or Enter key, while links are expected to be triggered using the Enter key. In other words, when links are used to behave like buttons, adding role="button" alone is not sufficient. It will also be necessary to add a key event handler that listens for the Space key in order to be consistent with native buttons.

**Comment by DipperTheDan** [comment]
FE-1788

**Comment by DipperTheDan** [comment]
@tempertemper - Just tagging you in this issue as it is in relation to accessibility. Have you got anything to add to this issue? As the issue from 2018 and the solution was also suggested in 2018, the world of accessibility may well have moved on. Your input would be greatly appreciated so we can get the best solution possible.

Thanks 😄

**Comment by sjohnson-sage** [comment]
@DipperTheDan @tempertemper FYI we actually have an open PR to remove the `href` prop from `Button` entirely so this issue will soon no longer be valid

**Comment by tempertemper** [comment]
Cheers @sjohnson-sage. Does that mean we won't be able to have buttons that look like links or links that look like buttons? They can be handy sometimes, but there's all that extra stuff mentioned earlier in the thread to consider. A link that looks like a button should:

- be given a `role="button"` so that speech recognition users can refer to it as a button (since they *see* a button)
- have some JavaScript to stop `space` scrolling the page down, and trigger the button/link instead
- have the `draggable="false"` attribute, to behave more like a button (you can drag links to your browser's tab bar to open the link in a new tab, for example)

So, assuming the `href` changes a `<button>` into an `<a>`, the `href` prop could stay on the `Button` as long as all that extra stuff is activated when the `<button>` becomes an `<a>`.

**Comment by sjohnson-sage** [comment]
Thanks @tempertemper, you've made us realise the error of our ways and we're going to leave the `href` prop on `Button` now and have it behave as you have described, I'll ask you to review it for us once the work is done if you don't mind!

**Comment by tempertemper** [comment]
All sounds good. Happy to review the component once done, or at any point along the line if you like, @sjohnson-sage 👍
