### ISSUE TITLE
Info prop not working for DateInput component.

### ISSUE THREAD

**Issue by adrianpastur** [Sage/carbon#1778]
**Issue:**

`info` prop not working on `DateInput` component.

![screen shot 2018-07-05 at 10 02 10](https://user-images.githubusercontent.com/32830770/42323456-2728df40-8058-11e8-8708-7a253b2847be.png)

PR Raised: https://github.com/Sage/carbon/pull/1779

**Comment by SeanArmstrong** [comment]
Fixed 🎉
