### ISSUE TITLE
Poller needs to have a callback for when it terminates after max retries

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1791]
We need to provide a callback for the user rather than the current `console.log`

If the Poller runs out of retries as defined by the time or poll count limits we need to provide the user with a callback so they can execute specific functionality for their app, for example, hiding a spinner and popping a message to say 'ran out of tries'

**Comment by toni-leigh** [comment]
https://github.com/Sage/carbon/pull/1792
