### ISSUE TITLE
Object titles for dialog break in Full Screen mode

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#1799]
If I use an image (object) in the Full Screen Dialog title prop (my logo, for example) the layout breaks

![image](https://user-images.githubusercontent.com/10499070/43204077-e9c2b7dc-9017-11e8-8c3a-2ad25e45f894.png)

This is because of [this line](https://github.com/Sage/carbon/blob/master/src/components/dialog/dialog.js#L271) that stops the `Heading` component being used unless it's a string which in turn stops the flex from being applied and the set height.

I suggest we remove this line.

**Comment by sianford** [comment]
Confirmed with UX, there are no designs that require this functionality of this component. Closing this issue.
