### ISSUE TITLE
DropdownFilter / DropdownFilterAjax allow use a class name in "No result" and "Create Item"

### ISSUE THREAD

**Issue by marianomms** [Sage/carbon#1802]
Currently is not possible customize the "No Result" and "Create Item" in DropdownFilter and DropdownFilter Ajax. Because the dropdown items are added in a `Portal` outside the dropdown hierarchy.

![image](https://user-images.githubusercontent.com/6368004/43508316-dfbe4adc-956f-11e8-90ac-4c3bb682005c.png)

![image](https://user-images.githubusercontent.com/6368004/43508583-a1cb2000-9570-11e8-9c06-ab2117961c23.png)

Possible solution:
Currently only one className is added in the created `Portal` for the list ([see](https://github.com/Sage/carbon/blob/master/src/components/dropdown/dropdown.js#L558)), we could add the dropdown `className` prop  in the `Portal`created for the list.

**Comment by ianforster-sage** [comment]
These components are now deprecated, however `createText` is an available prop in the latest version.
