### ISSUE TITLE
Convert icons to use JSX SVG and add alt text

### ISSUE THREAD

**Issue by ianoxley** [Sage/carbon#1805]
Most of the icons in Carbon were created before JSX supported SVG.

Now that JSX does support SVG we should convert our SVG icons to functional components and use JSX to render the SVG. This would also mean we can stop using `dangerouslySetInnerHTML` when rendering icons.

Using functional components would mean we can also pass props to set alternative text for the SVG icons e.g. using the `<title>` tag, where appropriate.

**Comment by sjohnson-sage** [comment]
Closing as no longer a valid issue
