### ISSUE TITLE
Unable to submit Form via <Enter> key when using leftAlignedActions

### ISSUE THREAD

**Issue by ianoxley** [Sage/carbon#1813]
Given the following code:

``` js
const deleteButton = () => (
  <Button
    onClick={ (e) => {
      e.preventDefault(); 
      console.log('deleted');
    }}
  >
    Delete
  </Button>
);

const MyExample = () => (
  <AppWrapper>
    <Form
      leftAlignedActions={ deleteButton() }
      cancel={ false }
      onSubmit={ (e) => {
        e.preventDefault();
        console.log('submitted');
      }}
    >
      <Textbox
        label='Name'
      />
    </Form>
  </AppWrapper>
);

ReactDOM.render(<MyExample />, document.getElementById('app'));
```
Codepen: https://codepen.io/anon/pen/djQwJJ

If you try and submit the form using the `<Enter>` key the `Delete` button is triggered before the `Save` button, as the `Delete` button comes first in the HTML.

**Comment by toni-leigh** [comment]
Following on from the Slack discussion:

I wouldn’t convert it to a link that looks like a button just so it won’t behave like a button (accessibility fail)

Selecting the first child of a form and assuming it’s the submit button is brittle code that should be fixed anyway, so that’s the solution

**Comment by andrewjtait** [comment]
> Selecting the first child of a form and assuming it’s the submit button is brittle code that should be fixed anyway, so that’s the solution

To be clear, we don't do that - it is how browsers behave. However you can set a `type` on the button to `button` (by default it seems to assume it is of type `submit`), and this should resolve the issue.
