### ISSUE TITLE
Automatic tooltip position when off screen

### ISSUE THREAD

**Issue by yngndrw-sage** [Sage/carbon#1814]
Currently the requested tooltip position is always respected, even if that results in the tooltip going partially off screen. This might change depending on the size of the window.

If would be nice if there was an option for the tooltip to be displayed in the opposite direction if it would go off screen.

**Comment by ianforster-sage** [comment]
This issue has been closed because it has not had recent activity. If you believe this issue is still valid and required please resubmit it as an RFC. Thank you for your contributions.
