### ISSUE TITLE
Inconsistencies in form field event objects

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#1831]
While developing with `DropDown` I've noticed that the event provided from the `onChange` doesn't include a name property.

This is awkward as we sometimes need to use that property to identify the field.

For example, we had two drop-downs that both used the same data storage functions, keying the result by the name of the field.

This resulted in us having to do the following to ensure the name got through:

```
onChange = (name) => (ev) => {
  Actions.store(ev, name);
}

...

<Dropdown onChange={ this.onChange('field-name') } />
```

Then, we had to write tests with added complexity to cover this!

I'd suggest that the form fields all deliver a consistent set of of values to the Actions and that `name` should be one of those values.

**Comment by andrewjtait** [comment]
@toni-leigh all input `onChange` events do pass through `props` as a 2nd argument, can you not attain `name` from that?

I'm confused by your example though as it shows a `Button` and an `onClick` event?

**Comment by toni-leigh** [comment]
It should be a drop-down on change

**Comment by andrewjtait** [comment]
You should be able to do this with

```
onChange = (ev, props) => {
  Actions.store(ev, props.name);
}

...

<Dropdown name='field-name' onChange={ this.onChange } />
```
