### ISSUE TITLE
Webpack not recompiling Sass files when changed

### ISSUE THREAD

**Issue by ianoxley** [Sage/carbon#1832]
Steps to reproduce:

1. Run `npm start`
2. Edit any `.scss` file e.g. `menu-item.scss`

Expected results:
The change to the Sass file causes webpack to recompile

Actual results:
Nothing is recompiled.

It looks like the fix is to require / import the relevant Sass file(s) in the components that use them:

``` js
// For example
import './menu-item.scss';
```

**Comment by andrewjtait** [comment]
Tried this locally myself and it appears to be working. Is there something else causing the issue?
