### ISSUE TITLE
Error Icon is displaced for TextArea

### ISSUE THREAD

**Issue by florianpilz** [Sage/carbon#1856]
In Carbon 5.2.0 when using a `textarea` combined with a validation, the error icon will overlap the text area. This is due to custom CSS for `textarea` which sets `margin-top: 9px` 

https://github.com/Sage/carbon/blob/d6512b1a4d57bf893f8c345f2311a3051802d905/src/components/textarea/textarea.scss#L5-L8

However the error icon is positioned absolutely from `top: 28px`, which is missing the extra `9px` for `textarea`

https://github.com/Sage/carbon/blob/d6512b1a4d57bf893f8c345f2311a3051802d905/src/utils/decorators/input/input.scss#L172-L182

That's how a displaced error icon looks like on `textarea`

![screen shot 2018-10-25 at 13 20 57](https://user-images.githubusercontent.com/518288/47496984-da8a0480-d858-11e8-8c42-2af2c03c2f20.png)

For a simple `input` it looks good

![screen shot 2018-10-25 at 13 21 03](https://user-images.githubusercontent.com/518288/47497006-e70e5d00-d858-11e8-84f5-aad8a17ef643.png)

Probably a simple addition to [textarea.css](https://github.com/Sage/carbon/blob/master/src/components/textarea/textarea.scss) is enough:
```
.carbon-textarea .carbon-icon.common-input__icon {
  top: 37px;
}
```

**Comment by ianforster-sage** [comment]
The PR #2259 has been closed as we have deleted `release` branch. If you believe this issue is still valid and required please comment below. It will be reviewed by the core Carbon team and may be closed if no further activity occurs.
