### ISSUE TITLE
DLS & CSS Modules

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1862]
To support [the DLS](https://carbon.sage.com/news/sage-design-system) we are considering removing all CSS from carbon-react, and instead have an external dependency manage the CSS.

This external resource, which may use Sass or PostCSS, will be precompiled and served as plain CSS files.

In Carbon we could consume these files as CSS Modules, this will allow us to define a light contract with the dependency, with an expectation of what classes are available (we could snapshot the object of classes returned). If these classes change our build will fail requiring an action to resolve it.

CSS Modules will also obfuscate the classes that are rendered to the DOM, preventing developers from overriding CSS on components which at the moment we can only discourage.

Having the CSS as an external dependency will separate concerns between the DLS and component implementation, while also allowing different tech stacks to share the same DLS code. Internally we can move away from Sass completely and instead use something like styled-components for a fully featured and scoped styling framework.

Alternatively we could fully embrace something like styled-components in Carbon - but this will not support re-use outside of Carbon.

**Comment by ianforster-sage** [comment]
Will be implemented when we cut-over to styled components.
