### ISSUE TITLE
Validations Refactor

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1864]
* To support async validators
* To be less restrictive
* To allow manual control of valid state

### Validator

A function which receives an array of validations and returns a `validate` function which can be executed with a given value. This value will be validated against the array of validations and return a boolean.

```js
const validate = validator([ presence, maxLength(10) ]);
const valid = validate('my value');
```

Supplying this separately enables developers to use it in other contexts, if they want to run validations themselves at any point.

### ValidateComponent

A higher order component to wrap components that you want to support validations.

```js
const Textbox = props => {
  const {
    error,  // string - the error message
    warning, // string - the warning message
    info,  // string - the info message
    validate // function - to trigger validations
  } = props;
  ...
};

export default ValidateComponent(Textbox);
```

```js
<Textbox validations={[ presence, maxLength(10) ]} />
```

It provides the props `error`, `warning`, `info` and `validate` to the child component. It also understands if the parent receives these props as well:

```js
<Textbox error='My error message' />
```

The higher order component will also provide the contextual connection to the `Form` component, which will know to validate any connected components on submit.

Depending on how error icons etc are rendered, we may also supply an `Input` or `InputIcons` component which knows what to do with the given props.

Generally the `validate` function would be triggered `onBlur` of the input, but this is not always the case. `select`, `radio` or `checkbox` may want to trigger validations `onChange`. So instead of setting this listener up automatically, we can allow developers to wire it up how they want by just supplying the callback from the higher order component.

### A Validation

Instead of being a class, validations are now promises.

```js
const presence = value => new Promise((resolve, reject) => {
  if (value) {
    resolve();
  } else {
    reject('This field is required.');
  }
});
```

This allows you to perform async actions from within the validation. The `Validator` will resolve the promises it is given.

If you need to pass config to your validator, such as with the `maxLength` example above, you can curry your validation:

```js
const maxLength = length => value => new Promise((resolve, reject) => {
  if (value.length <= length) {
    resolve();
  } else {
    reject(`This value can be no longer than ${length}.`);
  }
});
```

**Comment by andrewjtait** [comment]
A couple of additional considerations:

* How will the `Form` know about any manual validations? If a developer chooses to use a prop to control the valid state of a component, how can we check that validation when a form is submitted?
* Can we support validation linking? If we have an input whose validation depends on the value of another input, can we support that some how? For example a date range will have 2 inputs, but they must be in the order of min and max.

**Comment by andrewjtait** [comment]
Maybe we should not support `error` etc as prop, but instead require developers to create custom validations using the value from other inputs if they need to:

```js
const myValidator = myVal => value => new Promise((resolve, reject) => {
  if (myVal !== value) {
    resolve();
  } else {
    reject('Values cannot be the same');
  }
});

<Textbox value={ state.myVal } />
<Textbox value='other value' validations={[ myValidator(state.myVal) ]} />
```

What might be useful here though is being able to trigger validations on the 2nd input on blur of the 1st input.

Maybe a watch property would be useful:

```js
<Textbox
  value='other value'
  validations={[ myValidator(state.myVal) ]}
  revalidateOn={ state.myVal }
/>
```

This could trigger the validate procedure whenever this prop changes, there is the danger here though that this triggers for every key press on textboxes. It would work best with radio or select dropdowns.

**Comment by andrewjtait** [comment]
Also need to consider, from a functional perspective, how to abort async validations if new events are triggered.

**Comment by andrewjtait** [comment]
Taking inspiration from Formik we could optionally pass callbacks in via a render function, enabling developers to set up additional listeners if they want.

For example:

```
<Form>
  {
    (validateForm, validateField, errorCount) => (
      ...
    )
  }
</Form>
```

`validateField` could look up the field you want to validate by name, as long as you assign a name to the component.

For example:

```
<Textbox name='email_address' />
<Button onClick={ () => validateField('email_address') } />
```

**Comment by ianforster-sage** [comment]
Tagged `triage` so we can review but I expect to close this in favour of Formik/Yup

**Comment by ianforster-sage** [comment]
Validations will soon be handled by Formik. Closing.
