### ISSUE TITLE
Carbon tab lacks clearfix

### ISSUE THREAD

**Issue by mfolker-sage** [Sage/carbon#1889]
The carbon tab lacks a "Clearfix". This means content that is floating inside the tab overlays content below the tabs.

**Comment by toni-leigh** [comment]
You could try not using floats?

Assuming this is a layout fix (and not making text flow round an image, which is what floats are actually for) then the `flex` and `grid` specs should be used. They don't have any unexpected side effects which require clearfix hacks.

IMO, we probably shouldn't be making changes to support float based layouts.
