### ISSUE TITLE
core-js v3 support

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#1972]
We need to upgrade core-js support in Carbon as of the v3 release this month. Otherwise if someone tries to use Carbon with the newer version they will get an error such as

```
Cannot find module: 'core-js/modules/es7.symbol.async-iterator'. Make sure this package is installed.
```

**Comment by ianforster-sage** [comment]
Released in v8.0.0
https://github.com/Sage/carbon/releases/tag/v8.0.0
