### ISSUE TITLE
select management in Table

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#2077]
I have a paginated and selectable table.
I have overrided the onSelect method on the table AND on each row (TableRow) to control the selected rows in my state.
The onSelect Method on the Table (= selectAll) returns an object whose props are the ids of the selected rows.
The onSelect method on the TableRow returns the id of the row and a boolean (true if the row is selected).

PB : the object returned by the selectAll doesn't take into account when i select a row individually

Exemple ;
- i select all on page 1 => i will have 10 items selected
- i select 1 item on page 2 => everything is still fine (in my state)
- i select all on page 3 => **KO** : the selectAll method returns an object with 20 props. I should have 21.

**Comment by ianforster-sage** [comment]
@gusch if this is still a valid issue that requires a fix please could you provide us with a codesandbox example of the issue. 
https://codesandbox.io/s/carbon-quickstart-xi5jc

**Comment by gusch** [comment]
It was a bug on the v8.xx. I unfortunately don't have the time now to see if the bug is still there on the current version. So you can close it for now
