### ISSUE TITLE
Using Const

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#209]
Update out the carbon app to use const

---

Exert from https://strongloop.com/strongblog/es6-variable-declarations/

Constant Reference, Not Value
The other new keyword for variable declaration in ES6 is const, but it is often misinterpreted as being a “constant value”. Instead, in ES6 a const represents a constant reference to a value (the same is true in most languages, in fact). In other words, the pointer that the variable name is using cannot change in memory, but the thing the variable points to might change.

Here’s a simple example. In the code below we create a new variable with a constant reference to an Array. We can then add values onto the array and since this does not change the reference, everything works:

``` javascript
const names = [];
names.push( "Jordan" );
console.log( names );
```

However, if we try to change the variable reference to a new array – even to one with the same contents – we will get a SyntaxError (“Assignment to constant variable”):

``` javascript
const names = [];
names = [];  // Error!
```

Of course, if you have a const that points to a primitive such as a string or number, then there really isn’t anything to change about that value. All methods on String and Number return new values (objects).

The last note about using const is that it follows the same new scoping rules as let! This means that between let and const we should be able to complete replace var in our code. In fact, there are many folks supporting the idea of only “allowing” var to be used in legacy code that hasn’t been touched. When a developer jumps into a file to update some code, they could (and possibly should) be updating all var statements to let or const as appropriate, with proper scoping.

**Comment by abramin** [comment]
We have addressed this via new ESLint rule.
