### ISSUE TITLE
Date Input's View on GitHub URL is incorrect

### ISSUE THREAD

**Issue by jimmymcpeter** [Sage/carbon#2109]
Hello from Sage Intacct!  I noticed the _View on Github_ link on the [Date Input](https://carbon.sage.com/components/date-input) actually takes the user to a 404 Not found -- `https://github.com/Sage/carbon/tree/master/src/components/date-input`

I believe it should be to `https://github.com/Sage/carbon/tree/master/src/components/date` instead.

**Comment by jamime** [comment]
Demo site has been replaced with storybook, closing as wont fix.
