### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#211]
A styleguide should be added to the carbon library so that contributors are aware of how to structure the code correctly. This style guide can probably be borrowed and edited from another source. 

We should then review/update the code base to ensure that it follows the styleguide we introduce

**Comment by andrewjtait** [comment]
As we now have a lot of ESLint rules applied, we could potentially close this issue?

**Comment by SeanArmstrong** [comment]
I agress
