### ISSUE TITLE
Content shift to the left when openning Dialog Full Screen

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#2159]
For reproduce :
On Windows system / Chrome Browser alsosafari on Mac (maybe another .?)

https://carbon.sage.com/components/dialog-full-screen
Click on 'Open Preview'

The vertical scrool bar was removed to the page, so the time that the dialog full screen openning, the content of the page shift a little to the left.

**Comment by TomaszPanek** [comment]
I have the same issue in Firefox 67.0.2 on Win 10.

**Comment by edleeks87** [comment]
We don't feel this is a bug, the <html> element has class `..carbon-dialog-full-screen--open` applied when opening the full screen dialog, this sets `overflow: hidden` to prevent the user from scrolling the dialog off the screen.
You have the option to override the style attribute if you want but it isn't something we will be fixing in Carbon
