### ISSUE TITLE
Sage Carbon with ASP.Net MVC project

### ISSUE THREAD

**Issue by kkessels2019** [Sage/carbon#2160]
Hi, I want to use Sage Carbon in a new project, which will be realized with ASP.NET MVC. Has anyone done the implementation successfully and can help with a short to do list?

Greetings Kerstin

**Comment by chrisbarber86** [comment]
Carbon is basically a library of ReactJS components, so as long as you can use ReactJS with your ASP.NET MVC then you should be good to go. There are plenty of getting started guides online, but have a look at some of the following:

* https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio
* https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react-with-redux?view=aspnetcore-2.2
* https://dev.to/dance2die/setting-up-a-react-environment-for-aspnet-mvc-44la
