### ISSUE TITLE
Dropdown options and tooltips overlaps carbon-modal__background

### ISSUE THREAD

**Issue by krystian-jedrzejowski** [Sage/carbon#2165]
1. Type in dropdown some random string to get no results option 
2. Click on no result row
3. Invoke modal dialog to be opened

Please see screenshot attached:
<img width="1139" alt="Screenshot 2019-07-03 at 12 43 47" src="https://user-images.githubusercontent.com/1032741/60585665-87296800-9d90-11e9-8492-3bd7cf2ea852.png">

<img width="1093" alt="Screenshot 2019-07-03 at 12 02 47" src="https://user-images.githubusercontent.com/1032741/60585959-467e1e80-9d91-11e9-942d-37dd9762c2ec.png">

**Comment by jamime** [comment]
Please, can you provide a [code sandbox](https://codesandbox.io/s/carbon-quickstart-xi5jc) that reproduces this issue?

**Comment by ianforster-sage** [comment]
This issue has been closed because it has not had recent activity. Thank you for your contributions.
