### ISSUE TITLE
Tooltip UI Styling Issue

### ISSUE THREAD

**Issue by krystian-jedrzejowski** [Sage/carbon#2171]
Browser: Safari v12.0.3

Text does not fit the tooltip. Please check attached screenshot:

![Einnahmenrechnungen](https://user-images.githubusercontent.com/1032741/60718468-fafc7980-9f24-11e9-859f-9c00c237dfbc.png)

It looks like the problem is caused by the css property width:fit-content. It's not working as expected in Safari for short error messages - when I added some more text to the message it looked properly. We get this styling from the "common-input__message" class.

![error message styling problem](https://user-images.githubusercontent.com/1032741/60718561-4747b980-9f25-11e9-9a3e-5c62bf12d5f2.png)

**Comment by ianforster-sage** [comment]
Retested with Safari 13.0.3 & Carbon 16.8.1. This is no longer a valid issue. Closing.
