### ISSUE TITLE
Inputs - Placeholder not shown on IE 11

### ISSUE THREAD

**Issue by krystian-jedrzejowski** [Sage/carbon#2176]
## Browser: 
IE11

## Components: 
Textbox, Dropdown, etc

## Steps:
1. Type some text into textbox with placeholder
2. Remove text

## Expected:
Placeholder is shown. Please compare with other browsers

## Actual:
Textbox is empty

**Comment by ianforster-sage** [comment]
This is fixed in the new implementation of Date Input. This can be found in experimental/ folder in v9.0.0-rc2 and will be in the next full release.
