### ISSUE TITLE
In some case, the dialog title is behind the close button

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#2203]
![image](https://user-images.githubusercontent.com/18695818/61445656-17011180-a94e-11e9-8e25-a1f879768f23.png)

Depends of title and dialog size.
In some case, the Title of the Dialog component is behind the close button.
For reproduce on (https://carbon.sage.com/components/dialog)
size : small
title: Example Title for a Dialogggggggg

**Comment by ianforster-sage** [comment]
Fixed.
