### ISSUE TITLE
Tab away from date input decrease date value by 1 day

### ISSUE THREAD

**Issue by krystian-jedrzejowski** [Sage/carbon#2226]
Browser: Edge
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

**Steps**
1. Navigate to page https://carbon.sage.com/components/date-input
2. Click on date input
3. Type date via keyboard
4. Press tab

**Actual**
Date value changes to date minus one day

**Expected**
Date value stays unchanged

**Comment by ianforster-sage** [comment]
Fixed in experimental Date Input.
