### ISSUE TITLE
Datepicker does not disappear once click on another datepicker

### ISSUE THREAD

**Issue by KatarzynaQA** [Sage/carbon#2232]
**Browser**: all
**Steps:**
1. Open sandbox https://carbon.sage.com/sandbox
2. Create two DateInput components:
```html
<div>
	<DateInput />
	<br />
	<br />
	<br />
	<br />
	<br />
	<DateInput />
</div>
```
3. Click on date input with is lower on the page -> date picker is shown
4. Click on the first date input on the page.

**Actual outcome:**
Two date pickers are shown

![Zrzut ekranu 2019-07-31 o 15 12 26](https://user-images.githubusercontent.com/30634976/62214611-b211d680-b3a5-11e9-95c7-d403707e8226.png)

**Expected outcome:**
Date picker from step three disappears after clicking after on another date input

**Comment by chrisbarber86** [comment]
Fixed by https://github.com/Sage/carbon/pull/2283
