### ISSUE TITLE
Css : Date & warning

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#2274]
![image](https://user-images.githubusercontent.com/16415182/63580704-a923b780-c595-11e9-89a9-e26ab3f781b4.png)

I have a form with two date input, one with a validation presence, the other with a warning presence. The icon of the warning disappear when i hover it. Looking at the css, it appears that it is different between error and warning : the first uses a 'color: #fff' (and works), the other a 'fill: #fff'. If i replace fill by color, it works

the css class is '.common-input__input:hover ~ label .carbon-input-icon--warning .carbon-icon:before, .common-input__input:hover ~ label .carbon-input-icon--warning:hover .carbon-icon:before'

**Comment by ianforster-sage** [comment]
resolved in latest release.
