### ISSUE TITLE
Dropdown and custom validator

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#2294]
I have a custom validator. 
If i put it on a textbox, everything works fine. 
If i put it on a dropdown/dropdownfilter, the validate method is never called. 

In debug mode, in the _handleBlur method of input-validation.js, i see that the blockBlur prop is true for dropdowns and thus the validation is not done.

When a value is selected selectValue is called which sets blockBlur to true so I guess that what might be needed is some sort of deferred select method which would allow time for the validation to be triggered.

**Comment by ianforster-sage** [comment]
Dropdown has now been deleted, please use Select instead.
