### ISSUE TITLE
Textbox validation incorrect icon and misalignment

### ISSUE THREAD

**Issue by carlcheel-sage** [Sage/carbon#2325]
The textbox validation shows the incorrect icon and the alignment is broken. 

**Version of Carbon:** v9.0.0-rc3

![image](https://user-images.githubusercontent.com/25386428/65035277-aa4fc680-d940-11e9-86ca-702dd81c91cf.png)

**Comment by jamime** [comment]
Please, can you provide a [code sandbox](https://codesandbox.io/s/carbon-quickstart-xi5jc) that reproduces this issue? I think this will have been resolved in v9.0.1

**Comment by edleeks87** [comment]
Assume this is no longer an issue so we are closing, if it remains please reopen
