### ISSUE TITLE
Help component tabIndexOverride default prop type is incorrect

### ISSUE THREAD

**Issue by carlcheel-sage** [Sage/carbon#2326]
The Help component has the default prop of a number when the prop types indicate this is a string.

**Version of Carbon:** v9.0.0-rc3

```
Help.propTypes = {
  ...
  tagTypeOverride: PropTypes.string,
  ...
};

Help.defaultProps = {
  tooltipPosition: 'top',
  tooltipAlign: 'center',
  tabIndexOverride: 0
};
```

https://github.com/Sage/carbon/blob/master/src/components/help/help.component.js#L81
https://github.com/Sage/carbon/blob/master/src/components/help/help.component.js#L95

**Comment by jamime** [comment]
Thanks for raising this @carlcheel-sage it should be fixed in the first stable release of v9.
