### ISSUE TITLE
Switch icons are misaligned and incorrect colour

### ISSUE THREAD

**Issue by carlcheel-sage** [Sage/carbon#2332]
The switch icon colours are incorrect and the icons are misaligned.

**Carbon version:** v9.0.0-rc3

Example: https://carbon.sage.com/storybook/?path=/story/switch--default

![image](https://user-images.githubusercontent.com/25386428/65140670-fa915c00-da06-11e9-8959-53c1d2a9bad6.png)

![image](https://user-images.githubusercontent.com/25386428/65140686-02e99700-da07-11e9-9d95-febf29b21e33.png)

**Comment by jamime** [comment]
Please, can you provide a [code sandbox](https://codesandbox.io/s/carbon-quickstart-xi5jc) that reproduces this issue? I think this will have been resolved in v9.0.1

**Comment by edleeks87** [comment]
Closing as we feel this is fixed, please reopen if you find it still exists
