### ISSUE TITLE
Bug: Tool tip size is too large for the text on some browser

### ISSUE THREAD

**Issue by hytyip** [Sage/carbon#2434]
The tool tip rectangle size is too large for the text on some browser
On Chrome:
The tooltip size looks like a good fit for the text:
![image](https://user-images.githubusercontent.com/15752534/68022496-615b9380-fc9c-11e9-957c-1d97a2f3be87.png)

However, on Firefox or other browser, the tooltip size is too large:
![image](https://user-images.githubusercontent.com/15752534/68022406-22c5d900-fc9c-11e9-8d2d-cb2db291f19c.png)

**Comment by jamime** [comment]
Please, can you provide a [code sandbox](https://codesandbox.io/s/carbon-quickstart-xi5jc) that reproduces this issue?

**Comment by jamime** [comment]
Can't reproduce on experimental components.
