### ISSUE TITLE
Inline Styles?

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#244]
This is a discussion about having inline styles within our react components.

Ive seen a few discussions around having inline styles in your component. These inline styles would be purely structural. For example the position of the list for the `Dropdown` component. Colours would remain external the component. 

I believe people are making this shift to inline styles because they want their components to be easily consumed by others. Having all javascript, html (JSX) and structural css within the one file would mean users of the common library get everything they need to render the component correctly without worrying about how to include our styles within their build. 

This would add more complexity to the components and we would have to allow for the styles to be overwritten via a prop to the component.

https://www.youtube.com/watch?v=ERB1TJBn32c

**Comment by andrewjtait** [comment]
Another library to consider https://www.styled-components.com/

**Comment by edleeks87** [comment]
We switched to styled-components in v9 of Carbon
