### ISSUE TITLE
ButtonToggle can't set default value

### ISSUE THREAD

**Issue by carlcheel-sage** [Sage/carbon#2491]
Within a ButtonToggleGroup, you can't set the checked property of the ButtonToggle radio button.

This means that you can't set a default selected value.

**Comment by jamime** [comment]
@carlcheel-sage can you provide a [code sandbox](https://codesandbox.io/s/carbon-quickstart-xi5jc) showing how you expect it to work please :)

**Comment by jamime** [comment]
This has been fixed in master and will be included in the next release (https://github.com/Sage/carbon/commit/6348e2dfca47458aca46b8991a16b477ef9b7df2, https://github.com/Sage/carbon/commit/d113e808c13a801e658671bcea690df16601df00).
