### ISSUE TITLE
ActionPopover - When used within a selectable Table it's not possible to prevent propagation

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#2507]
I am trying to use the ActionPopover component within a grid and when I click the component to see the sub-components this triggers the click event of the TableRow.

I would expect when clicking the component to not click the Row the component is rendered on failing this, the ability to disable the propagation on the ActionPopover component would allow us to continue without issue.

Here is a codesandbox link: https://codesandbox.io/s/carbon-quickstart-ndbpj

If you click the ActionPopover component with the console visible, you will see the onClick console log trigger for the Row.

**Comment by jamime** [comment]
I think it's unlikely that anyone needs propagation, we should fix this in carbon by calling `event. stopPropagation()`
https://github.com/Sage/carbon/blob/3963c11eefa425e5b6469c0e55862d3b555f89c2/src/components/action-popover/action-popover.component.js#L34

**Comment by mkrds** [comment]
@jamime @philearley Fixed in this pr https://github.com/Sage/carbon/pull/2512
