### ISSUE TITLE
Time Input Component

### ISSUE THREAD

**Issue by vincentfodor** [Sage/carbon#2552]
**An input field which allows the user to input time (hh:mm:ss for example).**

The user should be able to visually select the time and should also have an option to get the current time (maybe as default value or a button).

_This is very useful when the user has to insert a more accurate timestamp than a date._

**Comment by shortly-portly** [comment]
Test comment.

**Comment by jamime** [comment]
@benwilsonsage can you confirm if this is on the roadmap for DLS?

**Comment by benwilsonsage** [comment]
We do have a new 'time input' component on the list of new components to develop, but we don't have a design effort in flight, or an engineering ticket yet.
I believe the X3 team also require this component, and may have a workaround if this helps?

**Comment by vincentfodor** [comment]
@jamime @benwilsonsage This could also be integrated into the date input component, so there is a date-time input component. I noticed this is kinda missing while using Carbon.

**Comment by jamime** [comment]
Given that this is known by UX and is on the todo list, I'm going to close this issue. Hopefully, you'll see this component in the future!
