### ISSUE TITLE
ActionPopover: When conditionally removing items the component errors.

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#2556]
When you conditionally remove an ActionPopoverItem the ActionPopover errors due to not being able to call type on child.

codesandbox example: https://codesandbox.io/s/goofy-dan-60peo

If you change the false to true for the second popover item, then the component renders.

**Comment by jamime** [comment]
This is caused by `React.Children.map` we need to filter out falsey values.

```jsx
{true ? <ActionPopoverItem icon="pdf">Download PDF</ActionPopoverItem> : false }
```
## Recomended solution
Change `React.Children.map(children, fn)` to `React.Children.toArray(children).map(fn)`
