### ISSUE TITLE
Select component : Error if only one option child is set

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#2567]
https://codesandbox.io/s/carbon-quickstart-d104r

to reproduce:
Put a Select component with only one Option in child, Set a value to Select.
> a error 'optionsComponents.find is not a function' throwed.

**Comment by jamime** [comment]
Still an issue on 12.4.0.
On backlog FE-2547

**Comment by ianforster-sage** [comment]
Fixed in https://github.com/Sage/carbon/pull/2735
