### ISSUE TITLE
Display a value other than the Option text in the Select.

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#2568]
# Scenario
> { value: '1234' , text: '1234 Account label' }
{ value : '2345', text: '2345 Account label 2'}
Because the account label maybe very long, the select text contains only the account number.
But in the options, the user can see the account number and the account label for make the selection easier.

@ardvi has been using `<Select />` in v9 to have a list of accounts where the dropdown (`<Option/>`) displays an account number and label, but once a selection has been made the `Select` would display only the account number.

## UX

1. Do we want to support this scenario?
2. Are there any accessibility issues caused by this approach?

**Comment by harpalsingh** [comment]
I would expect the text and value to not always be aligned and in a normal dropdown, when making changes the values/text stay what they were, so when a change is made I would expect it to still show the same text labels the user was used to.

**Comment by jamime** [comment]
Closing as wontfix.
