### ISSUE TITLE
Missing event parameter in experimental Checkbox onChange

### ISSUE THREAD

**Issue by jzipfler** [Sage/carbon#2576]
We are currently in a process of upgrading our components.
As of this process we came across the problem, that the `onChange` function of the *\_\_experimental\_\_* *Checkbox* component do not specify an event parameter.

The definition I am talking about comes from: *src/\_\_experimental\_\_/components/checkbox/checkbox.d.ts*

In our test, the *onChange* function passes the event as parameter, so that we now have to get around this problem by making the event optional and checking for its existence.

It would be easier to have the parameter specified for the property.

**Comment by jamime** [comment]
@jzipfler the `d.ts` files are written by hand at the moment, as you know what the solution is we would be grateful if you could submit a pull request?
