### ISSUE TITLE
Pagination dropdown position

### ISSUE THREAD

**Issue by sagedemdreisbusch** [Sage/carbon#2582]
Hi all,
the dropdown in the bottom left is always showing on the bottom (if you are using it in bottom positions it will resize your page and not be on top).

Sandbox: https://codesandbox.io/s/icy-violet-7tytl?fontsize=14&hidenavigation=1&theme=dark

Thank you for fixing and best wishes
Max

#sagegermany

![image](https://user-images.githubusercontent.com/50825327/71820896-e2fee180-3090-11ea-8fb3-50bb68897e76.png)
![image](https://user-images.githubusercontent.com/50825327/71820904-ea25ef80-3090-11ea-8922-0cce2cf84681.png)

**Comment by ianforster-sage** [comment]
Hi Max, Please could you raise these as two separate issues using the issue templates provided. Regarding the translation, please could you check the PagerNavigation component, which although it has hardcoded EN values for the link text these area translatable by setting the prop.
https://github.com/Sage/carbon/blob/0f243088cef3f2449ea86250ba4a04296b168636/src/components/pager/pager-navigation.component.js#L87

**Comment by jamime** [comment]
We have a ticket to make the Select component open up or down based on the available space (FE-2546).
Once this is ready we will update the Pager to use Select (FE-2480).

**Comment by ianforster-sage** [comment]
Pager now uses Select instead of Dropdown, we can schedule FE-2546

**Comment by jamime** [comment]
Nebula have asked for the same functionality.
