### ISSUE TITLE
Pagination component translation

### ISSUE THREAD

**Issue by sagedemdreisbusch** [Sage/carbon#2584]
### Current behaviour
The Pagination Component is only translatable for next, previous and last

### Expected behaviour
should also be translatable for first

### Suggested solution(s)
```
const navLinkConfig = {
      first: {
        **text: I18n.t('pager.first', { defaultValue: 'First' }),**
        destination: '1'
      },
      last: {
        text: I18n.t('pager.last', { defaultValue: 'Last' }),
        destination: String(maxPages())
      },
      next: {
        text: I18n.t('pager.next', { defaultValue: 'Next' }),
        destination: String(currentPage + 1)
      },
      back: {
        text: I18n.t('pager.previous', { defaultValue: 'Previous' }),
        destination: String(currentPage - 1)
      }
    };
```

**Comment by sagedemdreisbusch** [comment]
Hi, I also found this issue: 
`<PagerSizeOptionsInnerStyles>**Show** {sizeSelector()} {descriptor}</PagerSizeOptionsInnerStyles>`
Also Show is not translateable

Is it possible to commit with that one or should I create a new issue?

Thank you and best wishes
Max

**Comment by jamime** [comment]
@sagedemdreisbusch please create a new issue, the issue template will help us with more detail.
