### ISSUE TITLE
Incorrectly applied styling rules

### ISSUE THREAD

**Issue by jzipfler** [Sage/carbon#2587]
### Current behaviour

Building our application in production mode from a create-react-app based project, we get the following problem with the input Dropdown of the Pager component:

![image](https://user-images.githubusercontent.com/6718910/72156722-86fccb80-33b6-11ea-9434-0341bc9fbd92.png)

![image](https://user-images.githubusercontent.com/6718910/72157292-dc85a800-33b7-11ea-93fb-53c3f705d57d.png)

### Expected behaviour

I would expect, that the style is the same as in the storybook files and in development build.

### Reproducible example

I am not sure if providing a example with CodeSandbox would help somehow, as the problem only occurs when build for production.

### Suggested solution(s)

I suppose that the problem comes up because of the components used as StyledComponets.
These are injecting their styles as last element in the `<head>` section, which may cause some other styles to get overwritten. (See: https://www.styled-components.com/docs/advanced#existing-css)

I assume that the solution should be a 'hack' as stated by styled componets itself: https://www.styled-components.com/docs/advanced#issues-with-specificity

In this case, the *.carbon-input-icon* selector may be specified twice in `lib/utils/decorators/input-icon/input-icon.scss` so that the rule has a higher specificity than the one from StyledComponents.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 11.0.1 |
| carbon-factory   | - |
| react-scripts    |  3.2.0 |
| React            | 16.10.2 |
| Browser          | Chrome 79.0.3945.88 |
| npm              | 6.11.3 |
| Operating System | Windows |

**Comment by jamime** [comment]
We need to convert the sass `.carbon-input-icon` to be a styled component.
On backlog FE-2545

**Comment by WraithNath** [comment]
I was just about to log this too, I have the same issue with an app and I can confirm it does only seem to affect the production build. 

![OpportunitiesProduction](https://user-images.githubusercontent.com/51908336/88192102-0efc4180-cc34-11ea-9cfd-075bec46f984.png)

**Comment by DipperTheDan** [comment]
@WraithNath @jzipfler - This should be fixed in v35.2.0. Could you check this for me please and let us know if this is still an issue or not please and thank you.

**Comment by WraithNath** [comment]
@DipperTheDan I have just done a new production build and deployed and I can confirm the styling issue has now been resolved. Both dev and production look the same now.

I Had to make a fix to my menu styles with the new prop for light/dark mode, should have read the breaking changes first! fortunately a quick fix on my side.

Thank you for tagging me to test it.

**Comment by jzipfler** [comment]
Thank you for the feedback. I reported the fix of this issue to the relevant project and will consider it as fixed.
