### ISSUE TITLE
Pagination component translation

### ISSUE THREAD

**Issue by sagedemdreisbusch** [Sage/carbon#2592]
### Current behaviour
The Pagination Component is not translatable for show

### Expected behaviour
should also be translatable for Show

### Reproducible example
`<PagerSizeOptionsInnerStyles>**Show** {sizeSelector()} {descriptor}</PagerSizeOptionsInnerStyles>`

### Suggested solution(s)
`<PagerSizeOptionsInnerStyles>**{I18n.t('pager.show', { defaultValue: 'Show' })}** {sizeSelector()} {descriptor}</PagerSizeOptionsInnerStyles>`

**Comment by sagedemdreisbusch** [comment]
Hi all,
do you already know the timeline for this bug? I think it should be a very quick one
Thanks a lot and best wishes
Max

**Comment by jamime** [comment]
https://github.com/Sage/carbon/blob/master/src/components/pager/pager.component.js#L46

Hi @sagedemdreisbusch, thanks for raising this issue. This is currently low priority for us so we do not have an estimate of when this will be available. However, we would accept a pull request from yourself.

If you make the changes in a draft pull request we can go from there.

**Comment by jamime** [comment]
Fixed in #2641
