### ISSUE TITLE
DateRange validation doesn't interrupt submission if entered date is invalid.

### ISSUE THREAD

**Issue by SageSebNegahban** [Sage/carbon#2594]
### Current behaviour
DateRange validation does not interrupt the submission of a date, leading to queries that are known to be invalid still being sent forwards.
In ***, DateRange validation happens onBlur, while query submission happens on componentDidUpdate.  This alone leads to an issue where a submission is made before the validation steps are carried out by the component.  This is **not** an issue with Carbon, but I thought it best to highlight that this has been considered.
To get round this, the component was forced to blur in the codesandbox example below inside of componentDidUpdate, before the submission (or console.log) was carried out.  In this instance, when component validation had confirmed that the date entry was invalid, the rest of the update tasks still continued and the theoretical submission would have still been made.
It should be noted that the component validation does still handle error notification for the user (displaying an 'invalid date format' message), but does not prevent the invalid date from continuing on.

### Expected behaviour
I would expect for the component validation to interrupt the submission processes if it had been determined that the date entry was invalid (and provided that the validation is performed before the form is submitted).

### Reproducible example
https://codesandbox.io/s/priceless-oskar-6mkxm

### Suggested solution(s)
Make the component cause an interruption to the submission processes when an invalid date is entered.

### Additional context
I recognise that the suggestion made above does not solve the issue in ***, as the validation will still occur onBlur and submission will occur on componentDidUpdate.  However, if DateRange is capable of interruption, other changes can be made to facilitate the prevention of form submission.

### Your environment (in codesandbox)

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 8.1.5
| carbon-factory   | 
| react-scripts    | 3.0.1
| React            | 16.7.6 
| Browser          | Chrome
| npm              |
| Operating System | MacOS (Mojave)

**Comment by jamime** [comment]
When you use a `controlled` component you, the consumer, have to maintain the state as you are in your example (`onChange={this.handleChange}`).

If we were to prevent `onChange` on an invalid value, the user would lose the ability to type as the value would never be updated (`value={[this.state.startDate, this.state.endDate]}`).

We're in the process of adopting a `RFC` which will see our recommendation to use `Formik` and `yup` for validations, so the validation will take place in a component that you own.
https://github.com/Sage/carbon/pull/2481

I suggest that you do your validation within your own component (in `cDU`) or use the provided `Form` component which does prevent submission AFAIK.
