### ISSUE TITLE
Card footer import error

### ISSUE THREAD

**Issue by timhines** [Sage/carbon#2596]
### Current behaviour
When following example code to use the Card component, importing that single component does not allow you to use Card Row, Card Column or Card Footer (yet the example shows this should be possible).

I then manually imported Card Row, Card Column and Card Footer only to find that Card Footer cannot be used as it is missing an index.js file.

### Expected behaviour
Importing the Card parent component could automatically make row, column and footer available.  If not, at the very least, Card Footer needs fixing so it can be consumed and used.

### Reproducible example
https://codesandbox.io/s/elegant-platform-0u0b3?fontsize=14&hidenavigation=1&theme=dark

### Suggested solution(s)
Add missing index.js to Card Footer.
Fix incorrect example code.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 11.0.1 |
| carbon-factory   | 10.0.0 |

**Comment by jamime** [comment]
Thanks for the detailed bug report @timhines!

I've confirmed this is a bug, we will fix this.
In the interim, you can use the following import statement
`import CardFooter from "carbon-react/lib/components/card/card-footer/card-footer.component";`
