### ISSUE TITLE
Add text showing autofill prediction of DateRange

### ISSUE THREAD

**Issue by SageSebNegahban** [Sage/carbon#2603]
### Current behaviour

Currently, if a user clears the date in a DateRange and enters a single digit, the component will auto-fill the rest of the date, assuming the current month and year.  For example, entering '5' during January 2020 will return '2020-01-05'.  This extends on to if the user enters both a day and month, the year will be assumed to be the current year.  For example, entering '5/3' will return '2020-03-05'.
This is excellent and could be very useful for users.  Unfortunately, the UI does not give any indication that this autofill is occurring, and the input will pass validation and be successfully submitted as the full date, without telling the user.  This could cause confusion as search results could change seemingly randomly while the user is in the midsts of inputting a date.
If the user simply types a single digit and clicks off the input for any reason, the date will autocomplete itself and appear in full, but without knowing that this function exists, it's unlikely that users will utilise it.

An example to test this is in the codesandbox below:
https://codesandbox.io/s/solitary-platform-lt119

### Desired behaviour

It would be nice to have the autofilled date appear in the searchbox, much in the same way predictive text appears.  Perhaps in a lighter colour than the user-entered text to prevent confusion.  This would allow users to see what is happening and why their search results are changing, as well as saving them time typing out the full date unnecessarily when the autofill may have already submitted the request for them.

### Suggested solution

Fetching the completed date and displaying it in a lower opacity would allow users to see what is being searched at any given time without them needing to finish typing it all out.

### Describe alternatives you've considered

Alternatives could be:
Leaving it as it currently is, as nothing is actually broken, it would just be clearer to have the text.

### Additional context

The autofilling likely occurs in DateInput (otherwise just referred to as 'date') rather than DateRange, but I have little experience using DateInput so thought it best to report on a component that I know it occurs in!

### Your environment (as in CodeSandbox)

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 8.1.5
| react-scripts    | 
| React            | 16.8.6
| Browser          | Chrome
| npm              | 
| Operating System | macOS Mojave

**Comment by jamime** [comment]
Thanks @SageSebNegahban, we have a ticket on the backlog(FE-2543) to write a RFC for a new date component.
It will address this problem, the auto-formatting of dates will most likely become the responsibility of the implementing application.

**Comment by nicktitchmarsh** [comment]
FE-4459 is currently in progress to update the Date component, we currently have no plans to add this feature but after this work is complete this would be easier to implement. We will pass this suggestion onto the Design System team to evaluate.

**Comment by nicktitchmarsh** [comment]
HI @ClaireDenning Is this something DS would like to implement?

**Comment by v99rly** [comment]
I would advise against having this feature from an accessibility point of view. The only use case for auto complete is when someone uses auto complete functionality from there browser, such as pre filled name and address etc... 

Having an auto complete function for a date that ISNT someones date of birth will just get confusing for someone who is using a screen reader for example.

**Comment by debbierace** [comment]
Thanks for flagging and agree current behaviour is confusing.
@v99rly I agree - autofilling the date is quite tricky. 
We could investigate best practise and other examples of how this is handled and test with end users if appropriate.

**Comment by edleeks87** [comment]
@debbierace is there any update about the investigation? The Date and DateRange components have since been refactored but there is still a degree of auto-selecting that goes on within the date picker as some input strings will be seen as valid date formats so it would be good if we could find a way to communicate this to all users

**Comment by debbierace** [comment]
@edleeks87 I have created a Jira ticket which is now on the DS backlog: https://jira.sage.com/browse/DSY-1508 - I will let you know once I start working on it as would like to understand a bit more about the component and where it is currently used. Thanks

**Comment by nicktitchmarsh** [comment]
I am closing this ticket until DS have looked at this
