### ISSUE TITLE
Validations on Select Component send the text instead of null/empty value

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#2615]
### Current behaviour
When empty, the Select send the text intead of null/empty value for validate.

### Expected behaviour
The Select should send null or empty value is this case.

### Reproducible example
https://codesandbox.io/s/carbon-quickstart-csqbr

Enter a text that not match with a option in the select, leave the select by tab
The validator receve the text value to validate instead of null/empty value and the text is cleared.

**Comment by jamime** [comment]
Thanks for the bug report. We will be removing validations from field components as outlined in the Formik RFC #2481
