### ISSUE TITLE
[Card] component does not render with text as the children

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#2617]
### Current behaviour
The example in storybook does not work
```js
import Card from "carbon-react/lib/components/card";
export default () => <Card>content</Card>;
```
### Expected behaviour

I expect a Card component with the provided content to be displayed
### Reproducible example

https://codesandbox.io/s/flamboyant-meninsky-7j4c8
### Suggested solution(s)

It looks like it might be caused the `React.cloneElement` when the child is not an element.
https://github.com/Sage/carbon/blob/c807d152622c88b0ea010910259555537fe4db5f/src/components/card/card.component.js#L24
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |12.1.0
| carbon-factory   |N/A
| react-scripts    | N/A
| React            |16.8.6
| Browser          |Chrome 79.0.3945.130
| npm              |6.9.0
| Operating System |MacOS 10.14.6

**Comment by jamime** [comment]
Might just require an update to the docs.
FE-2542

**Comment by edleeks87** [comment]
Still exists in latest (v63) https://codesandbox.io/s/unruffled-buck-74zls?file=/src/index.js
