### ISSUE TITLE
Pager Component styling issue when used with Form

### ISSUE THREAD

**Issue by sagedemdreisbusch** [Sage/carbon#2620]
### Current behaviour
The currentPage input is displayed with a margin of 32px in Form component

### Expected behaviour
should have no margin (as in other use cases)

### Reproducible example
https://codesandbox.io/s/busy-poincare-xhlwu?fontsize=14&hidenavigation=1&theme=dark

### Suggested solution(s)
Give it an additional class deleting the margin

**Comment by jamime** [comment]
![image](https://user-images.githubusercontent.com/2328042/74250921-4066fd80-4ce3-11ea-9a19-235774b0f43b.png)
On backlog FE-2541

**Comment by sianford** [comment]
Created codesandbox with current version of Carbon v37.1.0 with the component arrangement reported in the ticket: https://codesandbox.io/s/jovial-forest-slju6?file=/src/index.js. Issue is resolved in Carbon v.37.1.0.

**Comment by sianford** [comment]
<img width="729" alt="Screenshot 2020-08-05 at 23 18 38" src="https://user-images.githubusercontent.com/12828099/89469767-0d716400-d772-11ea-8dce-35fe69d11a80.png">

Issue resolved in Carbon v37.1.0.
