### ISSUE TITLE
Textarea input height

### ISSUE THREAD

**Issue by abhoraniya** [Sage/carbon#2637]
### Current behaviour
In textarea component, the number of lines doesn't work as expected. The height doesn't change if I increse number of rows value. 

### Desired behaviour
The textarea input height shound be changed according to number of rows.

### Suggested solution
In deprecated version, It works perfectly - https://carbon.sage.com/storybook/?path=/story/deprecated-textarea--classic. but not  in new version of carbon

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 12.2.0

**Comment by jamime** [comment]
On backlog FE-2538

**Comment by basalter** [comment]
Reproducible example: https://codesandbox.io/s/recursing-perlman-f2h0f

**Comment by sianford** [comment]
Tested in v58.0.0 of carbon. The textarea height now increases/decreases as the number of rows is increased/decreased. Issue resolved ✅
