### ISSUE TITLE
Stop onClick event propagation on multiple Components

### ISSUE THREAD

**Issue by tboulis** [Sage/carbon#2643]
### Current behaviour
Event bubble of the onClick event on multiple components is propagated to its parents.
For example, if you have a Select inside an expandable component, clicking the Select to view the Options will trigger the expand as well.
I've noticed this behaviour on Select, Decimal, Input so far

### Expected behaviour
It should stop the propagation

### Reproducible example
https://codesandbox.io/s/carbon-quickstart-e0i26

### Suggested solution(s)
Add `event.stopPropagation` on the onClick handlers of the components

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 13.1.0 |
| carbon-factory   | - |
| react-scripts    | 3.2.0 |
| React            | 16.12.0 |
| Browser          | 79.0.3945.130 (Official Build) (64-bit) on MacOS |
| yarn              | 1.19.2 |
| Operating System | MacOS 10.15.2 |

**Comment by jamime** [comment]
FE-2614

This is on our backlog but a low priority at this time. If you want to submit a pull request we will happily review it.

**Comment by edleeks87** [comment]
https://codesandbox.io/s/carbon-quickstart-forked-7dkf4?file=/src/index.js

Updated sandbox with latest carbon version

**Comment by nicktitchmarsh** [comment]
Can you share a product design with me over Teams that shows why this is necessary. Thanks.
