### ISSUE TITLE
DateInput component - In small size, problem displaying's error

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#2661]
### Current behaviour
When Invalid Format error is displayed for the date fields, the last digit of the 4 digit year is not visible.
![image](https://user-images.githubusercontent.com/38658070/75021545-e27da700-5494-11ea-8e74-ff50b24b9871.png)

### Expected behaviour
The full 4 digit year should be visible when the error is visible.

### Reproducible example
Choose the size small and enter an invalid date.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 13.2.0
| carbon-factory   | 11.0.1
| react-scripts    | -
| React            | 16.12.0
| Browser          | Chrome
| npm              | 6.13.7
| Operating System | Windows 10

**Comment by jamime** [comment]
FE-2613

This is on our backlog but a low priority at this time. If you want to submit a pull request we will happily review it.

**Comment by edleeks87** [comment]
https://codesandbox.io/s/jolly-beaver-p4g1h?file=/src/index.js

Hi @hegou33 this looks like it's fixed in the latest version of carbon (v61.1.0), please feel free to raise another issue if that's not the case
