### ISSUE TITLE
Select Component customFilter additional value parameter

### ISSUE THREAD

**Issue by sagedemdreisbusch** [Sage/carbon#2697]
### Current behaviour
The customFilter function has got following params: (text, filter)

### Desired behaviour
And we request (text, filter, value)
actually the order should be another one but that would be a breaking change

### Suggested solution
Add the value to the function interface and call

**Comment by jamime** [comment]
Can you explain your use case with a code sandbox example?

We have a design ticket in progress to address some open issues around the Select component and it might be worth reviewing this at a later date.

**Comment by sagedemdreisbusch** [comment]
Hi Jamie, for sure here is the code sample:
https://codesandbox.io/s/affectionate-voice-w449t?fontsize=14&hidenavigation=1&theme=dark

**Comment by jamime** [comment]
SOGUX-7003

**Comment by jamime** [comment]
@sagedemdreisbusch if you can update your branch with some tests for your new functionality we will merge this as a stop-gap until SOGUX-7003 has been completed.

Please be aware that this functionality is likely to change again in the future, but will do so as a`BREAKING CHANGE`.

**Comment by sagedemdreisbusch** [comment]
@jamime Will do so right now, and also fixed another bug in this branch, which means if I type 'foo' it will not mark 'Foo' as found. Is that OK for you?
