### ISSUE TITLE
Tab with align="right" position="left" are positioned at the bottom

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#2698]
### Current behaviour
![image](https://user-images.githubusercontent.com/18695818/75864786-d84b9900-5e02-11ea-89cc-a1cce8882d08.png)

### Expected behaviour
When Tabs use postion='left' and align='right', the tab must be postioned to top of content.

### Reproducible example
https://codesandbox.io/s/carbon-quickstart-65gtx

### Suggested solution(s)
Remove justify-content style in this case.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     13.2

**Comment by jamime** [comment]
FE-2612

This is on our backlog but a low priority at this time. If you want to submit a pull request we will happily review it.

**Comment by edleeks87** [comment]
Fixed and released as part of https://github.com/Sage/carbon/pull/3141#issuecomment-682400712
