### ISSUE TITLE
Translation support for Switch component state on/off is missing

### ISSUE THREAD

**Issue by markusmuellerusi** [Sage/carbon#2722]
### Current behaviour
It's not possible to translate or localize on / off 

### Expected behaviour
Let the user set the labels by props and keep on/off as defaults

**Comment by jamime** [comment]
https://github.com/Sage/carbon/blob/ff9c2960eb82a09e27b9b989da303520cb259f03/src/__experimental__/components/switch/switch-slider.component.js#L15-L16

**Comment by jamime** [comment]
FE-2628
