### ISSUE TITLE
TextBox: Validation icon wraps when rendered within InlineInputs container

### ISSUE THREAD

**Issue by simon-johnstone** [Sage/carbon#2748]
### Current behaviour

When rendering a TextBox, with validation, within an InlineInputs container, the validation icon 'wraps' causing the TextBox to be rendered with increased height.

### Expected behaviour

A TextBox with validation should be rendered the same way irrespective of whether it's a child of an InlineInputs container or not.

### Reproducible example

Sample that reproduces the problem...
https://codesandbox.io/s/textbox-with-validation-within-inlineinputs-ijk06

### Suggested solution(s)

(See expected behaviour)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 13.4.0
| carbon-factory   | 
| react-scripts    | 3.3.0
| React            | 16.12.0
| Browser          | Chrome  (80.0.3987.149)
| npm              | 6.12.1
| Operating System | Win10

**Comment by ianforster-sage** [comment]
On backlog, ref: FE-2671
