### ISSUE TITLE
Sticky footer flickering

### ISSUE THREAD

**Issue by HelmutHenningson** [Sage/carbon#2759]
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by jamime** [comment]
We did fix an issue with flickering sticky footer in 0301e3c38b094f210312657c043d3041aebf160c.

This is available in versions `>=v11.0.0`.

Closing due to insufficient detail.
