### ISSUE TITLE
new (default) Property alignSelf and justifySelf for component "GridItem"

### ISSUE THREAD

**Issue by FrankHolder** [Sage/carbon#2823]
## Feature request
I would like to set alignSelf and justifySelf on Griditem level as a default for all widths. Only special responsive settings should be set in the responsiveSettings object.

### Current behaviour
In a Grid Item I have to use the responsiveSettings to define alignSelf and justifySelf. All the other props eg. gridColumnStart can be set for the GridItem itself as a kind of default

### Desired behaviour
Like e.g. gridColumnStart I would like to set the default-value for justifySelf and alignSelf in the props of the GridItem and not in the responsiveSettings, because in responsiveSettings I only want to set "special" props

### Suggested solution
new properties alignSelf and justifySelf at GridItem-level

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 16.7.0
| react-scripts    | 
| React            | 16.13.1
| Browser          |
| npm              |
| Operating System |

**Comment by ianforster-sage** [comment]
On backlog, ref: FE-2675

**Comment by harpalsingh** [comment]
Having had a look at this request, it makes sense to open the open for alignment using justify and align without needing a responsive value added and should be something a GridItem can accept without needing the responsive settings object, if there is not need for it.

All that align-self and justify-self do is position content within the GridItem itself and therefore would not break grid item layouts themselves.

**Comment by ianforster-sage** [comment]
Fixed in v23.2.0
