### ISSUE TITLE
Accordion : improve resizing content 

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#2848]
### Current behaviour
Currently, accordion resize content only on constructor or when you expend the accordion.

For example, when you add an element at the end of the content : it's hidden because the hight of the content isn't recalculted (even if we reload the component).
Before adding a new element :
![image](https://user-images.githubusercontent.com/60605396/78653353-492f1680-78c3-11ea-9722-4338b23bd9d4.png)
Afrter adding a new element :
![image](https://user-images.githubusercontent.com/60605396/78653437-65cb4e80-78c3-11ea-8d3c-3209f2a60275.png)

### Expected behaviour
When you add an element at the end of the content : the hight of the content is recalculted (even if we reload the component).
![image](https://user-images.githubusercontent.com/60605396/78653649-b9d63300-78c3-11ea-9c2e-62625d5a85d0.png)

### Suggested solution(s)
To solve this issue, `max-height` property must be set on reload action of the component.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 16.0.0
| carbon-factory   | 11.0.1
| react-scripts    |  ??
| React            |  16.13.1
| Browser          | Chrome 
| npm              | 6.14.4
| Operating System | Windows 10

**Comment by jamime** [comment]
@loeliarigault do you have a reproducible example on code sandbox? It will help us ensure that you problem has been resolved correctly.

https://codesandbox.io/s/carbon-quickstart-xi5jc

**Comment by ianforster-sage** [comment]
On backlog, ref: FE-2676

**Comment by mkrds** [comment]
@loeliarigault Fixed
