### ISSUE TITLE
Tabs: align tab header to latest DLS request

### ISSUE THREAD

**Issue by ggeis** [Sage/carbon#2862]
### Current behaviour
![image](https://user-images.githubusercontent.com/29042646/78774750-68967400-7995-11ea-81dd-7ddf90aa0cd2.png)

### Expected behaviour
Upgrade tab header paddings and outlines in compliance with latest Design Language System (DLS) requirements.

![image](https://user-images.githubusercontent.com/29042646/78774997-d17dec00-7995-11ea-983a-1c7a64c4b246.png)

![padding](https://user-images.githubusercontent.com/29042646/78775423-78fb1e80-7996-11ea-97f6-d99884e2c527.PNG)
### Reproducible example
https://carbon.sage.com/?path=/story/tabs--default

**Comment by jamime** [comment]
Fixed in #2863
