### ISSUE TITLE
Dialog, Form StickyFooter is not fixed

### ISSUE THREAD

**Issue by markusmuellerusi** [Sage/carbon#2872]
### Current behaviour
Flickering Form Footer

### Expected behaviour
Dialog, Form StickyFooter is not fixed, please reopen.

**Comment by ianforster-sage** [comment]
@markusmuellerusi Please could you follow the template provided when creating a new issue, this provides us with the information we require so we can resolve the issue for you. Here's a good example of a well written issue that you could use as a guide.
https://github.com/Sage/carbon/issues/2748
