### ISSUE TITLE
Decoupling of i18n vs Refactoring and Improvements

### ISSUE THREAD

**Issue by thehiggster** [Sage/carbon#2883]
### Current behaviour
Components like Pager, have text strings that are displayed such as "Next" and "Previous", using I18n-JS. 

If i18n-js is configured by the developer of the project using Carbon, will display text based on the current user's locale/language. 

If I18n-JS is not configured or if no translation is provided for the current locale, the default strings are used.

### Issues

- I18n-JS is a single instance library. It requires the end-developers to configure I18nJS and setup translations to use. If they don't use I18nJS but another library, they'll have to setup both.
- I18n-JS was originally built on top of a ruby tool so most of the documentation is based on Ruby.
- If the end-developers use I18n-JS, they are tied to the same version / compatible versions of the library, so upgrades can be difficult and complex.

### Desired behaviour
- Carbon not coupled to a single i18n library
- If using i18n-JS or similar, not to be tied to a version / able to override / upgrade easily.
- Ability to override all default strings easily
- Consistent across all components (not that it isn't already, just any change would need to be consistent also).

### Suggested solution
**String overrides:**
All strings in the system ship as default values but have the option to override. 
(Note the examples below are assuming the product developer is using a translations library and passing the translated strings as variables.)

This could be as props:
`<ComponentName greeting={t('general.hello')} another={t('general.anotherString')}/>`
 
as a single overrides object:
`<ExampleComponentWithObjectLabels translations={{greeting: t('general.hello'), another: t('general.anotherString')}}/>`

**Other ideas**
- Potentially configuring the translations using some form of singleton/config object to save repetition
- Passing the translation method / provider of choice as either callbacks or using Provider/Consumers.

**Comment by jamime** [comment]
Thanks for raising this @thehiggster it's on our roadmap for this year.

One of the ideas that I had was to use a Locale component.

```jsx
<I18n lang='en-gb'><Pager /></I18n>
```

I18n would be a `Provider` and `Pager` a `Consumer`.

This would allow us to ship sensible defaults for components in all languages, with the option of overriding a specific instance.

e.g.

```jsx
<I18n lang='en-gb'>
<Pager />
<I18n lang='en-us'><Pager /></I18n>
</I18n>
```

```jsx
<I18n lang='en-gb'>
<Pager />
<I18n translations={{
  pager: {
    first: 'Beginning',
    last: 'End'
  }
}}><Pager /></I18n>
</I18n>
```

I agree that the underlying implementation should be updated, I think `i18next` would be a suitable candidate. It has significantly more adoption within the react community, it seems to be more mature and as commercial backing.

**Comment by thehiggster** [comment]
For reference:

This requirement came out of a discussion in the architecture team about i18n going forwards. The new apps will be built using I18next instead of i18njs.

Having both i18njs and i18next in the projects is redundant, and we also discussed that it may be better if Carbon  was decoupled from any translations library, if possible. To be discussed how.

The template UI has i18next working and pulls in Carbon. It has i18n-js as a dependency but primarily uses i18next.
https://github.com/Sage/sbc.template.ui

Petrus have converted their code from using I18njs to i18next in this repo.  https://github.com/Sage/sbc.accountants.clientmanagement.ui

Thanks,
James

**Comment by ianforster-sage** [comment]
FE-2840
