### ISSUE TITLE
Colors: some colors are not compliant with DLS specifications

### ISSUE THREAD

**Issue by arturodrigues** [Sage/carbon#2889]
### Current behaviour
There is a mismatch between Carbon and DLS colors. Example:

- DLS

![image](https://user-images.githubusercontent.com/47244523/79978307-0020ba00-84a0-11ea-82bb-bea273a1d095.png)

- Carbon:
![image](https://user-images.githubusercontent.com/47244523/79978354-13cc2080-84a0-11ea-893e-52f2a7648ca4.png)

### Expected behaviour
Colors should be compliant with DLS specifications.

### Suggested solution(s)
In .\src\style\utils\mix.js, line 20, change Math.floor method to Math.round. This way, all colors are DLS compliant.

### Additional context
NA

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  17.2.2 |
| carbon-factory   | ?? |
| react-scripts    |  ?? |
| React            | 16.12.0 | 
| Browser          | NA |
| npm              | 6.9.0 |
| Operating System | Windows 10 |

**Comment by ianforster-sage** [comment]
Fixed in https://github.com/Sage/carbon/pull/2890
