### ISSUE TITLE
Create: make the component compliant with DLS

### ISSUE THREAD

**Issue by arturodrigues** [Sage/carbon#2891]
### Current behaviour
Currently, Create component has some small style discrepancies comparing with [DLS](https://designsystem.sage.com/components/show-edit/), which are:

- border color;
- text and icon font size;
- text and icon color when component is hovered or focused;
- padding between text and icon.

Colors are exactly the ones as it should be, however issue #2889 depicts this and #2890 is a proposal to fix that.

### Expected behaviour
Create component should look like the component in [DLS](https://designsystem.sage.com/components/show-edit/).

### Reproducible example
[Carbon storybook](https://carbon.sage.com/?path=/docs/create--default)

### Suggested solution(s)
Implement DLS rules.

### Additional context
NA

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  17.2.2 |
| carbon-factory   | ?? |
| react-scripts    |  ?? |
| React            | 16.12.0 |
| Browser          | Chrome 80 |
| npm              | 6.9.0 |
| Operating System | Windows 10 |

**Comment by jamime** [comment]
@arturodrigues Thanks for raising this, what project are you working on?

@harpalsingh @lukeemmerson 
We're in the process of adding a dashed button outline in https://github.com/Sage/carbon/pull/2870

|Carbon Storybook #2870|
|---|
![image](https://user-images.githubusercontent.com/2328042/80010369-3b33e500-84c2-11ea-96ef-5faa43fc465a.png)

It's used in the CM designs for "Add a new Service" and "Create Client". See ticket FE-2484.

|Create Client Handover|
|---|
![image](https://user-images.githubusercontent.com/2328042/80013616-17bf6900-84c7-11ea-9262-a0450c9d589f.png)

We also have a `Create` component:
|DLS Website Create|
|---|
![image](https://user-images.githubusercontent.com/2328042/80010998-24da5900-84c3-11ea-9fc8-3763fec65c5a.png)

|Storybook Create|
|---|
![image](https://user-images.githubusercontent.com/2328042/80011555-ee510e00-84c3-11ea-8d4c-306c655eda99.png)

Do we want to keep both components, `<Create />` and `<Button buttonType="dashed" iconType="plus" iconPosition="after">Create</Button>`

If we are to keep both components please can you raise a FE ticket with a link to the marvel handover.

Thanks!

**Comment by harpalsingh** [comment]
Having reviewed this, the updated style applied to the button component in PR https://github.com/Sage/carbon/pull/2870 handles the create component styling and the create component itself should be deprecated and the button with dashed styling is used.

**Comment by ianforster-sage** [comment]
The story to remove Create component has been added to our backlog ref: FE-2741
