### ISSUE TITLE
Menu items text change to link when onClick handler is used.

### ISSUE THREAD

**Issue by LondonMashabela** [Sage/carbon#2903]
### Current behaviour

The menu-items text is changed to link when onClick handler  is used.  When you use onClick event on the menu-item, it looses its styling. In the CodeSandbox link or image attached
 menu-item named "Item-one" is different from the rest because I used onClick handler. It was suppose to still have the same styling as other menu-items. 
<img width="251" alt="Menu-item bug" src="https://user-images.githubusercontent.com/52787922/82555313-d4a8f200-9b67-11ea-81ad-3deb5c7086d8.PNG">
### Expected behaviour

The menu-item should remain unchanged when onClick property is used. 

### Reproducible example

Updated example: https://codesandbox.io/s/optimistic-pike-wpju5?file=/src/App.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 20.1.2
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome
| npm              |
| Operating System | Windows

**Comment by ianforster-sage** [comment]
@LondonMashabela thanks for raising this issue. Unfortunately it's not clear from your description or the codesandbox example. Please could you add further details to help us identify the issue that you are describing.

**Comment by LondonMashabela** [comment]
Thanks for the response, I have edited the the description and added CodeSandbox with the latest Carbon version.

**Comment by jamime** [comment]
FE-2816
