### ISSUE TITLE
Remove /lib directory from git?

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#291]
In our current setup we precompile (through Babel) our JS code from the `/src` directory into the `/lib` directory.

We do this to speed up compilation for developers when using anything from Carbon, as the gulp task does not have to run the Carbon code through the Babel compiler as it is already compiled for them.

However, it does have some negative effects.
- It effectively doubles the source code in the Git repo.
- It is confusing for developers why there is a `lib` and `src` directory, and where they should make any changes.

As an alternative, instead of commiting the `lib` directory into Git, it can be generated whenever a developer installs Carbon through `npm`. For example when running `npm install carbon`. This means it is available to a developer when they need it, and isn't cluttering the Git repo. For this to work, the developer will require having Babel installed globally on their machine.
### What do other repos do?

Another reason we offer the precompiled code is that some developers may not want to use Babel - so we can give it to them already compiled. On top of this, they may not want to use any Node compiler at all - in which case we could even offer a fully compiled JS file which they could drop in browser without any compilation task

An example of a repo which does this is [this component](https://github.com/JedWatson/react-select).
- They have a [src](https://github.com/JedWatson/react-select/tree/master/src)
- They have a [lib](https://github.com/JedWatson/react-select/tree/master/lib)
- They have a [dist](https://github.com/JedWatson/react-select/tree/master/dist)

This is beneficial for open source projects, which Carbon is not yet, so maybe we do not have to cater for this at this point in time, and can get away with precompilation on install instead.

Looking for any thoughts/suggestions?

**Comment by chrisbarber86** [comment]
Now we're on NPM we've removed the `lib` folder - so I'll close this issue.
