### ISSUE TITLE
Link component  : open the link in another tab.

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#2921]
### Current behaviour
https://carbon.sage.com/?path=/story/link--default 
There is no props to open the link in another tab.
In the previous versions 8.1.5 we had the possibility to use target= '_blank'

### Expected behaviour
Have a props like target to be able to open the link in another tab.

### Suggested solution(s)
Have a props like target to be able to open the link in another tab ?

**Comment by jamime** [comment]
FE-2793
