### ISSUE TITLE
Accordion component: Unable to pass in data-roles using the component 

### ISSUE THREAD

**Issue by gedskikas** [Sage/carbon#2933]
### Current behaviour
It seems that we're unable to pass in and set data-roles on the Accordion component - https://github.com/Sage/carbon/blob/master/src/components/accordion/accordion.component.js#L21

### Expected behaviour
To be able to pass in and set data-roles on the Accordion component

### Reproducible example
https://codesandbox.io/s/blissful-cache-4he9v

Thanks to @philearley for the provided example

**Comment by ianforster-sage** [comment]
On backlog FE-2800
