### ISSUE TITLE
Select with preventFocusAutoOpen dismiss the first keydown

### ISSUE THREAD

**Issue by ardvi** [Sage/carbon#2941]
### Current behaviour
if preventFocusAutoOpen is set to Select component, the first [alpha numeric] keydown open the list but don't change the filter value.

### Expected behaviour
change the filter value

### Reproducible example
https://codesandbox.io/s/carbon-select-preventautofocus-2qewx

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     20.1.2 |

**Comment by ianforster-sage** [comment]
On backlog FE-2802

**Comment by ianforster-sage** [comment]
Resolved in latest `carbon-react/lib/components/select`
