### ISSUE TITLE
Cannot programatically clear search box

### ISSUE THREAD

**Issue by LondonMashabela** [Sage/carbon#2944]
### Current behaviour

I want to clear the search box by clicking a button which set search value to empty string. When I pass empty string as a value of search the search box is not cleared or set to empty value/string. Or when I pass any string, and set it to search value, the value displayed on the search box is not updated. The only way I can clear the search currently is though clicking "x" in the search input(interface). And the only way to update the search value is by typing it on the user interface, you cannot update it using code.

### Expected behaviour

I want to be able to pass a string to the search value, and see the value on the search box on the interface changing to the value passed to it. 
### Reproducible example

https://codesandbox.io/s/modest-cartwright-k9pyd?file=/src/searchComponent.js
https://codesandbox.io/s/admiring-tree-hrjun
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 20.1.1
| carbon-factory   |
| react-scripts    | 
| React            | 16.13.1
| Browser          | Chrome
| npm              |
| Operating System | Windows

**Comment by jamime** [comment]
I've updated the issue with another codesandbox and put this on our backlog.
 FE-2817
