### ISSUE TITLE
Property for integral-part-lenght for Decimal-Field (Squad SBC German)

### ISSUE THREAD

**Issue by gandalf92** [Sage/carbon#2947]
### Current behaviour
At the moment there is no possibility to set a maximal length for the number before the decimal point.

### Desired behaviour
When the number of digits, before the decimal point, is bigger than maximal defined length, the field should behave like when the precision length is exceeded.

### Suggested solution
A propertie has to be added, which includes the maximal length of the integral part as number.

Inside of the component there is a funtion called isValidDecimal. Here the integral-part-length could be added to the regExp like it has been done for the precision.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by ianforster-sage** [comment]
@gandalf92 we had feedback from UX

> using standard validation may be easier on the user and probably clearer

Please could you attempt this and feedback to us before we consider this for inclusion.

**Comment by ianforster-sage** [comment]
@gandalf92 we'll assume that you've resolved this with UX.
