### ISSUE TITLE
Option component no longer passes options property to onChange event

### ISSUE THREAD

**Issue by StevenMWood** [Sage/carbon#2950]
### Current behaviour
The Option component accepts an options property which we are using to customise the values we get out of the select. However, as a result of a change these are no longer passed to the onChange event of the component: the only things we can get out of that are optionValue and optionText

### Expected behaviour
That the options property is passed to the OnChange event

### Reproducible example
https://codesandbox.io/s/latest-carbon-options-not-accessible-in-onchange-fp45t

### Suggested solution(s)
As in  the expected behaviour. Pass any options to the onChange event

### Your environment
Please see code sandbox (latest versions).

**Comment by jamime** [comment]
We're actually in the process of writing a new `<Select/>` component to including 

- Basic Select (comparable with the HTML Select) - https://github.com/Sage/carbon/pull/2913
- Filter Select (filter a pre-determined list)
- Async Select (filter a list returned from a network request)

Once these have been completed the `__experimental__` and `__deprecated__` components will be removed.

I was surprised to see `options` in the `PropTypes` for the `<Option/>` component. It's not well documented/tested how this is supposed to behave.

I'd encourage you to update your example to use the `value` of the select to lookup this data. We know the `__experimental__` and `__deprecated__` isn't the easiest to use or maintain. We're creating the components above to follow the native `Select` behaviour more closely.

Here is an example of how you can accomplish what you want to achieve with the components that are available today:
https://codesandbox.io/s/latest-carbon-options-not-accessible-in-onchange-zuu34

**Comment by ianforster-sage** [comment]
> unfortunately Jamie's reply and workaround solution does not help us with this problem. It might be a good fix for the simple sandbox example but in a complex example where the data comes from our API, there is no simple way of matching the text and value from the Options component to the additional values we need. The question from us is why allow an options prop to be specified if you are not supplying it with the selected result? 
_StevenMWood_

Requires further consideration at next triage

**Comment by mkrds** [comment]
@StevenMWood Could you please show us a complex example that is impossible to be solved with the current implementation of `Select` component without the use of `options` prop?
To be honest same as @jamime I'm quite surprised of the existence of `options` prop on the `Options` component, however with our current approach of delivering input components resembling native HTML inputs as much as possible I don't see a reason for supporting arbitrary data structures.

**Comment by ianforster-sage** [comment]
Hi Steve. I tried to raise this on a DM with you too. We're going to close this now.
