### ISSUE TITLE
Type System

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#296]
Should we introduce a type system into the carbon library. There have been a couple of cases where we are expecting integers but get strings and vice versa. A type system should stop these errors from occurring and compile time(?) or at least be obvious to developers at run time.

Here a couple of options:
http://flowtype.org/
http://www.typescriptlang.org/

I believe that both systems can also be introduced slowly into a project. So we could only add typescript/flow into a couple of files and see how we like it

**Comment by mogusbi-sage** [comment]
Are there any plans to add typings to enable developers to use Carbon with TypeScript?

**Comment by andrewjtait** [comment]
@mogusbi-sage in progress! https://github.com/Sage/carbon/pull/1908

**Comment by ianforster-sage** [comment]
Typescript now supported as of https://github.com/Sage/carbon/pull/1908
