### ISSUE TITLE
Dialog not honoring autoFocus property

### ISSUE THREAD

**Issue by StevenMWood** [Sage/carbon#2960]
### Current behaviour
Dialog component is not honoring the autoFocus property. Focus is still on the background form that launched the modal.

### Expected behaviour
We'd like the focus on launch of a Dialog to be in a field.

### Reproducible example
https://codesandbox.io/s/compassionate-frost-jpyst
https://codesandbox.io/s/eloquent-smoke-i1svm
https://codesandbox.io/s/cranky-framework-gcngl
### Suggested solution(s)
As in the expected behaviour. 

### Your environment
Please see code sandbox (latest versions).

**Comment by jamime** [comment]
### Notes
Pod isn't focusable, but I already know that this doesn't work for things that are focusable such as Button or Input. I created a new sandbox to show this https://codesandbox.io/s/eloquent-smoke-i1svm

We can remove the `autoFocus` prop, its a requirement of dialog that focus moves to the first focusable element.

The user may change that element by providing a ref.

Should be a simple fix, looks like we forgot to call `firstFocusableElement.focus();` when the user first opens the dialog. The guard will prevent this from being called.
https://github.com/Sage/carbon/blob/c1ee5416c4cd8a112b5ef13222c4dd0e1c8f228e/src/utils/helpers/focus-trap/focus-trap.js#L24

We need to do this behaviour
https://github.com/Sage/carbon/blob/c1ee5416c4cd8a112b5ef13222c4dd0e1c8f228e/src/utils/helpers/focus-trap/focus-trap.js#L23-L28

when the user opens the dialog using the keyboard, OR a mouse.

**Comment by ianforster-sage** [comment]
FE-2836
