### ISSUE TITLE
Menu Item - divide styling - FE-2844

### ISSUE THREAD

**Issue by damianOfKyan** [Sage/carbon#2973]
### Current behaviour
Menu item that has `submenu` prop appears to have visual bug with dropdown chevron position when `divide` prop is provided is used on that menu item.

![image](https://user-images.githubusercontent.com/47245766/83855428-f2ea2280-a70f-11ea-939b-b75fb1898390.png)

### Expected behaviour
Menu item chevron should be correctly aligned.

### Reproducible example
https://codesandbox.io/s/menu-item-divide-issue-whowx?file=/src/index.js

### Suggested solution(s)
It should be confirmed with UX TEAM whenever a user should be able to use divide with submenu prop. If yes then styling should be fixed if no then correct validation should be put in place.

**Comment by jamime** [comment]
FE-2816
