### ISSUE TITLE
Button Toggle, default story - No focus indicated when buttons are selected in Safari or Firefox

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#2982]
### Current behaviour
When any of the buttons is selected with a mouse/trackpad, there is no gold outline applied to indicate it is in focus. This occurs in Safari and Firefox, but not in Chrome nor Edge (for Mac).
### Expected behaviour
When a button is selected by clicking on it with a mouse or trackpad it should indicate it is in focus with the gold outline.

### Reproducible example

1. Navigate to `carbon.sage.com`, or check out the `master` branch in the Safari or Firefox browsers.
2. Open Button Toggle > default story.
3. With the Actions tab selected, select any of the buttons. No gold focus outline is present.

### Suggested solution(s)
Show the gold outline when a button has been selected.

### Additional context
If the button is not in focus when it has been selected and then you navigate away from that button, it will not trigger an onBlur event.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 24.0.0 |
| carbon-factory   | 11.0.1 |
| react-scripts    | 
| React            | 16.8.3 |
| Browser          | Safari, Firefox |
| npm              | 6.14.5 |
| Operating System | mac OS Mojave 10.14.6 |

Logged Jira but ticket FE-2862.

**Comment by ianforster-sage** [comment]
FE-2862

**Comment by ianforster-sage** [comment]
This issue is resolved
Focus is visible now on Safari / Firefox 
onBlur is called correctly 
Chrome - still works as expected
