### ISSUE TITLE
Portrait does not work with sizes from sizesFull

### ISSUE THREAD

**Issue by stripeyjumper** [Sage/carbon#2995]
### Current behaviour
Portrait component throws an error if passed a size from the `sizesFull` collection: https://github.com/Sage/carbon/blob/63f4216f17ed7bd4295af9cec752d962bbe9f7bb/src/utils/helpers/options-helper/options-helper.js#L322

### Expected behaviour
Portrait component should work with sizes from `sizesFull`

### Reproducible example
https://codesandbox.io/s/brave-field-3ot7k?file=/src/index.js

### Suggested solution(s)
Values should be added to the lookup in `portrait-size.config.js`: https://github.com/Sage/carbon/blob/master/src/components/portrait/portrait-size.config.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 23.2.1
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.6
| Browser          | Chrome
| npm              |
| Operating System | MacOS

**Comment by jamime** [comment]
Thanks for raising this issue @stripeyjumper.

We've taken a look at this and compared it to the DSL.
We currently implement all of the sizes required by the DSL using the sizes listed on their website, or in the `OptionsHelper.sizesPortrait`.

#### Carbon
![image](https://user-images.githubusercontent.com/2328042/85273332-59dc3b00-b475-11ea-9ade-415eeda47b13.png)

#### DLS
![image](https://user-images.githubusercontent.com/2328042/85273363-66609380-b475-11ea-8ef5-bec7ab2a854b.png)


It appears that `OptionsHelper.sizesFull` has been incorrectly included in the prop-types for the `Portrait` component, we've raised FE-2889 to fix that.

**Comment by stripeyjumper** [comment]
> It appears that `OptionsHelper.sizesFull` has been incorrectly included in the prop-types for the `Portrait` component, we've raised FE-2889 to fix that.

Hi Jamie thanks for that, I'll update our props with the new values.
