### ISSUE TITLE
Add allowedFormats to DateInput

### ISSUE THREAD

**Issue by SAHesse** [Sage/carbon#2996]
### Current behaviour
Currently, the component seems to only support the date format that is defined by the locale we are in.
So when I'm on a DE locale, it supports `DD.MM.YYYY` or `D.M.YY`, but not `YY-MM-DD`, for example, while in an EN locale it would be reversed.

The issue here is, that users are not adhering to only typing locally recognised formatted dates. The users are typing one of the following:
```
export const DATE_FORMAT_EUROPE = 'DD.MM.YYYY';
export const DATE_FORMAT_US = 'YYYY-MM-DD';
export const DATE_FILLER_FORMATS = [
  'D.MM.YYYY',
  'DD.M.YYYY',
  'D.M.YYYY',
  'D.M.YY',
  'DD.M.YY',
  'DD.MM.YY',
  'YYYY-MM-D',
  'YYYY-M-DD',
  'YYYY-M-D',
  'YY-MM-DD',
  'YY-M-DD',
  'YY-MM-D'
];
```
This is not a completed list. For example, I can see a user going for a `MM/DD/YYYY` format, not listed above. The problem is, I have no possible way of telling the DateInput that this is the case.

Another issue is, that users are working the Numpad for quick entering of the
different numerical fields. So they also type in dates with this, in the format `DD,MM,YYYY`.
I also can't support this as the component doesn't trigger `onChange` or `onBlur` on an invalid date, which this of course is.

### Desired behaviour
The component does not only accept formats that are valid for the current locale.

### Suggested solution
One solution would be to have a Property called 'allowedFormats' or similar, that I can provide (optionally) so the DateInput doesn't convert (which it currently does, reproducible on https://carbon.sage.com/?path=/story/experimental-date-input--default) a date like `20-06-12` (YY-MM-DD) to `20.06.2012` (DD.MM.YYYY) because it expects locale dates.
Looking at the code this would be a rather big rewrite of the component, but it would be very needed for us to have a fully supported date component.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 16.6.0
| react-scripts    | 3.3.0
| React            | 16.12.0
| Browser          | Chrome, Firefox, Safari (Mac)
| npm              |  6.12.0
| Operating System | Windows, Mac

**Comment by benwilsonsage** [comment]
The legacy Carbon component had a range of formats specified (listed at the bottom of this page: http://designsystem.sage.com.s3-website.eu-central-1.amazonaws.com/components/datepicker/).
However, some formats may be ambiguous depending on the preferred format of the locale, so this example works for UK only.
I guess we could define config files for each major locale... although users might be developing for niche locales, or still need to specify more closely.
If the engineering effort is realistic, the approach described sounds good.

**Comment by jamime** [comment]
I'm not sure I fully understand the reasoning behind this, why are the users typing dates that are not their locale?

The main issue I see with the suggestion is formats like this where you want to change the date based on the separator. I think this is confusing.

```diff
export const DATE_FILLER_FORMATS = [
+  'DD.MM.YY',
+  'YY-MM-DD',
];
```
e.g.

| Format | Value | ISO |
|--------|-------|-----|
| DD.MM.YY | 01.02.03 | 2003-02-01 |
| YY-MM-DD | 01-02-03 | 2001-02-03 |

This means that users could see different formats in different pages of the same application or in other Sage products. If we are to make a change I think we should do it in the component itself to prevent this.

### Numpad

The numpad does not have a comma so I'm unsure as why users are entering one.
![image](https://user-images.githubusercontent.com/2328042/86258338-9f55e200-bbb2-11ea-89ac-7fe785b90837.png)

### Recommendation
As @benwilsonsage pointed out we do currently support a lot of different formats, but we support them in all locales. I think we should change that.

Theres two parts
#### Data Entry
This is the value that we allow the user to enter, we then format this in their local

##### Europe
I think we should enforce `DD-MM-YYYY` but we should accept all variations of `DD`, `MM`, and `YYYY` regardless of the separator used.

- `D-M-YY`
- `DD-M-YY`
- `D-MM-YY`
- `DD-MM-YY`
- `D-M-YYYY`
- `DD-M-YYYY`
- `D-MM-YYYY`
- `DD-MM-YYYY`

##### USA/Canada

I think we should enforce `MM-DD-YYYY` but we should accept all variations of `DD`, `MM`, and `YYYY` regardless of the separator used.

- `M-D-YY`

#### Data Display
This is after the user has entered their value, or when viewing data.
We should always format it as shown in the DLS and respect the users locale.

**Comment by SAHesse** [comment]
@jamime I agree, why should the user type values that are not their locale. But if they do so, the component should say "You used the wrong format". Not silently change it to the format, it assumes is right. This might lead to irritiations for the user and wrong data.
But why enforce the "-" seperator? German users type DD.MM.YYYY (or variations of it, like D.M.YY) or comma instead of dot, because comma is on the numpad.

**Comment by jamime** [comment]
> @jamime I agree, why should the user type values that are not their locale. But if they do so, the component should say "You used the wrong format". Not silently change it to the format, it assumes is right. This might lead to irritiations for the user and wrong data.

The main issue is we don't know if a date is entered in the wrong format, if it's still a valid date. We can't identify these.

e.g
| Format | Value | ISO |
|--------|-------|-----|
| DD-MM-YY | 01-02-03 | 2003-02-01 |
| YY-MM-DD | 01-02-03 | 2001-02-03 |

We also wouldn't autocorrect the input, we'd follow the formats that I listed above for EU (`DD-MM-YYYY`) or US (`MM-DD-YYYY`)

> But why enforce the "-" seperator? German users type DD.MM.YYYY (or variations of it, like D.M.YY) or comma instead of dot, because comma is on the numpad.

> regardless of the separator

I meant that the user could enter , . / - but we will display it in their local format once the field has blurred.

**Comment by benwilsonsage** [comment]
Hi all - here are some thoughts that I hope might help...

**Helpful things:**
- Tolerating different separators is likely to be useful - in some locales there is inconsistent use amongst users. , . / - seem sensible.
- Jamies examples of local formats with single and double days and months will be helpful to users, plus 2 or 4 digit years.
- It would also be helpful to support shorthand formats - e.g. DD/MM, D/M will add on the current year. D or DD will add on the current month and year.
- Would no punctuation (e.g. DDMMYY, and shorthand DDMM) also be helpful for speed key-ers?

**Less helpful things:**
- Legacy supports things like 1 Apr --> 01/04/2020 - probably not common or that helpful.
- 1st Apr --> 01/04/2020 - probably also not that common or helpful.
- I agree that changing an input value to a format ambiguous with another locale could be confusing and unintentional.

Something to think about could be Canada - I believe CA French uses one format, and CA English another - this is dependent on user settings. So, we might have users in this locale mixing up their local formats... but this is the only locale where this happens.

Does this help?

**Comment by jamime** [comment]
> It would also be helpful to support shorthand formats - e.g. DD/MM, D/M will add on the current year. D or DD will add on the current month and year.

This should be fine

> Would no punctuation (e.g. DDMMYY, and shorthand DDMM) also be helpful for speed key-ers?

This sounds reasonable too

> Legacy supports things like 1 Apr --> 01/04/2020 - probably not common or that helpful.
> 1st Apr --> 01/04/2020 - probably also not that common or helpful.

We'd remove support for this.

> Something to think about could be Canada - I believe CA French uses one format, and CA English another - this is dependent on user setting

I can see this being an issue for users, but I don't think we could fix it in the component. We'd have to make it clear to the user which locale they're using instead. I think there's a bigger question here, does the user set their locale in our apps, or do our components decide based on user agent. I think it is safer to have it as a user account setting.

**Comment by SAHesse** [comment]
@jamime Thanks for the clarifikation.
@benwilsonsage  Very helpful things, thank you.

@jamime  The different seperators (or no seperators like @benwilsonsage proposed) should work for us. 

Regarding those wrong formats, 

> The main issue is we don't know if a date is entered in the wrong format, if it's still a valid date. We can't identify these.
> e.g
> Format | Value | ISO
> -- | -- | --
> DD-MM-YY | 01-02-03 | 2003-02-01
> YY-MM-DD | 01-02-03 | 2001-02-03

we'd like to add valid formats like YY-MM-DD and except that specific result. So, when the user types 31-05-00 this would cause to validation to fail. If whe add both, YY-MM-DD and DD-MM-YY the component should recognise that only the last format matches. For your example, maybe add a validation message like "The inserted Date matches multiple formats and the value could not be determined".

**Comment by jamime** [comment]
@SAHesse 

> Format | Value | ISO
> -- | -- | --
> DD-MM-YY | 01-02-03 | 2003-02-01
> YY-MM-DD | 01-02-03 | 2001-02-03

In the case of a user wanting to enter that date, how would they proceed? We generally advise writing validations with formik/yup, we can produce both validation errors and warnings. Errors block form submission, warnings do not.

If we errored, the user wouldn't be able to enter that date.
If we displayed a warning, you wouldn't be able to determine which format the user entered on the backend.

**Comment by ianforster-sage** [comment]
@SAHesse we have added this to our backlog, to be considered as part of a wider review of the Date component.

**Comment by ianforster-sage** [comment]
FE-2543

**Comment by SAHesse** [comment]
@ianforster-sage Thank you very much, I appreciate it.

**Comment by edleeks87** [comment]
Still valid
