### ISSUE TITLE
destructive dashed button is not in the DLS

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#3000]
### Current behaviour
Carbon has a dashed destructive button
![image](https://user-images.githubusercontent.com/2328042/84925827-69006900-b0c2-11ea-98ee-6fd6c3f91e5d.png)

### Expected behaviour
Carbon and DLS should match.

### Reproducible example
https://codesandbox.io/s/wandering-wind-p9gvu

### Suggested solution(s)
This should be in the DLS or should be removed from Carbon.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |30.1.0

**Comment by jamime** [comment]
@harpalsingh what should we do?

**Comment by harpalsingh** [comment]
@jamime We should allow all buttons styles to use the various color options, so we should add this, while I can't see an exact use case right now, buttons should be flexible enough to use a mixture of the props, so this would be dashed/destructive and even full width etc.

**Comment by jamime** [comment]
FE-2907

**Comment by sjohnson-sage** [comment]
This can be closed now as dashed destructive buttons as in the new DLS
