### ISSUE TITLE
Help component not opening destination link specified in href

### ISSUE THREAD

**Issue by StevenMWood** [Sage/carbon#3009]
### Current behaviour
Clicking on the help icon does not open the URL in the href unless you right click on the icon and choose to open link in another tab/window.

### Expected behaviour
The destination URL is opened.

### Reproducible example
https://codesandbox.io/s/wizardly-diffie-lffkd

### Suggested solution(s)
As in the expected behaviour.

### Your environment
Please see code sandbox (latest versions).

**Comment by jamime** [comment]
FE-2906
