### ISSUE TITLE
Confirm : button order

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3060]
### Current behaviour
In the Confirm component, the order of buttons is the following : primary - secondary

### Expected behaviour
In the DLS, it is secondary - primary

![image](https://user-images.githubusercontent.com/16415182/87047657-131f6c80-c1fb-11ea-9d47-7eefde1d4ae7.png)

### Suggested solution(s)
Either the order is forced or, as for the Form component, we can choose which side is the secondary button

**Comment by ianforster-sage** [comment]
FE-2941
