### ISSUE TITLE
TextBox - issue with logging onChange action for the last character in word

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#3070]
### Current behaviour

*Steps to reproduce:*
1. Open Design System - Select - Filterable - basic.
2. Type `Amber` into input field.

The `onChange` does not fire when pressing r when typing Amber in `Design System` -> `Select` 
This is a Textbox bug.

### Expected behaviour

Fix the issue. Also we should remove the `fillLastFilterCharacter` workaround.

**Comment by DlgSHi** [comment]
FE-2948

**Comment by grabkowski** [comment]
Issue fixed, we need the `fillLastFilterCharacter` workaround as the onChange will not be reported by React (value does not change, only the text selection does).
