### ISSUE TITLE
Component Content missing HTMLProps in typescript interface

### ISSUE THREAD

**Issue by HelmutHenningson** [Sage/carbon#3075]
### Current behaviour
Cannot set Classname property, when using Content component in typescript.
declare const Content: React.ComponentType<ContentProps>;

### Expected behaviour
It should be possible to set className.

### Suggested solution(s)
declare const Content: React.ComponentType<ContentProps | React.HTMLProps<HTMLDivElement>>;

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 34.0.1

**Comment by jamime** [comment]
@HelmutHenningson 

We don't support custom CSS in our components, can you explain what it is that you're trying to achieve?

You shouldn't need to write any CSS to support a Sage application.

Please remember that this issue tracker is public, if you need to share something internal please contact me on Slack or via email.

**Comment by ianforster-sage** [comment]
Following discussion with Architecture and DLS teams, we are unable to support `className` so we won't be able to allow this change. If you need to discuss this further please contact us and we'll point you in the right direction.
