### ISSUE TITLE
NumeralDate: add support for label and labelInline

### ISSUE THREAD

**Issue by lukeemmerson** [Sage/carbon#3080]
### Current behaviour
`NumeralDate` doesn't have a label prop.

### Desired behaviour
Ability to have either a top-aligned or right-aligned label.
![image](https://user-images.githubusercontent.com/2328042/87954622-869b6680-caa4-11ea-8566-44e911775566.png)

### Suggested solution
- Add a Prop to add labels to the component.
- Add a prop to choose between top-aligned or in-line labels.

### Additional context
Needed for CM.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 32.0.3

**Comment by jamime** [comment]
FE-2957

**Comment by ianforster-sage** [comment]
Fixed in https://github.com/Sage/carbon/pull/3117
