### ISSUE TITLE
Issue with Toast stacked-delayed component example

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3087]
### Current behaviour

On the Carbon Canvas for [Toast (stacked-delayed)](https://carbon.sage.com/?path=/story/design-system-toast--stacked-delayed) component
There are two ways this bug has been experienced:
First, if one of the example Toasts is manually closed with 'x' before the preview button is toggled
Secondly if the toggle button is pressed after the first Toast has appeared but before the second is triggered.

Once either approach above has happened, the preview button now toggles the appearance of alternate Toasts rather than enabling/disabling both.

![Screen Recording 2020-07-22 at 14 55 34](https://user-images.githubusercontent.com/53473905/88185721-2fc09900-cc2c-11ea-8ae1-a858066a41c1.gif)

### Expected behaviour

Clicking the Toggle button that is currently in `Preview is: OFF` state should cause both Toasts to appear, regardless of previous state.
Clicking the Toggle button that is currently  in `Preview is: ON` state should cause both Toasts to vanish, regardless of previous state.

### Reproducible example
This was experienced on the Carbon component example page using the default button provided:
https://carbon.sage.com/?path=/story/design-system-toast--stacked-delayed

### Suggested solution(s)
I presume that this is just an issue with the sample code not checking for button state and instead just toggling the Toasts irrespective of current state.

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome (latest) 84.0.4147.89 |
| npm              |
| Operating System | OSX |

**Comment by ianforster-sage** [comment]
FE-2997
