### ISSUE TITLE
Number Input: Console warning "Invalid prop `propTablesExclude[2]` of type `object` supplied to `Story`, expected `function`."

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3089]
### Current behaviour
Detected in version 35.1.1 of Carbon on the master branch. It is not present in carbon.sage.com.

The warning message "Warning: Failed prop type: Invalid prop `propTablesExclude[2]` of type `object` supplied to `Story`, expected `function`." appears against all stories of the Experimental Number input component. The full warning details are as follows:

Warning: Failed prop type: Invalid prop `propTablesExclude[2]` of type `object` supplied to `Story`, expected `function`.
in Story (created by storyFn)
in storyFn
in ErrorBoundary

Jira ticket: FE-2966

### Expected behaviour
No console errors or warnings with any of the stories.

### Reproducible example

1. Run Storybook on the master branch of carbon
2. Select the Number Input component from Experimental http://localhost:9001/?path=/story/experimental-number-input--default
3. Open the developer tools console
4. Refresh the browser
5. Inspect the warnings and errors in the console

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 35.1.1
| carbon-factory   | 
| react-scripts    | 
| React            |  16.8.3
| Browser          | Safari, Chrome, Firefox, Edge(Chromium)
| npm              | 6.14.5
| Operating System | macOS 10.15.6

**Comment by ianforster-sage** [comment]
FE-2966

**Comment by ianforster-sage** [comment]
Re-tested on Safari / Chrome - no errors in console
