### ISSUE TITLE
Validation highlights should be possible on disabled and read-only controls. 

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon#3097]
### Current behaviour
On disabled/read-only fields there is limited highlighting available for validation errors. The tool-tip goes away completely.

### Desired behaviour
We have many cases where showing a validation tooltip in a disabled/read-only field is necessary. Perhaps we want to show an info to explain *why* a field is disabled. 

More commonly, we want to highlight warnings and errors in computed fields which are appropriately read-only. Perhaps the total value of an order which due to user defined settings, can not exceed a certain amount and be posted back to the server.

### Suggested solution
Allow us to over-ride the default behaviour with props and still highlight validation issues on disabled fields for the many use-cases we have.

### Describe alternatives you've considered
In our grid, we're using a custom (carbon-looking) renderer control in order to highlight validation errors in disabled fields. We have no work around for general form fields but might have to craft a similar one to our grid as this use-case isn't something we can ignore and is built into the design of our desktop application which customers are familiar with.

### Additional context
I appreciate the source of this issues "Why would a field be invalid if you can't type into it?" but as mentioned, we have many cases where that's true. Most commonly, where it is a calculated field that relies on other input. Those inputs themselves aren't inherently invalid but business logic depends on this computed field being within a certain value range. 

### Your environment
N/A

### Codesandbox
https://codesandbox.io/s/carbon-3097-b9wkt

**Comment by ianforster-sage** [comment]
Raised with UX, awaiting a reply.

**Comment by benwilsonsage** [comment]
In the case of read-only fields - for example, computed totals, validation is quite a common requirement - for example, allocating payments...
![Screenshot 2020-07-27 at 12 14 57](https://user-images.githubusercontent.com/12499090/88536135-273cd980-d003-11ea-8266-b24815c866fb.png)

In the case of disabled fields, typically the user must take an action to activate the field itself. Perhaps dynamic changes to disabled fields should be avoided unless the user activates them.
A tooltip to explain why a field is disabled is a good use case - although I imagine the location of the tip may vary (e.g. associated with a group of inputs, or with a control that activates the field, rather than the disabled field itself). Therefore, maybe a separate icon or tooltip element may work for this scenario?

**Comment by jamime** [comment]
> In the case of read-only fields - for example, computed totals, validation is quite a common requirement - for example, allocating payments...
> ![Screenshot 2020-07-27 at 12 14 57](https://user-images.githubusercontent.com/12499090/88536135-273cd980-d003-11ea-8266-b24815c866fb.png)

We don't currently support this.

I raised FE-3007 to implement it.

I think we simply need to move this line
https://github.com/Sage/carbon/blob/b0ab93a84ebd4b7ec4660b726f72a0067c02f561/src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js#L26

after this

https://github.com/Sage/carbon/blob/b0ab93a84ebd4b7ec4660b726f72a0067c02f561/src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js#L28-L42

then add examples to storybook.

I think this should be a simple fix but we don't have capacity to fix this at the moment @Chris3y. We'll happily accept a PR if you need this functionality.

**Comment by jamime** [comment]
![image](https://user-images.githubusercontent.com/2328042/89205934-6d201180-d5b0-11ea-8eb6-9cfc712c3cc0.png)
Here is a screenshot from codesandbox. I've added it to the PR.

Should we keep the same border thickness on all three variants?

It also looks like the label opacity changes when `disabled` but not `readOnly`. Should the `disabled` and `readOnly` styling be the same?

@harpalsingh what do you think?
