### ISSUE TITLE
[ Tabs ] one more grey line in the component

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#3106]
### Current behaviour

Open `carbon.sage.com` in safari browser
Go to `tabs` -> default story
Click few tabs (as shown on video
![Untitled](https://user-images.githubusercontent.com/34001198/88799708-8b9c9c00-d1af-11ea-95ea-6719d2c80c00.gif)
)
### Expected behaviour

There should not be any additional grey line

**Comment by DlgSHi** [comment]
FE-3016

**Comment by jamime** [comment]
@DlgSHi I can't reproduce this. @edleeks87 do you know about this?

**Comment by edleeks87** [comment]
@jamime yeah I spoke to @DlgSHi about it and we decided to raise it separately to the refactor work as it was the defect was present in master. I've not actually been able to recreate it myself so far though, if I can I'll link it into the enhancement stuff that's coming next as I'll likely have to make some style updates as part of that anyway

**Comment by ianforster-sage** [comment]
@edleeks87 what's the latest on this? We have failed to recreate it too.

**Comment by ianforster-sage** [comment]
What's the latest on this? Tagging with `triage` so we look into it next time

**Comment by DlgSHi** [comment]
Can't reproduce it now. Closing
