### ISSUE TITLE
Sidebar: Footer cuts through Main Content panel

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3111]
### Current behaviour
The footer buttons of the Sidebar in the 'with button' story cut through the Main Content panel.

Jira ticket FE-3019.

### Expected behaviour
The footer containing the buttons should be positioned at the bottom of the side bar.

### Reproducible example
https://carbon.sage.com/?path=/story/sidebar--with-button

### Suggested solution(s)
Provide more stories to showcase Sidebar with and without a footer, with the buttons to be contained within the footer as with the Dialog component.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 36.0.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.3
| Browser          | Safari, Chrome, Firefox, Edge
| npm              | 6.14.7
| Operating System | macOS 10.15.6

**Comment by jamime** [comment]
Looks like the buttons are in the `children` rather than being part of a footer.

**Comment by ianforster-sage** [comment]
invalid
