### ISSUE TITLE
DialogFullScreen : Get a ref of the content

### ISSUE THREAD

**Issue by bepud** [Sage/carbon#3116]
### Current behaviour
On the DialogFullScreen component, there is currently no way to get a ref of the content.

### Desired behaviour
I would like to be able to get a ref of the DialogFullScreen so I can know when a user scroll vertically in the dialog.

### Suggested solution
As there is a ref for the heading [headingRef](https://github.com/Sage/carbon/blob/f2563e14745942dabec9a17f096b8940ddb983e8/src/components/dialog-full-screen/dialog-full-screen.component.js#L29) is it possible to get a ref for the content ?

### Describe alternatives you've considered
I don't have any alternative at the moment.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 32.0.3
| react-scripts    | -
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.4
| Operating System | Windows 10

**Comment by ianforster-sage** [comment]
FE-3021
