### ISSUE TITLE
Button Toggle Group - labelInline knob in the 'Basic Grouped' story has no effect

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3118]
### Current behaviour
When you select the `labelInline` knob in the Basic Grouped story it does not place the label in line with the button toggle group.

Jira ticket: FE-3023

### Expected behaviour
The label position moves in line with the button toggle group when the knob is selected in this story as it does in the Basic and classic stories.

### Reproducible example
See https://carbon.sage.com/?path=/story/button-toggle-group-test--basic-grouped

### Suggested solution(s)
Amend the behaviour of this knob in the Basic Grouped story to be the same as that in the Basic and classic stories.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 37.0.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.3
| Browser          | Safari, Chrome, Firefox, Edge(Chromium)
| npm              | 6.14.7
| Operating System | macOS 10.15.6

**Comment by ianforster-sage** [comment]
Fixed
