### ISSUE TITLE
Portal container overlaps visible elements

### ISSUE THREAD

**Issue by mkrds** [Sage/carbon#3126]
### Current behaviour
Validation icon tooltip is rendered in Portal which as shown on the attached screenshot takes space equivalent to Tooltips dimensions however positioned in top left corner of the screen.
In edge case scenarios like shown on the attached video this interrupts with the hover functionality of the component placed below the Portal element.

![Zrzut ekranu 2020-08-11 o 19 33 51](https://user-images.githubusercontent.com/20651022/89994831-f4444800-dc88-11ea-8da1-d7426e969344.png)

### Expected behaviour
Ideally carbon-portal should be either positioned exactly the same as the element it contains (Tooltip in this case), or should have 0x0 dimensions and still be positioned in top left corner of the screen.

### JIRA Issue
FE-3032

### Your environment
carbon-react: 37.3.0

**Comment by DlgSHi** [comment]
Works properly after Tippy.js implementation
