### ISSUE TITLE
Dialog not centred when first loaded

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#3138]
### Current behaviour

![image](https://user-images.githubusercontent.com/2328042/90383749-7ad99a80-e078-11ea-845c-77c8c759bdec.png)

The dialog is positioned towards the bottom of the screen.

### Expected behaviour

![image](https://user-images.githubusercontent.com/2328042/90383770-8331d580-e078-11ea-9d2a-1b4c4bb30ee5.png)
The dialog should be centred when first opened.
### Reproducible example

https://codesandbox.io/s/determined-voice-b5fcy?file=/src/index.js

### Additional context

The issue is fixed when you resize the screen.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 35.2.0 
| React            | 16.13.1
| Browser          | Chrome
| Operating System | Windows 10

**Comment by jamime** [comment]
FE-3038

**Comment by grabkowski** [comment]
solution for this issue is to trigger the `centerDialog` method in the `Dialog` component after the content is loaded.

**Comment by jamime** [comment]
The root cause of this is because the content of the dialog is changing.
