### ISSUE TITLE
FlatTable: Unable to resize table height

### ISSUE THREAD

**Issue by gedskikas** [Sage/carbon#3145]
### Current behaviour
On the FlatTable component, there is currently no way to expand a table beyond its content. If it has 3 rows of data for example, currently it's impossible to expand it to be 3 rows of data and the rest would be 'filled' space to the bottom of the page.

### Desired behaviour
We would like to be able to resize the table height, no matter its contents.

### Suggested solution
From my understanding the old Table component had a shrink prop, which could determine the height of the table on the page. Perhaps reintroducing something like this, to allow us to control the height?

### Describe alternatives you've considered
I don't have any alternative at the moment.

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 37.3.0
| react-scripts    | -
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.4
| Operating System | MacOS

**Comment by jamime** [comment]
FE-3060

**Comment by edleeks87** [comment]
The `FlatTable` now supports setting a `height` value released in `v48.7.0`

https://github.com/Sage/carbon/pull/3370#issuecomment-726126047
