### ISSUE TITLE
GridContainer inside Accordion in FireFox not displaying

### ISSUE THREAD

**Issue by nicktitchmarsh** [Sage/carbon#3146]
### Current behaviour
In Firefox, having a GridContainer inside an Accordion component causes the GridContainer not to be visible. Replicated the behaviour on the latest code and it seems to be an issue with the expanded height of the Accordion not being set correctly. 

<img width="1569" alt="Screenshot 2020-08-17 at 15 32 16" src="https://user-images.githubusercontent.com/69150954/90407879-ef273480-e09e-11ea-9dad-a03f6d68dc64.png">

### Expected behaviour

Accordion should expand correctly
![Screenshot 2020-08-17 at 15 27 43](https://user-images.githubusercontent.com/69150954/90407860-e6cef980-e09e-11ea-8804-d0f30b4345a6.png)

### Reproducible example
https://codesandbox.io/s/smoosh-tdd-p41eq?file=/src/index.js

**Comment by jamime** [comment]
The `GridContainer` is not designed to be used within components. However, I've still put this on the backlog (FE-3061) to ensure that this is achievable once the grid enhancements are delivered (FE-3025).
