### ISSUE TITLE
Warnings on Pager component

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3152]
### Current behaviour
Since I upgraded to the v37.3.0 (from the v24), I have several warning of "Failed prop type" when I use a paginated table.
They all are located on the Pager component and I have them if I only add a <Pager totalRecords={100} onPagination={() => {}} /> to my page.

### Expected behaviour
No warnings

### Reproducible example
https://codesandbox.io/s/xenodochial-babbage-nmmjj?file=/src/index.js

### Additional context
Some warnings are only visible with some options of the Pager component

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v37.3.0 |

**Comment by jamime** [comment]
![image](https://user-images.githubusercontent.com/2328042/90532460-2e24bb00-e16f-11ea-8833-1d6f3756d1c9.png)
