### ISSUE TITLE
Placing ReactNode Elements inside a ActionPopoverItem

### ISSUE THREAD

**Issue by sagedemdreisbusch** [Sage/carbon#3196]
## Feature request
We need to display some specific content inside the ActionPopoverItem. Therefore we would be happy to place any ReactNode inside the children section
### Current behaviour
Currently only string is allowed
### Desired behaviour
Also allow ReactNode as a type

### Suggested solution
Add ReactNode as PropType

### Describe alternatives you've considered
Otherwise we can not use the component

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 39.0.0
| react-scripts    | 3.4.3
| React            | 16.12.0
| Browser          | any
| npm              | 6.14.5
| Operating System | Windows 10 (19041.2212.31.0)

**Comment by ianforster-sage** [comment]
FE-3097
