### ISSUE TITLE
Message "title" prop invalid type

### ISSUE THREAD

**Issue by tboulis** [Sage/carbon#3203]
### Current behaviour
If you provide a component instead of a string as a title, a warning is thrown in the console:
```
Warning: Failed prop type: Invalid prop `title` of type `object` supplied to `MessageContent`, expected `string`.
    in MessageContent (created by Message)
```

### Expected behaviour
It shouldn't throw this warning, docs mention that title should be of type `node` and propTypes of the Message component are correct:
```

Message.propTypes = {
  /** set type of message based on new DLS standard */
  variant: _propTypes.default.oneOf(_optionsHelper.default.colors),

  /** set type of message. This is legacy property */
  as: _propTypes.default.string,

  /** set border to component */
  border: _propTypes.default.bool,

  /** set content to component */
  children: _propTypes.default.node,

  /** set custom class to component */
  className: _propTypes.default.string,

  /** set custom id to component root */
  id: _propTypes.default.string,

  /** show message component */
  open: _propTypes.default.bool,

  /** function runs when user click dismiss button */
  onDismiss: _propTypes.default.func,

  /** set corners to be rounded or sharp */
  roundedCorners: _propTypes.default.bool,

  /** set message title */
  title: _propTypes.default.node,

  /** set background to be invisible */
  transparent: _propTypes.default.bool,

  /** Determines if the close icon is shown */
  showCloseIcon: _propTypes.default.bool
};
```
### Reproducible example
https://codesandbox.io/s/vibrant-blackburn-67f7d?file=/src/index.js

### Additional context
![image](https://user-images.githubusercontent.com/24255041/92468686-373c0180-f1dc-11ea-8974-e111e6634f68.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 40.0.0
| carbon-factory   | - 
| react-scripts    | 3.4.3
| React            | 16.13.1
| Browser          | Chrome 85.0.4183.83 (Official Build) (64-bit)
| npm              | yarn@1.22.5
| Operating System | MacOS 10.15.6

**Comment by jamime** [comment]
We need to allow `node` for this historical reason
https://github.com/Sage/carbon/issues/1543
https://github.com/Sage/carbon/commit/5aae88808779f807f5634744859a0cc0a92a090c

**Comment by jamime** [comment]
FE-3142
