### ISSUE TITLE
Error raised on build Note Component when inlineControl are setted

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#3208]
### Current behaviour
When  using `Note` component and set `inlineControl` property.
It works in local but raised an error when it's build :
**Invariant Violation: <Note> inlineControl must be an instance of <ActionPopover>**
If we don't set `inlineControl` property it works but no `ActionPopover` is display :
![image](https://user-images.githubusercontent.com/60605396/92622730-ab9e9f80-f2c5-11ea-9b63-bb70e4fa9886.png)

### Expected behaviour
When  using `Note` component and set `inlineControl` property.
No error is raised and `ActionPopover` is display.
![image](https://user-images.githubusercontent.com/60605396/92623428-81011680-f2c6-11ea-95e5-48d49ed75b1c.png)

### Reproducible example
Set a `Note` component and set `inlineControl` property. 
Test on a **minified** version only (build environment).
https://codesandbox.io/s/laughing-cdn-97swo?file=/src/index.js

### Suggested solution(s)
Acces the function to display the component in  **minified** version.

### Additional context
None

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 38.1.1
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.2
| Operating System | Windows

**Comment by jamime** [comment]
From Slack:
> Looks like a bug to me,
unminified it works fine https://codesandbox.io/s/laughing-cdn-97swo?file=/src/index.js
I get the same error when minified. In this case, the function is minified to be function b(){...}
>
> ![image](https://user-images.githubusercontent.com/2328042/92629009-90339480-f2c5-11ea-83e6-150a4dfa8d92.png)
>
> https://github.com/Sage/carbon/blob/2ed3560ab5d72b59300daf8bf816c29ac5080921/src/components/note/__internal__/note.component.js#L33-L34

**Comment by ianforster-sage** [comment]
FE-3134
