### ISSUE TITLE
Sidebar: making sidebar content scrollable

### ISSUE THREAD

**Issue by gedskikas** [Sage/carbon#3221]
### Current behaviour
Currently when using the Sidebar component, whenever we fill the contents of the sidebar to reach the bottom of the page it doesn't automatically add in a scroll bar and it cuts off the content.

### Desired behaviour
For the sidebar component to allow scrollable content.

### Suggested solution
I don't have a suggested solution.

### Describe alternatives you've considered
I don't have any alternative at the moment.

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 37.3.0
| react-scripts    | -
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.4
| Operating System | MacOS

**Comment by jamime** [comment]
@edleeks87 has asked UX for some guidance.

**Comment by jamime** [comment]
UX have approved this.

**Comment by jamime** [comment]
FE-3158
