### ISSUE TITLE
Textarea label is not aligned with the input when is labelInline

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#3224]
### Current behaviour

Textarea label is not aligned with the input when is labelInline.

**Steps to reproduce:**
1. Open [textarea_component](https://carbon.sage.com/iframe.html?id=experimental-textarea--default&knob-cols=0&knob-rows=0&knob-placeholder=placeholder&knob-fieldHelp=&knob-characterLimit=&knob-inputWidth=100&knob-label=Textarea&knob-labelHelp=&knob-labelInline=true&knob-labelWidth=30&knob-labelAlign=undefined)
2. Check the alignment for the label. 

<img width="574" alt="Screenshot 2020-09-17 at 13 41 58" src="https://user-images.githubusercontent.com/34001198/93466617-d18efa00-f8ec-11ea-9a9c-541da5b12e52.png">

<img width="472" alt="Screenshot 2020-09-17 at 13 42 09" src="https://user-images.githubusercontent.com/34001198/93466622-d2c02700-f8ec-11ea-8f05-b3e7e2117de8.png">

### Expected behaviour

The `label` should be aligned with the `placeholder` or `text` inputed inside the input.

**Comment by DlgSHi** [comment]
FE-3151

**Comment by jamime** [comment]
Confirmed that these should be in alignment. @grabkowski suggested that the label is out of alignment, not the baseline of the input.
