### ISSUE TITLE
Control the margin/padding of somes components

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#3225]
## Feature request
We want to align text in several component so we need to have the controle of the margin or padding.
We also want to control the margin in the DialogFullScreen component between the heading and the children.

### Current behaviour

We don't have the control of the padding/margin of somes component.

> in red: what we want to remove
> in green/.blue: what we want to align

![image](https://user-images.githubusercontent.com/17121053/93493458-373eae80-f90c-11ea-84bf-acc31e25a330.png)

### Desired behaviour

1. Control the padding/margin of the content of a dialog full screen
2. Control the padding/margin of the title of the drawer to align with the title of the dialog full screen
3. Control maybe the padding/margin of the title of a dialog full screen.

### Suggested solution

add parameters to the concerned component

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-3152
