### ISSUE TITLE
Lazy load ActionPopover

### ISSUE THREAD

**Issue by maxdreisbusch** [Sage/carbon#3226]
## Feature request

ActionPopoverItem - BeforeOpenSubmenu Event

We want to load dynamic submenuentries to be displayed in a action popover. To load these it is neccessary to get an event prop which is trigegred right before the submenu would start to open. If triggered, we want to show a Loader (https://github.com/Sage/carbon/pull/3197) and send a request to load the items. When this request is answered we want to give the submenu some new entries.

### Current behaviour
The submenu opens but has no event to load data before opening

### Desired behaviour
Trigger a function of the wrapping component which can send a request to load the submenu entries

### Suggested solution
Adding a prop to pass a function for loading the submenu would be great

### Describe alternatives you've considered
Loading the data onCLick of the Main Popover event, but then we got a big performance issue

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 39.0.0
| react-scripts    | 3.4.3
| React            | 16.12.0
| Browser          | all
| npm              | 6.14.5
| Operating System | Windows - 19041.508

**Comment by jamime** [comment]
If this is related to #3197 I'd like us to implement a complete solution for this. I've asked UX for some designs and placed it on our backlog while we wait for those.

**Comment by clairedenning** [comment]
Not sure how the DS team can help at this point?

**Comment by samtjo** [comment]
Hi @clairedenning - they could say whether this is a pattern we want in the Design System, and if so, provide designs so we can carry out the work

**Comment by ingridzillinger** [comment]
Design System team reached out to the proposer: another solution has been found in the meantime. However, the team would like to use the Carbon component as requested. As a next step I asked them for the original designs. I'll keep you posted.

**Comment by ingridzillinger** [comment]
After consulting with the Solution Designer, we can close this ticket. It works well with the currently implemented solution.
From Swen Esser: "Since we have found a solution for the current app and would implement it differently in the future (loader on the button), we can close the feature request."

**Comment by samtjo** [comment]
Great thanks @ingridzillinger!
