### ISSUE TITLE
ActionPopover does not close when a sub menu item is clicked

### ISSUE THREAD

**Issue by abhoraniya** [Sage/carbon#3229]
### Current behaviour
The `ActionPopover` stays open after clicking on `submenu` `ActionPopoverItem`.

### Expected behaviour
We want to close the ActionPopover when the `ActionPopoverItem` in a `submenu` is clicked.

### Reproducible Example

https://carbon.sage.com/?path=/docs/design-system-action-popover--keyboard-access#with-a-sub-menu

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 39.0.0
| react-scripts    | 3.4.3
| React            | 16.12.0
| Browser          | all
| npm              | 6.14.5
| Operating System | Windows - 19041.508

**Comment by nicktitchmarsh** [comment]
FE-3237 has been raised and added to the backlog

**Comment by ianforster-sage** [comment]
Fixed https://github.com/Sage/carbon/pull/3493
