### ISSUE TITLE
Button as an icon displays prop type error

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#3236]
### Current behaviour

When using the button component and displaying an icon only for such an event as a delete button, there is a prop type warning in the console. ```Warning: Failed prop type: The prop `children` is marked as required in `Button`, but its value is `undefined`.```

### Expected behaviour

No error to appear

### Reproducible example

View developer console in:
https://codesandbox.io/s/muddy-leftpad-4ni2j?file=/src/index.js

### Suggested solution(s)

The prop type to only expect children if the icon is prop is not set.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 41.1.1
| carbon-factory   | N/A
| react-scripts    | 3.0.1
| React            | 16.8.6
| Browser          | Chrome
| npm              | N/A
| Operating System | codesandbox

**Comment by nicktitchmarsh** [comment]
More information required from UX team for adherence to design patterns.

**Comment by nicktitchmarsh** [comment]
A workaround is available for this issue, https://codesandbox.io/s/keen-firefly-2uob4?file=/src/index.js

This will get rid of the error however we are getting information from UX before providing a further fix

**Comment by nicktitchmarsh** [comment]
Feedback from UX: we would want the ability to have icon buttons without text. This would be very useful for areas where space is at a premium, and the icon is unambiguous. We'd likely want a tooltip for the icon though.

**Comment by nicktitchmarsh** [comment]
FE-3240 has been raised and added to the backlog
