### ISSUE TITLE
ActionPopoverItem Submenu - Typescript Error

### ISSUE THREAD

**Issue by abhoraniya** [Sage/carbon#3237]
### Current behaviour

I created a submenu to the ActionPopoverItem but It shows a typescript error in the submenu. It only works if a line above @ts-ignore is written

TS2322: Type 'Element' is not assignable to type 'FunctionComponent<ActionPopoverMenuProps>'.   Type 'Element' provides no match for the signature '(props: PropsWithChildren<ActionPopoverMenuProps>, context?: any): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<...>)> | null) | (new (props: any) => Component<...>)> | null'.  action-popover-item.d.ts(10, 3): The expected type comes from property 'submenu' which is declared here on type 'IntrinsicAttributes & ActionPopoverItemProps & { children?: ReactNode; }'

### Expected behaviour
It should support without @ts-ignore

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 39.0.0
| react-scripts    | 3.4.3
| React            | 16.12.0
| Browser          | all
| npm              | 6.14.5
| Operating System | Windows - 19041.508

**Comment by nicktitchmarsh** [comment]
Unable to replicate this in latest Carbon React 41.1.1 (https://codesandbox.io/s/festive-noether-36sv1?file=/src/index.js).

Please can you provide a reproducible example

**Comment by abhoraniya** [comment]
I have created custom functional component. You can find the error in ActionPopover.tsx file 
Hier is the link - https://codesandbox.io/s/gallant-night-cbhqu?file=/src/index.js

**Comment by edleeks87** [comment]
FE-3199 raised and on our backlog
