### ISSUE TITLE
Unable to clear Select component value

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#3244]
### Current behaviour

When the new select component is `controlled` it is not possible to change it back to the state where it shows the placeholder value.

![2020-09-28 16 55 14](https://user-images.githubusercontent.com/2328042/94456841-ad180500-01ab-11eb-9907-b36166a3b6ff.gif)

### Expected behaviour
In the codesandbox example pressing the button should clear the current selected value.

### Reproducible example
https://codesandbox.io/s/clear-select-z9eb1

### Suggested solution(s)
N/A

### Additional context
N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |41.1.1

**Comment by ianforster-sage** [comment]
FE-3188

**Comment by ianforster-sage** [comment]
Fixed in https://github.com/Sage/carbon/pull/3284
