### ISSUE TITLE
Select: on a Formik form, the Select component remains in error

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#3262]
### Current behaviour

Since the last carbon version 42.3.0, we have a problem with the validation of a Select component on a Formik form. The field remains in error despite selecting a value and after leaving it. This works with the 42.2.0.

### Reproducible example

https://codesandbox.io/s/myformikform-2ysql?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 42.3.0
| react-scripts    | 3.4.3
| React            | 16.13.1
| Browser          | all
| npm              | 6.14.5
| Operating System | Windows 10

**Comment by ianforster-sage** [comment]
FE-3207
