### ISSUE TITLE
Numeral date errors when no dateFormat provided

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#3264]
### Current behaviour

`dateFormat` is an optional prop, but if it is omitted a prop type error is thrown.

![image](https://user-images.githubusercontent.com/2328042/95371183-c159b180-08d1-11eb-97cf-3cd95a8d0d5d.png)
![image](https://user-images.githubusercontent.com/2328042/95371324-f5cd6d80-08d1-11eb-975d-aac58bba6214.png)

### Expected behaviour

No errors should be thrown.

### Reproducible example
```jsx
<NumeralDate
        defaultValue={{
          dd: "01",
          mm: "02",
          yyyy: "2020"
        }}
      />
```
https://codesandbox.io/s/numeral-date-date-format-hp28e

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |42.3.1|

**Comment by nicktitchmarsh** [comment]
FE-3225 has been raised to look at this
