### ISSUE TITLE
Switch value should be optional

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#3265]
### Current behaviour
The switch component requires a `value` however, the underlying component is a checkbox.

We currently support using these as HTML Form elements, sometimes we refer this as uncontrolled.

A HTML checkbox has the attribute `value` but it is optional, when it is omitted, the value is `on` when received by the server.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value

![image](https://user-images.githubusercontent.com/2328042/95379449-50b89200-08dd-11eb-90a2-dacff6d15e58.png)

The mdx stories currently error when running them locally
![image](https://user-images.githubusercontent.com/2328042/95379588-7fcf0380-08dd-11eb-9301-d284978196c2.png)

### Expected behaviour

`value` should be optional.

### Reproducible example
https://carbon.sage.com/?path=/docs/experimental-switch--basic

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |42.3.1

**Comment by nicktitchmarsh** [comment]
FE-3224 has been raise to change this
