### ISSUE TITLE
GridContainer Prop Documentation Issue - Invalid Child Warning

### ISSUE THREAD

**Issue by smcguirk-sage** [Sage/carbon#3272]
### Current behaviour
Use of GridContainer with single GridItem throws 'invalid child' warnings:
```Warning: Failed prop type: Invalid prop `children` supplied to `GridContainer`.```

Using more than one GridItem removes warnings.

Documentation does not specify a need for more than 1 GridItem - https://carbon.sage.com/?path=/docs/design-system-grid--basic#gridcontainer-props
![GridContainerDoc](https://user-images.githubusercontent.com/61419656/95575405-946ae300-0a26-11eb-900f-118dddc5360e.png)

### Expected behaviour
Documentation reflects behaviour

### Reproducible example
Reproducible here - https://codesandbox.io/s/kind-tereshkova-98sek?file=/src/index.js

Once loaded, check console for error.

Adding a second GridItem will fix the warning

### Suggested solution(s)
Either update the documentation to specify the requirement of more than 1 GridItem child or update the GridContainer component to allow the use of a singular GridItem child

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 41.1.1 |
| carbon-factory   |  |
| react-scripts    |  |
| React            | 16.13.1 |
| Browser          | N/A |
| npm              | 6.14.4 |
| Operating System | MacOS 10.15.6 |

**Comment by nicktitchmarsh** [comment]
FE-3222 raised to look into this
