### ISSUE TITLE
Intermittent chromatic errors

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#3278]
### Current behaviour

We are aware of a few stories that produce visual artifacts, most of these are legacy and are scheduled to be removed and have been disabled but in theory it can happen to any component. Typical culprits are Profile and Select (autofocus)

![2020-10-12 09 58 38](https://user-images.githubusercontent.com/2328042/95727028-91176780-0c71-11eb-9927-eb4dbd8acb11.gif)

### Expected behaviour

Chromatic should not show differences on components that were not modified in this PR.

### Reproducible example
https://www.chromatic.com/snapshot?appId=5ecf782fe724630022d27d7d&id=5f6908080a0b030022a15fc0
https://www.chromatic.com/snapshot?appId=5ecf782fe724630022d27d7d&id=5ef0e5f867b69000224cc721

### Suggested solution(s)
Chromatic has an updated guide on how to load fonts. 
https://www.chromatic.com/docs/resource-loading#loading-custom-fonts

I think we should convert the following SCSS to CSS

https://github.com/Sage/carbon/blob/8990b8eb5c07a6dbc3399888e077f9f1195b4aa2/.storybook/preview.js#L7

Then we should load it with this approach

![image](https://user-images.githubusercontent.com/2328042/95726738-354cde80-0c71-11eb-972e-e17cdd7964fd.png)

### Additional context
N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |42.3.2|

**Comment by nicktitchmarsh** [comment]
FE-3221 raised to look into this

**Comment by sjohnson-sage** [comment]
Pre-loading of fonts in Storybook was added in https://github.com/Sage/carbon/pull/4151 and we've had no issues since - so I'm closing this
