### ISSUE TITLE
Menu/MenuItem - Error setIsOpenSubmenu is not a function

### ISSUE THREAD

**Issue by jlongridge** [Sage/carbon#3286]
### Current behaviour
Release 39.1.0 added keyboard navigation which causes an error when menu items are split between components.  

```js
Error: Uncaught [TypeError: setIsOpenSubmenu is not a function]
```

```
const App = () => {
  return (
    <Menu>
      <MenuItem>Menu Item 1</MenuItem>
      <MySubMenu />
    </Menu>
  );
};

const MySubMenu = () => {
  return (
    <MenuItem submenu="Foo">
      <MenuItem>Bar</MenuItem>
      <MenuItem>Baz</MenuItem>
    </MenuItem>
  );
};
```
Menu passes setIsOpenSubmenu to the MenuItem if you have an extra component inbetween that could be the cause.
### Expected behaviour
No JS errors when MenuItems are
Menu passes setIsOpenSubmenu to the MenuItem, it should be possible to have an extra component in between without causing js errors.

### Reproducible example
https://codesandbox.io/s/patient-fog-xj9qx?file=/src/App.js

### Your environment
Carbon >39.10

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | > 39.1.0
| react-scripts    | 3.4.3 
| React            | 16.13.1
| Browser          | Chrome
| Operating System | Mac

**Comment by jamime** [comment]
I think we'll look to solve this using [context](https://reactjs.org/docs/context.html) to pass the required props to the children.

**Comment by DipperTheDan** [comment]
FE-3243
