### ISSUE TITLE
Menu/MenuItem : bad alignment

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3292]
### Current behaviour
If I use onClick prop on a MenuItem, it is not aligned with the other

### Expected behaviour
All MenuItems are correctly aligned

### Reproducible example
https://codesandbox.io/s/amazing-volhard-t6gzo?file=/src/index.js

![image](https://user-images.githubusercontent.com/2328042/95996039-2198a800-0e2a-11eb-9cf2-7ec8a6414792.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 42.3.2

**Comment by DipperTheDan** [comment]
FE-3242

**Comment by sjohnson-sage** [comment]
Fixed in v54.4.0
