### ISSUE TITLE
Sidebar : error when closing with enableBackgroundUI

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3295]
### Current behaviour
When I close the Sidebar with enableBackgroundUI=true, I have the following error : this.removeFocusTrap is not a function

### Expected behaviour
The Sidebar is closed without error

### Reproducible example
https://codesandbox.io/s/focused-tree-uz49u?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 42.3.2

**Comment by DipperTheDan** [comment]
FE-3241
