### ISSUE TITLE
Help: wrong alignment for the bottom/top left alignment

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#3316]
### Current behaviour

When the tooltip is set to be shown `top`/`bottom` + `left` alignment - that the tooltip point arrow is shown not in the middle of the icon 

<img width="390" alt="Screenshot 2020-10-21 at 13 46 53" src="https://user-images.githubusercontent.com/34001198/96716452-56b27680-13a5-11eb-8368-977b4a8a227a.png">
<img width="212" alt="Screenshot 2020-10-21 at 13 56 34" src="https://user-images.githubusercontent.com/34001198/96716456-57e3a380-13a5-11eb-9a38-b355c30ddae3.png">

### Expected behaviour

The tooltip pointer should be aligned in the middle of the icon.

<img width="188" alt="Screenshot 2020-10-21 at 14 00 19" src="https://user-images.githubusercontent.com/34001198/96716775-c45ea280-13a5-11eb-8ef0-2707d979201a.png">

### Reproducible example

[An example](https://carbon.sage.com/iframe.html?id=help--default&knob-tooltipPosition=top&knob-tooltipAlign=left)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 44.1.0 |

**Comment by edleeks87** [comment]
FE-3271
