### ISSUE TITLE
Document dialog focusFirstElement

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#3319]
### Current behaviour
Dialog props are not documented in MDX.

### Desired behaviour
A MDX example showing how to focus an element when the dialog is opened.

### Suggested solution
* Update prop table
* Add MDX example

### Describe alternatives you've considered
N/A

### Additional context
Question raised by @gusch in Slack.

@sjohnson-sage did some work on this and demoed a Codesandbox, we could use that example ~if he still has it.~
https://codesandbox.io/s/funny-sky-89sn1

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |44.1.0

**Comment by sjohnson-sage** [comment]
Codesandbox mentioned above is here: https://codesandbox.io/s/funny-sky-89sn1

**Comment by edleeks87** [comment]
FE-3264
