### ISSUE TITLE
Last PopoverItem not displayed 

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#3321]
PopoverItem not displayed if last 

### Current behaviour
IF we have ActionPopoverItem Items with component in  below like GridContainer with Button for example : 
The latest items aren't displayed correctly .
In the sendBox https://codesandbox.io/s/gallant-bhaskara-c1ujf?file=/src/index.js:2693-2706 
You can see that Test3 is not displayed.
But if we resize the page (only in the sandbox) => We display correctly the all of the items.
We have the same problem with list of entities (test3 is not displayed) : 
![image](https://user-images.githubusercontent.com/17086956/96845981-9a62ba00-1451-11eb-9ec0-9f908c08d3c3.png)

### Expected behaviour

All ActionPopoverItem  itmes should be displayed 

### Reproducible example

https://codesandbox.io/s/gallant-bhaskara-c1ujf?file=/src/index.js:2693-2706

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 44.1.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by edleeks87** [comment]
FE-3265
