### ISSUE TITLE
The select component is not displaying the selected value when value is an object

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#3327]
### Current behaviour

When using the select component in controlled mode where the values of the option elements are an object, after selection and the value is fed back to the component it does not display the selected option.

### Expected behaviour

I'd expect passing the value back to the Select, the selected option to be visible.

### Reproducible example

Example extended by Jamie to show a string and an object example:

https://codesandbox.io/s/select-object-phil-bo3yc

### Additional context

Without this working we're having to track value as well as the additional value for all of our select components within our form.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v45.1.0

**Comment by edleeks87** [comment]
FE-3266

**Comment by grabkowski** [comment]
@philearley Looks like this is not a Carbon issue, you had a bug in your codesandbox example - every time the state is changed, component will re-render and all these options will be replaced with newly rendered ones. When this happens, object that is being kept in the `value` state is no longer the object found in options, so nothing will be displayed. You have to keep your options in between renders.

I have corrected that example:
https://codesandbox.io/s/select-object-phil-forked-6ghiw

**Comment by grabkowski** [comment]
I have found that there is also a PropType warning in the console, so I have committed a fix for that
