### ISSUE TITLE
Toast -> stacked - bug with logic in story

### ISSUE THREAD

**Issue by DipperTheDan** [Sage/carbon#3336]
### Current behaviour
![toast_stacked_bug](https://user-images.githubusercontent.com/56251247/97469067-e2944780-193d-11eb-84f4-5be522441d91.gif)

### Expected behaviour
Component should not get stuck in an infinite loop of being open once A or B is closed and the button is clicked.

### Reproducible example
https://carbon.sage.com/?path=/story/design-system-toast--stacked

### Suggested solution(s)
Apply the same logic as is utilised in the `stacked-delay` story for the Toast component.
https://carbon.sage.com/?path=/story/design-system-toast--stacked-delayed

### Additional context
N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react    | 47.1.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by jamime** [comment]
FE-3282
