### ISSUE TITLE
Storybook themes dropdown shows the wrong colours

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3338]
**Current behaviour**
The colour square next to the none theme and the mint theme in the drop down menu is #00a376.

**Jira Ticket**
FE-3278

**Expected behaviour**
The colour square next to the none theme in the drop down menu should be #008200.
The colour square next to the mint theme in the drop down menu should be #00815D.

**Reproducible example**
This can be reproduced by looking at theCarbon storybook on the master branch.

**Suggested solution(s)**
Change the colours in storybook 

**Your environment**
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 42.5.2 
| carbon-factory   | 
| react-scripts    | 
| React          | 16.12.0
| Browser          | Safari, Chrome, Edge, Firefox
| npm              | 6.14.8
| Operating System | macOS Catalina v10.15.7

**Comment by sjohnson-sage** [comment]
This has been changed so I'll close this issue
