### ISSUE TITLE
Tabbing behaviour is inconsistent in Menu

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#3343]
### Current behaviour

The tabbing behaviour in the Menu component is inconsistent, if you press `tab` whilst a `MenuItem` without a submenu it focuses the first item, but if you navigate to a submenu item and press `tab` it moves focus away from the `Menu`. This also effects the alpha key navigation as a result, after you have tabbed away from the submenu item if you then refocus the menu and press the `m` key it will jump to the item that was next before you originally tabbed away.

[example of weird keyboard behavior in menu.mov.zip](https://github.com/Sage/carbon/files/5474485/example.of.weird.keyboard.behavior.in.menu.mov.zip)

### Expected behaviour

I would expect it to behave like this https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html

### Reproducible example

Issue is present in latest version and can be seen here https://carbon.sage.com/?path=/story/design-system-menu--default-story

### Suggested solution(s)

Update the `actualFocusedItemIndex` ref when tabbing occurs

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by nicktitchmarsh** [comment]
FE-3304 has been raised for this
