### ISSUE TITLE
Unable to scroll tab component

### ISSUE THREAD

**Issue by StevenMWood** [Sage/carbon#3352]
## Feature request
Tab components should be scrollable to allow non visible tabs to be shown.

### Current behaviour
If there are too many tabs on a tab component to display all on the screen at once there is no way to scroll the tab component to see all the non-visible tabs.

### Desired behaviour
As per feature request.

### Suggested solution
Allow the tabs to be scrollable or provide a paging mechanism to cycle through them.

### Describe alternatives you've considered
None.

### Additional context
None.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by nicktitchmarsh** [comment]
FE-3302 has been raised to address this

**Comment by nicktitchmarsh** [comment]
An interim workaround could be to use a Box component with the overflow props set until we can get this included in Carbon as standard.
