### ISSUE TITLE
MultiActionButton : display on top

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3360]
## Feature request
The MultiActionButton should display the buttons on top if there is not enough space to display on the bottom.
Or at least a prop should allow that.

### Current behaviour
The buttons are always displayed on the bottom

### Desired behaviour
The MultiActionButton should display the buttons on top if there is not enough space to display on the bottom.
Or at least a prop should allow that.

### Describe alternatives you've considered
I'm adding a "bottom: 40px" to my style

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 47 |

**Comment by nicktitchmarsh** [comment]
FE-3301 has been raised to address this

**Comment by ianforster-sage** [comment]
This has been fixed with the implementation of popper.js. See https://carbon.sage.com/?path=/docs/multi-action-button--default-story for an example
