### ISSUE TITLE
Date : display on top

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3362]
## Feature request
In v8, there was of showPickerOnTop prop to display the picker on top when too close to the bottom of the screen.
Enable this prop again or something automatic

### Current behaviour
The picker is always display under the date component

### Desired behaviour
As defined in the feature

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.6.0 |

**Comment by nicktitchmarsh** [comment]
FE-3300 has been raised and added to the backlog

**Comment by sjohnson-sage** [comment]
Date picker auto positioning added in https://github.com/Sage/carbon/releases/tag/v68.5.0
