### ISSUE TITLE
Change behaviour of multiple Tabs Components when grouped together in a container

### ISSUE THREAD

**Issue by ianforster-sage** [Sage/carbon#3363]
### Current behaviour
Currently when multiple Tabs components work together in a containing element each Tab group highlights it's first Tab as active. 
![Screenshot 2020-11-09 at 09 44 44](https://user-images.githubusercontent.com/35449967/98525844-f52d4b80-2270-11eb-84e1-a0a56223b775.png)

### Desired behaviour
We should be able to override this default and allow multiple Tabs components to work together as a linked group with only one active Tab.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.5.0 |
| react-scripts    | 
| React            | 12.18.0 |
| Browser          |
| npm              |
| Operating System |

**Comment by edleeks87** [comment]
https://codesandbox.io/s/long-architecture-pokvf?file=/src/index.js

This functionality already exists, the active tabs can be set using the `selectedTabId`. We haven't really documented it well enough but we'll make sure it is done now. It might be worth looking into it at some point as the interface could be tidied up IMO
