### ISSUE TITLE
FlatTable showing compilation errors

### ISSUE THREAD

**Issue by Siphenathi-Nathi** [Sage/carbon#3369]
### Current behaviour
I am trying to use carbon flat table and i am getting some compilation errors. I just copied the code straight from the carbon docs. 
![image](https://user-images.githubusercontent.com/51409045/98682420-91884880-236c-11eb-850e-f25827ceac7d.png)

### Expected behaviour
I did not expect to get compilation errors

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 31.1.1, in CodeSandbox its 48.6.1
| carbon-factory   | 
| react-scripts    | 
| React            | 16.13.1
| Browser          | chrome
| npm              |
| Operating System | windows 10

**Comment by sjohnson-sage** [comment]
Changing the ts definition for the `children` prop in https://github.com/Sage/carbon/blob/master/src/components/flat-table/flat-table-head/flat-table-head.d.ts to not be an array should solve this issue

**Comment by edleeks87** [comment]
I'm about to raise a PR with some changes to flat-table so I'll update the type to be a `React.ReactNode` for now as part of it; that's how the prop type is defined in https://github.com/Sage/carbon/blob/master/src/components/flat-table/flat-table-head/flat-table-head.component.js

**Comment by Siphenathi-Nathi** [comment]
Hi guys, after you made some changes and released carbon flatTable version 48.7.0 I am getting other compilation errors. I am not sure whether is there any other thing i have to do to the project except installing flatTable version 48.7.0. 
![image](https://user-images.githubusercontent.com/51409045/99038332-f8387c80-258d-11eb-97a2-3f77f521a9ea.png)

**Comment by edleeks87** [comment]
My apologies @Siphenathi-Nathi I'm reopening this issue as there's some more incorrect definitions that we need to fix, I'll look to raise a PR to get them fixed today
