### ISSUE TITLE
Storybook Zoom on Docs tab

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3379]
### Current behaviour

When zooming in (using the buttons above the window) on a component on the canvas and then switching to the docs tab the window remains zoomed in/out but the buttons to change the zoom are no longer displayed 

### Expected behaviour
After visiting other storybook websites I think the expected behaviour should be that the docs tab remains the same level of zoomed in, independent of what has happened in the canvas tab.

### Reproducible example
- Visit - https://carbon.sage.com/?path=/story/design-system-accordion--default-story
- Zoom in using the buttons on the component in the canvas
- Click on the docs tab

### Suggested solution(s)
Either reset the docs tab viewpoint size each time it is changed to the docs tab or include the zoom in tools on the doc tab.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  48.7.0
| carbon-factory   | 
| react-scripts    | 
| React            |
| Browser          | Chrome
| npm              |
| Operating System | MacOs Catalina

**Comment by Alec-Walker-Sage** [comment]
FE-3314

**Comment by sjohnson-sage** [comment]
Closing as this has been resolved by updating Storybook to v6 in https://github.com/Sage/carbon/releases/tag/v66.18.0
