### ISSUE TITLE
MultiActionButton items not displayed  inside Accordion

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#3385]
MultiActionButton items are not displayed  inside Accordion 

### Current behaviour
IF we have MultiActionButton inside the accordion the items are not displayed   : 
In the sendBox https://codesandbox.io/s/condescending-tdd-kk0ib?file=/src/index.js 
The items are displayed only if we resize the page.

### Expected behaviour

All  itmes should be displayed 

### Reproducible example

https://codesandbox.io/s/condescending-tdd-kk0ib?file=/src/index.js 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.7.1
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-3331
