### ISSUE TITLE
MultiSelect component - The icon is displayed outside the Pill component into Dialog component

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#3397]
### Current behaviour

When we add a `MultiSelect` into a dialog, the close icon of the Pill is displayed outside the `Pill`. See picture:
![image](https://user-images.githubusercontent.com/38658070/99384998-9b5ffd80-28d0-11eb-9a63-b956386afb82.png)
 

### Expected behaviour

We expect that the closed icon is displayed into the `Pill`. See Picture:
![image](https://user-images.githubusercontent.com/38658070/99395689-16c9ab00-28e1-11eb-8238-7ad0dd777aee.png)

### Reproducible example

https://codesandbox.io/s/laughing-wilson-4lvbp?file=/src/index.js
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.7.1
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.6
| Browser          | Chrome
| npm              |
| Operating System | Windows

**Comment by sjohnson-sage** [comment]
This has been investigated and looks like a Pill issue rather than a MultiSelect one. It will be added to the backlog and fixed

**Comment by sjohnson-sage** [comment]
FE-3328
