### ISSUE TITLE
Button Component incorrect styling when using renderRouterLink

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#3398]
### Current behaviour

As demonstrated in this code sandbox below, when using the renderRouterLink on button, the styling for A tag overrides the button and adds an underline text.

https://codesandbox.io/s/funny-ritchie-y20f1?file=/src/index.js:572-588

![Screenshot 2020-11-17 at 13 40 21](https://user-images.githubusercontent.com/2411024/99397090-796b7880-28da-11eb-850b-8220e25c5fa7.png)

### Expected behaviour

When using the renderRouterLink, the button styling should match all default button styling, with no underlined text.

![Screenshot 2020-11-17 at 13 42 28](https://user-images.githubusercontent.com/2411024/99397287-c3545e80-28da-11eb-8808-1cb0057e683d.png)

### Reproducible example
https://codesandbox.io/s/funny-ritchie-y20f1?file=/src/index.js:572-588

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react | latest (v48.7.1)
| carbon-factory   | n/a
| react-scripts    | n/a
| React            | v16
| Browser          | all
| npm              | 6.14.x
| Operating System |

**Comment by edleeks87** [comment]
Looking into this a bit more the fix isn't general enough so I'm going to take it out of the carbon codebase. We'll need to do some refactoring as the implementation isn't quite right. In the meantime if consumers are using `RouterLink` from `react-router-dom` they can fix the styling with

```renderRouterLink={(routerProps) => <RouterLink {...routerProps} style={{ textDecoration: "none" }}/>}```

**Comment by sjohnson-sage** [comment]
FE-3327

**Comment by jamime** [comment]
Investigate the best solution FE-3332

**Comment by sjohnson-sage** [comment]
I'm going to close this as the `renderRouterLink` prop now no longer exists on `Button` as of v64.0.0. 

Detailed guidance on how to use React components as router links can be found here: https://carbon.sage.com/?path=/docs/documentation-usage-with-routing--page
