### ISSUE TITLE
Multiselect component - a pill disappears when push ENTER from an other component

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#3405]
### Current behaviour

![multiselect](https://user-images.githubusercontent.com/17083504/99540146-70001000-29af-11eb-9887-a0fbb2b9f742.gif)
It's in the case of a formik form and on a dialog component.

### Expected behaviour

The  pill doesn't have to disappear when push ENTER.

### Reproducible example

https://codesandbox.io/s/myformikform-forked-fobk5?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |49.0.2
| carbon-factory   |
| react-scripts    | 
| React            |16.13.1
| Browser          |Chrome
| npm              |
| Operating System |Windows

**Comment by jamime** [comment]
Confirmed on `49.0.2` using our official example.

https://codesandbox.io/s/gh-3405-tyyvm

![2020-11-18 14 55 01](https://user-images.githubusercontent.com/2328042/99546200-19460680-29ae-11eb-8af2-a929da27952f.gif)

**Comment by grabkowski** [comment]
Looks like pressing Enter anywhere in Form triggers onClick in the Icon Button which is part of the Pill Component

**Comment by jamime** [comment]
We've identified that this is because `IconButton` has no type, therefore is `type="submit"` which is automatically called when pressing `Enter` when within a `Form`. We'll need to define `type="button"` on the `IconButton` component.

**Comment by edleeks87** [comment]
FE-3336 created to add missing types to the buttons in carbon
