### ISSUE TITLE
Message component does not have sufficient voice over information

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3406]
### Current behaviour

When focusing on the close message button the Voice Over provides the information "button".

### Expected behaviour

There should be enough information to describe the button as when you press it, it will close the message.

### Reproducible example
Visit message in the carbon library

### Suggested solution(s)
Add an aria label to describe it `<button aria-label="Close" class="close">X</button>`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 49.0.2
| carbon-factory   |
| react-scripts    | 
| React            | 0.11.5
| Browser          | Chromne
| npm              |
| Operating System | Catalina OS

**Comment by jamime** [comment]
https://carbon.sage.com/?path=/docs/message--default-story

We need to consider i18n here too.

**Comment by Alec-Walker-Sage** [comment]
FE-3335
