### ISSUE TITLE
Dialog does not reposition itself when content changes in size

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3411]
### Current behaviour
I have a dialog which has two states: view and edit. Upon clicking edit, the content within the dialog will change from the view to the fields for editing. However, given that the fields cause the content for the edit state of the dialog to be much larger than the view state of the dialog, the dialog has to resize.

The issue is that when the dialog is opened in the view state, it is positioned directly the middle of the screen. When I update the component with new fields, the top of the dialog does not move to reposition itself, and the dialog grows straight downwards into the bottom of the page.

### Expected behaviour
Dialog adjusts location on screen when the content within changes, or alternatively there is a way I can tell the dialog when it needs to re-centre itself.

### Reproducible example
https://codesandbox.io/s/naughty-black-ieewi

**Comment by jamime** [comment]
Hi @limcoc thanks for raising this. Are you a Sage employee? If so, please contact me on Teams so I can triage this issue appropriately.

**Comment by jamime** [comment]
FE-3384

**Comment by jamime** [comment]
Also requested by Petrus/CM.

**Comment by DipperTheDan** [comment]
Issue is closed as this was fixed in v56.0.1.
