### ISSUE TITLE
Flat Table - Previous button is automatically selected when brought into focus using the keyboard

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3412]
### Current behaviour
If a keyboard is used to navigate around the pagination area, when the Previous button is brought into focus the table contents update to the previous page's contents despite the button not being selected and the correct page number maintained.

### Expected behaviour
Page selection and table contents do not update until the new option is selected with the Enter key.

### Reproducible example
https://carbon.sage.com/?path=/story/design-system-flat-table--paginated

### Suggested solution(s)
Fix so that the table contents only update when a new option is actively selected

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 49.2.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.3
| Browser          | Safari, Chrome, Firefox, Edge Chromium
| npm              | 6.14.8
| Operating System | macOS Catalina version 10.15.7

**Comment by sianford** [comment]
FE-3341

**Comment by ianforster-sage** [comment]
Linked to https://github.com/Sage/carbon/issues/3413

**Comment by sianford** [comment]
Tested in Safari, Chrome and Firefox on 28/01/2021 (ID). Testing passed ✅
