### ISSUE TITLE
Action Popover - Cannot exit a popover with a submenu using the keyboard

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3414]
### Current behaviour
When you're using the keyboard with Action Popover, if you open an Action Popover with sub menu items you cannot escape from it with the `Esc` key. It only closes the sub menu items, not the whole Action Popover. If you tab away from it, focus is lost and cannot be regained using the keyboard.

### Expected behaviour
The sub menu is closed then the first level menu is closed. Pressing tab moves to the next tabbable content.

### Reproducible example
https://carbon.sage.com/?path=/story/design-system-action-popover--keyboard-access-right-aligned-submenu

### Suggested solution(s)
Fix so that pressing the `Esc` key closes both levels of Action Popover. Focus is retained so when `Tab` is pressed it moves to the next tabbable content.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 49.2.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.8.3
| Browser          | Safari, Chrome, Firefox, Edge Chromium
| npm              | 6.14.8
| Operating System | macOS Catalina version 10.15.7

**Comment by sianford** [comment]
FE-3343

**Comment by ianforster-sage** [comment]
released in v54.3.1
