### ISSUE TITLE
Unit Test: Warning appears when we use Dd object in a list

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#3420]
### Current behaviour
warning on unit test when we put Dd object in a list (2 cases):
- without prop "key" in Dd object. This warning raised is:  Warning: Each child in a list should have a unique "key" prop.
- with prop "key" in Dd object.  This warning raised is: Warning: Dd: `key` is not a prop. Trying to access it will result in `undefined` being returned.

### Expected behaviour
No warning on unit test when we put Dd object in a list

### Reproducible example
https://codesandbox.io/s/dreamy-snyder-o5xl7?file=/src/index.js

**Comment by edleeks87** [comment]
FE-3372

**Comment by edleeks87** [comment]
Updated the codesandbox to remove the warning about each child having a key https://codesandbox.io/s/dreamy-snyder-o5xl72-forked-1dj3j?file=/src/index.js

**Comment by bulaj** [comment]
After @edleeks87 updates to codesandbox there seems to be no issues in library itself.
