### ISSUE TITLE
Pagination (Pager) does not resize correctly

### ISSUE THREAD

**Issue by SAHesse** [Sage/carbon#3425]
**Current behaviour**

When a list is smaller and shown in a dialog, the Pager component does not resize. 

![resize_pagination_1](https://user-images.githubusercontent.com/50664394/100110401-2d39ae80-2e6d-11eb-8e62-a05ead50c5ae.PNG)

**Expected behaviour**

Our XD team proposed a solution for that. Would it be possible to add that functionality to the Pager component?

![pagination_styled](https://user-images.githubusercontent.com/50664394/100110405-2e6adb80-2e6d-11eb-9791-3fae4f11c892.PNG)

**Your environment**

Software | Version(s)
carbon-react | 47.0.0
react-scripts | 3.4.4
react | 16.14.0

**Comment by edleeks87** [comment]
Hi @SAHesse we have some future enhancements planned for the Pager component as part of FE-3269 that will address the lack of responsive styling you've raised, I'll link this issue to the ticket so it has visibility when the work is picked up
