### ISSUE TITLE
FilterableSelect: value is not visible on first render

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3431]
### Current behaviour
I am fetching data in the useEffect and set an array which will be used to create the options of my FilterableSelect. 
That select has a predetermined value but upon render, that value is not selected. I have to expand the select and loose focus to see the correct option selected.

It works with a simple Select

### Expected behaviour
The correct value is selected after data are fetched and rendered.

### Reproducible example
 https://codesandbox.io/s/objective-fast-4n17j?file=/src/index.js 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.6.1 |

**Comment by jamime** [comment]
@grabkowski confirmed that this is a bug.

**Comment by jamime** [comment]
Confirmed in 50.3.0

**Comment by ianforster-sage** [comment]
FE-3385
