### ISSUE TITLE
Box Component: Extending the component to provide overflow-wrap prop

### ISSUE THREAD

**Issue by Manisureal** [Sage/carbon#3438]
### Current behaviour
 Currently, long character words just overflow the specified width of the box component.

### Desired behaviour

The ability to avoid long word characters overflowing and instead wrap onto a new line.

### Suggested solution

We should have access to this prop on the Box component.

### Describe alternatives you've considered

To use our own custom styled-component to extend the Box component so we can have access to the over-flow CSS property. handle it - https://styled-components.com/docs/basics#extending-styles

### Additional context

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.3.1
| react-scripts    | -
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.9.0
| Operating System | MacOS Mojave

**Comment by jamime** [comment]
We're going to speak to the DLS team about this, we'll update once we know more.

**Comment by ianforster-sage** [comment]
Still no word back from DLS team. I'll chase this again in the new year.

**Comment by ianforster-sage** [comment]
FE-3483

**Comment by jamime** [comment]
We've had no response from DLS. We've decided to go ahead an implement this.
