### ISSUE TITLE
Disable submit button on TextEditor when display error icon

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#3444]
## Feature request
The TextEditor component can raise an error icon with a pop up message and have a property to disable the submit button (with a text couting the error as Form component). 

### Current behaviour
The TextEditor component can raise an error icon with a pop up message, the submit button isn't disable and user can submit bad values.
![image](https://user-images.githubusercontent.com/60605396/100455820-a7fa0800-30bf-11eb-8006-84449bcd51c2.png)

https://codesandbox.io/s/carbon-quickstart-forked-80btt?file=/src/index.js

### Desired behaviour
The TextEditor component can raise an error icon with a pop up message, the submit button is disable and user can't submit bad values with the number of errors raised.

### Suggested solution
Adding properties to :
- disable submit button 
- pass number of errors count

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  48.7.1
| React            |  16.13.1
| Browser          | Chrome
| npm              |  6.14.2
| Operating System | Windows 10

**Comment by ianforster-sage** [comment]
3
