### ISSUE TITLE
Pager component currentPage display value changes when zero pages

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3453]
### Current behaviour

This behaviour can be seen on Carbon Design page, no need for CodeSandbox: https://carbon.sage.com/?path=/docs/design-system-pager--loading-state

When interacting with the 'page' field, if there are no results and page is '0', interacting with the field (click on, click off) will change it to default display value "1". Also the internal state is already held as 1, meaning React Testing Library queries such as getByDisplayValue("0") will fail.

### Expected behaviour

When there are no results and page is `0 of 0` that this remain the same after user interaction (or field is disabled/read-only when zero) and that internal state matches user visible state

### Reproducible example

The Loading State code example on Carbon Design page shows this error:
<https://carbon.sage.com/?path=/docs/design-system-pager--loading-state>

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | ^50.2.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome
| npm              |
| Operating System | OSX

**Comment by jamime** [comment]
![2020-12-01 10 58 04](https://user-images.githubusercontent.com/2328042/100736029-15f94480-33ca-11eb-81c1-8dc568f42d05.gif)

**Comment by jamime** [comment]
![2020-12-01 11 41 27](https://user-images.githubusercontent.com/2328042/100736125-37f2c700-33ca-11eb-95d6-0acc3f541513.gif)

**Comment by jamime** [comment]
FE-3388
