### ISSUE TITLE
Dialog - In the 'editable' story focus sticks on the Dismiss icon

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3457]
### Current behaviour
If you land on the form title with the mouse/trackpad and press the Tab key, the first field in the form is brought into focus. Once you tab through the elements to get to the Dismiss icon, you cannot forward tab off it. You can only reverse tab off it, but then focus misses the Dismiss icon.

![Dialog_focus_stuck_on_Dismiss_icon](https://user-images.githubusercontent.com/12828099/100776725-cc761d00-33fc-11eb-9ecf-eabfcc16ba8e.gif)

FE-3382

### Expected behaviour
Pressing Tab cycles through the elements continuously forward, or Shift + Tab cycles through the elements continuously in reverse.

### Reproducible example
https://carbon.sage.com/?path=/story/dialog--editable

### Suggested solution(s)
Fix to allow the Tab key to be used to cycle through all the elements.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 50.3.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.12.0
| Browser          | Safari, Chrome, Firefox, Edge (Chromium)
| npm              | 6.14.8
| Operating System | macOS Catalina 10.15.7

**Comment by ianforster-sage** [comment]
Fixed https://github.com/Sage/carbon/pull/3587
