### ISSUE TITLE
When using a Tile in the Sidebar component, the tile does not respect the parent width

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#3458]
### Current behaviour

When using the Tile component in the Sidebar, the width is set to 100% but this pushes the Tile up against the right side of the screen.

### Expected behaviour

I would expect the Tile component to respect any padding/margin and not be pushed up against the side of the screen.

### Reproducible example

https://codesandbox.io/s/jolly-flower-gms6g

### Suggested solution(s)

If in the browser, I add a width of inherit to the tile element, this fixes my issue. Not sure if this should be configurable or default.
If the Tile component could be given the positioning props, this would be an improvement also as it would remove the need to wrap the Tile in the Box component.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 50.2.0

**Comment by jamime** [comment]
FE-3389
