### ISSUE TITLE
DateInput - Exception when trying to type in a Date without the popup date selector.

### ISSUE THREAD

**Issue by AndreRobbertse** [Sage/carbon#3460]
### Current behaviour
Using the DateInput control breaks when entering a value by typing, rather than selecting from the popup seletor.
Codesandbox
https://codesandbox.io/s/jolly-hooks-7rvsg

### Expected behaviour
To be able to type a date into the inputbox without getting a page exception

### Reproducible example
https://codesandbox.io/s/jolly-hooks-7rvsg

### Suggested solution(s)
This used to work in a previous version (35.1.1), but after upgrading to 49.0.2 this no longer works

### Additional context
This used to work in a previous version (35.1.1), but after upgrading to 49.0.2 this no longer works

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
  "dependencies": {
    "carbon-react": "49.0.2",
    "core-js": "3.6.5",
    "i18n-js": "3.7.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-scripts": "3.0.1",
    "styled-components": "4.4.1"
  },
  "devDependencies": {
    "typescript": "3.9.3"
  }

**Comment by jamime** [comment]
Thanks for raising this. The `Date` component can't currently be used uncontrolled, you need to update the `value` when the input changes using the `onChange` callback.

Here is a working example based on your sandbox
https://codesandbox.io/s/interesting-monad-40ww4

If you find any more issues, please let me know.

**Comment by jamime** [comment]
The solution above does not work correctly.

> It happens when you have allowEmptyValue prop set and then typing in a date that is invalid or incomplete.

If you start with a `value` it works fine

e.g. 
```js
const [value, setValue] = useState("2020-10-01");
```

but if you change the code to be 

```js
const [value, setValue] = useState("");
```

it will throw the error.

**Comment by jamime** [comment]
FE-3391
