### ISSUE TITLE
[ Button ] Accessibility issue when there is no text passed

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#3464]
### Current behaviour

When the `button` component presents without provided text inside the button we have reporter the `accessibility` issue `Buttons must have discernible text` as shown below on screen

<img width="1416" alt="Screenshot 2020-12-03 at 12 04 26" src="https://user-images.githubusercontent.com/34001198/101001793-dd8b6f00-355f-11eb-9791-a9e3388f9e39.png">

### Expected behaviour

We should ensure that `button` without provided text is visible to screen readers

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 50.3.1 |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | All |
| npm              |
| Operating System | MacOS |

**Comment by DlgSHi** [comment]
FE-3397

**Comment by ianforster-sage** [comment]
Released in https://github.com/Sage/carbon/releases/tag/v66.5.0
