### ISSUE TITLE
Align left text of tooltip for TextEditor with validation component

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#3468]
### Current behaviour
Currently text of the tooltips is align center inside TextEditor with validation component.
![image](https://user-images.githubusercontent.com/60605396/101138398-6a8e0100-3610-11eb-8765-2aa8581ac485.png)
![image](https://user-images.githubusercontent.com/60605396/101138356-606c0280-3610-11eb-8858-2576bd2c843f.png)

### Expected behaviour
The text of the tooltips could be align left inside TextEditor with validation component.
![image](https://user-images.githubusercontent.com/60605396/101139231-87770400-3611-11eb-8c05-7d1ae59f9945.png)
![image](https://user-images.githubusercontent.com/60605396/101139183-76c68e00-3611-11eb-846b-678dd5238eb6.png)

### Reproducible example
Default use of the TextEditor with validation component.

### Suggested solution(s)
Giving a property to decide the alignment of the text.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 50.3.0
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.2
| Operating System | Windows 10

**Comment by ianforster-sage** [comment]
FE-3404
