### ISSUE TITLE
Select component - click on close icon doesn't clear text inside input

### ISSUE THREAD

**Issue by abhoraniya** [Sage/carbon#3474]
## Feature request
https://carbon.sage.com/?path=/story/experimental-select--default

### Current behaviour
In Select component, It select the text inside input wenn close icon clicked

### Desired behaviour
It should clear the text inside input wenn close icon clicked
![image](https://user-images.githubusercontent.com/60701990/101360232-a984b680-389d-11eb-8254-849ea6abd455.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 47.0.0

**Comment by edleeks87** [comment]
Hi @abhoraniya thanks for raising this issue. The `experimental select` component has been deprecated in favour of a new `select`, the basic functionality is demoed here https://carbon.sage.com/?path=/story/design-system-select--basic. Enhanced functionality has also been separated into a `filterable-select` and `multi-select` components. We would recommend migrating to use one of these new components. I'm going to close this issue but please feel free to re-open it or create a new one if you see the same issue.

https://github.com/Sage/carbon/tree/master/src/components/select
