### ISSUE TITLE
Select component clears selected item even if the options contains the item

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#3475]
### Current behaviour

When the select component is being interacted, if the array of options happens to change, even if the value still exists in the returned options.

### Expected behaviour

If I make an api call on open of the Select component and choose the first option in the response and then open the select element again and the api call happens again. If, the initially selected value is returned in the response, it should remain as the selected item.

### Reproducible example

https://codesandbox.io/s/compassionate-bose-b9u4m
Choose Amber, click the dropdown again wait for loading to finish.
The setTimeout is in place of our api call.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 52.0.0

**Comment by grabkowski** [comment]
to fix this issue we could enforce Option's object value to have the `value` key, so we're comparing only the values instead of whole objects.

FE-3421 on backlog

**Comment by grabkowski** [comment]
Issue fixed with #3593 merge. I have also corrected your code in the sandbox so it works as expected, you could check it there:
https://codesandbox.io/s/carbon-quickstart-forked-lpvbi?file=/src/MySelect.js
