### ISSUE TITLE
MultiSelect Component: Extending the component to provide isLoading functionality similar to Select Component

### ISSUE THREAD

**Issue by Manisureal** [Sage/carbon#3489]
### Current behaviour
There is no loading functionality for MultiSelect Component - Trying to use a Loader Component within this breaks the component once there is 1 item selected and re-opening it results in a console error of `Cannot read property 'props' of undefined`

### Desired behaviour
Loading functionality should be added and provided out of box with this component

### Suggested solution
To provide this functionality directly from the component via a isLoading prop

### Describe alternatives you've considered
Have tried disabling the custom loader after 1 item is selected from the dropdown, this way when opening the dropdown it does not break and does not result in an error but this is not efficient as we need to see the loader even if there are more than 1 items already selected.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 50.2.0
| react-scripts    | 
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.9.0
| Operating System | MacOS Mojave

**Comment by jamime** [comment]
I've messaged @Manisureal for milestone information.

**Comment by jamime** [comment]
All details logged in JIRA.
FE-3441

**Comment by ianforster-sage** [comment]
Released in https://github.com/Sage/carbon/releases/tag/v66.2.0
