### ISSUE TITLE
ButtonToggleGroup and Row causing display issues

### ISSUE THREAD

**Issue by danaldinho** [Sage/carbon#3495]
### Current behaviour
When using the `ButtonToggleGroup` and `Row` components, it seems as though the "Row" gets ignored and everything seems to just appear on the same row

![image](https://user-images.githubusercontent.com/28150291/102227193-343e6480-3ee1-11eb-9c68-0317dc352d87.png)

### Expected behaviour
I would expect that the rows get respected and not for all child elements to appear on the same row. 

### Reproducible example
[See here for a codesandbox example](https://codesandbox.io/s/carbon-form-validations-forked-5dw91?file=/src/index.js)

### Suggested solution(s)
Addressing the `display` property. Discovered within Inspect element in Chrome that it is possible to fix this by removing `display: flex` and then the rows are respected and inner elements appear below each other, not side by side

### Additional context
This occurred as part of an upgrade from version 3.2.5 to the latest version of Carbon

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 52
| carbon-factory   | N/A
| react-scripts    | N/A
| React            | 16.13.1
| Browser          | Chrome 87.0.4280.88
| npm              | 6.9.0
| Operating System | Mac OS Catalina 10.15.7

**Comment by jamime** [comment]
Hi @danaldinho thanks for raising this.

I've looked at this and looked at your current product design. Although this pattern worked previously it's not something that's listed in the DLS. As it's not in the DLS it's unlikely that we'll change this component.

I recommend that you reach out to UX to discuss your options, they will be able to advise on the best usage of the DLS, or even add this pattern to the DLS.

As you're upgrading from `v3` there will be some changes like this required while you migrate from the `classic` theme to a `DLS` theme.

Thanks 🙂

**Comment by harpalsingh** [comment]
@jamime Could you show me what you have seen in the DLS that implies Row should not work as a "row" regardless of the children elements?

**Comment by harpalsingh** [comment]
As Jamie has said, this pattern wouldn't work as it implies that you add a variety of components inside the ButtonToggleGroup, whereas by definition it should just be the buttons.
