### ISSUE TITLE
Allow null children on Menu component

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3497]
### Current behaviour
codesandbox shows it best.
I want to conditionally render some MenuItems within my Menu. This is fine when the condition is true and the MenuItem is returned as the Menu expects. However, should the condition return false, a null child is inserted, which is not allowed by the Menu component.

### Expected behaviour
Menu allows children which are either MenuItems, or null.

### Reproducible example
https://codesandbox.io/s/keen-cray-idicp?file=/src/index.js

**Comment by sjohnson-sage** [comment]
Thanks for raising this @limcoc 

Should be a simple fix, change this: https://github.com/Sage/carbon/blob/a69ee555d487fe4f92d699990540b275502eb32f/src/components/menu/__internal__/keyboard-navigation/index.js#L19 

to `if(child && child.type === MenuItem && ...`

I'll add it to our backlog to fix.

**Comment by sjohnson-sage** [comment]
FE-3448

**Comment by sjohnson-sage** [comment]
Out of curiosity have you seen this error outside of codesandbox @limcoc? I've tried it in storybook and in multiple different React apps and can't replicate the error!

**Comment by sjohnson-sage** [comment]
@limcoc there's a fix in progress that will sort it in codesandbox as well FYI
