### ISSUE TITLE
Button Component - No Text Wrapping

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#3503]
### Current behaviour
If you add a button in various usage and the content will self-flex, the button can go onto 2 lines.

Example usage
![Screenshot 2020-12-16 at 15 11 05](https://user-images.githubusercontent.com/2411024/102366857-07f21900-3fb1-11eb-9826-b681aa44a9b2.png)

### Desired behaviour
We would like the ability, where applicable, you can pass a value to prevent wrapping onto 2 lines (white-space: nowrap)

![Screenshot 2020-12-16 at 15 11 15](https://user-images.githubusercontent.com/2411024/102366970-23f5ba80-3fb1-11eb-991b-cebe31490afe.png)

### Suggested solution
Adding a new prop to prevent the button main text from wrapping onto 2 lines.

### Describe alternatives you've considered
n/a

### Additional context
n/a

### Your environment
n/a

**Comment by ianforster-sage** [comment]
FE-3459

**Comment by bulaj** [comment]
Please see codesandbox below for example of usage in message component:
https://codesandbox.io/s/carbon-quickstart-forked-litjl?file=/src/index.js
