### ISSUE TITLE
Menu - Inconsistent alignment

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#3505]
### Current behaviour
If the `onClick` prop is used the text is center aligned.
When `onClick` and `icon` is provided the icon is out of alignment when compared to `href`.
![image](https://user-images.githubusercontent.com/2328042/102387435-4941f300-3fc8-11eb-9e9c-a6d528db39a7.png)

### Expected behaviour
It should have the same styles applied as `href`.

### Reproducible example
https://codesandbox.io/s/menu-onclick-alignment-67f8o

### Additional context

Related https://github.com/Sage/carbon/issues/3292

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |54.1.1|

**Comment by jamime** [comment]
FE-3242

**Comment by nicktitchmarsh** [comment]
There is now a story that will demonstrate how to align menu items with icons and text, and with onClick handlers.
https://carbon.sage.com/?path=/docs/design-system-menu--submenu-icon-and-text-alignment

**Comment by sjohnson-sage** [comment]
Fixed in v54.4.0
