### ISSUE TITLE
Link components require two clicks to be followed when they are within a Heading

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3511]
### Current behaviour
Whenever a Link component is within a Heading component it starts behaving strangely. Upon the first click the Link becomes focused and wraps onto the next line, then only after the second click can you actually follow the link.

### Expected behaviour
Links within a Heading behave like all other links do

### Reproducible example
https://codesandbox.io/s/magical-herschel-q0nsf?file=/src/index.js

Here is another codesandbox showing how tables render links differently when in a Heading vs when not in one
https://codesandbox.io/s/cool-frog-f5ii2?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.7.1 ... 54.1.0 |

**Comment by limcoc** [comment]
Here is another codesandbox showing how tables render links differently when in a Heading vs when not in one
https://codesandbox.io/s/cool-frog-f5ii2?file=/src/index.js

**Comment by ianforster-sage** [comment]
FE-3460

**Comment by edleeks87** [comment]
Fixed in latest carbon (v66.0.1)

https://codesandbox.io/s/aged-sea-zi92x?file=/src/index.js
https://codesandbox.io/s/distracted-bhaskara-59f3h?file=/src/index.js
