### ISSUE TITLE
Tabs control with set location = false onTabChange event adds item to browser history

### ISSUE THREAD

**Issue by ravi-ankam** [Sage/carbon#3520]
### Expected behaviour
I am implementing simple routing to the Tabs control .
In my example I have 3 tabs namely Standard, custom, favourites and added a simple routing using the tabName as a variable/parameter.
OnTabchange I am updating the browser history with a tabName to the base route. 
The issue I am facing now is, after I select the tabs, 
when I click on browser back button, For the first time the tab navigates back the the correct previous selected tab using the route/browser history value but on the second browser back click it fails to navigate to the previous tab selected.
It looks like, there is a default browser history update with tabid value. the number of items added to the browser history are more than expected items.
Attached the link for code sandbox Example code I used for your reference.
Please check and advise what I am doing wrong or if there is a better way to add routes the tabs and slected tab.

### Reproducible example
https://codesandbox.io/s/shy-dust-4l2vc

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |48.3.1
| Browser          |Chrome

**Comment by jamime** [comment]
We'll need to allow consumers to pass `history` too, with a default of `window.history` so users can use a memory router, subscribe to history changes and block navigation.

**Comment by ianforster-sage** [comment]
@benwilsonsage should 'back' take you back to a previous tab in this scenario? The alternative would be to take you back to your previous page.

**Comment by benwilsonsage** [comment]
Thanks for the scenario.

When developing modern 'single page apps', I can see why it's helpful to allow the user to step backward through dynamic changes on the same page, not just between pages.

However, Accounting (GAC live) today doesn't behave like a single page app, and the user can't use 'back' to get to previously viewed tabs.

I guess the answer has two levels...
- If developing a new app (e.g. Client Manager, something else...) it'd be good to have the ability to back up through tabs so we can deliver modern experiences.
- But if developing something to go-live in legacy Accounting, I'd suggest not enabling this, so the user has a consistent experience and isn't surprised by different behaviours in different places. Although I don't think it'd be a catastrophe by any means!

So I guess it depends on context - if this is for the Reporting page with the list of reports, I'd suggest the standard 'back' behaviour is fine.

**Comment by MatthewSmythe** [comment]
@benwilsonsage this is for the Reporting tabs, so "new app" work.

**Comment by jamime** [comment]
We'll make this optional behaviour to use `history.push` instead of `history.replace`. We'll also need to support multiple `<Tabs>` on one page. E.g. a left hand vertical tab and a horizontal tab within.
