### ISSUE TITLE
FlatTable - Scroll when there are row headers 

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3523]
### Expected Behaviour
There are two bugs

1) 
There should be a 2px border on the right hand side of the row header. This should remain while the row cells scroll behind it. This should also apply to the the column header thats is above all the row headers (name)

2)
When the cells scroll behind the row headers the column header (name) should not move and should remain above the row headers 

### Current Behaviour
1)
There is only a 2px border when the row cells are in their original position. 

2)
Name travels with the scroll and is not fixed

![image](https://user-images.githubusercontent.com/72866515/103005800-f3220200-4529-11eb-858e-5f3d0f023f1a.png)
![image](https://user-images.githubusercontent.com/72866515/103006798-39776100-452a-11eb-8118-f4b60cbb13ce.png)
![Dec-23-2020 11-01-12](https://user-images.githubusercontent.com/72866515/103006846-4e53f480-452a-11eb-8201-82caf5e83de6.gif)

### Reproducible example

shrink the view so that the scroll is activated 
https://codesandbox.io/s/gracious-waterfall-w90rj?file=/src/index.js:0-2807

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 54.7.3
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System | MacOS Catalina

**Comment by Alec-Walker-Sage** [comment]
FE-3466

**Comment by DlgSHi** [comment]
In codesandbox should be used `<FlatTableRowHeader>Name</FlatTableRowHeader>` instead of `            <FlatTableHeader>Name</FlatTableHeader>
`
