### ISSUE TITLE
No matching version found for i18n-js@3.0.0

### ISSUE THREAD

**Issue by konrazem** [Sage/carbon#3525]
Please update [getting started guide](https://github.com/Sage/carbon/blob/master/docs/getting-started.stories.mdx) peer-dependencies of carbon-react and required. I am sorry if this is not a Bug but Feature.

**Comment by konrazem** [comment]
http://github.com/fnando/i18n-js/archive/v3.0.0.rc12.tar.gz

**Comment by DlgSHi** [comment]
FE-3470
