### ISSUE TITLE
DateInput: allowEmptyValue property cause error when date is removed

### ISSUE THREAD

**Issue by konrazem** [Sage/carbon#3527]
### Current behaviour
For DateInput component allowEmptyValue property cause error when date is removed (when calendar is open) on focus out.

### Expected behaviour
After removing date and click out (focus out) the empty date is set. 

### Reproducible example
[Example taken from carbon Storybook](https://carbon.sage.com/?path=/docs/experimental-date-input--empty)
1. set date
2. open calendar and keep calendar open!
3. remove date 
4. click outside component (close calendar)

### Additional context
Error log from local application:
Helpers.js?5490:112 Uncaught TypeError: Cannot read property 'length' of undefined
    at **Object.getWeekArray** (Helpers.js?5490:112)
    at Month.render (Month.js?2cfc:147)
    at finishClassComponent (react-dom.development.js?61bb:17160)
    at updateClassComponent (react-dom.development.js?61bb:17110)
    at beginWork (react-dom.development.js?61bb:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237)
    at invokeGuardedCallback (react-dom.development.js?61bb:292)
    at beginWork$1 (react-dom.development.js?61bb:23203)
    at performUnitOfWork (react-dom.development.js?61bb:22154)

react_devtools_backend.js:2430 The above error occurred in the <Month> component:
    in Month (created by DayPicker)
    in div (created by DayPicker)
    in div (created by DayPicker)
    in DayPicker (created by DatePicker)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by DatePicker)
    in span (created by Portal)
    in Portal (created by DatePicker)
    in DatePicker (created by BaseDateInput)
    in div (created by BaseDateInput)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by BaseDateInput)
    in BaseDateInput (created by WithUniqueIdProps)
    in WithUniqueIdProps (created by DateInput)
    in DateInput (created by Formik)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 51.0.0
| carbon-factory   | ^11.0.1
| react-scripts    | -
| React            | 16.13.1
| Browser          | Chrome Version 87.0.4280.88 (Official Build) (64-bit)
| npm              | 6.14.8
| Operating System | Windows 10

**Comment by DlgSHi** [comment]
FE-3471

**Comment by ianforster-sage** [comment]
Fixed https://github.com/Sage/carbon/pull/3597
