### ISSUE TITLE
Table: Keep pointer cursor for Link with icon in TableCell on hover

### ISSUE THREAD

**Issue by konrazem** [Sage/carbon#3531]
### Current behaviour
When Link with icon component in TableCell is used, { cursor: grab; } is applied on hover.

### Desired behaviour
I expect { cursor: pointer; } when Link component is used in TableCell.

### Suggested solution
Override style 
```
{
    cursor: move;
    cursor: -webkit-grab;
    cursor: -moz-grab;
    cursor: grab;
}
```
with inherited cursor type?

### Describe alternatives you've considered
Apply extra style for Link component 

### Additional context
Note that this issue do not appear for carbon V8.
Code to reproduce the issue:
```javascript
export default function CarbonTable() {
  const rows = [
    {
      id: 1,
      name: 'Name 1',
      age: 23
    },
    {
      id: 2,
      name: 'Name 2',
      age: 32
    }
  ];

  return (
    <div>
      <Table>
        <TableRow as='header'>
          <TableHeader>Name</TableHeader>
          <TableHeader>Age</TableHeader>
          <TableHeader />
        </TableRow>
        {rows.map(row => (
          <TableRow key={row.id}>
            <TableCell>{row.name}</TableCell>
            <TableCell>{row.age}</TableCell>
            <TableCell name='edit'>
              <Link icon='edit' onClick={() => console.log('Dragged cursor')} />
            </TableCell>
          </TableRow>
        ))}
      </Table>
      <h1>Link component with pointer cursor</h1>
      <Link icon='edit' onClick={() => console.log('Pointer cursor')} />
    </div>
  );
}
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 51
| react-scripts    | -
| React            | 16.13.1
| Browser          | Chrome 87
| npm              |  6.14.8
| Operating System | Win 10 64

**Comment by jamime** [comment]
We recommend that you use `FlatTable`. We intent to remove `Table` in the near future. We're in the process of adding any missing styles in https://github.com/Sage/carbon/pull/3516

Please can you check `FlatTable` and share a codesandbox if you need further assistance.

**Comment by konrazem** [comment]
The FlatTable seems to be good. There is no issue with the pointer. Thank you very much for you assistance.
