### ISSUE TITLE
Placeholder text for default select component is darker than placeholder text for multiselect and filterable select components

### ISSUE THREAD

**Issue by smcguirk-sage** [Sage/carbon#3532]
### Expected behaviour
Would expect the default styling for the placeholder text to be identical for all 3 components

### Reproducible example
Difference can be seen in storybook examples:
- Default/Single Select: https://carbon.sage.com/?path=/story/design-system-select--basic
- MultiSelect: https://carbon.sage.com/?path=/story/design-system-select-multiselect--basic
- Filterable: https://carbon.sage.com/?path=/story/design-system-select-filterable--basic

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v54.3.4 |

**Comment by ianforster-sage** [comment]
@harpalsingh please could you confirm which of the two styles should be used, then we'll correct it where necessary.

**Comment by harpalsingh** [comment]
Having spoken with accessibility and reviewing this design, both need updating, as we need to use black-55 (Black with an opacity of 55%) as placeholder text color.

**Comment by ianforster-sage** [comment]
FE-3551
