### ISSUE TITLE
Enable Links in Tab components

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3534]
### Current behaviour

https://codesandbox.io/s/objective-bird-5cxm2
Using a `<Tabs>` Component we have a need to have one Tab open a new page in the users browser when selected instead of showing new content on the page.
In the above Code Sandbox i have used a Sibling Link component but this is 1) un-clickable and 2) only the text itself is directly a link, rather than the entire Tab button itself.

### Desired behaviour

The ability to assign a link action to be executed when a Tab is clicked/selected instead of changing any code on existing page.

### Describe alternatives you've considered

The designs given do not allow for a navigation, menu list or accordion to be used. I have tried using the onTabChange() prop without success, but welcome suggestions.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v54.6.0
| react-scripts    | 3.0.1
| React            | 16.8.6
| Browser          | n/a
| npm              | n/a
| Operating System | n/a

**Comment by ianforster-sage** [comment]
FE-3486

**Comment by ianforster-sage** [comment]
Resolved in https://github.com/Sage/carbon/releases/tag/v66.10.0
