### ISSUE TITLE
Tabs/Tab lose `size="large"` prop when they have a sibling

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3537]
### Current behaviour

adding a sibling prop to a Tab alters height of that Tab only.

### Expected behaviour

Tab size to be independent of the Sibling prop

### Reproducible example

https://codesandbox.io/s/gallant-swartz-ep04g

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 54.6.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sianford** [comment]
FE-3476
