### ISSUE TITLE
Dialog Component only allows String for confirmLabel

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3550]
### Current behaviour

The confirmLabel prop definition allows for only `string` which causes a warning when when we have wanted/needed to put a <Loader> component inside the button to match our UX designs. Placing the loader inside still works, but generates a warning about disobeying type definition.

### Desired behaviour

The ability to either set a loading state for <Confirm> that adds <Loader> inside the button, or the typing of <Confirm> to allow more flexibility on contents of confirmLabel

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v54.3
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-2737

**Comment by jamime** [comment]
I've added these requirements to FE-3380

**Comment by ianforster-sage** [comment]
Resolved in https://github.com/Sage/carbon/releases/tag/v66.15.0
