### ISSUE TITLE
tooltipMessage and onClick event on Portrait Component

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3554]
### Current behaviour
The Portrait component does not support tooltipMessage like other components, such as Icon, do. A Portrait also has no onClick event.

### Desired behaviour
As an example: on the github issue list, when an issue is assigned to someone, only their profile picture is displayed. If you do not recognise that person then you can hover over their profile image and get a tooltip mentioning who they are.

I want to save horizontal space by only displaying a portrait component in my tables where the cell contains a user, and being able to hover over the portrait and show a tooltip with their name would make this possible.

I would also like to be able to click on the portrait and use it to navigate to the user's full profile through the use of an onClick event.

**Comment by jamime** [comment]
Thanks for the feature request Liam. We have several design and UX teams here at Sage for the most part carbon is an implementation of our design system.

I'll pass this over to the design system team and find if they want to implement this. Your use case sounds pretty reasonable.

**Comment by jamime** [comment]
The DLS team have agreed that we should implement this and are in the process of adding it to the DLS website.

**Comment by sjohnson-sage** [comment]
FE-3502
