### ISSUE TITLE
Select component clears selected item after its applied but clicking anywhere around the select component restores it

### ISSUE THREAD

**Issue by Manisureal** [Sage/carbon#3557]
### Current behaviour
Using a select component within a PopoverContainer Component is hiding the selected item after it's applied but when clicking around the select component or anywhere on the screen shows the selected item

### Expected behavior
If an item is selected within a select component and it's applied, this should then be visible when reopening the PopoverContainer Component. 

### Reproducible example
- [Sandbox Example:](https://codesandbox.io/s/currying-dust-r8ed3?file=/src/App.js:3248-3264)

Steps:
1. Click Filter to open PopoverConatiner
2. Make a selection from Company dropdown(Test Business 1)
3. Click Apply
4. A pill with the selection appears and the filter closes
5. Open Filter again
6. Selected item is not showing in the Company dropdown
7. Clicking anywhere in the filter or the document makes this selected item reappear 

### Additional context
- This used to work previously with **Carbon version 50.2.0** and all the versions until **53.0.0**. 
It seems to have broken in version **53.1.0** to all the versions till the latest version.

- The sandbox link is created using controlled usage with string as a value but the same issue with controlled usage with an object as a value.

- This issue might be related/identical to this open issue here: https://github.com/Sage/carbon/issues/3475 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 54.3.4
| React            | 16.8.3
| Browser          | Chrome
| npm              | 6.9.0
| Operating System | MacOS Mojave

**Comment by ianforster-sage** [comment]
FE-3552
