### ISSUE TITLE
Decimal: formatting numeric value imprecision in some locales

### ISSUE THREAD

**Issue by arturodrigues** [Sage/carbon#3559]
### Current behaviour
 
For some given locales, such as Spanish (es-ES) or Portuguese (pt-PT), when entering a number between 1000 and 9999 in the  Decimal component, the formatting of the numeric value is not quite correct: the locale's group separator only be used when the number is greater than or equal to ten thousand. Example:

| Number | Portuguese | Spanish |
| ---------------- | ---------------- | ---------------- |
| 100     | 100 | 100 |
| 1000     | 1000 | 1000 |
| 1000.23     | 1000,23 | 1000.23 |
| 10000     | 10 000 | 10.000|
| 10000.23     | 10 000,23 | 10.000,23 |
| 100000     | 100 000 | 100.000 |
| 1000000     | 1 000 000 | 1.000.000 |

### Expected behaviour
Formatted value appearing in the Decimal component should comply with [Intl object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat).

### Reproducible example
https://codesandbox.io/s/numberformatting-kijbl

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 55.0.0 |
| React            |  17.0.0 |
| Browser          | Chrome 87 |
| npm              | 6.14.8 |
| Operating System | Windows 10 |

**Comment by sjohnson-sage** [comment]
FE-3500
