### ISSUE TITLE
Manually typing into DateInput throws error when allowEmptyValue is set

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3560]
### Current behaviour
I am using react state to set the value on my DateInput component, this works fine for an ordinary DateInput. But when the allowEmptyValue property is set on a DateInput, I attempt to type in a date and an error is thrown. (see codesandbox for example).

### Expected behaviour
Can type a date into a DateInput which has allowEmptyValue set without error

### Reproducible example
https://codesandbox.io/s/aged-meadow-e01m5?file=/src/index.js
Try typing a date into the broken date input vs the working one

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 54.6.2 |

**Comment by ianforster-sage** [comment]
@limcoc thanks for this. We think this is related to the issue here https://github.com/Sage/carbon/issues/3527, which is already on our backlog. We'll use your scenario as further acceptance criteria for the fix.

**Comment by ianforster-sage** [comment]
Duplicate of https://github.com/Sage/carbon/issues/3460
