### ISSUE TITLE
Tabs Component Typescript definition has no defaults

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3568]
### Current behaviour

The Tabs Typescript definition file requires that all props be defined when implements, while on [Carbon](https://carbon.sage.com/?path=/docs/design-system-tabs--basic) most props have a default value, which is not being reflected.

### Expected behaviour

Only changes to default values should need specifying

### Suggested solution(s)

Altering the typescript definition to include the same default values as specified on the Carbon docs page.
Adding default values for props to match docs:
```
renderHiddenTabs true
align "left"
position "top"
setLocation true
size "default"
extendedLine true
borders "off"
variant "default"
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
Hi @PaulSumner-Sage, it isn't possible  to put default values on Typescript interfaces - Typescript only cares about the type of a value, not what the value actually is. 

You've raised this as a bug - are you seeing any problems or console errors relating to the Tabs prop types?

**Comment by sjohnson-sage** [comment]
The problem might be that some of the `Tabs` props should be set as optional in the Typescript interface, but they're set as being required - is this is issue you're having?

**Comment by jamime** [comment]
I messaged @PaulSumner-Sage on Slack for further information.

**Comment by PaulSumner-Sage** [comment]
> Hi @PaulSumner-Sage, it isn't possible to put default values on Typescript interfaces - Typescript only cares about the type of a value, not what the value actually is.
> 
> You've raised this as a bug - are you seeing any problems or console errors relating to the Tabs prop types? If so can you provide screenshots or copy and paste the errors please
> 
> The problem might be that some of the Tabs props should be set as optional in the Typescript interface, but they're set as being required - is this is issue you're having?

Bad wording on my end yes sorry. Tabs marked as optional is what I meant/intended.

**Comment by sjohnson-sage** [comment]
Thanks for clarifying @PaulSumner-Sage - I'll get this added onto our backlog

**Comment by sjohnson-sage** [comment]
FE-3694

**Comment by grabkowski** [comment]
FE-2818
