### ISSUE TITLE
Definitions wrapped in React fragments are not shown in DefinitionList

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3582]
### Current behaviour
I have a definition list where I want to conditionally render some of the definitions, to do this I have wrapped them in react fragment which is rendered depending on the outcome of my condition. But a definition is not displayed unless it is a direct child of the Dl component

### Expected behaviour
Dt and Dd are displayed the same regardless of whether they are wrapped in a react fragment

### Reproducible example
https://codesandbox.io/s/eloquent-borg-8rr0b?file=/src/index.js

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 58.0.0 |

**Comment by sjohnson-sage** [comment]
Thank you for raising but we don't think we should support rendering the `Dt` and `Dd` within a fragment (or any other wrapper), instead you could build your component as shown in this sandbox to conditionally render these components:

https://codesandbox.io/s/pensive-williams-ksudy?file=/src/index.js

We will add an example of this into the documentation for the Definition List component

**Comment by sjohnson-sage** [comment]
FE-3600

**Comment by limcoc** [comment]
> Thank you for raising but we don't think we should support rendering the `Dt` and `Dd` within a fragment (or any other wrapper), instead you could build your component as shown in this sandbox to conditionally render these components:
> 
> https://codesandbox.io/s/pensive-williams-ksudy?file=/src/index.js
> 
> We will add an example of this into the documentation for the Definition List component

Thanks for this, however in the console log react throws an error because each element within the list does not have a 'key' prop. If I then add a unique key to each item (https://codesandbox.io/s/crazy-bouman-7dqzg) within the list I then get the following error:

`Dd: 'key' is not a prop. Trying to access it will result in 'undefined' being returned. If you need to access the same value within the child component, you should pass it as a different prop.`

**Comment by sjohnson-sage** [comment]
Thanks for that @limcoc - I'll change the ticket on the backlog to allow support for your original issue, I can see your use case and we probably should support that

**Comment by dawidzarzycki** [comment]
This issue has been resolved by https://github.com/Sage/carbon/pull/3737
