### ISSUE TITLE
Pod - The display edit button on hover causes incorrect colouring of the footer

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3584]
### Current behaviour

When hovering over pod the footer of the pod does not change colour and the text within the footer turns white. This makes it hard to read and creates an unpleasant visual. 

### Expected behaviour

The footer should be readable when the pod is hovered

### Reproducible example

https://carbon.sage.com/?path=/story/pod--with-display-edit-button-on-hover

### Suggested solution(s)

Change the styling on hover

### Additional context

![Jan-15-2021 14-05-07](https://user-images.githubusercontent.com/72866515/104737340-03e62200-573c-11eb-8c05-80f81b3a40bf.gif)
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by Alec-Walker-Sage** [comment]
FE-3505

**Comment by sjohnson-sage** [comment]
It also looks like the styling is incorrect when you click on the pod as well, the border colour should be the normal orange one, not blue

**Comment by ianforster-sage** [comment]
@harpalsingh  please could you advise on the correct style for this
