### ISSUE TITLE
Menu - When a submenu overlaps the search component it is no accessible with the mouse

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#3588]
### Current behaviour

We have a use case where the Navigationbar component has a Menu with a sub menu.
We also have a Table that is searchable.

When you expand the Menu showing its contents, if it covers the Search component it is not accessible with the mouse.

An example of this behaviour can be found here:  https://codesandbox.io/s/elegant-forest-8096m

### Expected behaviour

The Menu to have a priority in position over any elements the sub menu is rendered on top of.

### Additional context

I have not tested with other components, but I have seen in demos where parts of the elements within the Table are hiding the bottom of the sub menu.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 58.1.0

**Comment by sjohnson-sage** [comment]
FE-3598
