### ISSUE TITLE
Selected tab overlaps menu dropdown items on hovering

### ISSUE THREAD

**Issue by SivalenSivalingam** [Sage/carbon#3589]
### Current behaviour
We have 3 tab component under a navigation menu item and list of reports. When a tab is selected and you try and hover over the menu item to show the list of reports. The tab selected element overlaps the dropdown menu item.

### Expected behaviour
When you select a tab and try and hover over a menu drop down to show a list of reports, the drop down list should take preference over the selected tab element

### Reproducible example
https://codesandbox.io/s/great-cache-t5fm1

### Additional context
This only happen when you hover over the menu item when a tab is selected

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 48.3.0
| react-scripts    | 3.4.3
| React            | 16.13.1
| react-router-dom | 5.2.0
| react-dom        | 16.13.1

**Comment by sjohnson-sage** [comment]
FE-3598
