### ISSUE TITLE
Can't set an alternate background color for menu search component

### ISSUE THREAD

**Issue by mmaciorowski-sage** [Sage/carbon#3591]
### Current behaviour
Wrong background color for menu search component.

### Expected behaviour
 The same search background color like "Item Submenu Two" and "Item Submenu Three".

### Reproducible example
https://codesandbox.io/s/red-voice-pdiqn

### Suggested solution(s)
It would be nice to have a component that allows you to set the prop `variant="alternate"`.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 58.0.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.11
| Operating System | OSX

**Comment by sjohnson-sage** [comment]
FE-3597

**Comment by bulaj** [comment]
Example can be found here: https://carbon.sage.com/?path=/story/design-system-menu--submenu-with-search
