### ISSUE TITLE
Multi Select - Can't access options using keyboard 

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3602]
### Current behaviour

Can't access and select options using the keyboard
### Expected behaviour

Should be able to select options using the keyboard
### Reproducible example

visit https://carbon.sage.com/?path=/story/design-system-select-multiselect--basic

**Comment by Alec-Walker-Sage** [comment]
FE-3613

**Comment by jamime** [comment]
To clarify, it's not possible to arrow down to the options from the main input.

**Comment by tempertemper** [comment]
I've been having a look at the keyboard accessibility for this component and should have a spec ready soon.

**Comment by mkrds** [comment]
https://github.com/Sage/carbon/pull/4569 This PR fixes the keyboard accessibility part

I also created a ticket - FE-4470 - to implement the new specification provided by Martin
