### ISSUE TITLE
Filterable Select - Options can be selected even though the filtered list shows no results 

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3607]
### Current behaviour

If you filter the select options so that there is no options available and press enter then it selects the most recently filtered item.

### Expected behaviour

If there is nothing in the filtered list of options then there should be no event when enter is pressed.
### Reproducible example

visit https://carbon.sage.com/?path=/story/design-system-select-filterable--basic and type a string that has a letter from one of the options in it and press enter from example typing "grooooo" selects green and "blueeeeee" selects blue

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 59.0.2
| carbon-factory   |
| react-scripts    | 
| React            | 
| Browser          | google chrome
| npm              |
| Operating System | OS Catalina

**Comment by Alec-Walker-Sage** [comment]
FE-3615

**Comment by grabkowski** [comment]
fixed as part of #3669
