### ISSUE TITLE
Select - Trying to drag the options list closes the component 

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3608]
### Current behaviour

If you open the list of options and then try to drag to scroll it closes the list of options.
### Expected behaviour

Unsure of the expected behaviour. I know that drag to scroll is not implemented however I do not think it should close the list of options if a user does try to navigate in this way. Could cause some confusion.
### Reproducible example

Visit https://carbon.sage.com/?path=/story/design-system-select--default-story and try and drag to scroll 
### Suggested solution(s)

Probably needs UX to be involved to work out if this is actually an issue or not.
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 59.0.2
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome 
| npm              |
| Operating System | OS Catalina

**Comment by Alec-Walker-Sage** [comment]
Have not created a Jira ticket as unsure whether a bug or not

**Comment by DipperTheDan** [comment]
Planning to as UX whether this is a genuine bug or not.

**Comment by jamime** [comment]
I've messaged @harpalsingh on Slack for more information.

**Comment by ianforster-sage** [comment]
reminded @harpalsingh in Slack.

**Comment by harpalsingh** [comment]
Had a chat with @Alec-Walker-Sage, as discussed, the behaviour we should aim for consistency is that which the filterable select does.

If a use "left mouse clicks" an option, then drags the cursor away from that option, if they release the left click it can do one of 2 things:

1. If still inside options, they remain open and use can now select another option to click
2. IF released outside the component, the open options are closed

**Comment by sjohnson-sage** [comment]
Closing this issue as we have confirmed that it behaves as per Harpal's comment above, the bug is no longer present.
