### ISSUE TITLE
Focus leaves dialog after shift-tab on a radio button group 

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3623]
### Current behaviour

If you are in a dialog and you shift-tab back into a radio group and then shift-tab again the focus leaves the dialog and out of the focus trap. **This only happens if it is the last item in the radio group selected.**

![2021-02-04 11 05 24](https://user-images.githubusercontent.com/2328042/106884300-069fbb80-66d9-11eb-8c83-6f07e0392c39.gif)

### Expected behaviour

The focus should remain in the dialog (like it does when the first item in the radio group is selected).

![2021-02-04 11 04 08](https://user-images.githubusercontent.com/2328042/106884284-02739e00-66d9-11eb-8d1b-d9f690b7c5ec.gif)

### Reproducible example

https://codesandbox.io/s/compassionate-dew-17i49?file=/src/index.js
1) open the dialog 
2) select the second radio button 
3) tab onto the form inputs
4) use shift tab to go back onto the radio buttons
5) press shift tab again which take you out of the dialog

### Additional context

This was found out during FE-3586 looking into the Focus Trap.
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 62.0.0
| Browser          | All
| Operating System | Mac OS Catalina

**Comment by jamime** [comment]
FE-3690
