### ISSUE TITLE
Navigating through Radio buttons in Safari has wrong keyboard interaction

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3626]
### Current behaviour

When focused on a radioButtonGroup you can use the keyboard to switch between the options. However if you press the down key when you are on the last option instead of returning to the top option it has no interaction. 
### Expected behaviour

Pressing down on the last option should return focus to the first option. This also works visa versa if you are on the top option and press the up key 
### Reproducible example

https://carbon.sage.com/?path=/story/experimental-radiobutton--with-legend-and-labels

### Additional context

Only occurs in safari 
https://brand.sage.com/d/NdbrveWvNheA/components#/basics/radio-buttons/accessibility
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 62.0.1
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Safari
| npm              |
| Operating System | Mac OS Catalina

**Comment by Alec-Walker-Sage** [comment]
FE-3678

**Comment by ianforster-sage** [comment]
This is the default behaviour in Safari. Closing.
