### ISSUE TITLE
Validation on Select components

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3628]
## Feature request
I have set up validation in my application which handles on form submission whether a component has the required prop set, if this is the case and there is no value for the component, then I add a required validation message using the error prop. This is fine for Textboxes, DateInputs and other controls, but Selects, FilterableSelects and MultiSelects don't have the error, info, and warning props for me to display my validation.

### Desired behaviour
error, warning, and info props on FilterableSelect, Select, and MultiSelect.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 61.1.0 |

**Comment by jamime** [comment]
Hi @limcoc, validation props are supported on these components.

![image](https://user-images.githubusercontent.com/2328042/106885736-f1c42780-66da-11eb-88fe-1a407c8ec8c1.png)

Here is a basic codesandbox https://codesandbox.io/s/gh-issue-3628-6kqqh

Hope that helps 🙂

**Comment by limcoc** [comment]
@jamime thanks for this, I had been getting errors using them in a version many moons ago and stopped using them. I didn't realise they are in now because they are not yet in the documentation, thanks!
