### ISSUE TITLE
[ FilterableSelect ] the text inside the Select is highlighted

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#3634]
### Current behaviour

**Browser:** 
Safari issue

**Steps to reproduce:** 
- Open an Design System Select Filterable [disabled](https://carbon.sage.com/?path=/story/design-system-select-filterable--disabled) or [readonly](https://carbon.sage.com/?path=/story/design-system-select-filterable--readonly) or [with disabled portal](https://carbon.sage.com/?path=/story/design-system-select-filterable--with-disabled-portal) or [with object as value](https://carbon.sage.com/?path=/story/design-system-select-filterable--with-object-as-value) stories
- Check the value (text)

**Actual result:** 
The text is highlighted

![Screenshot 2021-02-02 at 14 26 42](https://user-images.githubusercontent.com/34001198/106607274-6aa07380-6563-11eb-89cc-47e6554b2ab9.png)
![Screenshot 2021-02-02 at 14 26 47](https://user-images.githubusercontent.com/34001198/106607278-6b390a00-6563-11eb-90bb-0fd7ea7060b0.png)
![Screenshot 2021-02-02 at 14 26 53](https://user-images.githubusercontent.com/34001198/106607279-6bd1a080-6563-11eb-842f-e9c585481704.png)
![Screenshot 2021-02-02 at 14 26 58](https://user-images.githubusercontent.com/34001198/106607280-6c6a3700-6563-11eb-9cd9-a3b17ca9f1d7.png)

### Expected behaviour

The text should not be highlighted

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 63.2.0 |
| carbon-factory   |
| react-scripts    | 
| React            | 
| Browser          | Safari |
| npm              | 6.0.0 |
| Operating System | MacOS |

**Comment by DlgSHi** [comment]
FE-3684

**Comment by ianforster-sage** [comment]
checked in latest Safari
