### ISSUE TITLE
Icon component to allow additional configurable sizes.

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#3655]
### Current behaviour

The [Icon Component](https://carbon.sage.com/?path=/story/icon--default-story) currently only allows sizes "Small" and "Large", these default to the following sizes:

- Small: Font Size 16px 
- Large: Font Size 24px

![Screenshot 2021-02-09 at 11 51 16](https://user-images.githubusercontent.com/2411024/107359914-2e25c800-6acd-11eb-9cec-5715fbb548fd.png)
![Screenshot 2021-02-09 at 11 51 10](https://user-images.githubusercontent.com/2411024/107359918-2ebe5e80-6acd-11eb-911d-165811ee84c1.png)

### Desired behaviour

We should allow more configurable sizes to the Icon component, in particular as they are designed against a 16px size, therefore fit a 16x multiplier moreso than 8.

### Suggested solution

Add two additional sizes.

**Font Size 32px**

![Screenshot 2021-02-09 at 11 54 40](https://user-images.githubusercontent.com/2411024/107360654-2581c180-6ace-11eb-98f8-712489dd2bb3.png)

**Font Size 48px**

![Screenshot 2021-02-09 at 11 57 20](https://user-images.githubusercontent.com/2411024/107360667-29154880-6ace-11eb-919f-1c57441cab59.png)

The naming of these I leave to. the developer team, but maybe we revert the previous names to be more appropriate.

**Comment by nicktitchmarsh** [comment]
FE-3711

**Comment by ianforster-sage** [comment]
Resolved in https://github.com/Sage/carbon/releases/tag/v68.0.0
