### ISSUE TITLE
Date Input and Range - Safari only - Entering 29, 30 or 31 defaults date to January 0029

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3660]
### Current behaviour
In Safari browser only, when day numbers 29, 30 or 31 are entered in the Date Input or Data Range components the month and year of the date picker defaults to January 0029. See attached movie.

https://user-images.githubusercontent.com/12828099/107391649-cda88200-6af0-11eb-9f49-533590efcddb.mov

### Expected behaviour
The date picker should default to the current month and year.

### Reproducible example
https://carbon.sage.com/?path=/story/experimental-date-input--default-story

### Suggested solution(s)
Have the month and year default to the current one.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.0.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.12.0
| Browser          | Safari Version 14.0 (15610.1.28.1.9, 15610)
| npm              | 6.14.11
| Operating System | macOS Catlina 10.15.7 (19H2)

**Comment by sianford** [comment]
FE-3708

**Comment by grabkowski** [comment]
Fixed in #3730
