### ISSUE TITLE
Data-role not being injected into the Content component

### ISSUE THREAD

**Issue by adamfriedland** [Sage/carbon#3661]
### Current behaviour
I have encountered an issue where my data-role attribute has stopped being injected into the `Content` component. This occurred when I bumped my Carbon version from 59.1.0 to anything higher

### Expected behaviour
data-role to be injected

### Reproducible example
I have replicated the scenario with the ver 59 https://codesandbox.io/s/boring-dust-qfbl5 and 61 here https://codesandbox.io/s/goofy-cohen-umltm

**Comment by nicktitchmarsh** [comment]
FE-3710
