### ISSUE TITLE
Textarea - fieldHelp and labelHelp props are missing from the listed prop types

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#3673]
### Current behaviour
The fieldHelp and labelHelp props are not listed in the props list in the docs.

### Expected behaviour
To show the props in the list.

### Reproducible example
https://carbon.sage.com/?path=/docs/experimental-textarea--default-story

### Suggested solution(s)
Show the props in the list.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.0.3
| carbon-factory   |
| react-scripts    | 
| React            | 16.12.0
| Browser          | Safari, Chrome, Firefox, Edge Chromium
| npm              | 6.14.11
| Operating System | macOS Catalina 10.15.7

**Comment by sianford** [comment]
FE-2289

**Comment by sjohnson-sage** [comment]
Closing this as they are now in the prop table: https://carbon.sage.com/?path=/docs/textarea--default-story
