### ISSUE TITLE
Support downloads from ActionPopovers

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3676]
### Current behaviour
If I want to make a button which can perform a download, then all I need to do is add an href to render it as an anchor and provide the download prop. On the other hand if I want to make an ActionPopover which can perform a download, there is no such option. I can force my way around it by using the onClick event and window.open but browsers will often try to prevent it as a popup.
https://codesandbox.io/s/relaxed-wescoff-z0gky?file=/src/index.js

### Desired behaviour
allow href and download props on an ActionPopover so I can download from a table row.

**Comment by edleeks87** [comment]
FE-3760
