### ISSUE TITLE
Date is reformatted when a selected day is below 12

### ISSUE THREAD

**Issue by arturodrigues** [Sage/carbon#3688]
### Current behaviour
This issue is visible using `en-US` locale which is `'MM/DD/YYYY'`. When choosing a date in the date picker whose day is less than 12, the value is reformatted to `'DD/MM/YYY'` and then, when blurring the date input, it will reformat back to the american locale.

### Expected behaviour
The value should be formatted to the correct locale right after selecting from the date picker.

### Reproducible example
https://codesandbox.io/s/carbon-date-locale-deyrz?file=/src/index.js

### Suggested solution(s)
NA

### Additional context
NA

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.0.3
| carbon-factory   | NA
| react-scripts    | 4.0.0
| React            | 16.12.0
| Browser          | only tested in Chorme 88.0.4324.150
| npm              | 6.14.8
| Operating System | Windows 10

**Comment by ianforster-sage** [comment]
FE-3733

**Comment by grabkowski** [comment]
Fixed in #3730

**Comment by grabkowski** [comment]
Fixed in #3730
