### ISSUE TITLE
Checkbox typescript definition file missing 'name' prop

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3693]
### Current behaviour

The checkbox typescript definition file has no entry for 'name' which is used in all examples on Carbon.sage.com storybook page for checkbox. Example from top of Carbon page:
```typescript
import { Checkbox } from "carbon-react/lib/__experimental__/components/checkbox"

const MyComponent = () => (
  const [isChecked, setIsChecked] = useState(false);
  return (
    <Checkbox
      label="Label"
      name="checkbox-name"
      checked={isChecked}
      onChange={ e => setIsChecked(e.target.checked) }
    />
  )
);
```
`name` is not listed amongst the props at the bottom of the docs page, but if not using this prop the component won't function correctly.

### Expected behaviour

`name` to be a valid prop to use on checkbox component without a typescript error

### Suggested solution(s)

add:
```typescript
name?: string;
```
to the CheckboxProps interface and add an entry to the props section on the carbon docs page.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v59.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by edleeks87** [comment]
FE-3743

**Comment by grabkowski** [comment]
FE-2818
