### ISSUE TITLE
Drawer component Typescript definition for 'children'

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3694]
### Current behaviour

Current entry for Drawer children is:
```Typescript
children: React.FunctionComponent | React.ComponentClass;
```
In our current usage, we are passing ```Typescript React.ReactElement``` into the component, which raises a Typescript error.

### Expected behaviour

The ability to use ```React.ReactElement``` code inside a drawer component to render the right-side of the drawer

### Suggested solution(s)

add ```React.ReactElement``` to the allowed children in Drawer:
```Typescript
children: React.FunctionComponent | React.ComponentClass | React.ReactElement;
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v59.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by edleeks87** [comment]
FE-3744

**Comment by grabkowski** [comment]
FE-2818
