### ISSUE TITLE
PopoverContainer: can't display a Select correctly

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#3695]
### Current behaviour

The select Options are displayed outside the PopoverContainer. So we didn't see all the Option.
![image](https://user-images.githubusercontent.com/38658070/108053311-891b6a00-704d-11eb-8504-97afc3ac09e3.png)

### Expected behaviour

We expect to use Select into PopoverContainer.

### Reproducible example

https://codesandbox.io/s/eloquent-gareth-gn8i6?file=/src/index.js:953-969

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.4.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome
| npm              |
| Operating System | Windows

**Comment by nicktitchmarsh** [comment]
Triage note: this looks like a z-index issue with portal and modal dialogs. Might need to think about how we add z-index to these items

**Comment by edleeks87** [comment]
Might be worth checking if Maciek's PR adding popper into Select will fix it

**Comment by edleeks87** [comment]
Think it does https://codesandbox.io/s/carbon-quickstart-ldgzq?file=/src/index.js

**Comment by edleeks87** [comment]
FE-2546
