### ISSUE TITLE
 Checkboxes do not work along side row headers

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3721]
### Current behaviour

When using FlatTableCheckbox alongside FlatTableRowHeader when you scroll to the right the row header remains where it is but the checkbox scrolls off the screen. 

### Expected behaviour

The checkbox should remain next to the row header and the rest of the content should scroll behind it, like it does with the row header

### Reproducible example

I added Row headers to the MDX example in storybook 
![2021-02-18 14 21 24](https://user-images.githubusercontent.com/72866515/108371756-f9fd8600-71f5-11eb-9323-fac207ee47ca.gif)

**Comment by Alec-Walker-Sage** [comment]
FE-3721

**Comment by sjohnson-sage** [comment]
@harpalsingh could you take a look at this please and confirm whether the Checkbox column should be sticky as well?

**Comment by harpalsingh** [comment]
@sjohnson-sage Yes, in the design, the idea is that whichever column is "sticky" all the columns to the left should also become sticky with it. if we only allow the first "Content" column to be sticky, then yes if checkboxes are presents, they should also stick. An example of this is shown in my prototype too.
