### ISSUE TITLE
Focus state of FlatTableRow in safari 

### ISSUE THREAD

**Issue by Alec-Walker-Sage** [Sage/carbon#3722]
### Current behaviour

When you highlight a row in safari the gold outline appears but it is not a consistent width on the top and bottom. Also moving the mouse cause the gold outline to change widths. This only occurs in safari, not in any other browsers
### Expected behaviour

The gold outline should be consistent in Safari and the same as all the other browsers

### Reproducible example

Visit storybook
https://carbon.sage.com/?path=/story/design-system-flat-table--selectable-and-highlightable-rows
![2021-02-18 14 42 11](https://user-images.githubusercontent.com/72866515/108373879-477af280-71f8-11eb-9556-e1edf62b271c.gif)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Safari
| npm              |
| Operating System | Mac OS

**Comment by ianforster-sage** [comment]
FE-3766

**Comment by sjohnson-sage** [comment]
This issue is no longer present, both myself and @Alec-Walker-Sage have been unable to replicate it with the latest version of Carbon. Closing this issue
