### ISSUE TITLE
GridContainer with (multiple) ternary statements for GridItem children gives typescript error

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3729]
### Current behaviour

If a GridContainer has optional children that we want to conditionally render using a ternary statement, this causes issues if more than one ternary is required.

Will be fine / no Typescript error:
``` Javascript
<GridContainer>
    <GridItem> one </GridItem>
    {booleanCheck1 ? <GridItem> two </GridItem> : null}
    <GridItem> three </GridItem>
    <GridItem> four </GridItem>
</GridContainer
```

Will give error:
``` Javascript
<GridContainer>
    <GridItem> one </GridItem>
    {booleanCheck1 ? <GridItem> two </GridItem> : null}
    {booleanCheck2 ? <GridItem> three </GridItem> : null}
    <GridItem> four </GridItem>
</GridContainer
```
Typescript error from the below linked sandbox code:
```
Type '{ children: (boolean | Element)[]; }' is not assignable to type 'GridContainerProps'.
  Types of property 'children' are incompatible.
    Type '(boolean | Element)[]' is not assignable to type 'ReactElement<GridItemProps, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)> | ReactElement<...>[]'.
      Type '(boolean | Element)[]' is not assignable to type 'ReactElement<GridItemProps, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)>[]'.
        Type 'boolean | Element' is not assignable to type 'ReactElement<GridItemProps, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)>'.
          Type 'boolean' is not assignable to type 'ReactElement<GridItemProps, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)>'.ts(2322)
```
### Expected behaviour

Usage of multiple ternary statement within GridContainer to conditionally render GridItem children be possible without error.

### Reproducible example

https://codesandbox.io/s/long-pond-5i09o?file=/src/index.tsx
^^ thanks to Ed for the sandbox. His gave the error as I loaded it up so didn't need to make any change :)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v66.7
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by ianforster-sage** [comment]
@grabkowski please could you provide a codesandbox example using only an array of valid components, as discussed.

**Comment by grabkowski** [comment]
@PaulSumner-Sage you should compose your GridItem list using an array and then passing that array as children of the GridContainer:

https://codesandbox.io/s/wizardly-paper-gzh60
