### ISSUE TITLE
Box typescript definition file is blank

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3733]
### Current behaviour

when using:
```import Box from "carbon-react/lib/components/box";```
the definition file is currently:
```export { default } from './box.component';```

This issue is **NOT** actively blocking any ongoing work, raising purely to document missing definition.

### Expected behaviour

A valid typescript definition file for the Box component

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v66.7
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by ianforster-sage** [comment]
FE-2818
