### ISSUE TITLE
[FilterableSelect] Error thrown on mouse down

### ISSUE THREAD

**Issue by stripeyjumper** [Sage/carbon#3754]
### Current behaviour
When clicking on the select component it intermittently throws an error.

### Expected behaviour
It should not throw an error

### Reproducible example
https://codesandbox.io/s/cocky-napier-jmfe6?file=/src/index.js

### Suggested solution(s)
The component does not check for the existence of the `data-element` attribute on the target element before inspecting its value.
See here: https://github.com/Sage/carbon/blob/c18255b6b8c62681bbf717eab9871968bef35af6/src/components/select/filterable-select/filterable-select.component.js#L389

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.11.1
| react-scripts    | 3.4.4
| React            | 16.8.3
| Browser          | Chrome
| npm              | 6.14.4
| Operating System | MacOS

**Comment by sjohnson-sage** [comment]
FE-3802
