### ISSUE TITLE
Fullscreen Dialog animation is broken

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#3770]
### Current behaviour

The fullscreen dialog, when actioned appears on the page as a quick fade without any movement animation.

https://user-images.githubusercontent.com/2411024/109625511-4ec6c800-7b37-11eb-974e-8627896d38b4.mov

### Expected behaviour
All dialogs have a movement animation to show it appearing, in particular the fullscreen to show its not a new page.

### Suggested solution(s)

After some discussions with @edleeks87 it appears this might be related to `FocusTrap` component.

**Comment by edleeks87** [comment]
Can be fixed by moving `FocusTrap` a level lower in the html, move it inside `StyledDialogFullScreen`

**Comment by edleeks87** [comment]
FE-3795
