### ISSUE TITLE
FlatTableRow component doesn't allow null as a child value

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#3790]
### Current behaviour
FlatTableRow component doesn't allow null or false as a child.

### Expected behaviour
FlatTableRow component should allow null or false to be passed as they are valid React children.

### Reproducible example
https://codesandbox.io/s/pedantic-frog-cuo55?file=/src/index.js
https://codesandbox.io/s/awesome-surf-bsf2c?file=/src/index.js

### Suggested solution(s)
Handle props property check on child object when null.

### Additional context
N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |    v66.18.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sianford** [comment]
FE-3826
