### ISSUE TITLE
Allow customising height option in Drawer

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#3792]
### Current behaviour

Currently, the wrapper for Drawer component has a height value passed into it, which is `height: 100%`, this however causes a problem when trying top handle custom heights on the component.

https://github.com/Sage/carbon/blob/master/src/components/drawer/__internal__/drawer.style.js#L159

### Desired behaviour

You should be able to control this value with either:

- auto
- 100%
- custom calc height

### Suggested solution

Those options listed above added allow better control when children have the height controlled as needed.

**Comment by sianford** [comment]
FE-3825
