### ISSUE TITLE
Multi Select dropdown icon moves around

### ISSUE THREAD

**Issue by jordanware** [Sage/carbon#3802]
### Current behaviour

When multiple address type pills are added the downward carat icon moves around the comonent. Sometimes it appears in the bottom right of the component and sometimes in the bottom left depending on the address types selected. 

### Expected behaviour
The carat icon needs to remain centrally aligned vertically and horizontally whilst being positioned 16px from the right hand side of the component no matter how many address types are selected.

### Reproducible example
https://codesandbox.io/s/lucid-galileo-yzoim

### Suggested solution(s)
The carat icon needs to remain centrally aligned vertically and horizontally whilst being positioned 16px from the right hand side of the component no matter how many address types are selected. 

### Your environment

| Client Management       | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System | Mac

**Comment by sianford** [comment]
FE-3824

**Comment by dawidzarzycki** [comment]
🎉 This is fixed in version 68.8.3 🎉
