### ISSUE TITLE
Search icon overlaps submenu 

### ISSUE THREAD

**Issue by jordanware** [Sage/carbon#3803]
### Current behaviour
In the Menu component the search icon is overlapping with the nav dropdown.  

### Expected behaviour
The icon from the search bar below the Nav should not appear on top of the nav. 

### Your environment

| User Management        | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |Mac

**Comment by sjohnson-sage** [comment]
@jordanware I have removed the screenshots and will change the description - this Carbon Github is open source and viewable to the public, therefore you shouldn't put any product information or screenshots in these issues

**Comment by jordanware** [comment]
Thanks @sjohnson-sage I wasnt sure how to find the info about the environment.

**Comment by sjohnson-sage** [comment]
No problem @jordanware - the Carbon codesandbox template is in the Github issue template when you open it (under the Reproducible example section) but here it is as well: https://codesandbox.io/s/carbon-quickstart-xi5jc 

If you fork that and make a copy of the Menu/Search setup that has the issue (without any product info) we'll be able to replicate it and get to the bottom of the issue. A dev on your team should be able to assist with that if you need a hand

Feel free to send me (or anyone on the Carbon team) any product screenshots on slack or email that may assist as well

**Comment by sianford** [comment]
FE-3823

**Comment by sjohnson-sage** [comment]
This issue was fixed in Carbon version `63.3.1`
