### ISSUE TITLE
DialogFullScreen does not focus the first input element

### ISSUE THREAD

**Issue by arturodrigues** [Sage/carbon#3817]
### Current behaviour
When using DialogFullScreen component, the focus is in the close button icon on the top right, instead of focusing the first element in the dialog body, like the Dialog component.

### Expected behaviour
DialogFullScreen component should behave like the Dialog by focusing the first element of the dialog body.

### Reproducible example
https://codesandbox.io/s/dialogs-with-input-rn1pv?file=/src/App.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.0 | 
| carbon-factory   | NA |
| react-scripts    | 4.0 | 
| React            | 1701 | 
| Browser          | any |
| npm              | 6.14.18 |
| Operating System | any |

**Comment by sjohnson-sage** [comment]
Thanks for raising @arturodrigues - this looks like a valid issue, we will change the `DialogFullScreen` behaviour to be the same as `Dialog`

**Comment by sjohnson-sage** [comment]
FE-3968

**Comment by sjohnson-sage** [comment]
This was fixed in version 70.6.0 so I'm closing it - https://github.com/Sage/carbon/releases/tag/v70.6.0
