### ISSUE TITLE
Typescript - Dialog - Missing typescript declaration file

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#3818]
### Current behaviour

There is currently no exported typescript file for the Dialog component

### Expected behaviour

A Typescript file exported for the Dialog component

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v68.3.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
This will be added by @grabkowski in FE-2818

**Comment by grabkowski** [comment]
Fixed in #3837
