### ISSUE TITLE
Dialog : Header style when too long

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3828]
### Current behaviour
When a title is too long, it exceeds the size of the dialog

### Expected behaviour
Either the title is truncated (with '...') or displayed on multiple lines.

### Reproducible example
![image](https://user-images.githubusercontent.com/16415182/111290461-785b1580-8646-11eb-87c8-a9db49193e63.png)

Reproducible in the storybook

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.0.2 |

**Comment by sjohnson-sage** [comment]
@harpalsingh should we truncate this or let the title wrap over multiple lines? and if we truncate, should we have a tooltip that displays the full title when you hover over it? Thanks

**Comment by harpalsingh** [comment]
Hey, in this case the title should wrap onto two lines, increasing the header size, its not content we need to hide with truncation and we have enough room to work with. That being said, this is also a lot to do with text choice from content, but bringing in responsive work we want to handle, wrapping is the sensible solution.

**Comment by mkrds** [comment]
FE-4025
