### ISSUE TITLE
Error when typing in search box within MenuItem

### ISSUE THREAD

**Issue by jlongridge** [Sage/carbon#3830]
### Current behaviour
When typing in a search box within a menu item an error occurs:
```
TypeError
Cannot read property ‘toLowerCase’ of undefined
```
https://codesandbox.io/s/charming-matsumoto-gxyz9?file=/src/index.js

### Expected behaviour
No Errors when typing.

### Reproducible example
Use the following codesandbox and type in the search box.
https://codesandbox.io/s/charming-matsumoto-gxyz9?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.3.1
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
Hi @jlongridge thanks for raising, we will put it on our backlog and get it fixed

**Comment by sjohnson-sage** [comment]
FE-3966
