### ISSUE TITLE
Add prop to Dialog to enable a help link in the heading

### ISSUE THREAD

**Issue by NucsuM** [Sage/carbon#3831]
### Current behaviour
The `help link` is placed on the next line

### Expected behaviour
The `help link` have to be aligned to the right side of the title (this dialog header is custom styled without a `Heading` component)

### Reproducible example
https://codesandbox.io/s/jovial-sammet-hp90r

### Additional context
This codesandbox uses carbon `42.6.0` but this problem also exists in version `62.0.0`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  62.0.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.13.1
| Browser          | Chrome / Firefox
| npm              |
| Operating System | MacOS

**Comment by sjohnson-sage** [comment]
Hi @NucsuM, the issue here is that the `title` prop on Dialog does not currently accept a node. It either accepts a string or an object so this usage is incorrect.

If you need a help icon in the Dialog header like this we can convert this to a feature request and enable that feature?

**Comment by NucsuM** [comment]
Hi @sjohnson-sage Thank you for this answer. Do you mean that the `Dialog` could get an `helpLink` property so that my `Heading` only needs a `title`? This could be very usefull and would avoid my workaround. 👍

**Comment by sjohnson-sage** [comment]
Yeah exactly that @NucsuM - let's turn this into a feature request to add that option in!

**Comment by sjohnson-sage** [comment]
As above, the solution here should be to add on option to `Dialog` to allow a help link in the header

**Comment by dawidzarzycki** [comment]
@harpalsingh do you think we should have that functionality?

**Comment by harpalsingh** [comment]
Hey @dawidzarzycki Yes I think we should, in the live app we allow help tooltips with all titles where needed, so for me it should be an option on dialog titles too, though how often we really should use them is a different question. As per design though if a help link/tooltip/icon is used, I would place it inline with the end of the title.

**Comment by mkrds** [comment]
FE-4026
