### ISSUE TITLE
Tabs: Menu like Select or FilterableSelect stays open when the tab is changed

### ISSUE THREAD

**Issue by konrazem** [Sage/carbon#3833]
### Current behaviour

Menu like Select or FilterableSelect stays open when the tab is changed

### Expected behaviour

Menu should be closed when I change the tab

### Reproducible example 
[https://codesandbox.io/s/dazzling-roentgen-snkff?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/dazzling-roentgen-snkff?fontsize=14&hidenavigation=1&theme=dark)
### Suggested solution(s)

Set z-index for each tab content or reset components states on tab change (?)

### Additional context

I think workaround would be to handle the states of those components by setState method, by the programmer and not by Tabs component. However I do not see any method like onChange  for Tabs component.
[https://github.com/Sage/carbon/blob/master/src/components/tabs/tabs.component.js](https://github.com/Sage/carbon/blob/master/src/components/tabs/tabs.component.js)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  68.0.2
| carbon-factory   | 11.0.1
| react-scripts    |  
| React            | 16.13.1
| Browser          | Chrome 
| npm              |  6.14.8
| Operating System | Windows 10

**Comment by sjohnson-sage** [comment]
Hi @konrazem - thanks for raising this. To fix it you can simply add the `disablePortal` prop to `FilterableSelect`

This could also be a bug however, I would expect this select dropdown to close when it loses focus, I will add it to our backlog to look into

**Comment by sjohnson-sage** [comment]
FE-3965
