### ISSUE TITLE
Date Range component throwing compilation error

### ISSUE THREAD

**Issue by Siphenathi-Nathi** [Sage/carbon#3838]
### Current behaviour
I just added the DateRange component and i received a compilation error same time. Looking at the error message it seems like the date picker is trying to import some css.
![image](https://user-images.githubusercontent.com/51409045/111647949-94f47a80-880b-11eb-9209-a78e04cff60f.png)

### Expected behaviour
I would expect the DateRange component no to throw compilation error

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react    |  63.0.0
| carbon-factory   |
| react-scripts    | 
| React            | 16.13.1
| Browser          |
| npm              |
| Operating System | win 10

**Comment by ianforster-sage** [comment]
FE-3975
