### ISSUE TITLE
Styled components padding does not apply correctly to table cells

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#3846]
### Current behaviour

As you can see below, the following code is used on a TableCell

`<FlatTableCell p={2}>`

![Screenshot 2021-03-22 at 09 20 33](https://user-images.githubusercontent.com/2411024/111967543-14c26380-8af0-11eb-91fe-1a3d16e611cf.png)

However the problem is the padding left and right is using the base table cell padding and not the provided override, whereas the cell has no top/bottom default padding therefore those worked correctly.

### Expected behaviour

The passed padding values should take precedence.

**Comment by dawidzarzycki** [comment]
FE-3986
