### ISSUE TITLE
FlatTable - height issue

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#3850]
### Current behaviour

When `hasStickyHead` is added to FlatTable, a `height: 100%` is added to a table, this causes the following issue based on layout decisions:

![Screenshot 2021-03-22 at 15 53 46](https://user-images.githubusercontent.com/2411024/112018837-d3997600-8b26-11eb-8f8c-bfcad35ca4ea.png)

code:

![Screenshot 2021-03-22 at 15 55 27](https://user-images.githubusercontent.com/2411024/112019141-0fccd680-8b27-11eb-9628-74e5513683b7.png)

### Expected behaviour

Either the table should have an adequate background/borders or a max-height: 100% option, rather than height:100%

### Suggested solution(s)

Allow the option of either using max-height:100%, or if height: 100% is used then we need correct background and border styling and not a transparent gap.

**Comment by dawidzarzycki** [comment]
FE-3986
