### ISSUE TITLE
Filterable select and reset

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#3854]
### Current behaviour
I have a controlled filterable select with a value.
If i remove the value, the 'Please select....' is displayed and stays if i loose focus.
The onchange is not triggered so my controlled value is not changed and, with the next render, the old value is redisplayed.

### Expected behaviour
When i remove the value, the onchange is triggered

### Reproducible example
https://codesandbox.io/s/ecstatic-tu-n1ix9?file=/src/index.js
remove the value of the first select then change the value of the second : the value of the first one will roll back to the old one

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.0.2 |

**Comment by dawidzarzycki** [comment]
FE-3985
