### ISSUE TITLE
FlatTableRow prop "expanded" does not work if controlled

### ISSUE THREAD

**Issue by tboulis** [Sage/carbon#3875]
### Current behaviour
If we try to control the `expanded` prop of a `<FlatTableRow>` the component does not handle the changed `expanded` prop.

### Expected behaviour
The component should respond to changes in the `expanded` prop

### Reproducible example
https://codesandbox.io/s/lucid-mahavira-f5gw7?fontsize=14&hidenavigation=1&theme=dark

### Suggested solution(s)
Seems like a useEffect is missing for the `expanded` prop (as @edleeks87 mentioned)

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.9.0 |
| carbon-factory   | - |
| react-scripts    |  4.0.3 |
| React            | 16.14.0 |
| Browser          | Chrome | 
| npm              | - |
| Operating System | MacOS |

**Comment by ianforster-sage** [comment]
FE-4007
