### ISSUE TITLE
Checkbox in FlatTable head scolls with body if "hasStickyHead" is true

### ISSUE THREAD

**Issue by tboulis** [Sage/carbon#3876]
### Current behaviour
When `<FlatTable>` has `hasStickyHead={true}` and the table has fixed height and the header row is selectable (has Checkbox), the header checkbox scrolls with the body of the table:
http://g.recordit.co/wlvvmDuOR2.gif

### Expected behaviour
The checkbox in the header should "stick" with the rest of the header cells

### Reproducible example
https://codesandbox.io/s/proud-brook-6gtz3?fontsize=14&hidenavigation=1&theme=dark

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.9.0 |
| carbon-factory   | - |
| react-scripts    |  4.0.3 |
| React            | 16.14.0 |
| Browser          | Chrome |
| npm              | - |
| Operating System | MacOS |

**Comment by ianforster-sage** [comment]
FE-4008
