### ISSUE TITLE
Expandable Flat Table: text not centered with a row headers 

### ISSUE THREAD

**Issue by clbor** [Sage/carbon#3887]
There is an alignment gap between the "colapse" icon and the folder name if we configure the expand only on the first column. There is a similar issue in the Carbon story book, see the image below.

![image](https://user-images.githubusercontent.com/16819211/114053492-49277500-988f-11eb-82f6-b39393d357f8.png)

### Expected behaviour
All the text in the columns are aligned

### Reproducible example
In the section"With row header section" of this story book link
https://carbon.sage.com/?path=/docs/design-system-flat-table-expandable--default-story 

### Your environment
"carbon-react": "68.8.3"
Chrome: 89.0.4389.114

**Comment by ianforster-sage** [comment]
FE-4015
