### ISSUE TITLE
Link icons are visible when horizontally scrolled behind a FlatTableRowHeader

### ISSUE THREAD

**Issue by limcoc** [Sage/carbon#3909]
### Current behaviour
As in the code sandbox example, when I have a link component with an icon, when it is horizontally scrolled behind a flattablerowheader, the icon remains visible when it should be hidden behind the flattablerowheader.

### Expected behaviour
the icon should be hidden behind the flattablerowheader like all the other content within a table cell.

### Reproducible example
https://codesandbox.io/s/icon-above-flattablerowheader-18qgg?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.11.0 |

**Comment by mkrds** [comment]
FE-4028
