### ISSUE TITLE
Dropdown Menu in Pager Component

### ISSUE THREAD

**Issue by Mahergall** [Sage/carbon#3911]
### Current behaviour

in the Pager Component when setting the showPageSizeSelection to true , Clicking the dropdown Menu to change the size of the showed elements will lead to ReferenceError: ResizeObserver is not defined, 

### Expected behaviour

  we can change the size of page when needed
### Reproducible example

 the storyBook page , just open the pager Component with Firefox(68.2.0esr)
### Suggested solution(s)
add Polyfill for ResizeObserver  as it's not supported by some browsers

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory    @|
| react-scripts    | 
| React            |
| Browser          | Firefox 68.2.0esr
| npm              |
| Operating System |

**Comment by mkrds** [comment]
@Mahergall Please update your browser to the latest version
