### ISSUE TITLE
Wrong typesfor pager

### ISSUE THREAD

**Issue by gandalf92** [Sage/carbon#3922]
### Current behaviour
Types should be re-evaluated for various components.
In this case the Pager.

### Expected behaviour
Types used inside of the component should be correct.

### Reproducible example
onPagination-property of the pager-component has wrong typings.

At the moment it is:
`onPagination: (pageSize: number, currentPage: number) => void`

Also, when clicked on "showLast", the current-page is not typeof number.
Instead it is typeof string.

### Suggested solution(s)
Re-Evaluate typings vor components.

onPagination for example should be:
`onPagination: (currentPage: number, pageSize: number, type: string)`

Also here types could be the possible types instead of a string.

**Comment by nicktitchmarsh** [comment]
This will be addressed by our task FE-2818
