### ISSUE TITLE
[ Menu ] the component opens in wrong way in small screen when in Nav Bar

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#3935]
### Current behaviour

1. Open [storybook](https://carbon.sage.com/?path=/story/design-system-menu--full-navbar-alignment-example)
2. Open DevTools
3. Drag the devtools to the left to make the screen smaller
4. Hover over the Menu Item One

it looks like on a screen below:

<img width="873" alt="Screenshot 2021-04-21 at 10 56 00" src="https://user-images.githubusercontent.com/34001198/115532572-37ce6780-a296-11eb-99de-bafa01385899.png">

### Expected behaviour

it should be opened straight below the `Menu` parent item.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.21.1 |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | All |
| npm              |
| Operating System | MacOS |

**Comment by DlgSHi** [comment]
FE-4043

**Comment by nicktitchmarsh** [comment]
Menu item truncation should solve the visual issue seen here
