### ISSUE TITLE
MultiSelect x for Pills displayed outside the input when in a sidebar

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#3943]
### Current behaviour
When I have a multiselect within a sidebar the little x is displayed outside of the pills
![image](https://user-images.githubusercontent.com/16744242/116055473-a59ed880-a674-11eb-860e-251eeb8bcb67.png)

### Expected behaviour
the cross on a pill for a selected option in a multiselect component is displayed in the correct position when rendered within a sidebar, like it is when placed elsewhere.

### Reproducible example
https://codesandbox.io/s/hidden-wildflower-hz15v?file=/src/index.js

**Comment by sjohnson-sage** [comment]
This by this CSS in Sidebar: https://github.com/Sage/carbon/blob/fcd8177f0842007d3ab521908bd7ae81bd3b378e/src/components/sidebar/sidebar.style.js#L38 
It targets all `StyledIconButton`s inside of a Sidebar - it should be made more specific to target just the Sidebar close icon

**Comment by ianforster-sage** [comment]
FE-4055
