### ISSUE TITLE
Portrait tooltip throws errors if src prop is undefined

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#3958]
## Current behaviour
The changes added in #3554 to the portrait component produce bugs when the new tooltip props are used but the portrait does not have the src prop set.

If I specify a tooltipMessage but no src, the tooltip is simply not displayed.
If I specify a tooltipMessage and initials but no src, a Syntax Error is displayed (see codesandbox)

### Reproducible example
https://codesandbox.io/s/vigorous-nash-0o6iu?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 70.4.0 |

**Comment by ianforster-sage** [comment]
FE-4057
