### ISSUE TITLE
DateRangeInput has large gaps between inputs when labels are inline

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#3959]
### Current behaviour
If I use the labelsInline property on a DateRangeInput, and give it labels which are slightly longer, requiring wrapping onto a second line, the div for the input becomes a lot wider than the actual input itself and the two inputs become widely spaced apart.
![image](https://user-images.githubusercontent.com/16744242/116524374-383ab400-a8cf-11eb-835b-f51eb4b9826d.png)

### Expected behaviour
There should be no excess trailing gap behind the DateInputs within a DateRangeInput except the margin.

### Reproducible example
https://codesandbox.io/s/practical-cookies-g2xy9?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | latest |

**Comment by ianforster-sage** [comment]
FE-4058
