### ISSUE TITLE
Can not retrieve the ref of a DialogFullScreen component since v70.0.0

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#3980]
### Current behaviour

Since version 70.0.0, we can't retrieve the ref of a DialogFullScreen component? In CM, we used it to scrollable content.

### Reproducible example

https://codesandbox.io/s/lingering-sun-7j3ff?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |70.0.0
| carbon-factory   |
| react-scripts    | 4.0.3
| React            |17.0.2
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-4062
