### ISSUE TITLE
TileSelect - titleAdornment - Pill styling with word wrap

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#3982]
### Current behaviour

When using a Pill in ```titleAdornment``` the text inside will wrap if there are multiple words.

### Expected behaviour

Pill text should not wrap when in ```titleAdornment``` as ti does not wrap when outside of a TileSelect

### Reproducible example

https://codesandbox.io/s/sharp-sunset-2vh1k?file=/src/index.js
<img width="288" alt="Screenshot 2021-05-04 at 13 42 05" src="https://user-images.githubusercontent.com/53473905/117004936-91935080-acde-11eb-9388-fc194c4b60b1.png">

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v70.9.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by nicktitchmarsh** [comment]
FE-4076 has been raised for this issue
