### ISSUE TITLE
Accordion - Enable children in title

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4010]
### Current behaviour
The type of the accordion's title prop is string.

### Expected behaviour
We would like to use children

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v70.0.0 |

**Comment by dawidzarzycki** [comment]
@harpalsingh Could you confirm that this feature should be implemented in Carbon?

**Comment by harpalsingh** [comment]
I think there is good logic to allow this, so we can open the design to maybe use the type component, pills, info.

Default of course is string, but I dont see any problem in allowing use of components if needed, as long as this didnt impact the usage of the click to open or confuse users, e.g if someone decided to add a button.

**Comment by sjohnson-sage** [comment]
FE-4133
