### ISSUE TITLE
Definition list terms are duplicated when each definition is wrapped in a react fragment

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4013]
### Current behaviour
I would to start using the changes made in #3582 to start conditionally rendering the definitions within my definition lists based upon a condition on each of them. However, when they are all wrapped in fragments, the dt elements are visually duplicated.
Also if I only have one definition in the list and it is wrapped in a fragment, then an error is thrown.

### Expected behaviour
Sometimes I have definition lists where all the entries within that list are conditionally rendered. If all of the definitions in the list are wrapped in fragments, the dt elements should not be duplicated.

### Reproducible example
When a definition list only contains definitions that are wrapped with react fragments, the dt elements are duplicated
https://codesandbox.io/s/practical-https-y8wxb?file=/src/index.js
When there is only one definition in the list and it is wrapped in a fragment, the error "Cannot read property 'type' of undefined" is thrown
https://codesandbox.io/s/stoic-ramanujan-wvnnj?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 70.9.0 |

**Comment by dawidzarzycki** [comment]
FE-4099
