### ISSUE TITLE
GridContainer not accepting Array of GridItems

### ISSUE THREAD

**Issue by ravi-ankam** [Sage/carbon#4018]
### Current behaviour

GridContainer Throws a console error when  Array of GridItems  are used as children.
 "console.error
      Warning: Failed prop type: Invalid prop `children` supplied to `GridContainer`."
### Expected behaviour
GridContainer should accept an array of GridItems.
### Reproducible example

https://codesandbox.io/s/mutable-pond-dr3yy
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by grabkowski** [comment]
FE-4085
