### ISSUE TITLE
Tabs on left are changing width when content change

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4024]
### Current behaviour
When text in tab is longer then space in the tab it make content narrower.
![image](https://user-images.githubusercontent.com/75613789/118251455-e5a0f080-b4a7-11eb-9222-6d92afe3c30e.png)

### Expected behaviour
Tab width should be the same width for any content.

### Reproducible example
https://codesandbox.io/s/objective-fog-0t19d?file=/src/index.js

### Suggested solution(s)
Prop for set width of tabs or max width.

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  74.0.0
| react-scripts    |  4.0.3
| React            | 16.14.0
| Browser          | any
| Operating System | any

**Comment by sjohnson-sage** [comment]
@maspychaj-sage what's the use case for having two sets of tabs on top of one another?

**Comment by maspychaj-sage** [comment]
> 
> 
> @maspychaj-sage what's the use case for having two sets of tabs on top of one another?

I've got two Tabs on two different pages and it's not consistent when you change pages. It's not possible to have the same layout when tabs strings are longer.

**Comment by nicktitchmarsh** [comment]
FE-4161 has been raised to address the width of the tabs
