### ISSUE TITLE
TileSelect component - Type definition file missing footer prop definition

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#4038]
### Current behaviour

using ```footer``` prop on a TileSelect component gives type warning as it is missing from the ```tile-select.d.ts``` file. 
The footer prop itself is present in the actual component and functions correctly.

### Expected behaviour

Correct type definitions to match Carbon docs: <https://carbon.sage.com/?path=/docs/design-system-tile-select--with-a-footer>

### Suggested solution(s)

add in a definition for ```footer``` prop to definition file that allows JSX.Element or similar.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v72.0.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-4109

**Comment by edleeks87** [comment]
Fixed and released as part of https://github.com/Sage/carbon/releases/tag/v75.2.6

#4089
