### ISSUE TITLE
Definition List component - Type definition file missing  pb prop definition

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#4039]
### Current behaviour

using **pb** prop on a Dl component gives type warning as it is missing from the dl.d.ts file.

### Expected behaviour

Correct type definitions to match Carbon docs https://carbon.sage.com/?path=/docs/design-system-definition-list--default-story

### Suggested solution(s)

add in a definition for **pb** prop to definition file 
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 74.1.1
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by grabkowski** [comment]
hi @hagad, have you installed the styled system types?
```npm i @types/styled-system --save-dev```

**Comment by grabkowski** [comment]
I've just mirrored what is in js adding types, this might be a leftover from before styled-system was implemented in this component.
