### ISSUE TITLE
dropdown-filter with accent opens by itself (InternetExplorer)

### ISSUE THREAD

**Issue by frbar** [Sage/carbon#404]
If `dropdown-filter` component has item with accent in it, and if that item is selected, then when component is displayed the dropdown opens by itself.

I have reproduced this issue with **Internet Explorer 11** and carbon demo:
- edit `dropdown-demo.js`
- import `dropdown-filter` instead of `dropdown`
- rename `Option Four` to `Option ééé` (or add new option)

![drop-down-with-accent](https://cloud.githubusercontent.com/assets/16399900/14527540/04d29be4-024b-11e6-84ed-a1938c9b7c2b.gif)

**Comment by edleeks87** [comment]
DropdownFilter has been deprecated in favour of Select, we believe this issue is now fixed so we are closing this
