### ISSUE TITLE
TileSelect component - description prop only allows string in type definition

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#4040]
### Current behaviour

To match UX designs we need to use Markdown to enforce newlines in the description text.

Using the 'SageMarkdown' component:
```sbc.core.orghub.ui/src/components/SageMarkdown/SageMarkdown.tsx```
gives a type error in TileSelect as it only allows ```string | undefined```.
When Type warning is ignored the markdown renders correctly inside the Tile.

### Expected behaviour

The ability to use values other than string for the description param

### Suggested solution(s)

Not sure what generic type you will add for this, but SageMarkdown returns ```JSX.Element``` and uses ```<ReactMarkdown>```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v72.0.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-4108

**Comment by edleeks87** [comment]
Fixed and released as part of https://github.com/Sage/carbon/releases/tag/v75.2.6

https://github.com/Sage/carbon/pull/4089
