### ISSUE TITLE
Link component: Link is wrapped in a div which when used in markdown renders invalid html

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4052]
### Current behaviour

I am trying to create a Markdown component that uses Carbon elements such as the Carbon Link to have correctly styled output.

![image](https://user-images.githubusercontent.com/3584292/118980810-94927000-b971-11eb-900e-81d5339ec9ed.png)

![image](https://user-images.githubusercontent.com/3584292/118980526-76c50b00-b971-11eb-9e68-c38e71c40e13.png)

I receive the following error in console: 
```
validateDOMNesting(...): <div> cannot appear as a descendant of <p>
```

### Expected behaviour

I would expect the Link to be an `<a>`

### Reproducible example

https://codesandbox.io/s/focused-leftpad-wux1m?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 74.3.1
| carbon-factory   | n/a
| react-scripts    |  n/a
| React            | 16
| Browser          | 
| npm              | 6
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-4132
