### ISSUE TITLE
SimpleColor - onBlur is not a function

### ISSUE THREAD

**Issue by dawidzarzycki** [Sage/carbon#4062]
### Expected behaviour
no errors

### Reproducible example
Issue occurs on carbon story

https://carbon.sage.com/?path=/story/experimental-simple-color-picker--default-story

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react   | 74.5.1|
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by edleeks87** [comment]
FE-4124
