### ISSUE TITLE
characterLimit for Text Editor is not shown

### ISSUE THREAD

**Issue by gfigueras-sage** [Sage/carbon#4077]
### Current behaviour
The number of characters won't appear on the editor box even though I specified it.

### Expected behaviour
Remaining characters should appear on the editor box.

### Reproducible example
Sorry, I can't make the import of text editor work on codesandbox, but my code looks like this:

```
<TextEditor
  labelText=''
  onChange={setValue} 
  value={value} 
  ref={ref} 
  characterLimit={limit} 
  toolbarElements={actions}
  plugins={[emojiPlugin,mentionPlugin]}
  rows={2}
  handleKeyCommand={handleKeyCommand} />
```

### Suggested solution(s)
Show number again.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | ^71.2.0 |
| carbon-factory   | not used |
| react-scripts    | ^4.0.3 |
| React            | ^16.13.1 |
| Browser          | Tested on Chrome & Safari |
| npm              | 6.14.11 |
| Operating System | macOS Catalina 10.15.7 |

**Comment by edleeks87** [comment]
Hi @gfigueras-sage I've created a sandbox to test it out and I'm not able to recreate the issue you're having, would you mind using it and updating it so we can investigate? FYI `plugins` and `handleKeyCommand` aren't currently supported props within `TextEditor`.

https://codesandbox.io/s/exciting-tharp-j6w84?file=/src/index.js

**Comment by grabkowski** [comment]
Hi @gfigueras-sage, can we have an update on this please?

**Comment by ianforster-sage** [comment]
DMed author on Slack.

**Comment by ianforster-sage** [comment]
Author advised to close this as it is invalid.
