### ISSUE TITLE
Accordion height not being calculated correctly

### ISSUE THREAD

**Issue by DipperTheDan** [Sage/carbon#4078]
### Current behaviour
<img width="651" alt="Screenshot 2021-05-25 at 14 32 02" src="https://user-images.githubusercontent.com/56251247/119506597-fc77fa80-bd65-11eb-9205-b822d950c87b.png">

### Expected behaviour
<img width="649" alt="Screenshot 2021-05-25 at 14 37 49" src="https://user-images.githubusercontent.com/56251247/119507513-cdae5400-bd66-11eb-914d-75facd4b4153.png">

### Reproducible example
https://codesandbox.io/s/busy-mestorf-jvxgk

### Suggested solution(s)
N/A

### Additional context
There seems to be something strange going on with the flex styles on `StyledAccordionContentContainer` - it actually has the correct height based on the accordion’s content, but it seems to offset it’s content vertically which causes it to cut off the bottom

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 74.5.1
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
FE-4131
