### ISSUE TITLE
The onClick routing approach does not support all of the features of an anchor tag

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4084]
### Current behaviour
After moving away from having routerLink properties on components and using onClick events to perform navigation as advised in the [usage with routing](https://carbon.sage.com/?path=/docs/documentation-usage-with-routing--page) documentation. Links do not behave in the same way as a Link component from a routing library or an ordinary anchor tag would because the component will now render a button in the HTML rather than an anchor. This means that some of the functionality is also lost, such as hovering over and getting the URL displayed at the bottom of the page, middle-clicking to open in a new tab or having the specific right-click options available for an anchor tag.

### Expected behaviour
Any component that is expected to provide routing and has an href property (Button, Link, FlatTableRow, MenuItem, ActionPopoverItem...) can be provided with a router link component from a library of choice as can be done in other component libraries such as [in material ui](https://material-ui.com/guides/composition/#routing-libraries). 

### Reproducible example
This code sandbox shows the difference in behaviour between a pure react-router link and a carbon link component: https://codesandbox.io/s/laughing-germain-i9lmi?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | latest |

**Comment by sjohnson-sage** [comment]
FE-4130

**Comment by StylianosKoidakisSage** [comment]
Maybe a good idea is the CarbonLink component to use/consume the Link component of react router library, whatever change occur on the future regarding navigation we will be up to date. Also we should consider that we need to support external links. For achieving this maybe on the CarbonLink component we can pass a property `to` for internal links and a property `href` for external ones. From a design point of view i would not use buttons ui elements for navigation but in some cases could make sense.

<CarbonLink to="/parent/child" />
<CarbonLink href="https://github.com/Sage/carbon/blob/master/src/components/link/link.component.js" />

**Comment by jamime** [comment]
We should be able to support 
```js
<RouterLink component={CarbonLink} to="/home">Home</RouterLink>
```

**Comment by ianforster-sage** [comment]
@tempertemper should we use an <a> element with onClick here? Right now we render a <button> that looks like a Link.

**Comment by tempertemper** [comment]
We should render an `<a>` element with an `href` attribute wherever a link is intended. @liam-cochrane is right that loads of functionality is different between links and buttons:

- You can activate a button with <kbd>space</kbd> or <kbd>enter</kbd>, where a link should only activate with <kbd>enter</kbd>; <kbd>space<kbd> should scroll the page down
- Links are draggable, so they can be dropped on the tab bar to open in a new tab, on a filesystem window to save the target as a .html file, etc.
- Links can open in a new window (by holding a modifier key like <kbd>command</kbd> on Mac or <kbd>control</kbd> on Windows), choosing the option to open in a new tab/window from a context menu, or using a fancy mouse button
- Buttons are read out as 'button' by screen readers, which can be a confusing experience
- If a link is a button, a speech recognition software user can't ask to "click X link" as it's not a link (even though it might look like one)

'Faking' a link on an element other than `<a>` involves a good amount of ARIA (like changing the `role`), HTML attributes (e.g. `draggable="true"`), JavaScript (to change the <kbd>space</kbd> behaviour), etc. Possible, but nothing is more robust than rendering an `<a href="">` as you get all behaviour and semantics for free.
