### ISSUE TITLE
Text Editor : add a text size option

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4108]
### Current behaviour
The Text Editor component provides 4 options : Bold, Italic, bulleted list, numbered list.

### Desired behaviour
We would like an option to define the size of the text, like h4, h3 and normal
![image](https://user-images.githubusercontent.com/16415182/119998657-31d45080-bfd1-11eb-80e7-ab78c50299ba.png)

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 69.0.0 |

**Comment by DipperTheDan** [comment]
@harpalsingh Is this request OK from a UX point of view? Have you got anything you would like to add to this too. Thank you 😄

**Comment by harpalsingh** [comment]
Hey @DipperTheDan, I believe @kylemayne did the work on the component originally and the requirement of the formatting was based around notes and how they would be used. I don't see a problem is adding the option for formatted text sizes as it goes directly down to other potential use cases. I would suggest each "formatting" option is of course off by default and so designs/devs pick/choose based on requirements.

I would suggest we need a design to consider the best options on how to add a text size changer to the component though, so I don't think you can work directly from the concept provided and should go through a design task.

**Comment by jamime** [comment]
Awaiting designs from UX.

**Comment by mmaciorowski-sage** [comment]
Hi @harpalsingh do we have some more information about designs?

**Comment by mkrds** [comment]
@harpalsingh

**Comment by clairedenning** [comment]
From the DS team: As far as I am aware this hasn't been requested by other products yet, so I'm afraid we can't advise on this as we haven't considered this topic yet.

**Comment by DlgSHi** [comment]
@clairedenning can you provide more information about when you will consider this?

**Comment by clairedenning** [comment]
Generally if something is only requested by one product, then it's too product-specific to add to the DS.

**Comment by samtjo** [comment]
@nicktitchmarsh does this mean we can close the issue - it sounds like it will not be added to the Design System?

**Comment by nicktitchmarsh** [comment]
I'm having a meeting with DS to discuss their intentions for Text Editor. We are thinking of switching away from draft.js so we could easily include this, I don't think this is something a wrapping component could include easily so a change like this would have to come from Carbon. I'd like to include it if possible.

**Comment by samtjo** [comment]
@nicktitchmarsh where did we get to with the Design System team on this one?

**Comment by nicktitchmarsh** [comment]
It is on the list of components for redesign so I am going to close this ticket
