### ISSUE TITLE
Storybook : provide the resources for translation

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4109]
### Current behaviour
In the storybook, each component has its list of props listed and explained.

### Desired behaviour
We would like the same thing for the potential resources used by that component.

For example, listing the following resources for the pager : pager.of_y, pager.records, .....
And the meaning of each.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 69.0.0 |

**Comment by DipperTheDan** [comment]
FE-4144
