### ISSUE TITLE
Text Editor : allow tooltip translation

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4121]
### Current behaviour
Currently, the tooltips of the toolbar in the Text Editor are hard coded.
![image](https://user-images.githubusercontent.com/16415182/120664206-0945ce00-c48b-11eb-8ec9-a02571a1ef62.png)

### Expected behaviour
Provide resources (I18n) or props allowing to translate.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 69.0.1 |

**Comment by nicktitchmarsh** [comment]
FE-4159 has been raised to address this
