### ISSUE TITLE
Typography component does not have option to style white-space

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#4122]
### Current behaviour

Using Typography component to display text in a tight space can cause unwanted line wraps

### Expected behaviour

A prop to be available to control the behaviour of white-space and provide nowrap

### Additional context

Issue raised as discussed and requested in Slack thread

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v72.1.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by jamime** [comment]
We should consider

- white-space
- word-wrap
- text-overflow

**Comment by nicktitchmarsh** [comment]
FE-4158 has been raised to address this
