### ISSUE TITLE
trouble with onClick on Search component 

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#4127]
### Current behaviour

With Search component, if you click in the box of the search, the onClick is called.
It should be called only when you click on the search button (as explained in storybook)

### Expected behaviour
It should be called only when you click on the search button (as explained in storybook)

### Reproducible example
Test in sandbox : https://codesandbox.io/s/cool-fermi-3vt3v?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 76.1.5
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by ianforster-sage** [comment]
FE-4151
