### ISSUE TITLE
Editor links not rendering correct html when content is loaded from storage

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#4137]
### Current behaviour

The valid url strings are rendered as `span` instead of `a` tags
### Reproducible example

https://codesandbox.io/s/editor-and-note-with-json-9d8m1?file=/src/index.js:323-606
### Suggested solution(s)

Need to ensure the decorators are attached to the EditorState in `Note` component

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react    latest |

**Comment by edleeks87** [comment]
FE-4153

**Comment by sianford** [comment]
FE-4153
