### ISSUE TITLE
Accordion component does not resize when children re-render

### ISSUE THREAD

**Issue by nicktitchmarsh** [Sage/carbon#4143]
### Current behaviour
If the child of an accordion has its size changed, then the accordion does not resize to allow this to display correctly. This can be worked around by opening and closing the accordion. 

![Screenshot 2021-06-09 at 16 13 32](https://user-images.githubusercontent.com/69150954/121381615-c6c63a80-c93d-11eb-8de3-5a2db726c93d.png)

![Screenshot 2021-06-09 at 16 14 05](https://user-images.githubusercontent.com/69150954/121381631-ca59c180-c93d-11eb-8442-fbf14ac36557.png)

### Expected behaviour
The accordion should resize itself automatically based on its content

### Reproducible example
https://codesandbox.io/s/confident-aryabhata-2lfon?file=/src/index.js

Open the accordion -> change the shown items number -> close then open the accordion again

### Suggested solution(s)
Accordion should re-render when its children change size

**Comment by mkrds** [comment]
FE-4156
