### ISSUE TITLE
Padding Left doesn't work on FlatTableCell

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#4145]
### Current behaviour
Currently when padding property is setted for a `FlatTableCell`, the left value doesn't to be apply.
![image](https://user-images.githubusercontent.com/60605396/121387507-03e4f980-c94b-11eb-9cb4-63605cad6327.png)

### Expected behaviour
When padding property is setted for a `FlatTableCell`, the left value is displayed for top, right, bottom and left.

### Reproducible example
https://codesandbox.io/s/peaceful-roentgen-en47c?file=/src/index.js:1136-1258

### Suggested solution(s)
Lets override left padding property .

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 76.2.0
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.2
| Operating System | Windows

**Comment by nicktitchmarsh** [comment]
FE-4160 has been raised to address this
