### ISSUE TITLE
PodMananger is not working correct on screen resize

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4146]
### Current behaviour
When i use a PodManager to ensure same heights of all Pods and i resize the screen the height of the Pods is not re calculated and UI break.

Before screen resize:
![image](https://user-images.githubusercontent.com/84023810/121472506-94f6b780-c9c1-11eb-8a1d-963f46d24ad6.png)

After screen resize:
![image](https://user-images.githubusercontent.com/84023810/121472551-a17b1000-c9c1-11eb-815f-fdb40e0d63c3.png)

### Expected behaviour
On screen resize Pods height should be adjusted/re calculated and UI should not break.

### Reproducible example
https://codesandbox.io/s/currying-rain-fd4d3?file=/src/index.js

### Suggested solution(s)
I would create a new state on PodManager for screen size, and i would have a useEffect that will calculate screen size with debounce(important).  Then on the current useEffect i would add as a dependency the screen size values to be able trigger the correct Pod sizes when a change happen.

You could take a look here: https://www.pluralsight.com/guides/re-render-react-component-on-window-resize

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | ^76.1.2
| React            |  16.13.1
| Browser          | Chrome
| npm              | 6.14.11
| Operating System | Mac

**Comment by nicktitchmarsh** [comment]
FE-4157 has been raised to look at this

**Comment by sjohnson-sage** [comment]
This was addressed in https://github.com/Sage/carbon/releases/tag/v77.4.0 - closing this issue
