### ISSUE TITLE
Allow null children in ButtonToggleGroup

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4167]
### Current behaviour
I have a ButtonToggleGroup in which there are some conditionally rendered buttons. When the condition is false and the child is null, the ButtonToggleGroup is unable to handle it.

### Expected behaviour
If a ButtonToggleGroup has a null child, it is ignored.

### Reproducible example
https://codesandbox.io/s/magical-goldstine-kxvb3?file=/src/index.js

**Comment by mkrds** [comment]
FE-4178
