### ISSUE TITLE
RadioButton - the legend for the story with inline legend is not inline

### ISSUE THREAD

**Issue by ZhuoyuJin** [Sage/carbon#4171]
### Current behaviour
For the RadioButton component, the legend for the story "with inline legend" is not inline currently. 

![image](https://user-images.githubusercontent.com/72838192/122402616-8be38880-cf75-11eb-9eef-dc2e845696fa.png)

### Expected behavior
The legend should be inline for that story

### Reproducible example
1. Go to the master branch
2. click into RadioButton component
3. find with inline legend story, the legend is not inline.

**Comment by ZhuoyuJin** [comment]
FE-4182

**Comment by ianforster-sage** [comment]
This is a browser width issue, the legend is actually inline but wrapping to a second line.
