### ISSUE TITLE
Search: Type for onClick is invalid and does not see the target.value

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4185]
### Current behaviour

When you add the onClick function to the Search component in Typescript, the default type indicates that value does not exist on target.

### Expected behaviour

The type to understand that when you do event.target.value, value exists due to it being the value of the textbox in the search.

### Reproducible example

https://codesandbox.io/s/mystifying-clarke-fkb11

### Suggested solution(s)

To get the event of the Textbox and the Button maybe we need both of these types?

```typescript
onClick?: (ev: React.ChangeEvent<HTMLInputElement> & React.MouseEvent<HTMLButtonElement>) => void;
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v77.1.4
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by grabkowski** [comment]
FE-4195
