### ISSUE TITLE
Sticky column breaks on multi-level headers with various compositions

### ISSUE THREAD

**Issue by adamfriedland** [Sage/carbon#4187]
### Current behaviour
When applying sticky columns on multi-level headers with various compositions that clipping seems to appear on the first child element. Applies for both axis.

### Expected behaviour
No clipping

### Reproducible example
https://codesandbox.io/s/reverent-dust-9eqte

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 76.1.2
| carbon-factory   | N/A
| react-scripts    | N/A
| React            | 16.13.1
| Browser          | Opera, Edge, Chrome, Firefox
| npm              | 6.14.3
| Operating System | Windows

**Comment by sjohnson-sage** [comment]
Hi @adamfriedland - to get a sticky table header you need to use the `hasStickyHead` prop on the `FlatTable` component - it is not sticky by default. That solves the problem when scrolling up or down in your sandbox.

It looks like we do have a bug for the sticky row headers when scrolling horizontally however
