### ISSUE TITLE
sage_coin missing in IconType in the icon.d.ts

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4188]
### Current behaviour
When using Icon component type _sage_coin_ is not a valid prop value.

### Expected behaviour
_sage_coin_ is a valid prop value.

### Reproducible example
https://codesandbox.io/s/carbon-quickstart-xi5jc?file=/src/index.js

### Suggested solution(s)
Added _sage_coin_ to the IconType in the icon.d.ts

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 77.1.1

**Comment by grabkowski** [comment]
FE-4194
