### ISSUE TITLE
FlatTable - text within cell with rowSpan of 2 is positioned absolutely

### ISSUE THREAD

**Issue by sjohnson-sage** [Sage/carbon#4190]
### Current behaviour
The text within a cell with a `rowSpan` of `2` or more in a `FlatTable` is positioned absolutely, which doesn't look right when you scroll.

See the below sandbox, the top left header cell.

Also when scrolling up it seems to be offset with the other header rows: 

![image](https://user-images.githubusercontent.com/14963680/123109960-94373a00-d433-11eb-91c9-3dfe8de22e3b.png)

### Expected behaviour

The text should scroll with the cell, as in the other cells, and the row should be aligned correctly when scrolled.

### Reproducible example
https://codesandbox.io/s/reverent-sea-5zmxb?file=/src/index.js:902-909

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | Latest
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by grabkowski** [comment]
FE-4193
