### ISSUE TITLE
MenuItem does not support `onClick` and `href`

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#4205]
### Current behaviour
When rendering a `MenuItem` we want to add a `href` and a `onClick`. This allows users to right click open in new tab, but also use something like `react-router` for left click navigation.

At the moment, the `href` prop is discarded when you pass an `onClick` prop.
```jsx
<MenuItem
  href="/my/app/onClickHref"
  onClick={(e) => {
    e.preventDefault();
    navigate({ to: "/my/app/onClickHref" });
  }}>
  OnClick and Href
</MenuItem>
```
### Expected behaviour

`MenuItem` should render
```jsx
<a href="/my/app/onClickHref" onClick={(e) => {
            e.preventDefault();
            navigate({ to: "/my/app/onClickHref" });
}}>OnClick and Href</a>
```

### Reproducible example
https://codesandbox.io/s/menu-item-on-click-z44cz?file=/src/index.js

### Suggested solution(s)
@sjohnson-sage identified this line as the culprit
https://github.com/Sage/carbon/blob/37ca8b54d5d58281f4426a276335ed4f1f616b68/src/components/link/link.component.js#L94

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |76.1.3

**Comment by ianforster-sage** [comment]
FE-4197

**Comment by DlgSHi** [comment]
Fixed by this [PR](https://github.com/Sage/carbon/pull/4353)
