### ISSUE TITLE
Multiselect - The enter key is being propagated in all selects and that triggers form submit

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#4216]
### Current behaviour

On a dialog, we have a Multiselect component. When we select a option using the keyboard (ENTER), this causes the dialog to be validated instead of staying on the input.

### Expected behaviour

The dialog should only be saved if you type enter in an input, not by selecting a pill.

### Reproducible example

https://codesandbox.io/s/myformikform-forked-goic2?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |7.4.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by ianforster-sage** [comment]
FE-4206
