### ISSUE TITLE
Background color on textbox when auto-fill used on Chrome

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#4218]
### Current behaviour
With `required` props on `Textbox`, if you use the auto fill from the webbrowser (tested with Chrome), we have blue background color on the field filled.

### Expected behaviour
Do not have background color

### Reproducible example
https://codesandbox.io/s/nice-turing-k0u0t?file=/src/index.js
You can see on surname for exemple you will not have background color.
If you remove the `required`, you will not have background color.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |  77.6.1
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by maduv** [comment]
@ianforster-sage i updated the work in the sandbox

**Comment by ianforster-sage** [comment]
FE-4209

**Comment by ChrisBPetty** [comment]
From a UX point of view we'd prefer to remove the coloured background on the `required` fields as this will keep all autofilled fields consistent. I'll raise this with the DS team for sign-off
