### ISSUE TITLE
MultiSelect component should allow different pill colours

### ISSUE THREAD

**Issue by ChrisBPetty** [Sage/carbon#4236]
**Current behaviour**
The MultiSelect component currently only allows pills with a green stroke:
![image-2021-05-13-09-11-37-256](https://user-images.githubusercontent.com/77669052/125437954-a74a69ce-57ea-4f37-ac4d-d821e050a7e4.png)

**Expected behaviour**
The MultiSelect component should allow different pill colours.New designs require a variety of pill colours to be used within this component:
![image-2021-05-13-09-13-59-335](https://user-images.githubusercontent.com/77669052/125438503-a94f4efb-b2ca-4aa5-9eb3-a23f5908e150.png) 

![Screenshot 2021-07-13 at 11 39 20](https://user-images.githubusercontent.com/77669052/125438548-090c35df-b662-4499-bcea-046737f26000.png)

**Reproducible example**
n/a

**Suggested solution(s)**
Pill colour should be a configurable property for this component

**Additional context**
This additional functionality has been discussed with the design system team and has been approved by Ingrid Zillinger on 12/07/21

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by edleeks87** [comment]
FE-4226
