### ISSUE TITLE
[ Sidebar ] header doesn't respect the container width when rendered within a sidebar

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#4240]
### Current behaviour

The Header in sidebar expands more than the width of the sidebar.

![Screenshot 2021-07-14 at 15 13 46](https://user-images.githubusercontent.com/34001198/125628236-d6417c44-0040-4984-bf7e-f2da4d14a5a7.png)

### Expected behaviour

The Header in sidebar remains the same width of the sidebar.

### Reproducible example

https://codesandbox.io/s/white-sunset-vqypu?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 77.12.1 |
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | All |
| npm              |
| Operating System | MacOS |

**Comment by DipperTheDan** [comment]
FE-4232
