### ISSUE TITLE
Toast variant prop options don't work

### ISSUE THREAD

**Issue by samtjo** [Sage/carbon#4248]
### Current behaviour
A few of the options for the `Toast` `variant` prop do not work, `maintenance` for example (see sandbox). The docs also don't give the list of options for this prop: 

![image](https://user-images.githubusercontent.com/14963680/125934703-3b1452c3-5591-4962-98ae-f87b143b849f.png)

### Expected behaviour
The docs should show the correct list of options and they should all work.

### Reproducible example
https://codesandbox.io/s/prod-moon-26jzm?file=/src/index.js

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | Latest
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by sjohnson-sage** [comment]
Also, all of the stories in the Test folder under Toast on Storybook don't work anymore

**Comment by DipperTheDan** [comment]
FE-4234

**Comment by dawidzarzycki** [comment]
_The docs also don't give the list of options for this prop_
This part is covered by this PR https://github.com/Sage/carbon/pull/4134
