### ISSUE TITLE
Tabs - Grey inner line inside Tabs 

### ISSUE THREAD

**Issue by ZhuoyuJin** [Sage/carbon#4254]
### Current behaviour
Tabs have a light grey inner line inside (Tab 2 & Tab 3)

### Expected behaviour
Tabs should look exactly the same. 

### Reproducible example
1. Go to Tabs component with-validations-positioned-left
2. For Tab 2 and Tab 3, there are inner light grey line on the right hand side inside the Tabs

![image](https://user-images.githubusercontent.com/72838192/126200328-168a52e5-f3fd-4f05-8339-37c3763b2407.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | Latest
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

**Comment by DipperTheDan** [comment]
FE-4235

**Comment by harpalsingh** [comment]
Had a look at this issue, when you "select" the tab with the warning or info, there is no additional border on the right, but it appears when another tab is selected, so for consistency I would suggest that if an error/warning is present then we dont have the 2px border on a none selected tab to ensure no "visual blur" with a light grey border next to it.

This isn't impacted by error, as its thickness "hides" the additional pixel.
