### ISSUE TITLE
Card is setting type and tabIndex when non-interactive

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#4262]
### Current behaviour

The `Card` component sets the root element to `type="button"` and `tabIndex="0"` when the `interactive` prop is falsy. this means you can tab and focus the `Card` (but there is no visual feedback to say it is focused). 

### Expected behaviour

These props should only be set when `interactive` is true

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/design-system-card--default-story

### Suggested Solution

```
 <StyledCard
      data-component="card"
      cardWidth={cardWidth}
      interactive={interactive}
      draggable={draggable}
      spacing={spacing}
      type={interactive ? "button" : undefined}
      onClick={onClickHandler}
      tabIndex={interactive ? 0 : undefined}
      data-role={dataRole}
      {...rest}
    >
      {draggable && <Icon type="drag" />}
      {renderChildren()}
    </StyledCard>
```

### Carbon Version

77.13.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
FE-4243
