### ISSUE TITLE
Search - Extra margin when Search is wrapped in the Form component

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4274]
### Current behaviour

When we have a Search component into a form, we got a `margin-bottom: 24px` on the Textbox component.
https://codesandbox.io/s/strange-varahamihira-rrh8f

![image](https://user-images.githubusercontent.com/38658070/126992677-db3776b9-04e7-47bf-b77c-8ddef3ef51ab.png)

### Expected behaviour

We want to have the same design for the Search component with or without a Form. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/strange-varahamihira-rrh8f

### Carbon Version

79.0.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
FE-4245
