### ISSUE TITLE
DateInput Component - Improve user experience with nested Year and Month selection controls

### ISSUE THREAD

**Issue by kairynners** [Sage/carbon#4275]
### Desired behaviour

Even though users can manually enter a date using the keyboard, it would be great if they had more control when trying to move through the years and months. So the ability to select a year and/or month within the component.

### Current behaviour

Given that the user needs to specify a date in the past (either a previous year or several months back etc.).

To get to that specific value they need to cycle backwards month-by-month until they reach the required time frame, and then select the specific value. Similarly, if the user wants to specify a future date the same applies.

### Suggested Solution

Something similar to the jQuery UI Date Picker variant where the user is given a month and year input to give them greater control over the selection of a value.
[jQuery UI Date Picker](https://jqueryui.com/datepicker/#dropdown-month-year)

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
@harpalsingh what do you think?

**Comment by harpalsingh** [comment]
@jamime this would be a good enhancement for the component, but I think we need to do further work with the DLS team around date components first, so can raise this and consider the design for it.

**Comment by mmaciorowski-sage** [comment]
Hi @harpalsingh do we have some more information about designs?

**Comment by nicktitchmarsh** [comment]
FE-4075 is on our backlog but we need a design from DLS team

**Comment by edleeks87** [comment]
Closing as this functionality is implemented and #5248 has been raised to fix the bug associated with it
