### ISSUE TITLE
[ Form ] the sentence for errors and warnings is built not correctly

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#4282]
### Desired behaviour

IMHO it should be like:

![Zrzut ekranu 2021-07-30 o 10 36 37](https://user-images.githubusercontent.com/34001198/127629188-929c83fa-c636-4394-9a27-30a5d28a7853.png)

or 

![Zrzut ekranu 2021-07-30 o 10 40 25](https://user-images.githubusercontent.com/34001198/127629217-6be90c9c-d29f-4f57-890c-861c18a3836f.png)

### Current behaviour

We have a `Form` component with a `validation` story. The sentence of the `validation` is NOT correctly provided.

We have: 
<img width="527" alt="master" src="https://user-images.githubusercontent.com/34001198/127629144-eead5eb8-1fa0-497f-8fcd-9dcb9fa595cb.png">

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/design-system-form--with-both-errors-and-warnings-summary

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sjohnson-sage** [comment]
@harpalsingh - looks like this one is for you, would you mind having a look please?

**Comment by harpalsingh** [comment]
@sjohnson-sage I agree, the proposed visual update would be better 👍

**Comment by mmaciorowski-sage** [comment]
FE-4262
