### ISSUE TITLE
[ Pod ] issues with functionalities for onDelete/onUndo

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#4291]
### Current behaviour

We have few issues with newly added functionality to the `Pod` component.
1. Incorrect hover state for Pod (colour is changing) 

https://user-images.githubusercontent.com/34001198/128465356-72a41b04-69df-4546-b5e0-7792d9fd8fe2.mov

2. Incorrect focus state for Pod for onDelete button

https://user-images.githubusercontent.com/34001198/128465385-ed15bfbe-e444-4451-b41e-0afe19610663.mov

3. onDelete button is not shown when `displayEditButtonOnHover=true`

https://user-images.githubusercontent.com/34001198/128465404-a0ab6caa-2913-45e6-b6a4-d5c949e1d0fa.mov

### Expected behaviour

1. Pod colour on `hover` should not be changing
1. `onDelete` / `onUndo` should be focused with the all `Pod` as it is for `onEdit` button
1. when `displayEditButtonOnHover=true` and `onDelete=true`&&`onEdit=true` the `onDelete` and `onEdit` should be visible OR we need to add something like `displayOnDeleteButtonOnHover=true`

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/pod-test--default

### Carbon Version

77.13.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mmaciorowski-sage** [comment]
FE-4263

**Comment by nicktitchmarsh** [comment]
Rested, seems issue 1. and 2. have been corrected but issue 3 is still present. DS currently have no plans to update this component but it is being used in some products.
