### ISSUE TITLE
Behaviour for TileSelect when it becomes disabled

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#4292]
### Current behaviour

We had an issue raised previously (https://github.com/Sage/carbon/issues/4227) where the focus outline was remaining on the a `disabled` `TileSelect`. A fix was implemented where the `TileSelect` loses focus when it is `disabled`. https://codesandbox.io/s/optimistic-mendeleev-f4i19?file=/src/index.js

### Expected behaviour

Some implementation teams have requested that once the `disabled` prop is removed the `TileSelect`, be focused again/ not lose focus. The current behaviour seems to match how html inputs behave as default (https://codesandbox.io/s/peaceful-banach-y1e0w?file=/src/index.js), so I think it would be worth having a UX investigate so we can ensure we implement the correct behaviour. 

### CodeSandbox or Storybook URL

 https://codesandbox.io/s/optimistic-mendeleev-f4i19?file=/src/index.js

### Carbon Version

81.04

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@harpalsingh @tempertemper would you guys be able to look at this when you have a chance please?

**Comment by mmaciorowski-sage** [comment]
Hi @harpalsingh do we have some more information about designs?

**Comment by edleeks87** [comment]
Closed as current behaviour seems to match how html inputs should behave
