### ISSUE TITLE
Add character limit functionality into Textbox component

### ISSUE THREAD

**Issue by franip-sage** [Sage/carbon#4296]
### Desired behaviour

`Textarea` has the character limit functionality to restrict the text a user can enter in a field but, on the contrary, the `Textbox` component doesn't have it.

The desired behavior is `Textbox` should implement the character limit functionality the same way and with the same format `Textarea` does.

### Current behaviour

The `Textbox` component doesn't implement the character limit functionality so you have to do it programmatically if you want to achieve the same behavior as `Textarea`.

### Anything else we should know?

I have tried to use the `Textarea` as a `Textbox` passing the `rows={1}` prop but the result is not what expected. The `Textarea` renders with the same height as a `rows={2}` as can be checked in the following [CodeSandbox](https://codesandbox.io/s/bold-booth-xos5b?file=/src/index.js). And this solution is not optimal because although the component could be rendered as a one row the user could enter `\n` characters.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mmaciorowski-sage** [comment]
FE-4265

**Comment by samtjo** [comment]
This was added in Carbon in [v87.2.0](https://github.com/Sage/carbon/releases/tag/v87.2.0) - closing this issue
