### ISSUE TITLE
Sidebar ref is undefined

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4298]
### Current behaviour

When I have a Sidebar and pass a ref to it, the ref is not forwarded and is therefore always undefined.

### Expected behaviour

I want to use a ref on a sidebar component so I can detect when the user has scrolled to the bottom, allowing me to implement an infinite scroll.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/still-dew-ep8qc?file=/src/index.js

### Suggested Solution

Put a React.forwardRef on sidebar.component rather than declaring the ref within the component.

### Carbon Version

80.1.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mmaciorowski-sage** [comment]
FE-4266

**Comment by edleeks87** [comment]
https://github.com/Sage/carbon/pull/4309#issuecomment-900092738
