### ISSUE TITLE
Inline Input labels do not align with other inputs on a form

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4300]
### Current behaviour

InlineInputs labels are always inline and the same width of the text within them, this does not match with the other fields you can put on a form which have properties to configure where to display them, how much width to give them, or when to break between displaying them inline or above the field.
The result is a strange looking form where the InlineInputs are not aligned with anything else, including each other.
![image](https://user-images.githubusercontent.com/16744242/128880052-f354c991-c3c3-42c1-a692-67b2b523d37e.png)

### Expected behaviour

When I do not provide the labelInline property to an InlineInput component, the inline inputs span the full width of the form with the label displayed above them. If I do provide the labelInline property, then I can use the same labelWidth and input width properties so that it aligns with the other fields on the form.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/wonderful-moore-f1nc4?file=/src/index.js

### Carbon Version

80.1.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-4279
