### ISSUE TITLE
Sub-Menu Events

### ISSUE THREAD

**Issue by jlongridge** [Sage/carbon#4303]
### Desired behaviour

I would like to be able to trigger custom code to run when a sub-menu opens/closes.

### Current behaviour

There is currently no way to trigger code to run when a sub-menu opens/closes.

### Suggested Solution

I think a callback prop that’s triggered when the submenu opens/closes would be a good idea.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sjohnson-sage** [comment]
Seems like a reasonable request to me, added to our backlog

FE-4269
