### ISSUE TITLE
DateInput Picker does not allow to navigate between months

### ISSUE THREAD

**Issue by vejalingo** [Sage/carbon#4307]
### Current behaviour

Unable to move between months using the DateInput's arrows

<img width="437" alt="Screenshot 2021-08-15 at 22 11 45" src="https://user-images.githubusercontent.com/8371355/129491394-902e2e12-b182-4c50-98b5-23e7ccff2d8a.png">

See loom 👇🏾  
https://www.loom.com/share/fd66ea73983748cd86d11286379e2e46

### Expected behaviour

Should be able to navigate between months

### CodeSandbox or Storybook URL

https://codesandbox.io/s/stupefied-pine-nsmpq

### Carbon Version

81.0.5

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-4274
