### ISSUE TITLE
TypeScript error for Pod due to missing height prop in components TypeScript interface

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#4312]
### Current behaviour

Unable to use the height prop for the Pod component due to the following error
![image](https://user-images.githubusercontent.com/84381483/129690275-82c958e8-ea17-47e4-ad4b-7d7a62b3c728.png)

The [commit](https://github.com/Sage/carbon/commit/2ed25352d14f2d4cc4c972b6bde49ee19f2be007) to add the height prop to Pod in v77.4.0 does not have the prop added to the PodProps interface. This in not the latest version as well.

### Expected behaviour

height prop is added to the PodProps interface allowing the use of the prop without a TypeScript error.

### CodeSandbox or Storybook URL

N/A

### Carbon Version

77.14.1

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-4278
