### ISSUE TITLE
Textbox - Extra white block with props required on Textbox

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4319]
### Current behaviour

We have an extra white block on the textbox when we have the props `required`.
![image](https://user-images.githubusercontent.com/2328042/130220321-c5175969-ca15-4a7a-b441-b317f9794fbc.png)

### Expected behaviour

We expect to have the same design with `required` props than witout this props.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/gh-4319-op29g

### Carbon Version

81.2.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows, MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
Confirmed on 81.2.1 on Chrome, MacOS. I updated the ticket to include the `GlobalStyle`.
