### ISSUE TITLE
locales/en-GB is missing a typescript file

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4321]
### Current behaviour

When you import this file into a project using Typescript an error is generated 
`"Could not find a declaration file for module 'carbon-react/lib/locales/en-gb'."`

Manual work around at the moment is to declare the module in a top level file
`declare module "carbon-react/lib/locales/en-gb";`

### Expected behaviour

To not need to manually declare this in our own app.

### CodeSandbox or Storybook URL

N/A

### Carbon Version

81.2.1

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
FE-4291
