### ISSUE TITLE
Dropdown selection issue with Guid as Id - InternetExplorer

### ISSUE THREAD

**Issue by frbar** [Sage/carbon#433]
If Id of option in dropdown is a guid with only numbers in first group, then option cannot be selected.

![dropdown-guid-internetexplorer](https://cloud.githubusercontent.com/assets/16399900/14714347/f12c9438-07e4-11e6-9fad-dd150793ae9c.gif)

This issue has been reproduced in carbon demo (master), using Internet Explorer 11.

`dropdown-demo.js`

```
  get demo() {
    let opts = Immutable.fromJS([
      { id: '60106667-c953-4077-82e5-bfc868496211', name: "Option 60106667" },
      { id: '4340a408-f9f6-4ccb-85f4-0fdf885f4011', name: "Option 4340a408" },
      { id: '11111100-bbd8-42c9-a11c-d628af8a930d', name: "Option 11111100" },
      { id: 'ac287954-d207-4682-a9d4-ee3bbdd29b6d', name: "Option ac287954" }
    ]);

    return (
      <Dropdown options={ opts } { ...FormInputHelper.demoProps(this, this.action) } />
    );
  }
```

With this set of data, only options 2 and 4 can be selected. Options 1 and 3 have only numbers in first of group of Id.

**Comment by edleeks87** [comment]
Dropdown has been deprecated in favour of Select, we believe this issue is now fixed so we are closing this
