### ISSUE TITLE
Sidebar component missing children in interface

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4332]
### Current behaviour

When using the SideBar component in a typescript project, there is an error stating
`Property 'children' does not exist on type 'IntrinsicAttributes & SidebarProps & RefAttributes<HTMLDivElement>'`

### Expected behaviour

The Sidebar component should have a type of Children.
File to be updated: https://github.com/Sage/carbon/blob/master/src/components/sidebar/sidebar.d.ts#L6-L21

An extra nicety would be for position and size to be updated with the actual options that are allowed vs a generic string.

### CodeSandbox or Storybook URL

N/A

### Suggested Solution

Interface to include
```
import { ReactElement } from "react";
{
  ...
  children: ReactElement,
  position?: "left" | "right,
  size: "extra-small" | "small" | "medium-small" | "medium" | "medium-large" | "large" | "extra-large"
  ...
}
```

### Carbon Version

81.2.1

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4301 has been raised to address this
