### ISSUE TITLE
VoiceOver for Select component reads it's textbox instead of listbox popup

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4339]
### Current behaviour

When focus on Select component VoiceOver reads it's textbox component. VoiceOver also reads only name of option.

### Expected behaviour

VoiceOver should read that it's listbox popup and should add how many options in the select are e.g Option First (1 of 4).

### CodeSandbox or Storybook URL

https://codesandbox.io/s/interesting-thompson-iuhjq

### Carbon Version

82.0.0

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4300 has been raised to address this
