### ISSUE TITLE
RadioButton - make `fieldHelp`prop visible for screen readers

### ISSUE THREAD

**Issue by alzieba** [Sage/carbon#4341]
### Desired behaviour

We need screen readers to read `fieldHelp` text for `RadioButton` component

### Current behaviour

Screen reader only reads `label` text

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Currently we have FE-3635 looking at addressing the readability of validation messages which use the same tooltip mechanism. I believe DS team is looking to phase out usage of tooltip in order to enhance accessibility. @harpalsingh can you confirm?

**Comment by nicktitchmarsh** [comment]
We have FE-4324 raised to look at this and #4363 also seems to be the same issue.

**Comment by nicktitchmarsh** [comment]
@alzieba are you ok for me to close this issue so we only track one?

**Comment by alzieba** [comment]
totally ok 👍  

closing this issue as it's duplicated - https://github.com/Sage/carbon/issues/4363
