### ISSUE TITLE
Pager: Page-Size not updated after prop "pageSize" changed

### ISSUE THREAD

**Issue by gandalf92** [Sage/carbon#4344]
### Current behaviour

Page-Size inside page-size-selection not updated after prop "pageSize" has been changed.

### Expected behaviour

Page-Size inside page-size-selection should also change, when property "pageSize" changes.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/beautiful-oskar-yxjes?file=/src/index.js

### Suggested Solution

there should be an useEffect inside of the pager which should set the value of the current pageSoze, when the property changes.

### Carbon Version

77.13.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4299 has been raised for this
