### ISSUE TITLE
Padding Left pl property  is not working for FlatTableCell in SubRows

### ISSUE THREAD

**Issue by ravi-ankam** [Sage/carbon#4348]
### Desired behaviour

Padding Left (pl) property is not working for FlatTableCell  when used in SubRows of the FlatTable component.
But the pl (padding-left) property works fine for FlatTableCell when used in normal Rows in a FlatTable component.
Here is the CodeSandbox example to replicate the issue.
https://codesandbox.io/s/flattable-subrows-padding-example-4i6ni

### Current behaviour

Add padding-left with pl property  to the FlatTableCell when used in SubRows of FlatTable Component
Padding Left (pl) property is not working for FlatTableCell  when used in SubRows of the FlatTable component.
But the pl (padding-left) property works fine for FlatTableCell when used in normal Rows in a FlatTable component.
Here is the CodeSandbox example to replicate the issue.
https://codesandbox.io/s/flattable-subrows-padding-example-4i6ni

### CodeSandbox or Storybook URL

https://codesandbox.io/s/flattable-subrows-padding-example-4i6ni

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@ravi-ankam, this appears to be affecting the first cell in a subRow only. In your example the value of {20} is invalid. It only expects a multiplier of {10} (this adds multiples of 8px) or you can supply a css string value. I believe the subRows set the first cell padding in order to have the text line up with the icon on the parent row. Is there a design showing the need for a different pattern?

**Comment by ravi-ankam** [comment]
@nicktitchmarsh  yes, you are right  padding is not working for the first cell in the row. I was trying different values and used {20}.

**Comment by ravi-ankam** [comment]
@nicktitchmarsh ,  I will speak to the  UX/XD design team to get the design for this scenario.

**Comment by ravi-ankam** [comment]
@nicktitchmarsh here is the design we looking for the padding pl  in subrows
https://www.figma.com/proto/F6YWIuEgfy8hxaPlk6Lyja/Reporting-Prototype-(2021)?node-id=4259%3A8316&scaling=min-zoom&page-id=4057%3A4&starting-point-node-id=4427%3A114814

![image](https://user-images.githubusercontent.com/40062261/131656579-606de213-be30-435a-b5fb-a2d9ee369bf1.png)

**Comment by nicktitchmarsh** [comment]
Have confirmed the designs with @ravi-ankam, we need to add the ability to adjust the padding on the first cell as well as others. Supplying the prop should override the default padding

**Comment by nicktitchmarsh** [comment]
FE-4306 has been raised to address this issue
