### ISSUE TITLE
Select options only saying parts of an options text on Voiceover (firefox only)

### ISSUE THREAD

**Issue by JohnOxleySage** [Sage/carbon#4356]
### Current behaviour

Currently if we run Mac Catalina Voiceover on Firefox against a Select component that has options with multiple words only parts of the text are read. E.g; for option `Amber some` only `Amber` was read. 

### Expected behaviour

It is expected that the full option text would be read. E.g. for option `Amber some` expect `Amber some` to be read.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/cool-goodall-cv9m0

### Carbon Version

76.1.3

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4321
