### ISSUE TITLE
Message prop 'title' doesn't accept Typography component as valid

### ISSUE THREAD

**Issue by SageSebNegahban** [Sage/carbon#4361]
### Current behaviour

When creating a Message component and using a Typography component in the title prop, an error appears in the console saying that the prop type is invalid.
The typography component is still displayed as the title and it functions correctly, there's just an unexpected console error.

### Expected behaviour

The console error should not be thrown.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sad-faraday-5fkv4?file=/src/index.js

### Suggested Solution

Change the permitted prop type.

### Carbon Version

79.1.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4320
