### ISSUE TITLE
MultiActionButton and SplitButton VoiceOver reads only option and not a parent

### ISSUE THREAD

**Issue by DipperTheDan** [Sage/carbon#4372]
### Current behaviour

"Exporting" could not be read by VoiceOver as it's not focused on parent.

### Expected behaviour

VoiceOver is able to read a parent and not only the option

### CodeSandbox or Storybook URL

https://codesandbox.io/s/loading-spinner-for-export-forked-xjxml?file=/src/index.js

### Carbon Version

77.14.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
This issue was originally logged with #4352 but for ease of managing the work, I've separated them in to their own tickets.

**Comment by DipperTheDan** [comment]
FE-4323

**Comment by nicktitchmarsh** [comment]
@LiliyaGi  we have tested the VoiceOver for MultiActionButton, this works if you set focus on the button again when the "exporting" text has been rendered. We will consult with UX to see if this is the desired behaviour for this pattern.
