### ISSUE TITLE
FlatTable : error with less than 2 FlatTableHeader

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4378]
### Current behaviour

If i create a FlatTable with a header with 2 rows and 1 column, it crashes.

### Expected behaviour

The FlatTable is displayed correctly no matter the number of rows/columns in the header

### CodeSandbox or Storybook URL

https://codesandbox.io/s/flattable-error-header-do3sf

### Carbon Version

84.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by gusch** [comment]
If there is only 1 row in the header or 2 or more columns, it works fine

**Comment by jamime** [comment]
FE-4326
