### ISSUE TITLE
FilterableSelect-onchange event fires when navigating through dropdown list using keyboard

### ISSUE THREAD

**Issue by ravi-ankam** [Sage/carbon#4393]
### Current behaviour

Using FilterableSelect dropdown component and noticed that when navigating through the dropdown list items using the keyboard up/down arrows , onChange event is fired for each item I navigated through the list  before I select the item.
Works fine when using the mouse to navigate/scroll  through the dropdown list items. But the onChange fires for every dropdown item I navigated through using the key board. Its because the dropdown input text is changed when using the keyboard up/down arrows while navigating through the dropdown list items.

### Expected behaviour

Up/Down arrow should only use for navigating the dropdown option. Enter/ Space key should be the one to select the  drop down option.
Using FilterableSelect dropdown component and noticed that when navigating through the dropdown list items using the keyboard up/down arrows , onChange event is fired for each item I navigated through the list  before I select the item.
Works fine when using the mouse to navigate/scroll  through the dropdown list items. But the onChange fires for every dropdown item I navigated through using the key board. Its because the dropdown input text is changed when using the keyboard up/down arrows while navigating through the dropdown list items.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sidedrawer-filterableselect-selectionfunctionality-h9zd3

### Suggested Solution

Up/Down arrow should only use for navigating the dropdown option. Enter/ Space key should be the one to select the  drop down option.

### Carbon Version

84.4.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by grabkowski** [comment]
FE-4250
