### ISSUE TITLE
Menu in NavBar component create Axe fails - Certain ARIA roles must contain particular children

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4394]
### Current behaviour

Using `Menu` without `submenu` in a `NavBar` create Axe fails.
https://carbon.sage.com/?path=/story/design-system-navigation-bar--with-custom-spacing
![image](https://user-images.githubusercontent.com/38658070/133226172-0d453d32-a7e4-414a-824a-992dd4a90b12.png)

### Expected behaviour

Add a good role to the child to avoid this Axe fails.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/design-system-navigation-bar--with-custom-spacing

### Carbon Version

86.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
I have raised FE-4327 to look at this
