### ISSUE TITLE
Scrollbar & multiple Modals

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4419]
### Current behaviour

In this sandbox, when i submit the form, i open another dialog to wait for the response of the request (simulated with the timeout). Then i close both the waiting dialog and the form. 
As you can see, when a dialog is open, the scrollbar is hidden.

if I close the form THEN the wait, the scroll remains hidden.
If I close the wait THEN the form (last opened, first closed), the scroll is shown.

### Expected behaviour

When all the modals are closed (no matter the order), the scroll bar should be shown again.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/eager-andras-2u4cw?file=/src/index.js 

### Carbon Version

87.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
This is because when the second modal is opened the html element will already have an overflow, so when it is restored, it is restored back to `overflow:hidden`.
https://github.com/Sage/carbon/blob/master/src/components/modal/modal.component.js#L28-L46

**Comment by edleeks87** [comment]
FE-4361
