### ISSUE TITLE
onClick event prop is never triggered on DateInput

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#4421]
### Current behaviour

When the user clicks on the date input field, it the onClick prop is never called. The onClick prop is part of the propTypes of the DateInput property types.

It works for the generic textbox that the DateInput extends. See sandbox example.

### Expected behaviour

The onClick event is triggered when the user clicks on a date input component

### CodeSandbox or Storybook URL

https://codesandbox.io/s/exciting-mountain-knx4j

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

The issue can be reproduced with any of the last 10 versions and on any browser and OS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4362
