### ISSUE TITLE
[radio-button] (accessibility) - the label help tooltip doesn't open when the input is focused

### ISSUE THREAD

**Issue by mmaciorowski-sage** [Sage/carbon#4426]
### Current behaviour

The label help tooltip doesn't open when the input is focused.

https://user-images.githubusercontent.com/77274590/134679390-d69d8b95-1002-4276-b957-f6b6111d46d5.mov

### Expected behaviour

The label help radio button has the same behaviour like for validations (warning, error, info).

Please test in the storybook, because in the code sandbox the tooltip doesn't appear at all.
```
      <RadioButton
        id="legend-and-labels-radio-1"
        value="radio1"
        label="Radio Option 1"
        labelHelp="test"
      />
      <RadioButton
        id="legend-and-labels-radio-2"
        value="radio2"
        label="Radio Option 2"
        warning="test"
      />
      <RadioButton
        id="legend-and-labels-radio-3"
        value="radio3"
        label="Radio Option 3"
        error="test"
      />
      <RadioButton
        id="legend-and-labels-radio-4"
        value="radio4"
        label="Radio Option 4"
        info="test"
      />
    </RadioButtonGroup>
```

### CodeSandbox or Storybook URL

https://codesandbox.io/s/friendly-paper-dwrsi?file=/src/index.js

### Carbon Version

91.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
@harpalsingh Could you please say if the tooltip should be visible for the `labelHelp` prop in this scenario?

**Comment by samtjo** [comment]
This should behave the same as the validation so we will raise a ticket to fix this

FE-4442
