### ISSUE TITLE
[ AnchrorNavigation ] the component is not rendered in storybook

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#4465]
### Current behaviour

The `Anchor Nav` component is not rendered on master in storybook

### Expected behaviour

It should be rendered as other components

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/anchor-navigation--page

### Carbon Version

92.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DlgSHi** [comment]
FE-4387

**Comment by DipperTheDan** [comment]
This issue was addressed in PR #4466.
