### ISSUE TITLE
Multi Select "Cannot read property 'length' of undefined" error message

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#4482]
### Current behaviour

Getting an error while selecting a theme.

Steps to Reproduce:

1) Go to https://carbon.sage.com/?path=/story/welcome--welcome-page
2) After that go to Select ---> Multi-select ---> Default 
3) Then click to canvas.
4) After that click to the text-box and select values.
5) After selecting the values try to change the theme you will see the error.

<img width="1265" alt="Screenshot 2021-10-11 at 13 32 32" src="https://user-images.githubusercontent.com/88449494/136797287-9b2a2a2b-ae81-4abf-a4bc-db90ec940e93.png">

### Expected behaviour

Any error should not come while changing the theme.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select-multiselect--default-story&globals=locale:pl-PL

### JIRA Ticket (Sage Only) 

FE-4396

### Carbon Version

93.0.2

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
Ticket for this issue is FE-4396. Defect has been raised against FE-4337 as this bug was discovered during that test session.
