### ISSUE TITLE
Add padding props to Sidebar

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4494]
### Desired behaviour

I would like to customise the padding within a sidebar component so that the content within can span across the entire width of the sidebar.

### Current behaviour

It is not possible to change the padding within the sidebar without writing custom CSS.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/floral-pine-hd3zt?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
@harpalsingh - What is your opinion on adding the padding props to Sidebar?

**Comment by clairedenning** [comment]
From the DS team: I would expect the header and the footer to have set padding, but the central area could in theory be used for any content. For that reason, it would be good if the padding in the central area padding could be adapted according to requirements. In the case when there are no specific requirements, the default padding should be used.

**Comment by DlgSHi** [comment]
FE-4458

**Comment by nicktitchmarsh** [comment]
@clairedenning please could you make sure that this change is reflected in the DS docs and we will schedule in the change.

**Comment by clairedenning** [comment]
Hi, as our team hasn't yet "migrated" the component (ie analysed, fixed, enhanced, documented, etc...) it may be a while before the documentation is added. But I will update the backlog with this request.

**Comment by clairedenning** [comment]
I believe we have a new ticket for this in an upcoming sprint https://jira.sage.com/browse/DSY-2267, is that right @ingridzillinger ?
