### ISSUE TITLE
Tab axe warning when rendering a link

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#4517]
### Current behaviour

When an `href` string is passed to a `Tab` it renders an anchor element which causes an axe warning about [nested interactive controls](https://dequeuniversity.com/rules/axe/4.3/nested-interactive?application=axeAPI)

### Expected behaviour

No axe warning please 

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/tabs--with-link-as-a-tab

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4441
