### ISSUE TITLE
Multi Action Button can't close with Esc key

### ISSUE THREAD

**Issue by szeyingyau** [Sage/carbon#4522]
### Current behaviour

The `MultiActionButton` cannot close when the Esc key is used.

### Expected behaviour

The `MultiActionButton` should be able to close when the Esc key is used.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/autumn-wave-wg9gc?file=/src/index.js

### Carbon Version

95.1.0

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
@tempertemper would you mind having a look at this please? 

If you tab onto the multi-action-button it will open, but there's no way to close it with the keyboard, other than tabbing away from it. Should we be able to press escape (or something else) to close the dropdown buttons? 

Thanks

**Comment by tempertemper** [comment]
<kbd>esc</kbd> should close the pop up and return focus to the trigger. Problem is, focusing the trigger automatically shows the dropdown menu…

I'm not sure what the right direction to take to fix this is, but I'm pretty sure it's design-led, and probably linked to the hover/focus triggering the dropdown menu, rather than behaving like a default button, which would take focus and provide a hover affordance, but would require a click/tap/enter/space to show the drop down. Maybe @harpalsingh can advise on the best course of action here; maybe a multi-action button task force.

**Comment by nicktitchmarsh** [comment]
Please can Design System team review Martin's comments here and advise on the behaviour for Multi Action Buttons

**Comment by clairedenning** [comment]
I think @andy varley would be the best person to answer this. Can't tag him here, I'll message him.

**Comment by tempertemper** [comment]
I'm catching up with him on Friday morning so I'd be happy to fill him in 👍

**Comment by tempertemper** [comment]
Tagging @v99rly

**Comment by samtjo** [comment]
Hi @tempertemper - did Andy and yourself get anywhere with this?

**Comment by tempertemper** [comment]
Thanks for the nudge, @samtjo. I caught up with him, but there's a good chunk of work in re-speccing the component, and I think the DS team have been struggling to prioritise non-brand-related work recently. I'll catch up with him on it when he returns from his holiday next week 👍

**Comment by nicktitchmarsh** [comment]
FE-5188

**Comment by tempertemper** [comment]
Might be worth coming back to the Esc key functionality, since there could be the question of re-opening the menu, which would mean tabbing off then back onto the multi-action button. I'll address this with @v99rly again when I catch up with him on Friday.

**Comment by v99rly** [comment]
Had a chat with @tempertemper and checked what should be the correct behaviour. Will look into the with the design system team week commencing the 6th June.
