### ISSUE TITLE
Sticky navbar in Dialog doesn't stick to the top

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#4526]
### Current behaviour

When we use navbar component in a dialog component and stickyPosition="top" used, navbar is hidden when scroll down in dialog.

### Expected behaviour

When we scroll in the dialog, navbar should be on the top, always visible.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/recursing-nightingale-39hsp?file=/src/index.js

### Carbon Version

94.4.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4439

**Comment by nicktitchmarsh** [comment]
DS input required to identify the required pattern for this, or if we recommend that a one off component extension is written for this case. We also thought the position of the nav should be full-width and flush with the top of the dialog to mirror sticky footers.

**Comment by clairedenning** [comment]
From DS team: This is a product-specific requirement, and as far as we are aware, hasn't been requested by any other product. We would recommend that you create prototypes and test with users to find the best solution. Perhaps it's worth exploring a different user flow that doesn't require the use of tabs at all. But if you think tabs are the best way, be sure to make it clear what elements they encompass. In the example shared, the tabs are so close to the top input, that they seem to be disconnected from all the other inputs.

**Comment by nicktitchmarsh** [comment]
Hi @maduv you can use the `title` prop in `Dialog` which accepts a node to allow your menu to remain sticky. https://codesandbox.io/s/sleepy-feather-t1o03?file=/src/index.js

**Comment by samtjo** [comment]
@nicktitchmarsh can we close this as it looks like it won't be added to the Design System?
