### ISSUE TITLE
Focus default on "cross" icon inside a Toast message

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#4532]
### Desired behaviour

To have focus default on "cross" icon inside a Toast message to be align with accessibility criterias.

### Current behaviour

Get the focus only by clicking first on the toast, then by pressing "tab"  key on keyboard.

### Suggested Solution

Display the Toast message  with the focus on the cross icon by default.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/vibrant-hertz-y45lm?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DlgSHi** [comment]
@harpalsingh can you confirm we need this as the `default` option?

**Comment by sianford** [comment]
FE-4462
