### ISSUE TITLE
Accessibility props for DialogFullScreen component

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#4537]
### Desired behaviour

Allow `role` and `aria-labelledby` props to be passed to the DialogFullScreenComponent:
```
<body>
  <nav>Nav content goes here</nav>
    <DialogFullScreen data-role="dialog-full-screen" role="main" aria-labelledby="heading-1">
      <h1 id="heading-1">Dialog Heading</h1>
      <p>Dialog paragraph</p>
    </DialogFullScreen>
</body>
```
Expected be rendered as follows in the browser:
```
<body>
  <nav>Nav content goes here</nav>
  <span portal-id="abcd"/>
  <div portal-id="abcd">
    <div data-role="dialog-full-screen" role="main" aria-labelledby="heading-1">
      <h1 id="heading-1">Dialog Heading</h1>
      <p>Dialog paragraph</p>
  </div>
  </div>
</body>
```

### Current behaviour

When using the DialogFullScreen component which uses React Portals, this renders the dialog outside the normal DOM hierarchy where the below code:
```
<body>
  <nav>Nav content goes here</nav>
  <main>
    <DialogFullScreen data-role="dialog-full-screen">
      <h1>Dialog Heading</h1>
      <p>Dialog paragraph</p>
    </DialogFullScreen>
  </main>
</body>
```
Can be viewed as follows in the browser:
```
<body>
  <nav>Nav content goes here</nav>
  <main>
    <span portal-id="abcd"/>
  </main>
  <div portal-id="abcd">. <---- div is outside main landmark
    <div data-role="dialog-full-screen">
      <h1>Dialog Heading</h1>
      <p>Dialog paragraph</p>
  </div>
  </div>
</body>
```

### Suggested Solution

Allow `role` and `aria-labelledby` props to be passed to the same div which has `data-component` and `data-role` prop values in the DialogFullScreen component. This enables all children elements within the DialogFullScreen component to be enclosed within a landmark for accessibility.

See accessibility rule link for more information: https://dequeuniversity.com/rules/axe/4.3/region?application=AxeChrome

### CodeSandbox or Storybook URL

N/A

### Anything else we should know?

N/A

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DlgSHi** [comment]
@tempertemper, can you check this please?

**Comment by tempertemper** [comment]
Is it possible to be less flexible on this? In other words, can assume every modal has:

- has a heading
- is a `<div role="region">` or `<section>` (which adds the `region` role implicitly)

If so, it would be great if we could automatically:

- ensure the modal has a heading
- add the `<section>` or `<div role="region">` to the component
- reference the heading in an `aria-labelledby` attribute on the `<section>` or `<div role="region">`

I'm looking at this from an ideal perspective, but there may be a use case for a modal without a heading and that might need a role other than `region` that I'm missing.

**Comment by sianford** [comment]
FE-4469
