### ISSUE TITLE
Height of form with sticky footer is too big

### ISSUE THREAD

**Issue by stripeyjumper** [Sage/carbon#4538]
### Current behaviour

The new footer behaviour makes the form a nested scrollable panel.  The height of the panel has not been calculated correctly when a heading is included before the form, so the outer window also requires scrolling in order to see the form footer.

![image](https://user-images.githubusercontent.com/12202813/140712273-ce33c7e8-8799-452d-acd8-081c178590b4.png)

### Expected behaviour

The panel containing the form should be sized so it is fully visible on the screen.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/modest-babbage-gr6f9?file=/src/index.js

### Carbon Version

94.1.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DlgSHi** [comment]
Hi, thank you for raising an issue but we think you might need to add just a `height={value}-{height of sticky_footer}-{height of Header}` and it should fix your issue. Can you confirm is this fixes your issue @stripeyjumper ?

**Comment by sianford** [comment]
Messaged @stripeyjumper requesting a review of Igor's suggested fix above.

**Comment by stripeyjumper** [comment]
Hi @DlgSHi, thanks for the suggestion.  Using the height below works:
```html
<Form stickyFooter height="calc(100vh - 260px)"></Form>
```
If this is the recommended usage, could it be added to the docs and storybook?  It's not very easy to discover, and it's the only way to make this component work as intended.

**Comment by nicktitchmarsh** [comment]
Adding Design System review to see if they would like us to add this as a standard pattern and adjust the component accordingly

**Comment by samtjo** [comment]
We should dynamically calculate the height of the form using refs to get the height of the header/footer - to cater for them changing size and users zooming in etc

FE-4491
