### ISSUE TITLE
Icon-only buttons with tooltip are focused twice

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#4542]
### Current behaviour

When I use the keyboard to navigate within the application, the icon-only buttons that a tooltip message will get focus twice: once the button and once the icon within the button.

### Expected behaviour

When I use the keyboard to navigate within the application, the icon-only buttons that have a tooltip message should only get focus on the button, but not on the icon. I would also expect the tooltip to display when the icon-only gets focused.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/wonderful-fog-4f2fq

### Suggested Solution

The logic in `src/components/icon/icon.component.js:75` seems to cause this issue. It was added a month ago, we just upgraded from version 85 and the problem doesn't exist in that version. I think the icon component should receive a prop from the parent button component, which checks only enables the tabindex on the icon component if the button has an `iconType` but doesn't have any `children`

### Carbon Version

96.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

The issue is not browser or OS specific.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### Screenshots
<img width="690" alt="Screenshot 2021-11-09 at 08 42 34" src="https://user-images.githubusercontent.com/4557844/140883092-9832dc24-e0d4-4080-a674-538209c4a539.png">

<img width="683" alt="Screenshot 2021-11-09 at 08 42 39" src="https://user-images.githubusercontent.com/4557844/140883065-44af0887-d07d-4dcd-b2ad-12d3258b0a22.png">

**Comment by DlgSHi** [comment]
FE-4457
