### ISSUE TITLE
ResizeObserver errors being reported

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4547]
### Current behaviour

We are seeing the following 2 errors being reported in our application:
1. ResizeObserver loop limit exceeded
2. ResizeObserver loop completed with undelivered notifications.

This is happening in two different applications we have using Carbon.

### Expected behaviour

These errors to not be generated

### CodeSandbox or Storybook URL

NA

### JIRA Ticket (Sage Only)

SBS-23620

### Carbon Version

91.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Anything else we should know?

We are not sure what is causing this to happen, the pages in our applications where we are seeing this happen have different functionality.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-4468
