### ISSUE TITLE
Bad behaviour on TextEditor with some sequences of character

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#4550]
### Current behaviour

A part of a text is underline when you type ":" following by a number exemple:

-  **:1rrr** set underline to 1rrr.

### Expected behaviour

You should not interprete sequences of character to introduce some style in the text. Exemple:

- **:1rrr** should not introduice underline to 1rrr

### CodeSandbox or Storybook URL

https://codesandbox.io/s/suspicious-hypatia-bk2ug

### Carbon Version

95.1.1 and the lastest on storybook

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-4467
