### ISSUE TITLE
cloneElement of FlatTableRow children means props aren't passed when they are wrapped in custom component

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#4561]
### Desired behaviour

 Be able to wrap flat-table-cell component where props by carbon are injected in a transparent manner. 

### Current behaviour

As the flat-table-row is using `React.cloneElement` method the direct children have to be the flat-table-cell, see [here](https://github.com/Sage/carbon/blob/5c4a6e8bcf3fd279b946e46d8fc109100ce5cea2/src/components/flat-table/flat-table-row/flat-table-row.component.js#L163). This stops consumers to wrap the carbon flat-table-cell component or instead the props have to be spread across flat-table-row children.

### Suggested Solution

As @jamime suggested, these props could be injected via context provider or render props.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/purple-bird-lyr5p?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-4465

**Comment by nicktitchmarsh** [comment]
@MarcServat Having discussed this we have a requirement to control the ordering of the children closely. It would be more work to allow these props to be passed via context and then ensure ordering without the cloneElement calls that it gives as a benefit. We will add some explanation in documentation as to why we do this which you can point to in your PR as justification for spreading the props.

**Comment by MarcServat** [comment]
@nicktitchmarsh makes sense. Would you also consider exporting a type for the props injected? This would help up to give visibility to the spreading props. In any case, thanks for your help.

**Comment by mkrds** [comment]
@MarcServat Could you please give me an example that shows why you need to wrap the `FlatTableCell` ?

**Comment by MarcServat** [comment]
@mkrds  The `FlatTableCell` and the `FlatTableRow` are wrapped to avoid increasing the nested levels where the `FlatTable` component lives.
