### ISSUE TITLE
`Page` component cannot be currently used by consumers

### ISSUE THREAD

**Issue by adamfriedland** [Sage/carbon#4562]
### Current behaviour

`Page` component cannot be currently imported by consumers as it's not exposed through the [Pages](https://github.com/Sage/carbon/blob/master/src/components/pages/pages.d.ts) module's [interface](https://github.com/Sage/carbon/blob/master/src/components/pages/index.d.ts).

### Expected behaviour

`Page` being exposed through an interface.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/pages--default-story

### Carbon Version

95.1.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-4464
