### ISSUE TITLE
Button with Icon: Add aria-hidden="true" to span wrapping icon

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#4579]
### Current behaviour

Presently the span element that wraps the icon within a button is considered as the first character of the button text preventing the Voice Control tool on Mac to recognise the button text when scanning the page for the phrase spoken by the user.

### Expected behaviour

When the user speaks the button text phrase, it should be recognised on the page so the user can use voice commands to click the button.

### CodeSandbox or Storybook URL

N/A

### Carbon Version

91.0.2

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

Adding `aria-hidden="true"` to the `<span>` element that wraps the icon within a button will ensure the Voice Control tool or any other assistive technology does not consider the icon to be part of the button text while scanning the page for the phrase spoken by the user and so the user is able to click button using the Voice Control tool.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4477
