### ISSUE TITLE
"Skip to main content" is not translatable

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#4581]
### Current behaviour

"Skip to main content" string literal is hard coded to the source code.

### Expected behaviour

"Skip to main content" string literal is not hard coded to the source code so the literal can be translated into other languages.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/wandering-frost-6sny3

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

Other

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4476
