### ISSUE TITLE
Dialog component initialization issue

### ISSUE THREAD

**Issue by lamilsage** [Sage/carbon#4585]
### Current behaviour

In some cases Dialog component is not displayed.

#### React 17
In react 17, navigating directly to `/popup` the dialog is not displayed when button is clicked.
When navigate to the page using a navlink, the dialog is displayed when button is clicked.

https://codesandbox.io/s/vigorous-shockley-11bmh
https://11bmh.csb.app/popup

#### React 16
This works as expected with react 16.
https://codesandbox.io/s/suspicious-phoebe-e9zfz
https://e9zfz.csb.app/popup

### Expected behaviour

Dialog is displayed in any cases

### CodeSandbox or Storybook URL

https://codesandbox.io/s/vigorous-shockley-11bmh

### Carbon Version

100.1.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@lamilsage Carbon is currently only supporting React 16, we have a ticket in to upgrade to React 17 but this is currently blocked by some 3rd party libraries that don't support it yet. We can investigate to see if there is anything that can be done but please bear in mind that you might find other issues with React 17 as it is untested with Carbon.

**Comment by nicktitchmarsh** [comment]
FE-4475

**Comment by mamurph** [comment]
I've had issues with the Dialog component working in React 17 as well, and if it helps triage the issue, it's because react-dom flushes the document stack between the initial call to getPortalContainer() in the Portal component that adds the carbon-portal div and a subsequent call which thinks it's already there and doesn't render it. In Portal.js, I had to change the line 64 from:
`  const getPortalContainer = () => {
    const portalClassName = "carbon-portal";
    let node = portalNode;

    if (!node && id !== undefined && document.getElementById(id)) {
      node = document.getElementById(id);
      setPortalNode(node);
    } else if (!node) {
      node = document.createElement("div");
      node.classList.add(portalClassName);
      node.setAttribute("data-portal-exit", uniqueId);
`
to: 
`  const getPortalContainer = () => {
    const portalClassName = "carbon-portal";
    let node = portalNode;

    if (!node && id !== undefined && document.getElementById(id)) {
      node = document.getElementById(id);
      setPortalNode(node);
    } else if (!node || document.getElementsByClassName("carbon-portal")) {
      node = document.createElement("div");
      node.classList.add(portalClassName);
      node.setAttribute("data-portal-exit", uniqueId);
`
