### ISSUE TITLE
Advanced Color Picker - Add props disabled

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4586]
### Desired behaviour

In a `Form`, we want to have the possibility to disable an `Advanced Color Picker`.

### Current behaviour

The Advanced Color Picker enable the user to select a color. We don't have the ability to disable it.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/advanced-color-picker--default-story

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Design system to approve this change or allow us to close the ticket

**Comment by samtjo** [comment]
@nicktitchmarsh can we close this?

**Comment by ingridzillinger** [comment]
@hegou33 I wonder why we need this: If the user can't select a color, why should the advanced color picker show up as disabled?

**Comment by samtjo** [comment]
@hegou33 I'm going to close this unless it comes from the DS team that this is something we should add.
