### ISSUE TITLE
Expose Tooltip Interactive Property

### ISSUE THREAD

**Issue by shavonne-sage** [Sage/carbon#4593]
### Desired behaviour

As a developer I would like to make a tooltip interactive so that our end users can click the links and buttons contained within it.

### Current behaviour

Users cannot currently interact with tooltips.

### Suggested Solution

Please expose [Tippy's interactive property](https://atomiks.github.io/tippyjs/v6/all-props/#interactive) so that our platform development team can decide when users should be able to interact with tooltips.

More details can be found on this [GitHub issue](https://github.com/atomiks/tippyjs/issues/751).

### Anything else we should know?

While implementing a design provided by our UX team, we noticed that Carbon tooltips are not interactive. This functionality is key to realizing the workflow envisioned for our users.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
As we are working towards removing tooltips from Carbon I'm just going to close this feature request, sorry to disappoint @shavonne-sage
