### ISSUE TITLE
Alert - Typescript - children is not declared as a valid prop

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4600]
### Current behaviour

When using the Alert component where the title prop is a ReactElement, we receive this typescript error:
```typescript
Type '{ children: string; "data-role": string; onCancel: () => void; open: boolean; size: string; title: Element; }' is not assignable to type 'IntrinsicAttributes & DialogProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & DialogProps'.
```

### Expected behaviour

children to be a valid prop and to match: https://github.com/Sage/carbon/blob/master/src/components/alert/alert.component.js#L14

### CodeSandbox or Storybook URL

n/a

### JIRA Ticket (Sage Only)

SBS-24897

### Carbon Version

95.1.1

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4490
