### ISSUE TITLE
AdvancedColorPicker - Accessibility issue - Buttons must have discernible text

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4603]
### Current behaviour

AdvancedColorPicker button as an accessibility issue: `Buttons must have discernible text`.
![image](https://user-images.githubusercontent.com/38658070/144022422-3458ecdb-07ec-423e-98d8-ea048f3faaba.png)

### Expected behaviour

The button need to be visible to the screen readers.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/advanced-color-picker--default-story

### JIRA Ticket (Sage Only)

SBS-6759

### Carbon Version

95.1.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
This will be fixed as part of FE-4479

**Comment by nicktitchmarsh** [comment]
I have retested in the latest version of Carbon and this appears to be fixed now with the usage of aria-labels
