### ISSUE TITLE
Accessibility Pod Title prop always shown H4

### ISSUE THREAD

**Issue by ibsenjg** [Sage/carbon#4607]
### Desired behaviour

Be able to use a similar prop as ["as" present in typography](https://carbon.sage.com/iframe.html?id=typography--variants&viewMode=docs#typography-1) to modify the rendered title element to solve Accessibility issues coming from SBS-24478
### Current behaviour

Always returning an H4 element besides his internal rendered node which may be even an H3, H2.

### CodeSandbox or Storybook URL

https://carbon.sage.com/iframe.html?id=pod--default-story&viewMode=docs#pod-1

### Anything else we should know?

SBS-24478

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4493

**Comment by nicktitchmarsh** [comment]
Design system to clarify if they want Pod to have different title weights above H4. Or if content designers should be discouraged from putting higher heading tags in the body of a Pod

**Comment by nicktitchmarsh** [comment]
I had added to the JIRA ticket a possible solution of allowing `title` and `subtitle` to be passed as a React node instead of rendering into the provided Heading tags

**Comment by samtjo** [comment]
Does that mean we can remove the triage label and do this ticket then @nicktitchmarsh or do we still need DS input as well?
