### ISSUE TITLE
onTabChange in Tabs component is fired twice when a different tab is clicked

### ISSUE THREAD

**Issue by franip-sage** [Sage/carbon#4611]
### Current behaviour

When a function is passed to `onTabChange` prop in `Tabs` component, and a tab different from the currently selected one is clicked, the action is executed twice. If the currently selected tab is clicked, only is fired once.

### Expected behaviour

The action should be fired only once when the tab is changed.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pensive-elgamal-1rnpe?file=/src/index.tsx

### Carbon Version

95.1.1 and 101.0.2

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4909 raised
