### ISSUE TITLE
Loader - Add a data role prop

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4612]
### Desired behaviour

Many of the Carbon components accept the `data-role` prop.
This is often used when there are no other selectors available when writing tests.

At the moment, there is nothing clear to check for the display or removal of the Loader component.
If we had the ability to add the prop `data-role` this would solve our problem.

### Current behaviour

We currently wrap every loader in something such as a div, example:
```javascript
    <div data-role="table-loader">
      <Loader />
    </div>
```

### Suggested Solution

The Loader component to accept data-role:
```javascript
      <Loader data-role="table-loader" />
```

### CodeSandbox or Storybook URL

na

### Anything else we should know?

I am not sure if there should be any accessible markers on a loader component and if so, they could be used as a querySelector in react testing library as well as it fixing a problem of something happening on the screen.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4508 raised

**Comment by samtjo** [comment]
Hi @philearley - it is currently possible to add a `data-role` onto `Loader` - example here: https://codesandbox.io/s/dazzling-euler-0ur8w?file=/src/index.js 

Are you seeing a TypeScript error or something? If not I'll just close this issue 👍🏻
