### ISSUE TITLE
FlatTable - Scroll bar is visible even when there is no content to scroll to

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#4613]
### Current behaviour

When using the FlatTable with a height, stickyFooter and stickyHeader, we are seeing a scroll bar even when there is no content to scroll.

### Expected behaviour

The scroll bar would only be visible when there is content to scroll to.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/stupefied-sound-dzjtu?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-25034

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Anything else we should know?

On a Mac, if the scroll bar is not visible unless you scroll, then this is a setting in system preferences that needs turning on

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4507 raised
