### ISSUE TITLE
Select component display a misleading cursor

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4618]
### Current behaviour

 As is: If a default Select is implemented (may be called "SimpleSelect" in Carbon - https://carbon.sage.com/? 
 path=/docs/select--default-story#props), (without ability to filter or freely type into it), then the flashing text cursor is 
 shown. This might be misleading, because the user can't type (although standard html Select behaviour does apply, like 
 typing the first letter jumps to that option).

### Expected behaviour

 Unless the Select is filterable, then don't show the flashing text cursor.
 Retain behaviour like typing the first letter jumps to that option.
 Basically, replicate the behaviour of a standard html  https://developer.mozilla.org/en- 
 US/docs/Web/HTML/Element/select

### CodeSandbox or Storybook URL

https://codesandbox.io/s/black-leaf-no66z?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-24752

### Suggested Solution

I think the Textbox that is used could be rendered also with the expected behaviour by passing the relevant new props(or existing if we have)

### Carbon Version

101.4.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by grabkowski** [comment]
this will be fixed by: https://github.com/Sage/carbon/pull/4506
