### ISSUE TITLE
DismissibleBox - width prop is missing in d.ts file

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#4621]
### Current behaviour

If we import DismissibleBox component, we can not set width property as it's missing in d.ts file

### Expected behaviour

When i import DismissibleBox component, we can set width property

No CodeSandbox as it's working in codeSandbox environement

### CodeSandbox or Storybook URL

https://carbon.sage.com/storybook?path=/docs/dismissible-box

### JIRA Ticket (Sage Only)
SBS-24456

### Carbon Version

102.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4572
