### ISSUE TITLE
Add required prop to `InlineInputs`

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4625]
### Desired behaviour

Add a required prop to inline inputs which adds the required asterisk to the inline input legend label.

### Current behaviour

If I want some controls on the same line and do not have labels for each one individually, instead opting to use a legend so that it is aligned with other items on the form, there is no way for me to flag that group of inputs as required.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pensive-ride-gqq4e?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
This seems like a reasonable request but we'll just double check with the DS team before we raise a ticket for it.

@clairedenning

**Comment by clairedenning** [comment]
I'm not sure that this solution addresses accessibility requirements. Will get back to you

**Comment by nicktitchmarsh** [comment]
@v99rly could you take a look at this please?

**Comment by samtjo** [comment]
@v99rly - do you have any time to look at this?

**Comment by v99rly** [comment]
Using as Asterix isn't really sufficient for accessibility. I would recommend using the word required within the label itself.

That way a visual user can see that its required and also a screen reader would read out the word required as well.

For more information check out this link https://dequeuniversity.com/tips/identify-required-elements

Thanks

**Comment by nicktitchmarsh** [comment]
@v99rly @clairedenning, any update on Jamie's comment above?

**Comment by nicktitchmarsh** [comment]
@ljemmo can you check if this is on DSY backlog?

**Comment by ljemmo** [comment]
@nicktitchmarsh we have a ticket on our [backlog for this here](https://jira.sage.com/browse/DSY-1635).

**Comment by ljemmo** [comment]
@jamime and @nicktitchmarsh - I've reviewed the [NN article](https://www.nngroup.com/articles/required-fields/) and also taken a few options to the accessibility surgery. Based on those two inputs, i would recommend we do the following:

- Mark all required fields with a red asterisk (we already do this in carbon as Jamie says). NN recommend this as an industry norm.
- Mark all optional fields with an (optional) string of text.

**Here's the spec below (nothing sage sensitive there)**
[Optional & Required spec (no sensitive data).pdf](https://github.com/Sage/carbon/files/10185174/Optional.Required.spec.no.sensitive.data.pdf)

____

There were some concerns raised from the accessibility surgery participants that the red asterisk might not be fully understood by all users, so i've created tickets for Debbie to do further research on this. With that in mind, the spec may change in the future. But as an MVP, we can probably unblock this for now by continuing to support the red asterisk and if the field isn't required, inject the (optional) text in. Sound like a plan?
