### ISSUE TITLE
Dissmissible box - minWidth setted but not wanted

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#4627]
### Current behaviour

If i want a little dissmissble box, i can not because we have a minWidth setted.
The 600px is related to the content displayed inside, not related to the size of the dissmissible box.

### Expected behaviour

I want to have a little dissmissible box less than 600px

### CodeSandbox or Storybook URL

https://codesandbox.io/s/little-waterfall-hh1pb?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-24456

### Carbon Version

102.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4633
