### ISSUE TITLE
Select - The focus cannot be removed once it's disabled

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#4631]
### Current behaviour

Given the `Select` component
When it is focused and disabled 
Then the focus cannot be removed

For the codesandbox:

1. Select two options in the MultiSelect
2. Press Tab to move the focus to the Reset button

As a result, both elements are focused.

![image](https://user-images.githubusercontent.com/11317965/145381031-f9c8c3e8-470f-4530-afae-c161d1615650.png)

### Expected behaviour

Once the `Select` component is disabled the focus should be removed.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/wandering-feather-vtqi0?file=/src/index.js:875-886

### Carbon Version

102.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
This should just be a case of removing the focus CSS when the disabled prop is set to true. If the Select is currently focused when it gets disabled I think focus should be moved to the next focusable element on the page (although let's check that bit with UX).

**Comment by samtjo** [comment]
FE-4631
