### ISSUE TITLE
Screen Reader reads two separate elements as one within Flat Table with StickyFooter

### ISSUE THREAD

**Issue by szeyingyau** [Sage/carbon#4637]
### Current behaviour

The screen readers, NVDA (Windows) and VoiceOver (MacOS) combines two elements on the StickyFooter in the Flat Table component and reads the elements on the StickyFooter - Pager component as one. 

### Expected behaviour

The screen readers are able to read the elements separately instead of reading it at once.

### CodeSandbox or Storybook URL

https://carbon.sbc-ui.com/?path=/docs/flat-table--with-sticky-footer

### JIRA Ticket (Sage Only)

SBS-25588

### Carbon Version

101.1.0

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Anything else we should know?

If the StickyFooter - Pager component has a `Next` and `Previous` button, the screen reader reads the elements correctly.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
Thanks @tempertemper - I think you've given us what we need for now 👍🏻

**Comment by samtjo** [comment]
FE-4985
