### ISSUE TITLE
Textarea component does not display initial state value

### ISSUE THREAD

**Issue by lamilsage** [Sage/carbon#4645]
### Current behaviour

In a simple page, I add a texteare component.

```
<Textarea
        id="licenceTextArea"
        value={displayedLicence}
        onChange={handleDisplayedLicenceChange}
      />
```

The displayedLicence value is initialized with some text.
When the page is displayed, the textarea is empty.

### Expected behaviour

Textarea component display value passed in parameter.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/brave-framework-mr5ms

### Carbon Version

102.4.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
The `value` prop isn't being passed to the input anymore
