### ISSUE TITLE
SplitButton dropdown toggle button inside a form triggers submit event when clicked

### ISSUE THREAD

**Issue by clheppell** [Sage/carbon#4651]
### Current behaviour

When a `<SplitButton>` is used within a `<form>` (either post or get), clicking on, rather than just hovering over the dropdown toggle button causes a submit event.

This is because there is no `type` attribute set on the button, so the browser default whilst within a form is to treat the button as a submit button.

Our `<SplitButton>`s outside of forms are not impacted as the default here for browsers is not to treat them as a submit.

### Expected behaviour

On clicking the dropdown toggle button, the dropdown should be displayed and the dropdown toggle button should not fire a submit event.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/blissful-hermann-xbwb4

### Suggested Solution

Set `type="button"` on the dropdown toggle button.

### Carbon Version

95.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows, iOS

### Anything else we should know?

On Sage 200 we are upgrading to Carbon 95.1.0 and assume this is a regression introduced when `<SplitButton>` became a functional component. We're using a wrapper around this component as a temp fix.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4696
