### ISSUE TITLE
Pages component transition issue

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4657]
### Current behaviour

When we use Pages component with Page as a child in a different component then there is an error: _props.transitionName is not a function_

Same happens also when the list of pages is been returned by a method.

### Expected behaviour

Error will not occur and pages component could work as expected 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/transition-error-test-forked-bnk1q?file=/src/index.js

### Suggested Solution

For now instead of using ` <TestPage />` we use `TestPage()`.

### Carbon Version

102.4.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4702 - we'll decide after an investigation if this is meant to be fixed on our side or on client side
