### ISSUE TITLE
StepSequenceItem line max-width property

### ISSUE THREAD

**Issue by YariMVSage** [Sage/carbon#4659]
### Desired behaviour

The UX/UI team has asked us to reduce the length of the line that appears before text in StepSequenceItem component and center all StepSequenceItem components. Trying to do so through CSS is a little bit tricky and we are not getting the expected results. We would like to have a property in the component to set the max-width of this line in an easier way

### Current behaviour

Right now the StepSequenceItem component occupies all available space, and if we short the line through CSS then a long white space appears, we have tried to adjust it but if we do so, the line disappears.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/hungry-hooks-2tq2u

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Hi @YariMVSage, You can use Box to adjust the layout of other components. Please see this sandbox and let us know if this solves your issue https://codesandbox.io/s/jovial-rui-uupns?file=/src/index.js:543-612

**Comment by samtjo** [comment]
@harpalsingh - is this something we'd like to introduce to the StepSequence component (https://carbon.sage.com/?path=/docs/step-sequence--default-story) - the ability to change the length of the lines between the items?

**Comment by Parsium** [comment]
Hi @harpalsingh do you have any updates on this?

**Comment by edleeks87** [comment]
@harpalsingh and @ljemmo any thoughts on this?

**Comment by YariMVSage** [comment]
Hi excuse me this request belongs to an old UX design, we don't need it anymore

**Comment by Parsium** [comment]
Thanks for letting us know @YariMVSage 👍🏼
