### ISSUE TITLE
Linter issue importing DialogFullScreen component 

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4669]
### Current behaviour

Using the DialogFullScreen we have a linter error: 'JSX element class does not support attributes because it does not have a prop's property'

### Expected behaviour

not having linter errors

### Carbon Version

102.4.1 

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
@DipperTheDan thinks this is due to an incorrect typescript definition.

**Comment by justin-rankin** [comment]
As a TEMP fix, i was able to satisfy those errors by adding to `src/types/carbon-react.d.ts`:

```
declare module "carbon-react/lib/components/modal";
declare module "carbon-react/lib/components/dialog-full-screen";
```

**Comment by DipperTheDan** [comment]
> @DipperTheDan thinks this is due to an incorrect typescript definition.

I think it is this line [here](https://github.com/Sage/carbon/blob/master/src/components/dialog-full-screen/dialog-full-screen.d.ts#L21) causing the issue. It should be declared as a function and not a class. Look at Dialog's `d.ts` file [here](https://github.com/Sage/carbon/blob/master/src/components/dialog/dialog.d.ts#L27) for the correct code.

**Comment by DipperTheDan** [comment]
FE-4705
