### ISSUE TITLE
Not consistent padding/margin in radio and checkbox

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4670]
### Current behaviour

Radio button has margin-bottom 12px and checkbox has padding-top 12px. It causes issues with wrong spacing between label and fields (for radio it's 8px, for checkbox it's 20px).

![image](https://user-images.githubusercontent.com/75613789/148188288-5b405d3d-92a4-4d4f-bbb1-15de6c44fbcf.png)

### Expected behaviour

Spacing should be the same in both cases.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/modern-snow-p09k6?file=/src/index.js

### JIRA Ticket (Sage Only)

RIV-580

### Carbon Version

102.4.6

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows, Linux

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4718
