### ISSUE TITLE
MenuFullscreen has an horizontal scrolling 

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4674]
### Current behaviour

MenuFullscreen has an horizontal scrolling that breaks the UI

### Expected behaviour

Remove that scrolling

![image](https://user-images.githubusercontent.com/84023810/148242921-bfd62bd6-f7a0-4f6d-80f9-896edf9911ac.png)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/bold-snowflake-iuw9f?file=/src/index.js:1108-1122

### Suggested Solution

Fix the issue with the menu item with submenu header

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
I will fix this as part of FE-4416
