### ISSUE TITLE
MenuFullscreen with Search and MenuItems break the UI

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4675]
### Current behaviour

UI is broken when we use those elements. The Search border bottom is not displayed 

![image](https://user-images.githubusercontent.com/84023810/148245370-a7f1d16a-4187-4328-9ad2-b3be094c86b3.png)

### Expected behaviour

display correct those items, see the Search border bottom line. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/bold-snowflake-iuw9f?file=/src/index.js

### Suggested Solution

The Search component should work as block element.

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
I will fix this as part of FE-4416

**Comment by StylianosKoidakisSage** [comment]
@samtjo  could you also see on this issue something that is related with it? the display prop is not working in menu items , when we pass a value for example "flex" still is "list-item". thank you

**Comment by samtjo** [comment]
Hi @StylianosKoidakisSage I'm sorry but there's already 3 issues being fixed by this PR, and that isn't really related to any of them so can you raise a separate Github issue for that please?

**Comment by StylianosKoidakisSage** [comment]
i will take a look after the fix and i will create a new issue if i think we need it then. thank you
