### ISSUE TITLE
Carbon Quickstart is out of date

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#4679]
### Current behaviour

Carbon Quickstart is out of date, it references `carbon-react/lib/utils/css` which we no longer export.

### Expected behaviour

It should match the codesandbox template.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/documentation-getting-started--page#quickstart

### Carbon Version

102.7.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4718
