### ISSUE TITLE
Review node engines

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#4680]
### Current behaviour

@timhines reported this warning when installing carbon.
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'carbon-react@102.7.1',
npm WARN EBADENGINE   required: { node: '>=14.16.0', npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
npm WARN EBADENGINE }
```

### Expected behaviour

We should support the latest node/npm LTS as a minimum, possibly older. We should only warn if there is something we depend upon (e.g. syntax) and we should consider if those features are already handled by `babel/preset-env`. Do we need to enforce npm version for consumers?

### CodeSandbox or Storybook URL

N/A

### Carbon Version

102.7.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4717

**Comment by stripeyjumper** [comment]
This is a major blocker for our project - upgrading Node from 12 to 14+ to support Carbon will require changing the entire application stack.
Also, use of fancy new syntax like null-coalescing (I know it's not *that* new 😄) doesn't work in Webpack 4, and it will be hard to transition to 5.

**Comment by samtjo** [comment]
Hi @stripeyjumper - the [end of life for Node v12](https://nodejs.org/en/about/releases/) is the 30/04/2022 so you really should be upgrading soon (to at least v14, ideally the current LTS). We will soon be updating to the latest LTS, although we will keep support for v14 as it's still in maintenance until April 2023. 

There are Babel plugins you can use with Webpack 4 to support the nullish-coalesing operator etc, such as https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator - although admittedly it would be a lot better to just upgrade to webpack v5, I appreciate that can be a time consuming task though!

**Comment by edleeks87** [comment]
I'm reopening as there are still some issues to resolve with npm install when using npm >=7
