### ISSUE TITLE
MultiActionButton - not closing when it loses focus

### ISSUE THREAD

**Issue by mrtn-a** [Sage/carbon#4683]
### Current behaviour

Using keyboard navigation, MultiActionButton's dropdown stays open and active when we open a Dialog component. It also allows further keyboard actions and navigating other web elements.

### Expected behaviour

MultiActionButton should close when it loses focus, not allowing to navigate/focus other elements behind the Dialog.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/white-darkness-8mxt5?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-25882

### Carbon Version

102.7.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4887

**Comment by mkrds** [comment]
Seems like the issue is fixed in newest version of carbon
https://codesandbox.io/s/bold-haze-qzoh8?file=/src/index.js
