### ISSUE TITLE
Pages component in smartphone version - headings positions are different after second page, titles are too close to the close button 'x'

### ISSUE THREAD

**Issue by ZhuoyuJin** [Sage/carbon#4685]
### Current behaviour

Repo Steps:

1. Go to Pages component default story https://carbon.sage.com/v/102.7.1/index.html?path=/story/pages--default-story
2. Change it to Smart Phones (P) version
3. Click on 'Open Preview' button, the heading "My First Page" can be seen (see screenshot)
4. Click on 'Go to second page' button, the heading "My second Page" doesn't aligned the same as the previous "My First Page" heading (see screenshot)

![Image 07-01-2022 at 19 00](https://user-images.githubusercontent.com/72838192/148593607-205e7815-a277-4a7c-847a-dada66d3110d.jpg)

![Image 07-01-2022 at 19 00 (1)](https://user-images.githubusercontent.com/72838192/148593627-b7827524-08bd-4e85-8a80-a696683230e9.jpg)

### Expected behaviour

Second page title and third page title should look better or a bit far from the close button. 

### CodeSandbox or Storybook URL

https://carbon.sage.com/v/102.7.1/index.html?path=/story/pages--default-story

### Carbon Version

v102.7.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4715

**Comment by nicktitchmarsh** [comment]
This appears to be working correctly now
