### ISSUE TITLE
Tabs component with misleading cursor:pointer 

### ISSUE THREAD

**Issue by mrtn-a** [Sage/carbon#4686]
### Current behaviour

When hovering on the adjacent space around the Tabs, the cursor keeps as cursor:pointer, also on the blank areas which are not interactive. 

### Expected behaviour

It'd be ideal to remove the cursor:pointer from the adjacent blank areas, as in the extendedLine={false} option.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/tabs--default-story

### JIRA Ticket (Sage Only)

SBS-17136

### Carbon Version

102.7.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

I can provide a draft PR with the solution
### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4715

**Comment by mrtn-a** [comment]
I've created a [draft PR](https://github.com/Sage/carbon/pull/4696/files) with an easy fix
