### ISSUE TITLE
FullScreenDialog ARIA-MODAL implementation for screen voice command tools

### ISSUE THREAD

**Issue by ibsenjg** [Sage/carbon#4687]
### Desired behaviour

When using screen voice command tools and asking for the numbers on the screen to show, the dialog should only show current active/opened modal numbers and not the ones that could exist behind.

### Current behaviour

When opening a modal, fullscreen mode and asking the voice command tool e.g Mac OS VoiceOver to show the numbers to navigate using voice commands it shows the focusable elements and links form active modal and behind elements which is not correct based on a11y preferences

### Suggested Solution

add aria-modal and role dialog to the StyledFullScreenDialog to cater for this a11y issue

### CodeSandbox or Storybook URL

https://carbon.sage.com/storybook?path=/docs/dialog-full-screen--default-story

### Anything else we should know?

Current scope SBS-25895

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by grabkowski** [comment]
will be fixed when #4604 is merged

**Comment by ibsenjg** [comment]
FullScreenDialog not support `aria-modal` 

Dialog with `aria-modal` 
<img width="1609" alt="Captura de pantalla 2022-01-14 a las 9 46 38 a  m" src="https://user-images.githubusercontent.com/18384611/149488501-939077d2-14f3-4364-b310-4d720dc37690.png">

FullScreenDialog without aria-modal
<img width="1568" alt="Captura de pantalla 2022-01-14 a las 9 46 57 a  m" src="https://user-images.githubusercontent.com/18384611/149488166-be719769-1df7-4433-974c-1df58e535d6b.png">

FullScreenDialog with `aria-modal` manually added in browser
<img width="1571" alt="Captura de pantalla 2022-01-14 a las 10 00 59 a  m" src="https://user-images.githubusercontent.com/18384611/149488178-e9b5802a-2aea-4853-868d-2d26be7ba0e6.png">
