### ISSUE TITLE
NavigationBar: Add z-index css property when sticky position css is applied

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#4690]
### Current behaviour

When the `NavigationBar` component with a submenu has `stickyPosition="top"` applied to it and there is an element below it that has the `position: relative` css applied, for instance the `Drawer` component, the below component (`Drawer`) appears in front the opened submenu dropdown.

### Expected behaviour

The submenu dropdown appears in front of the relatively positioned element.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/snowy-dawn-mngih?file=/src/index.js

### Suggested Solution

A value of `1` for `z-index` seems to suffice when the `Drawer` component is below the `NavigationBar` component but taking into consideration other components, this value may need to be different.

### Carbon Version

101.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-4712
