### ISSUE TITLE
NavigationBar: position sticky does not work when the component is placed in a div separate to the main content

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#4691]
### Current behaviour

When the `NavigationBar` is wrapped within a `<div>`, separate to the main content, `position: sticky` does not work and so the `NavigationBar` does not remain visible at the top of the viewport when the user scrolls through the main content.

### Expected behaviour

Expect an approach to allow the `NavigationBar` to remain visible at the top of the viewport when the user scrolls through the main content.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/eloquent-williams-xt8u1?file=/src/index.js

### Suggested Solution

Use `position: fixed` instead of `sticky`, with `top: 0`, `width: 100%` and `box-sizing: border-box`. This will allow the `NavigationBar` to remain visible at the top of the viewport when the user scrolls through the main content, despite being wrapped in a `<div>` separate to the main content.

### Carbon Version

101.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-4711
