### ISSUE TITLE
Refactor `Heading` to be a functional component

### ISSUE THREAD

**Issue by Parsium** [Sage/carbon#4697]
### Desired behaviour

Refactor `Heading` from a class-based component to a functional-based one.

### Current behaviour

Currently `Heading` is a class-based component. It is utilised in the following components:
- `Confirm`
- `Dialog`/`DialogFullScreen`
- `Page`
- `Select` (specifically `OptionGroupHeader`)
- `SettingsRow`

### Suggested Solution

Refactor `Heading`

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
Hi @Parsium - we don't need a Github issue for this, just raise a ticket straight onto the Jira backlog for this 👍🏻  Good spot though
