### ISSUE TITLE
ActionPopoverMenuButton hover/focus bug

### ISSUE THREAD

**Issue by DipperTheDan** [Sage/carbon#4701]
### Current behaviour

When the button is hovered or focused, the text becomes white and blends into the background colour of the component.

![action-popover-button-bug](https://user-images.githubusercontent.com/56251247/149164898-e2fd7fc8-54d2-45a9-a4f2-092bb0696ff0.gif)

### Expected behaviour

There should be sufficient contrast between the text colour and the background colour when the element is focused or hovered over.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/action-popover--with-custom-menu-button

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

This was working fine before v102.4.0

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4725 will address this open issue.

**Comment by samtjo** [comment]
This appears to be fixed now, closing the issue.
