### ISSUE TITLE
Margin left is incorrect when cancelButtonType is "tertiary"

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#4711]
### Current behaviour

https://github.com/Sage/carbon/blob/master/src/components/confirm/confirm.component.js
This line overrides the margin to 3px when the type is tertiary

![image](https://user-images.githubusercontent.com/44157880/149384344-8489010d-8add-4b8e-9ca4-c932632fcd27.png)

### Expected behaviour

Margin left should be consistent at 16px irrespective of the cancel button type

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/confirm--destructive

### JIRA Ticket (Sage Only)

SBS-26125

### Suggested Solution

remove ternary and have `ml={2}` only

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4750
