### ISSUE TITLE
Tooltips do not re-position when the target element moves

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#4713]
### Current behaviour

Tooltips remain anchored to the current position of the target element even when the target re-positions.

### Expected behaviour

Tooltip re-positions when target element does.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/cocky-noether-yr46m?file=/src/index.js

### Carbon Version

102.10.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Anything else we should know?

This behaviour was spotted due to [changes](https://github.com/Sage/carbon/commit/f5ec1c71655ff4ecd8150f167130ebe38ae25efc) made to the `StickyFooter` and how the scrollbar changed as this only happens after `v102.7.3`.

Issue can be recreated in sandbox by opening the Select and clicking the option

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4749
