### ISSUE TITLE
Tab focus state not maintained when child dialog is closed inside parent dialog

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#4714]
### Current behaviour

A function component called ExampleComponent contains a parent dialog which has a nested child dialog.

When the function component is called as a function in JSX, i.e. `{ExampleComponent()}`, tabbing focus state is lost when the nested child dialog is closed using the keyboard. The tab focus state is trapped outside the parent dialog.

### Expected behaviour

When the function component is called as a function in JSX, i.e. `{ExampleComponent()}`, tabbing focus state is not lost when the nested child dialog is closed using the keyboard. The tab focus state is expected to be trapped inside the parent dialog.

### CodeSandbox or Storybook URL

N/A

### JIRA Ticket (Sage Only)

SBS-25172

### Carbon Version

101.1.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

A branch for testing has been linked in the ticket description provided above.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4751
