### ISSUE TITLE
Better UI for nested sub menus

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4715]
### Desired behaviour

It would be nice to give to the UI a better way to navigate thought menu nested items.

### Current behaviour

Right now all the submenus are been displayed in the same direction, like so we can not see all the menu items.

![image](https://user-images.githubusercontent.com/84023810/149729769-2b3ccff8-239c-477a-9610-a1fc3782d3d4.png)

### Suggested Solution

 I think the best solution is to position sub menus aside.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/determined-pateu-ww8hq?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
@harpalsingh - Are nested submenus something that we want to support in Carbon?

**Comment by harpalsingh** [comment]
@DipperTheDan I believe we have explored concepts for nested menus inside a submenu and I feel supporting that will be useful but this is work we need to do alongside the DS team. As it stands we only have the design set for 1 level parent.

**Comment by nicktitchmarsh** [comment]
@clairedenning could you advise if this is something that Design System have on their backlog?

**Comment by clairedenning** [comment]
@nicktitchmarsh Is your work related to [Left navigation](https://zeroheight.com/2ccf2b601/p/58fa64-left-navigation/b/8975c9)? If so, we are aware of issues, and we still have to rebrand it. @ingrid.zillinger@sage.com may be able to tell you more about backlog status.

**Comment by nicktitchmarsh** [comment]
@clairedenning This is something that is unintentionally supported. We don't recommend it as per the above issue but we aren't doing anything to restrict the usage of submenus to one level. It's more a question of do you want this component to be used in this way, or should UX designers come up with other solutions instead of needing nested submenus
