### ISSUE TITLE
AutoFocus for Link component

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4719]
### Desired behaviour

Link component should have autoFocus param to set it on load content.

### Current behaviour

There is no autoFocus param available.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/link--default-story

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by msinga** [comment]
RIV-608

**Comment by DipperTheDan** [comment]
FE-4748

**Comment by samtjo** [comment]
Hi @maspychaj-sage - we provide a forward ref for the `Link` component for exactly this kind of use case, you can use it to focus the Link yourself when it is first rendered. See this sandbox for an example of how to do this: https://codesandbox.io/s/spring-butterfly-g5qyc?file=/src/index.js 

`autofocus` is not a valid HTML attribute for an anchor element https://www.w3schools.com/tags/att_autofocus.asp and so we shouldn't add this to the `Link` component either.

I'm going to close this issue as focusing the Link here is something you should be doing in your own code 👍🏻
