### ISSUE TITLE
Scale Toast to Display on Small Screens

### ISSUE THREAD

**Issue by shavonne-sage** [Sage/carbon#4722]
### Desired behaviour

Toast messages (info, warning, success, error) scale well on all screens.

### Current behaviour

Toast messages (info, warning, success, error) do not scale well on small screens (320x534).

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
Hi @shavonne-sage, By wrapping `Message` in a `Box` component you will be able to achieve the responsive behaviour. I have provided a codesandbox [here](https://codesandbox.io/s/wonderful-haibt-jywmp?file=/src/index.js) so you have a code example of this. 

I've also attached a screenshot as a visual reference too.
![Screenshot 2022-01-19 at 15 40 22](https://user-images.githubusercontent.com/56251247/150164378-a3d0966d-a103-41f6-882a-37e94f30aeaf.png)

**Comment by nicktitchmarsh** [comment]
Hi @shavonne-sage, the same fix can be applied to Toast however it will wrap the content. There aren't any responsive designs yet for these components and that would have to come from Design System. Please could you ask your designer to raise this with the DS team and link them to this issue?

**Comment by shavonne-sage** [comment]
@samtjo , one of our UX designers is going to discuss toast messages on small screens with DS.

**Comment by benjamin-dean-web** [comment]
@shavonne-sage, I'm the UI Designer

**Comment by benjamin-dean-web** [comment]
@shavonne-sage  Carbon is working on the update on this issue. This is clearly something the matter with the toast component. Max width, middle-positioned close icon, and toast shadow will have to be resolved for our DS.

**Comment by samtjo** [comment]
Hi @benjamin-dean-web - we on the Carbon team are not working on this. We're waiting on an update on this issue before we add it to our backlog, if the Design System team say that this is something we need to do.

**Comment by ingridzillinger** [comment]
Hello from the Design System Team! We currently have a task force working on the responsive design to propose the grid layout and rules. Once we have reached an agreement on this proposal, the rules will be applied to the components. Until then, unfortunately, work on this component will have to wait to avoid duplicating efforts. We will work with the product teams to sort the components by urgency so that the most important and biggest issues are resolved first.

**Comment by shavonne-sage** [comment]
Thank you for the update, @ingridzillinger. What is the timeline for proposing the grid layout and rules?
