### ISSUE TITLE
Input with labelHelp & Hover

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4725]
### Current behaviour

When an input with a labelHelp is hovered, the help is displayed.
Pb : when the content of the help is big, I can't see the content of my input especially when it is a select

### Expected behaviour

When the input has the focus, hide the help.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/kind-driscoll-cp95x?file=/src/index.js

### Carbon Version

102.16.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
The above PR should fix this issue as this was incorrectly changed.

**Comment by nicktitchmarsh** [comment]
FE-4713
