### ISSUE TITLE
Tooltip on icon button doesn't work if the button has been previously disabled.

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#4745]
### Current behaviour

- When a button is enabled on first render with `iconType` and `iconTooltipMessage` properties and the user hovers over the button the tooltip renders as expected.
- When the button gets disabled, the tooltip doesn't render on hover as expected.
- When the button becomes enabled again, the tooltip still doesn't render if the user moves the mouse over.

### Expected behaviour

- When a button is enabled on first render with `iconType` and `iconTooltipMessage` properties and the user hovers over the button the tooltip renders as expected.
- When the button gets disabled, the tooltip doesn't render on hover as expected.
- When the button becomes enabled again, the tooltip renders on hover.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/focused-volhard-41sl1?file=/src/index.js

### Carbon Version

102.16.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

The tooltip will never be displayed, if the button is rendered as disabled first.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4880
