### ISSUE TITLE
Incorrect behaviour with FlatTableCheckbox and keyboard navigation

### ISSUE THREAD

**Issue by thedannygoodall** [Sage/carbon#4751]
### Current behaviour

When there is a `FlatTableCheckbox` within a `FlatTableRow`, using `event.stopPropagation()` inside the `onClick` handler for the `FlatTableCheckbox` successfully prevents the click handler for the row from executing. However, when using keyboard navigation to click on the checkbox (by pressing [space] on the keyboard), the row's click handler is incorrectly being executed.

https://user-images.githubusercontent.com/28150291/150993750-1929de80-2d2f-49c5-8523-a6d03cd2e4a2.mov

### Expected behaviour

When the keyboard is used to navigate the table and toggle a `FlatTableCheckbox`, the row that the checkbox is inside should not have it's event handler triggered if `event.stopPropagation()` is inside the event handler for the `FlatTableCheckbox`

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sad-dijkstra-9e6wm?file=/src/index.js

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4886
