### ISSUE TITLE
`Search` component calls `onChange` handler twice

### ISSUE THREAD

**Issue by thedannygoodall** [Sage/carbon#4768]
### Current behaviour

When the text inside the `Search` component updates/changes, the `onChange` handler for the component gets triggered twice. 

https://user-images.githubusercontent.com/28150291/151791534-0bfdceb4-49b9-47f2-9611-b9dd128c1261.mov

### Expected behaviour

For the `onChange` handler to only be triggered once. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/patient-voice-r3dru

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4899
