### ISSUE TITLE
[Select - Textbox - Input] - Focus border style sticks on component

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#4769]
### Current behaviour

Given a component that uses an `Input`
When it gets disabled and enabled programmatically 
Then the orange border style is rendered

Here is a [Codesandbox](https://codesandbox.io/s/elated-dawn-6zsbn?file=/src/index.js). Steps to reproduce:
Select the first option
Click the button
The orange border is rendered in both components (`Select` and `Button`) when it should only be in the `Button`.

### Expected behaviour

The orange border only shows up when the element is the active element.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elated-dawn-6zsbn?file=/src/index.js

### Carbon Version

104.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4898
