### ISSUE TITLE
Dialog component - changing theme has no affect on the colour of the buttons.

### ISSUE THREAD

**Issue by DianeGit22** [Sage/carbon#4772]
### Current behaviour

Repro Steps: 
Navigate to the Dialog component Test Default story. 
The theme is set to Sage(Experimental) by default. The Save button is displayed in green. 
Change the theme to aegean. 

Expected Results: 
The Save & Cancel buttons should be displayed in aegean. 

Actual Result:
Changing the theme has no affect on the colour of the Save & Cancel buttons as shown here: 

![image](https://user-images.githubusercontent.com/47564230/151944830-0ce8f3fa-7227-4e3f-9030-749d70d362e3.png)

### Expected behaviour

Changing the theme to aegean should cause the Cancel & Save buttons to be displayed in aegean. 

### CodeSandbox or Storybook URL

https://carbon.sbc-ui.com/?path=/story/dialog-test--default-story

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4896

**Comment by samtjo** [comment]
In canvas view, the custom classname being added to the Portal for the Design Tokens CSS variables isn't changed when switching themes.

The way this works is being rewritten in https://github.com/Sage/carbon/pull/4791 which fortunately fixes this issue as well
