### ISSUE TITLE
Icons are not shown for ActionPopoverItems within react fragments

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4773]
### Current behaviour

When I wrap my ActionPopoverItems in a React.Fragment within an ActionPopover, the icons do not display.

### Expected behaviour

When I have several ActionPopoverItems rendered from the same condition, I must either wrap the two in separate conditions to avoid this issue, but it would be more convenient to just use the one condition requiring them to be put within a fragment.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/relaxed-bose-wtwwl?file=/src/index.js

### Carbon Version

104.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4895

**Comment by samtjo** [comment]
Hi @liam-cochrane - Thanks for raising but as you can see from the console warning in your sandbox there, this is intended behaviour as the only type of children that `ActionPopover` accepts are `ActionPopoverItem` and `ActionPopoverDivider` . 

If you want to conditionally render children here you can add the `ActionPopoverItem`s and `ActionPopoverDivider`s` into an array and pass that in as the children of `ActionPopover`, you can build the array based on your conditional requirements 👍🏻
