### ISSUE TITLE
Box component justify content prop is not working on Safari

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#4779]
### Current behaviour

When i use the Box component with display flex and justify content end is not placed the expected item at the end.

### Expected behaviour

Item should be placed at the end.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sweet-cache-q8gj6?file=/src/index.js

### Suggested Solution

Use `-webkit-justify-content `in css

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4921

**Comment by nicktitchmarsh** [comment]
Closed due to currently working in the latest Safari
