### ISSUE TITLE
Unable to select options from SplitButton with keyboard if children are link buttons

### ISSUE THREAD

**Issue by clheppell** [Sage/carbon#4784]
### Current behaviour

On Sage 200 some of our SplitButtons contain children which are links. For this we make carbon buttons into links following the example given in the [usage with routing](https://carbon.sage.com/?path=/docs/documentation-usage-with-routing--page) documentation.

When a user tries to use the keyboard to select an option from the split button, they are unable to. In the console we see `Uncaught TypeError: additionalButtons.current[nextIndex].focus is not a function` from within the Carbon SplitButton component.

Impacts accessibility and slows down our power users who like to use the keyboard.

### Expected behaviour

User should be able to select options from the dropdown with their keyboard as when the split button has only buttons as children.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/bold-sunset-ztpoc?file=/src/index.js

### Carbon Version

104.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

Also applies to the MultiActionButton

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4920
