### ISSUE TITLE
[Checkbox] Three state checkboxes

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4808]
### Desired behaviour

I would like to be able to display an extra state on checkboxes. When I have a checkbox that is as of yet unset, there is no way to display that in the UI, and will look the same as an unchecked checkbox. I would like there to be an additional unset/indeterminate state, and clicking the checkbox will cycle through each of the three different states.

### Current behaviour

Checkboxes can only be checked or unchecked, with no way to display if the value is unset.

### Suggested Solution

Visually the [MUI Indeterminate Checkbox](https://mui.com/components/checkboxes/#indeterminate) is what I would like, however, this is only indeterminate prior to being checked.

![image](https://user-images.githubusercontent.com/16744242/153179547-6d3e7761-2485-4467-bef6-fcb038e2d2e2.png)
In Windows you can cycle through the three states upon each click

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@clairedenning is this something we would want to include in Design System?

**Comment by clairedenning** [comment]
I have always thought this state was missing, and so I would like it included. I can add it to the backlog. I think we would also benefit from an indeterminate state when a checkbox is used to batch select or deselect a group of checkboxes. If a user ticks individual checkboxes, then the batch checkbox should neither be checked nor unchecked.

**Comment by jamime** [comment]
@clairedenning please can you provide the JIRA ticket reference.

**Comment by ingridzillinger** [comment]
Design System Jira ticket: [DSY-1480](https://jira.sage.com/browse/DSY-1480)

**Comment by jamime** [comment]
I'm leaving this open but removing the `triage` label. We'll review this once we have a detailed spec from the Design System team.

**Comment by ingridzillinger** [comment]
Although the indeterminate state is common in other design systems we recommend that we do not add it to the Sage Design System.

We should encourage designers to find more meaningful ways to illustrate to the user how many checkboxes have been selected / deselected rather than relying on an indeterminate state (which provides the user with little feedback and increases the users cognitive load).
