### ISSUE TITLE
FlatTable with colspan : missing props

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#4821]
### Current behaviour

The props :  "width"  "overflowX" "overflowY" don't exist in flat-table.d.ts

### Expected behaviour

Looking at https://carbon.sage.com/?path=/docs/flat-table--with-colspan   :
The props :  "width"  "overflowX" "overflowY" should exist in  flat-table.d.ts

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/flat-table--with-colspan 

### Carbon Version

104.12.1 

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4950

**Comment by samtjo** [comment]
Hi @hagad - thanks for raising, this will be fixed in https://github.com/Sage/carbon/pull/4868.

Just note we will add `width` and `overflowX`, but not `overflowY` - this is not a prop we want to expose to users as we currently set that based on the values of other props.
