### ISSUE TITLE
Decimal prop type validation fails if you do not supply precision prop

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#4826]
### Current behaviour

```
Warning: Failed prop type: Precision prop must be a number greater than 0 or equal to or less than 15.
```

### Expected behaviour

If the precision prop is omitted it should default to `2`.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/decimal-precision-5s6l0

### Suggested Solution

Consider patching major versions.

### Carbon Version

102.18.0, 104.15.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-4941
