### ISSUE TITLE
[Link] Carbon links perform a full page redirect

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#4827]
### Current behaviour

Thanks to #4084, links are now be correctly rendered as anchor tags when an href is provided. However, when now adding an href to a link component, a full page refresh is performed, causing the client to fetch the entire site again from the server every time the user navigates.

![firefox_lwF0g651jH](https://user-images.githubusercontent.com/16744242/153851755-75f0b478-3c51-41d9-a5d3-d7166fd6a668.gif)

### Expected behaviour

Links perform navigation in the same fashion as whichever routing library you are using and purely are there to provide carbon styling.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/muddy-cache-ji5iu?file=/src/index.js

### Suggested Solution

https://github.com/Sage/carbon/issues/4084#issuecomment-863327396

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4948

**Comment by mkrds** [comment]
@liam-cochrane 

It seems that the wanted behaviour is simply not provided out of the box by v5 version of react-router-dom (I've not checked it in v6 so maybe it works there). Library maintainers provide a solution for that case but it requires an implementation of code that would make our Link component not router agnostic thus I'm not sure if we're going to fix that issue on our side.

Please check this codesandbox - all examples + workaround are here
https://codesandbox.io/s/awesome-waterfall-r67v8t?file=/src/index.js

**Comment by liam-cochrane** [comment]
Thanks for this @mkrds. That workaround does exactly what I was looking for
