### ISSUE TITLE
ARIA attribute is not allowed: aria-expanded="false"

### ISSUE THREAD

**Issue by SageSebNegahban** [Sage/carbon#4840]
### Current behaviour

Two Select components are causing AXE errors as they have an `aria-expanded=false` param, which appears to be invalid.

### Expected behaviour

The `aria-expanded=false` param should not be present.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/young-feather-yss0t3

### JIRA Ticket (Sage Only)

RIV-636

### Suggested Solution

Remove `aria-expanded=false` from Select components

### Carbon Version

102.7.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
@SageSebNegahban According to https://www.w3.org/TR/wai-aria/#aria-expanded, `aria-expanded` is a valid attribute to use for a combobox component, which Select is. The state can be "true" or "false", so `aria-expanded="false"` is valid for Select.

**Comment by samtjo** [comment]
Thanks @sianford -can we close this issue then?
