### ISSUE TITLE
Axe violation with Drawer component

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#4849]
The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable

### Current behaviour

![Uploading Screenshot 2022-02-16 at 15.51.16.png…]()

### Expected behaviour

No Axe violation should occur.

### CodeSandbox or Storybook URL

https://5ecf782fe724630022d27d7d-yxabgfdbae.chromatic.com/?path=/story/drawer--side-view-navigation

### JIRA Ticket (Sage Only)

FE-4914

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by grabkowski** [comment]
looks like it could not be replicated in the current version of Carbon
