### ISSUE TITLE
FlatTableBodyDraggable crash when using multiple tables

### ISSUE THREAD

**Issue by mattsusans-sage** [Sage/carbon#4857]
### Current behaviour

On the linked codesandbox, when you drag the US row from the first table to the second table, the app crashes with an error :

TypeError
Cannot read properties of undefined (reading 'props')
eval
[https://fxxkoc.csb.app/node_modules/carbon-react/lib/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js:100:17]()
FlatTableBodyDraggable
[https://fxxkoc.csb.app/node_modules/carbon-react/lib/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js:99:21]()
renderWithHooks
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:14985:18]()
updateFunctionComponent
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17356:20]()
beginWork
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19063:16]()
HTMLUnknownElement.callCallback
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3945:14]()
Object.invokeGuardedCallbackDev
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3994:16]()
invokeGuardedCallback
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4056:31]()
beginWork$1
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23964:7]()
performUnitOfWork
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22776:12]()
workLoopSync
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22707:5]()
renderRootSync
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22670:7]()
performSyncWorkOnRoot
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22293:18]()
eval
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11327:26]()
unstable_runWithPriority
[https://fxxkoc.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12]()
runWithPriority$1
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10]()
flushSyncCallbackQueueImpl
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11322:9]()
flushSyncCallbackQueue
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11309:3]()
scheduleUpdateOnFiber
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21893:9]()
dispatchAction
[https://fxxkoc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16139:5]()
moveItem
[https://fxxkoc.csb.app/node_modules/carbon-react/lib/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.js:83:5]()
Object.hover
[https://fxxkoc.csb.app/node_modules/carbon-react/lib/components/flat-table/flat-table-row/__internal__/flat-table-row-draggable.component.js:57:9]()
DropTargetImpl.hover
[https://fxxkoc.csb.app/node_modules/react-dnd/dist/esm/hooks/useDrop/DropTargetImpl.js:59:14]()
eval
[https://fxxkoc.csb.app/node_modules/dnd-core/dist/esm/actions/dragDrop/hover.js:55:12]()
hoverAllTargets
[https://fxxkoc.csb.app/node_modules/dnd-core/dist/esm/actions/dragDrop/hover.js:53:13]()
DragDropManagerImpl.hover
[https://fxxkoc.csb.app/node_modules/dnd-core/dist/esm/actions/dragDrop/hover.js:20:5]()
Object.eval [as hover]
[https://fxxkoc.csb.app/node_modules/dnd-core/dist/esm/classes/DragDropManagerImpl.js:93:38]()
eval
[https://fxxkoc.csb.app/node_modules/react-dnd-html5-backend/dist/esm/HTML5BackendImpl.js:211:23]()

### Expected behaviour

The flatTableBodyDraggable does not cause a crash, the value should not actually move to the other table though.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/divine-fog-fxxkoc?file=/src/App.js

### Carbon Version

104.18.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4981
