### ISSUE TITLE
Add data-role tag to all components in the flat table folder

### ISSUE THREAD

**Issue by stephenpowers-sage** [Sage/carbon#4862]
### Desired behaviour

We require data-role tag on the components for automation tests. These were present on the old table comopenents.

### Current behaviour

There is no data-role tag on the flat-table components.

### Suggested Solution

Add the data-role tag for the flat-table components. Most of the carbon components have these but a handful does not. Could we look to add data-role tags for all components please for the reasons outlined above? 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4980
