### ISSUE TITLE
[ Search in Menu ] the divider became invisible after hover

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#4869]
### Current behaviour

**Branch:**
run: `git checkout master`
run: `git pull & npm ci`
run: `npm start`

**Steps to reproduce:**
1. Open the storybook
2. Open Menu component (white theme)
3. Hover over the Divider (bottom of the Search component)

**Actual result:**
The bottom of the Search component in Menu disappears

### Expected behaviour

The bottom of the Search component in Menu should only change it's color

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/menu--submenu-with-search

### JIRA Ticket (Sage Only)

FE-4968

### Carbon Version

104.20.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
This was fixed in https://github.com/Sage/carbon/releases/tag/v104.23.0
