### ISSUE TITLE
Color of icons in Tabs

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4875]
### Current behaviour

The color of an icon in the customLayout of a Tab is not correct

### Expected behaviour

If i use the color prop on a icon, the icon should be displayed with that color

### CodeSandbox or Storybook URL

https://codesandbox.io/s/jolly-fire-3wcfj6

### Carbon Version

104.21.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by gusch** [comment]
That style is the culprit : 
`.jyIKJy [data-component="icon"] {
    color: var(--colorsActionMinorYin065);
}`

It overrides the color props

**Comment by edleeks87** [comment]
FE-4970
