### ISSUE TITLE
Text Editor - axe violation with validation and multiline validation 

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#4877]
### Current behaviour

ARIA hidden element must not contain focusable elements
![Uploading Screenshot 2022-02-21 at 21.08.19.png…]()

### Expected behaviour

No axe violation should occur.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/text-editor--with-multiline-validation

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4978
