### ISSUE TITLE
SimpleSelect story crashes when component is clicked

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#4878]
### Current behaviour

When the `SimpleSelect` in the `default` story is clicked an error is thrown due to the `ActionLogger`.

![image](https://user-images.githubusercontent.com/44157880/155115008-714b0161-4af7-4c5a-94db-f4718179f494.png)

![simple-select-crash](https://user-images.githubusercontent.com/44157880/155115655-e9cb485f-26ca-457f-8005-720914d2f389.gif)

### Expected behaviour

Story does not crash.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select--default-story

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-4976
