### ISSUE TITLE
Tab click handler is on child element instead of parent

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#4883]
### Current behaviour

If in jest spec element clicked is button then tab is not changing. To change tab it has to be clicked span inside button.

### Expected behaviour

After clicking button tab should change.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/tabs--default-story

### Carbon Version

104.27.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

In console this doesn't work: `$$("button")[2].click()`
that works fine: `$$("button > span")[2].click()`

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
FE-5013
