### ISSUE TITLE
The placeholder property of the Select component cannot be updated

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#4894]
### Current behaviour

We can no longer update the placeholder property of the Select component.

Example: https://codesandbox.io/s/select-placeholder-0vus7w?file=/src/index.js

### Expected behaviour

To be able to modify the placeholder property of the Select component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/select-placeholder-0vus7w

### Carbon Version

104.26.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
FE-5005
