### ISSUE TITLE
Icon color in Table

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#4904]
### Current behaviour

If I give a color to an Icon in a FlatTable, the color is overwritten by 
.kubjnu [data-component="icon"] {
    color: var(--colorsActionMinor500);
}

### Expected behaviour

The Icon has the wanted color

### CodeSandbox or Storybook URL

https://codesandbox.io/s/angry-dust-tr3ci9?file=/src/index.js

### Carbon Version

104.31.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by gusch** [comment]
Same problem for a Link with an Icon in a FlatTable

**Comment by edleeks87** [comment]
FE-4997
