### ISSUE TITLE
Scrollable Tables

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#493]
We may need to support scrollable tables. Currently, we need `overflow: visible` to support Dropdowns. But if a developer choses to, they could maybe pass a prop of `scrollable={ true }` to enable a scrollable table.

**Comment by andrewjtait** [comment]
Once React Portal is introduced, we could remove overflow visible.

**Comment by paulsturgess** [comment]
I've created ticket CARBON-954 to cover this feature

**Comment by chrisbarber86** [comment]
We have road map plans to introduced more advanced tables and will cover this as part of that.
