### ISSUE TITLE
PopoverContainer Badge is outside of Button zone when specifying the mr prop for Button

### ISSUE THREAD

**Issue by ToTenMilan** [Sage/carbon#4934]
### Current behaviour

badge is outside of button zone when giving mr prop to button

### Expected behaviour

define mr prop while keeping badge within Button zone

### CodeSandbox or Storybook URL

https://codesandbox.io/s/determined-voice-brfmt?file=/src/index.js

### Carbon Version

102.18.0

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

Linux

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by grabkowski** [comment]
@harpalsingh looks like this is not a bug, as the badge is added to the edge of any component that it wraps in, but to resolve that we need to add styled-system margin props (and padding?) to the Badge component. Could you create an enhancement ticket if you are ok with that?

**Comment by jamime** [comment]
You can achieve this using the `Box` component and moving the `mr` prop.

![image](https://user-images.githubusercontent.com/2328042/161763009-c699b077-4599-4f18-beb5-4c3cfda1c919.png)

```jsx
<Box mr={3}>
  <Badge counter={1}>
    <Button
      pr={3}
      iconType={"filter_new"}
      iconPosition="after"
      {...rest}
    >
      Filter
    </Button>
  </Badge>
</Box>
```
