### ISSUE TITLE
Portrait background doesn't fill when using circle at certain zoom levels

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#4939]
### Current behaviour

At zoom levels > 50% and < 100% (not inclusive), the dark background of the `Portrait` component doesn't fill entirely if using the `shape="circle"` prop.
<img width="41" alt="Screenshot 2022-03-07 at 09 01 44" src="https://user-images.githubusercontent.com/55696743/157000914-a74c9a9d-55f5-4560-a2d7-45466cda8831.png">

### Expected behaviour

The background fill between these zoom levels should be consistent

### CodeSandbox or Storybook URL

N/A

### Carbon Version

104.48.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by grabkowski** [comment]
@DlgSHi I think that we were looking into issues with browser zoom a long time ago and we've decided that we'll be not looking for solutions to resolve them, could you confirm this?

**Comment by DlgSHi** [comment]
> @DlgSHi I think that we were looking into issues with browser zoom a long time ago and we've decided that we'll be not looking for solutions to resolve them, could you confirm this?

nope, we were discussing this issue but in iFrame context. So I think this is a legit issue

**Comment by nicktitchmarsh** [comment]
FE-5102
