### ISSUE TITLE
Dialog Full Screen - axe violation with complex example

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#4942]
### Current behaviour

Interactive controls must not be nested - Ensures interactive controls are not nested as they are not always announced by screen readers or can cause focus problems for assistive technologies

### Expected behaviour

No axe violation should occur.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/dialog-full-screen--with-complex-example

### Suggested Solution

![Uploading Screenshot 2022-03-07 at 14.27.55.png…]()

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Issue relates to focusable elements within a button element, we will need to rewrite how the Tabs component is styled to achieve the same UI layout without the focusable elements being children of the button

**Comment by grabkowski** [comment]
FE-5025
