### ISSUE TITLE
Button with Icon in FlatTable component: the icon of the buttons have the wrong color

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#4945]
### Current behaviour

With `sageTheme` theme, if we create a `FlatTable` and having a `Button with an Icon` in it, the `icon` don't have the same color than the text.

### Expected behaviour

With `sageTheme` theme, if we create a `FlatTable` and having a `Button with an Icon` in it, we expect that the `icon` have the same color than the text.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/gallant-albattani-40ulwx?file=/src/index.js

### Carbon Version

104.50.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-4997
