### ISSUE TITLE
Accessibility issues when using Pager component

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#4947]
### Current behaviour

1) When multiple Pager components are used in a single webpage, axe reports as follows:
axe issue: IDs of active elements must be unique. Ensures every id attribute value of active elements is unique.
axe link: https://dequeuniversity.com/rules/axe/4.4/duplicate-id-active?application=AxeChrome
probable cause is pager component has id="page-select"
pager code link: https://github.com/Sage/carbon/blob/d191ea10a3fe7ab8370f1e6e784cdc5e23f0e2ab/src/components/pager/pager.component.js#L141

2) When page size options are displayed within the Pager component, axe reports as follows:
axe-issue: ARIA attributes must conform to valid values
axe-link: https://dequeuniversity.com/rules/axe/4.4/aria-valid-attr-value?application=AxeChrome
probable cause is select-list component has aria-labelledby attribute to which a guid is passed that has no links to any other element on the page.
pager code link: https://github.com/Sage/carbon/blob/d191ea10a3fe7ab8370f1e6e784cdc5e23f0e2ab/src/components/pager/pager.component.js#L135
select code link: https://github.com/Sage/carbon/blob/d191ea10a3fe7ab8370f1e6e784cdc5e23f0e2ab/src/components/select/simple-select/simple-select.component.js#L59

### Expected behaviour

Pager component should not report accessibility issues described in current behaviour.

### CodeSandbox or Storybook URL

N/A

### JIRA Ticket (Sage Only)

SBS-30534

### Suggested Solution

N/A

### Carbon Version

104.7.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5040

**Comment by kishanivelupillai-sage** [comment]
> Thanks for raising these @kishanivelupillai-sage. Looking at the [page size selection options story](https://carbon.sage.com/?path=/story/pager--page-size-selection-options) with regards to the second issue, this axe violation is present in v104.7.0 like you said but not on the latest version of carbon. Please could you provide a codesandbox for your use case of `Pager` in the second issue, so we can confirm if this is fixed?

Hey @Parsium, thanks for taking a look at this.

Running axe using dev tools on storybook shows the issue for v104.7.0 but not the latest version. See storybook example: https://carbon.sage.com/v/104.7.0/index.html?path=/story/pager--page-size-selection-options

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/77396222/158413873-8e5a09c2-e689-4354-96f4-1b2420538bd3.png">

Codesandbox example, same as in storybook: https://codesandbox.io/s/pager-size-options-mwpmf3?file=/src/index.js
