### ISSUE TITLE
[DuellingPickList] accessibility warning with remove item

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#4953]
### Current behaviour

<li> elements must be contained in a <ul> or <ol> ---> List item does not have a <ul>, <ol> parent element

<img width="760" alt="Screenshot 2022-03-09 at 23 09 16" src="https://user-images.githubusercontent.com/88449494/157554677-ce82814b-7963-4e5e-8845-e832352b5add.png">

### Expected behaviour

No axe issues should occur

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/duellingpicklist--remove-item

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5038
