### ISSUE TITLE
Textarea - not possible to use both props together: `rows` and `expandable`

### ISSUE THREAD

**Issue by dawidzarzycki** [Sage/carbon#4959]
### Current behaviour

If you want to use both props togheter `rows` and `expandable` it looks like the rows is not working

### Expected behaviour

Make possibility to use both props together. For example if you need to have min hight but also you want to have expandable textarea

### CodeSandbox or Storybook URL

https://codesandbox.io/s/quizzical-maxwell-omy5or

### JIRA Ticket (Sage Only)

SBS-18429

### Carbon Version

^102.19.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5037
