### ISSUE TITLE
[Toast] Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by pbochnak** [Sage/carbon#4963]
### Current behaviour

Currently application is crashed, if we use Toast component: 
![image](https://user-images.githubusercontent.com/98875319/158184111-8e33bc76-78ed-4d86-ada9-281b4db9a047.png)
The console errors appear:
![image](https://user-images.githubusercontent.com/98875319/158184321-0e11593d-be68-4d1f-a37a-90be9b7f6cbd.png)

### Expected behaviour

The Toast component is working correctly, without crashing the app, with no console errors. 

### CodeSandbox or Storybook URL

Can't reproduce on CodeSandbox

### Carbon Version

104.53.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @pbochnak-sage, please could you share a codesandbox with us so we can replicate this issue?

**Comment by pbochnak-sage** [comment]
Unfortunately, I can't reproduce it in codesandbox, but I can show you the bug in my application. It's connected with `global` and @mkrds suggested that you should remove it from your side.

**Comment by Parsium** [comment]
FE-5042

**Comment by nicktitchmarsh** [comment]
@pbochnak-sage please could you link us to your project that causes the issue so we can replicate the error. Then we can confirm it is fixed and QA it.
