### ISSUE TITLE
GridItem - TypeScript - Type 'string' has no properties in common with type GridRowProps / GridColumnProps

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#4964]
### Current behaviour

When setting the gridRow, we receive the following TypeScript error:

`Type 'string' has no properties in common with type 'GridRowProps<Required<Theme<TLengthStyledSystem>>>'. The expected type comes from property 'gridRow' which is declared here on type 'IntrinsicAttributes & GridItemProps'`

When setting the gridColumn, we receive the following TypeScript error:

`Type 'string' has no properties in common with type 'GridColumnProps<Required<Theme<TLengthStyledSystem>>>'. The expected type comes from property 'gridColumn' which is declared here on type 'IntrinsicAttributes & GridItemProps'`

### Expected behaviour

To be able to specify start / end row & columns without TypeScript errors, eg:

```html
<GridItem gridRow="1 / 1" gridColumn="3 / 7">
```

### CodeSandbox or Storybook URL

n/a

### JIRA Ticket (Sage Only)

SBS-30910

### Carbon Version

104.53.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @johnb-sage, thanks for raising this with us. We are currently in the progress of migrating Carbon to Typescript as our components are written in Javascript. We have a ticket FE-4793 on our backlog to refactor `Grid` to Typescript, so we'll take a look at this alongside it.
