### ISSUE TITLE
Flat Table - cut outline when header is sticky, no exported types

### ISSUE THREAD

**Issue by JoannaMikul** [Sage/carbon#4968]
### Current behaviour

1. When I use hasStickyHead with clickable rows then outline for focus state is cutting.

Example: https://codesandbox.io/s/elastic-darkness-yb7ohv 
Screenshot:
![Zrzut ekranu 2022-03-15 o 14 08 04](https://user-images.githubusercontent.com/44143630/158385084-b771a2d0-5d72-4c63-9510-4b2acb55dbae.png)
 
2. For this example : https://carbon.sage.com/?path=/docs/flat-table--with-horizontal-scrolling 
Types like as `width`, `overflowX` are not exported.

### Expected behaviour

1. The thickness of the outline is visible from all sides the same.

2. All usable types should be exported.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elastic-darkness-yb7ohv

### Suggested Solution

For this variant, maybe you should use box-shadow internals.

### Carbon Version

104.53.1

### What browsers are you seeing the problem on?

Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @JoannaMikul, could you please clarify where these props are not being exported? As the declaration file for `FlatTable` does include `width` and `overflowX`, so we can take a look if there is some missing export somewhere in the directory. We'll raise a ticket for the border issue 👍🏼

**Comment by Parsium** [comment]
FE-5036 for border issue

**Comment by JoannaMikul** [comment]
@Parsium 
![Zrzut ekranu 2022-03-15 o 14 54 56](https://user-images.githubusercontent.com/44143630/158393512-b95db7fc-3aea-477f-a9e7-77b53f0c5b47.png)

**Comment by Parsium** [comment]
Thanks for this @JoannaMikul, these missing props were actually added in v104.54.0 so they should be there in the latest version of carbon 👍🏼  https://github.com/Sage/carbon/releases/tag/v104.54.0

**Comment by nicktitchmarsh** [comment]
It appears as these borders are being rendered with outline instead of border prop in order to maintain table proportions. We will investigate.
