### ISSUE TITLE
Select's Options aren't rendered correctly with children

### ISSUE THREAD

**Issue by pbochnak-sage** [Sage/carbon#4973]
### Current behaviour

If the Option has children, then the text isn't displayed, furthermore, the TS error appears: Type 'Element' is not assignable to type 'ComponentType<{}>'.

### Expected behaviour

We can pass any children to the Option component which is displayed next to the text.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/wispy-fog-psqt5m?file=/src/index.tsx

### Carbon Version

104.53.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5093

**Comment by nicktitchmarsh** [comment]
@pbochnak-sage We will change the typescript definition for children to be React Node. Text prop is used to filter and provide other functionality but we cannot automatically assume where to render it when there are other elements inside the option. For this reason we recommend composing the text into the option as well as providing the prop
