### ISSUE TITLE
FlatTable no longer displays sort indicator arrows

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#4984]
### Current behaviour

When sorting, the current FlatTable no longer shows the icons next to the header to indicate direction

### Expected behaviour

The arrows appear as appropriate

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/flat-table--with-sorting-headers

### Carbon Version

104.58.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5091
