### ISSUE TITLE
Duellingpicklist - button border is missing from top and right in canvas mode

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#4991]
### Current behaviour

Duellingpicklist - border is missing for buttons in canvas mode.

Note for Safari browser-
The yellow border doesn't appear after clicking on the button using Safari. for some button it's coming for some it's missing.

<img width="859" alt="Screenshot 2022-03-22 at 22 26 19" src="https://user-images.githubusercontent.com/88449494/159586592-ac1ccfd9-cac5-4d62-baa9-6a0bf4fb5f55.png">

### Expected behaviour

After clicking on the button border should be there for all the sides.

<img width="845" alt="Screenshot 2022-03-22 at 22 27 50" src="https://user-images.githubusercontent.com/88449494/159586731-f6cc5728-45ac-472e-8faf-53fddcc562eb.png">

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/duellingpicklist--add-item

### Carbon Version

104.58.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
This is due to the canvas HTML. We should add a general style to canvas on Storybook to add some margin to all stories in canvas
