### ISSUE TITLE
Invalid ARIA attribute value aria-activedescendant on select component

### ISSUE THREAD

**Issue by slloyd-hirst** [Sage/carbon#4995]
### Current behaviour

AXE errors are being raised due to a invalid aria attribute `aria-activedescendant` on select components.

### Expected behaviour

No invalid ARIA attributes

### CodeSandbox or Storybook URL

https://codesandbox.io/s/headless-hooks-ed7qd4?file=/src/index.tsx

### JIRA Ticket (Sage Only)

SBS-31621

### Carbon Version

104.58.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
I have tested this in the latest version of Carbon using your sandbox example. I could not replicate the error. Please could you confirm that this issue is still present if you update to the latest version of Carbon
