### ISSUE TITLE
Prop to close date control

### ISSUE THREAD

**Issue by AnushriJajoo2019** [Sage/carbon#5007]
### Desired behaviour

Need to programmatically close date control.

### Current behaviour

There is no way to close date control programmatically

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
@AnushriJajoo2019 please can you explain your use case for this? 

Feel free to contact me on Slack.

**Comment by AnushriJajoo2019** [comment]
Scenario is :

If  a supplier which is on hold, it makes an API request to check it’s status.
If supplier status is on hold a dialog appears.
But if meanwhile user tabs to next field, which is date control then on screen status dialog as well as date picker both are open.

If date control has a close prop then in such scenario it can be programmatically closed.

***@***.***


Regards,
Anushri

**Comment by samtjo** [comment]
Hi [AnushriJajoo2019](https://github.com/AnushriJajoo2019) - is the Date input inside the Dialog in this scenario? If not the user won't be able to tab from the open Dialog to the Date control, because the Dialog has a focus trap.

**Comment by nicktitchmarsh** [comment]
Hi @AnushriJajoo2019 , which version of Carbon are you using at the moment? Dialog should take the focus of the user and not allow interaction with the form behind. It would be useful to see if there is a bug with this behaviour in the latest version of Carbon
