### ISSUE TITLE
Cannot read properties of undefined (reading 'height') - Number Input

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5011]
### Current behaviour

<img width="1792" alt="Screenshot 2022-03-31 at 16 15 39" src="https://user-images.githubusercontent.com/88449494/161096061-47cd982f-5b3f-4108-af0b-b2f7950f586a.png">

### Expected behaviour

No error should occur like this, need to remove XS size as we don't support this anymore.

### CodeSandbox or Storybook URL

https://carbon.sbc-ui.com/?path=/story/number-input-test--default-story&args=size:extra-small

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
Upon investigation it looks like the `"extra-small"` just needs taking out the `options` array for `size`. This error will also likely exist in our other stories that use the `commonTextboxArgTypes()` function.

![Screenshot 2022-03-31 at 16 52 38](https://user-images.githubusercontent.com/56251247/161097486-3208e531-042b-4e1e-a56e-feb6d13e15f0.png)

**Comment by jamime** [comment]
FE-5117
