### ISSUE TITLE
Pager does not respect width of FlatTable

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#5015]
### Current behaviour

When adding a width to FlatTable - the width of the Pager can overflow which causes scrolling issues.

To reproduice easily:
We can reproduce the issue if we  use the resolution  1280/1024 , if we zoom up (150%).

### Expected behaviour

The pager should be 100% of the width of the FlatTable and not able to be scrolled.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/gracious-wind-g6eo3k?file=/src/index.js 

### JIRA Ticket (Sage Only)

SBS-28541

### Carbon Version

105.1.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
You just need to add `width="100%"` to your FlatTable here @jerlau - example using your sandbox here: https://codesandbox.io/s/festive-bose-ct5ohp
