### ISSUE TITLE
Popover container appears above dialog

### ISSUE THREAD

**Issue by ToTenMilan** [Sage/carbon#5017]
### Desired behaviour

Directly set the z-index of the popover container.

### Current behaviour

There is a scenario where the popover container is "above" the modal and its backdrop, which can also be opened on the same view. Popover container has a z-index of 2000 by default, while the modal authors gave it the z-index of 1003, and 1002 for the backdrop. Unfortunately, there is no way to directly control the z-index neither of the modal nor the Carbon's popover container, so the only way is to do a workaround like the below one to catch the popover container and hide it under the modal and backdrop
```
.myclass > div > div:nthclass(2) {
  z-index: 1001
}
```

### Suggested Solution

```javascript
<PopoverContainer
  // ...
  zIndex={1001}
>
```

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
FE-5115
