### ISSUE TITLE
ActionPopoverItem is not working correctly after click

### ISSUE THREAD

**Issue by sagedemdreisbusch** [Sage/carbon#5018]
### Current behaviour

After clicking an ActionPopoverItem it creates an error:
null is not an object (evaluating 'buttonRef.current.querySelector("[data-component='action-popover-button']").focus')

### Expected behaviour

It should execute the onClick function without triggering an error

### CodeSandbox or Storybook URL

https://codesandbox.io/s/hungry-water-9wkwci?file=/src/index.js

### JIRA Ticket (Sage Only)

OL-47691

### Suggested Solution

the data-component selector changed from action-popover-button to action-popover. Maybe this is the reason for that

### Carbon Version

105.1.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
You'll need to spread the props onto the element passed into the `renderButton` prop

https://codesandbox.io/s/inspiring-albattani-em2ss4?file=/src/index.js

**Comment by sagedemdreisbusch** [comment]
Great, that helped. Thank you @edleeks87
