### ISSUE TITLE
Dialog stick to the right edge when used on small screen

### ISSUE THREAD

**Issue by dawidzarzycki** [Sage/carbon#5020]
### Current behaviour

When we use Dialog component and we use it on a small screen then we can see that the margin is only on the left side of the dialog. The right side of Dialog stick to the right edge

![image](https://user-images.githubusercontent.com/19231884/161797620-b16a8e8b-b286-4231-81fc-d6e21abf43bb.png)

### Expected behaviour

Margin in both sides: right and left.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/admiring-beaver-jo5m0k

### Carbon Version

105.1.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
Hey @dawidzarzycki - I think at the moment we don't really support that small a screen size with a Dialog. 

@harpalsingh - what do you think we should do in this situation where the Dialog runs out of room? Should we give the users an option to make the Dialog even smaller?

**Comment by davidsmallman** [comment]
Hi @graham-blake please can you review @samtjo's questions above and advise?

**Comment by graham-blake** [comment]
@samtjo @dawidzarzycki 

Hi Sam and David, I created the dialog designs in Figma as a best guess of how a dialog should behave on smaller screen sizes. I'm not sure I understand the issue where the right side of Dialog sticks to the right edge, you should be able to be view dialogs on smaller screens with equal margins.

Dialogs are used on multiple products and how Carbon components behave on smaller screens is a much larger responsive issue that should involve the Design System. What I'm trying to say is that we need to make dialogs (and all Carbon components) responsive but that will need to be part of a wider responsive strategy and not just for one single feature.

**Comment by samtjo** [comment]
@graham-blake @davidsmallman - that's what I was getting at as well, how Dialogs work on smaller screen needs to come from UX/Design System. 

We could only "fix" this for a tiny range of viewport widths, before the viewport is just too small for the Dialog anyway, at which point something else needs to happen to the component, whether it switches to a full screen dialog, or something else - we need DS guidance on this responsive behaviour before we can do anything.

@ingridzillinger - do you know if there's any work being done on the Design System side about responsive behaviour for Dialogs?

**Comment by davidsmallman** [comment]
For additional context, here's a video demo of the current behaviour in the Give Feedback use case: https://user-images.githubusercontent.com/3584292/158998924-f86ad406-9c77-486a-8de5-ad9038ba98b0.mov

**Comment by Parsium** [comment]
Hi @dawidzarzycki, just to avoid you waiting on this, we recommend for the time being trying `DialogFullScreen` instead and see if that works for you.

**Comment by nicktitchmarsh** [comment]
DS/UX to review responsive usage on all components, this will be considered as part of that work
