### ISSUE TITLE
Focus Trap - Dialog with a select component throw act warnings

### ISSUE THREAD

**Issue by philearley** [Sage/carbon#5023]
### Current behaviour

There was an update (Unable to remember when) where we started to see act warnings in every one of our tests that interacts with a dropdown.

```javascript
  console.error
    Warning: An update to FocusTrap inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in FocusTrap (created by Dialog)
        in Transition (created by CSSTransition)
        in CSSTransition (created by Modal)
        in div (created by TransitionGroup)
        in TransitionGroup (created by Modal)
        in div (created by Context.Consumer)
        in StyledComponent (created by styled.div)
        in styled.div (created by Modal)
        in div (created by Context.Consumer)
        in StyledComponent (created by styled.div)
        in styled.div (created by Portal)
        in span (created by Portal)
        in Portal (created by Modal)
        in Modal (created by Dialog)
        in Dialog
```

I am unable to add a codesandbox link as I am not sure the right way to get jest, react testing library and carbon to work.

I have created a branch of carbon with a test that generates the issue.

https://github.com/Sage/carbon/compare/focus-trap-example

In this example, we could wrap the events in the act function, however this then fails the following eslint rule: https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-unnecessary-act.md
As this was not the original behaviour, it would be good to understand if this can be fixed internally to carbon.

### Expected behaviour

To not have console errors / act warnings in our test suite.

### CodeSandbox or Storybook URL

https://github.com/Sage/carbon/compare/focus-trap-example

### Suggested Solution

When I uncomment the following line in local node modules, the error went away: https://github.com/Sage/carbon/blob/master/src/__internal__/focus-trap/focus-trap.component.js#L53
However I suspect other issues occurred.

### Carbon Version

master

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-5128
