### ISSUE TITLE
'id' prop no longer passed down to Decimal component

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon#5035]
### Current behaviour

ID on internal <input> is just a GUID which isn't helpful for UI automation

### Expected behaviour

Would like ID to be passed down as it used to be.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/great-babbage-hftrsy?file=/src/index.js

### Carbon Version

105.1.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-5127
