### ISSUE TITLE
Storybook story containers on docs page are incorrect height on Firefox

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5037]
### Current behaviour

https://user-images.githubusercontent.com/88449494/162642608-b2b033f9-08fa-4d52-8fe5-0511260de99c.mov

### Expected behaviour

Tooltip button must be stable. it should not scroll.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/tooltip--default-story

### Carbon Version

106.0.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
This looks like a Storybook bug - the height for the story containers don't seem to be correct on the docs page. We'll investigate and see if there's anything we can do.

**Comment by samtjo** [comment]
FE-5126

**Comment by robinzigmond** [comment]
closing as this is a known Storybook issue https://github.com/storybookjs/storybook/issues/15368 - not worth the effort to put a workaround in as all is fine on other browsers and on the Canvas tab in Firefox
