### ISSUE TITLE
Multiselect add twice value when use enter keyboard

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#5044]
### Current behaviour

When i use keyboard to add a value in multiselect, it adds the value twice.
We don't have the probleme if we use mouse and click to select

### Expected behaviour

When i use keyboard to add a value in multiselect, it adds the value once, as we have when select value with mouse.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nice-worker-44iu7e?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-32481

### Carbon Version

105.1.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-5130

**Comment by samtjo** [comment]
Hi @maduv - this appears to be fixed in the latest version of Carbon, could you retest and let us know if you still see the issue please? 
Sandbox with latest version: https://codesandbox.io/s/lingering-voice-vg603o?file=/src/index.js
