### ISSUE TITLE
Textarea - found Minified React error when trying to set an object for Children

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5046]
### Current behaviour

<img width="1597" alt="Screenshot 2022-04-11 at 21 58 30" src="https://user-images.githubusercontent.com/88449494/162832341-5333dbd7-a24d-400c-92d4-6ec060804f85.png">

### Expected behaviour

This error should not occur

### CodeSandbox or Storybook URL

https://carbon.sbc-ui.com/?path=/story/textarea-test--default

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-5125
