### ISSUE TITLE
On going back two Tabs are selected

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#5059]
### Current behaviour

When going back using browser mechanism then Tabs linked with path has two Tabs selected (only when Tabs are in the Drawer component):

<img width="328" alt="image" src="https://user-images.githubusercontent.com/75613789/163328206-4bc29ee1-5f0c-4795-891b-3bf667dd7fbe.png">

### Expected behaviour

Only Tab related to active path should be highlighted.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/new-tree-moolr1

### JIRA Ticket (Sage Only)

SBS-25438

### Suggested Solution

Problem is with line 309 in src/components/tabs/tabs.component.js 

### Carbon Version

106.0.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
Hi @maspychaj-sage - we are unable to replicate this in your sandbox. Can you please provide us with some steps to be able to replicate the issue please?

**Comment by maspychaj-sage** [comment]
> Hi @maspychaj-sage - we are unable to replicate this in your sandbox. Can you please provide us with some steps to be able to replicate the issue please?

That only occurs in the app - @mkrds could you provide details?

**Comment by samtjo** [comment]
@maspychaj-sage @mkrds can one of you please provide replication steps for this? We'll close this next triage session if none have been provided, thanks

**Comment by mkrds** [comment]
@Parsium @maspychaj-sage Sorry for the delay guys, I'll take a look at it this week.
