### ISSUE TITLE
Storybook- observing a blank page for docs, some docs aren't loading

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5061]
### Current behaviour

https://user-images.githubusercontent.com/88449494/163371887-b6e4e0b8-1e3d-444b-8669-566a91a989a6.mov

![image](https://user-images.githubusercontent.com/14963680/164006876-3401a22f-818c-48c5-a616-d203bc96482e.png)

### Expected behaviour

All docs should work accordingly

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/welcome--welcome-page

### Carbon Version

106.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-5136
