### ISSUE TITLE
Hover state of navigation green for 

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#5064]
### Current behaviour

Hover state of navigation menu with drop down - should not be green when hover over, should be the grey menu

### Expected behaviour

Should be the Menu Item Three https://carbon.sage.com/?path=/docs/menu--default-story#default 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/determined-booth-zbxqr6?file=/src/index.js

### Carbon Version

106.0.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

It work fin in  105.2.0

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-5135
