### ISSUE TITLE
Form Component: When Footer is empty it still renders padding

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#5065]
### Current behaviour

When the form component uses it's own custom action buttons and does not provide a footer / default submit buttons the Footer is still added to teh DOM with a hardcoded 48px Margin

### Expected behaviour

When no footer is present in the code, no footer is rendered on the DOM.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sweet-fermi-ct40l9?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-16945

### Suggested Solution

Do not render the footer when no buttons rendered inside

### Carbon Version

106.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
Hi @PaulSumner-Sage - I think you've provided the wrong sandbox there. Could you update it with one that replicates the issue please?

**Comment by PaulSumner-Sage** [comment]
@samtjo Whoops not sure what happened there!
Recreated here: https://codesandbox.io/s/adoring-tharp-4ug9ex?file=/src/index.js:0-997

**Comment by edleeks87** [comment]
FE-5147
