### ISSUE TITLE
Textarea have different margins for character counter

### ISSUE THREAD

**Issue by dawidzarzycki** [Sage/carbon#5074]
### Current behaviour

Hey! If we use Textarea inside of the Form component we can see that the gap between textarea component and the counter is bigger than usual. Probably it is related to the fieldSpacing={3} which is already a default value for that prop.

### Expected behaviour

I expect to see the same gap between counter and textarea when use it inside or outside of the Form component

### CodeSandbox or Storybook URL

https://codesandbox.io/s/festive-hooks-m0ykde?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-18429

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5146
