### ISSUE TITLE
NavigationBar and Menu with "black" variant sets wrong background-color

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#5082]
### Current behaviour

NavigationBar and Menu with "black" variant sets background-color to `var(--colorsComponentsMenuWinterParent500)` which is transparent.

### Expected behaviour

NavigationBar and Menu with "black" variant sets background-color to black.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/black-types-on-navbar-and-menu-50sy4r

### JIRA Ticket (Sage Only)

SBS-32925

### Carbon Version

106.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
Token 

https://github.com/Sage/design-tokens/blob/909e0969f5f38b8175cfbb22e766822134700f8a/data/tokens.json#L414-L417

**Comment by johnb-sage** [comment]
Yes, you're correct. 

`var(--colorsComponentsMenuWinterParent500)` is the token used in our newBrand feature branch (carbon v106.0.0) for the `Menu` background-color. This has obviously changed for v106.0.2.
