### ISSUE TITLE
Select - dropdown list continue to exist after selecting a different story

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5087]
### Current behaviour

https://user-images.githubusercontent.com/88449494/165072600-5e4c097f-2fc2-4664-b521-a443e3291593.mov

### Expected behaviour

dropdown list should get close automatically while selecting any story.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select-filterable--default-story

### Carbon Version

106.0.3

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
This is an issue with how storybook handles transitioning between docs and canvas tabs
