### ISSUE TITLE
Dropdown issue with placeholder text with IE11

### ISSUE THREAD

**Issue by mipil** [Sage/carbon#509]
With use the property 'placeholder' with Dropdown component to display a text by default.
Under IE11, we have an issue : the first launch, we can see the placeholder text, but if we do a selection then we delete this one, the placeholder text doesn't appear anymore.

No issue with others browsers, below chrome :

![chrome_no_issue](https://cloud.githubusercontent.com/assets/17121093/15431826/dd1cae6e-1eab-11e6-8179-aa661dbae1c6.gif)

Issue with IE11 (it works on Edge) : 

![ie11_issue](https://cloud.githubusercontent.com/assets/17121093/15431827/dd1f63f2-1eab-11e6-880a-83e72c4a8b5e.gif)

This issue has been reproduced in carbon demo (master) with the modified lines below :

dropdown-filter demo.js : 

```
return (
  <DropdownFilter options={ opts } placeholder='Choose an item'  { ...FormInputHelper.demoProps(this, this.action) } />
);
```

  }

**Comment by edleeks87** [comment]
Dropdown has been deprecated in favour of Select, we believe this issue is now fixed so we are closing this
