### ISSUE TITLE
[Dialog | Toast] - possibility of focus management

### ISSUE THREAD

**Issue by dawidzarzycki** [Sage/carbon#5092]
### Desired behaviour

Hey! I'd love to have possibility to manage focus for the Dialog and Toast. When Toast appears to the screen then focus should target the Toast while Dialog is open.

### Current behaviour

For now when we use Dialog component and then Toast will appear with an error message, then we are able to close the Toast with ESC key but there is no focus on the Toast

### CodeSandbox or Storybook URL

https://codesandbox.io/s/zealous-flower-m797mw?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by samtjo** [comment]
FE-5156
