### ISSUE TITLE
Simple Selects opens the keyboard on touchscreen devices

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#5100]
### Current behaviour

When I tap on a Simple Select within the carbon documentation on a mobile or tablet, the keyboard opens. I know this is used when on a PC with a keyboard, typing will select the first option matching the key pressed, but on a mobile device this does nothing. While the select is still usable, it slows down entry considering that unlike the filterable selects, these simple selects will generally have few enough options that it should be quicker to just scroll to the one I need.

![Screenshot_20220428-162246_Chrome](https://user-images.githubusercontent.com/16744242/165788001-47f913bf-4bfb-4f76-a8ed-4fea60611c9d.jpg)

### Expected behaviour

SimpleSelects do not open the keyboard when opened on a mobile device.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select--default-story

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Android

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5155
