### ISSUE TITLE
Icon Buttons may wrap regardless of noWrap

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#5101]
### Current behaviour

Button currently sets `flex-flow: wrap` which permits an icon to wrap under some circumstances regardless of `noWrap`. While `noWrap` only prevents button labels from wrapping, this might not be the expected behaviour by users.

### Expected behaviour

Button prevents icons from wrapping when `noWrap` is specified.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/flex-wrap-button-p6fgu8?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-33451

### Carbon Version

106.1.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5154
