### ISSUE TITLE
Decimal: doesn't reliably display its props.value

### ISSUE THREAD

**Issue by clintpeddie** [Sage/carbon#5103]
### Current behaviour

If onchange handler changes the value passed back to the control, it seems to ignore it.

Typically we will truncate the number of characters after the decimal point, any subsequent characters being suppressed.
This used to work on Carbon 95.1, but not on 106.0
In Sandbox: I've mimicked behaviour: 
Type 22.22222 into the decimal. We are overriding value to remain at 22.22, but control displays the longer string, and stays that way when tabbing out.
On Carbon 95.1, it seems to toggle between 22.22 and 22.222, but would always revert to 22.22 on tabbing out.

But not an issue when setting value programmatically. 
Clicking button on sandbox does work.

### Expected behaviour

The decimal control would display the value being passed into its props.value

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pensive-easley-tz9lsf

### Carbon Version

106.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
Thanks for the report, I think this likely is a defect however we'd also recommend using validations instead of manipulating the user input. 

We changed that behaviour in [this PR](https://github.com/Sage/carbon/pull/3732) to fix an issue with "dead keys" and after receiving some accessibility guidance.

**Comment by Parsium** [comment]
FE-5153
