### ISSUE TITLE
ProgressTracker does not fit container

### ISSUE THREAD

**Issue by YariMVSage** [Sage/carbon#5106]
### Current behaviour

ProgressTracker component has got a default width of 256px.
When adding ProgressTracker in dialogs it is not possible to adapt the width to the Dialog and it looks weird

### Expected behaviour

I would like to be able to set the ProgressTracker width or even better, adapt the component width automatically by itself

### CodeSandbox or Storybook URL

https://codesandbox.io/s/kind-beaver-fo1irq?file=/src/index.js

### Carbon Version

102.2.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5152
