### ISSUE TITLE
FilterableSelect in a Box with display flex doesn't open correctly

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#5109]
### Current behaviour

If I have a filterable select in box with display="flex", the style breaks when i try to open the select.

### Expected behaviour

The style should be correct

### CodeSandbox or Storybook URL

https://codesandbox.io/s/silly-varahamihira-xn2ucv?file=/src/index.js

### Carbon Version

106.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5164
