### ISSUE TITLE
Ability to set Help Icon colour on heading component

### ISSUE THREAD

**Issue by stephenpowers-sage** [Sage/carbon#5110]
### Desired behaviour

We would like to be able to set the colour of the help icon on the heading component. We currently use a custom component for headers in order for us to have a green icon. This was done following feedback on accessibility.

### Current behaviour

The icon color is hardcoded on the header component to be the same colour as the text. Currently --colorsActionMinor500.colour

### Suggested Solution

Add property to allow us to set the icon colour. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
@harpalsingh @clairedenning is this something we should consider?

**Comment by clairedenning** [comment]
Please can you share a screengrab so that I can see exactly what you're asking about?

**Comment by clairedenning** [comment]
Presumably hovering/clicking on the icon spawns a tooltip? This is not behaviour that we recommend in the DS. Icon-only "buttons" are not accessible. 

General guidance for icon colour is that it's yin.060 when shown inline with text, just for information. If it is actionable it should be action.minor.500 or action.major.500

**Comment by stephenpowers-sage** [comment]
Yes, custom it has a hover tooltip and the action when clicked to be taken to a help page. I can confirm the colour of the icon in the Carbon header is hardcoded to Yin065. Carbon also has a hover tooltip which is a blue tint

**Comment by edleeks87** [comment]
Whilst we're waiting for a steer from DS about whether we want to surface this level of configurability, you can compose the `Heading` `title` to achieve a similar layout if you wanted

https://codesandbox.io/s/withered-wave-qjdhqr?file=/src/index.js

**Comment by v99rly** [comment]
Yes we need to avoid using icon only. Every icon should have appropriate and meaningful label.

**Comment by Parsium** [comment]
Hi @stephenpowers-sage, please could you confirm if the workaround @edleeks87 suggested helped with your issue? If so, we can close this issue and let the Design System team discuss this further
