### ISSUE TITLE
Close MultiActionButton and SplitButton onClick

### ISSUE THREAD

**Issue by liam-cochrane** [Sage/carbon#5113]
### Current behaviour

Currently, you can hover over a Multi-Action or Split Button for it to open, which will then be closed again once you are no longer hovering. This works fine on a device where I have a mouse. But if I am using a touchscreen device, I tap an option on the MultiActionButton, and it does not close until I tap somewhere else on the screen, because it doesn't realise I am no longer hovered over the button.

This becomes a problem when I have a MultiActionButton to open a dialog, and the dialog opens with the contents of the MultiActionButton still overlaid.

### Expected behaviour

Having the option to either hover or click on the button to open it as it does currently is fine. But for the Button to close I should be able to either end the hover, or click on one of the options within.

### CodeSandbox or Storybook URL

https://carbon.sage.com/index.html?path=/docs/multi-action-button--default-story

### Suggested Solution

[Bootstrap Dropdown Button](https://getbootstrap.com/docs/5.1/components/dropdowns/#single-button) and [MUI Split Button](https://mui.com/material-ui/react-button-group/#split-button) both are closed when an option is clicked.

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

Android

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Will be fixed as part of FE-4887
