### ISSUE TITLE
DialogFullScreen component - mandatory contentRef prop should be optional for typescript

### ISSUE THREAD

**Issue by kairynners** [Sage/carbon#5121]
### Current behaviour

Currently when using the DialogFullScreen component with Typescript the `contentRef` prop is required and must be specified. 
If it isn't needed, the only way to currently get around it is to include a ts-ignore statement which isn't ideal.

### Expected behaviour

The `contentRef` prop on the DialogFullScreen component should be optional. This would then allow consumers to use is like they would if they were not working with Typescript.

### CodeSandbox or Storybook URL

https://carbon.sage.com/iframe.html?id=dialog-full-screen--default-story&viewMode=docs#props

### Carbon Version

105.2.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

Discussed on Slack.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5162
