### ISSUE TITLE
Add disabled prop to the Option component

### ISSUE THREAD

**Issue by psaumell** [Sage/carbon#5123]
### Desired behaviour

The current Select and MultiSelect components can be disabled entirely but you can't disable only an internal Option.
For our purpose we need a MultiSelect component with the ability to disable an Option and also disable an Option that can be selected programatically.

### Current behaviour

The component Option doesn't admit a disabled prop

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
@harpalsingh is this something we should consider?

**Comment by Parsium** [comment]
FE-5165
