### ISSUE TITLE
LinkProps not exported from link module

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#5132]
### Current behaviour

LinkProps interface is only exported from `src/components/link/link.component`.

### Expected behaviour

LinkProps interface to be re-exported from `src/components/link/index.ts`.

### CodeSandbox or Storybook URL

n/a

### JIRA Ticket (Sage Only)

SBS-33933

### Carbon Version

106.2.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5167
