### ISSUE TITLE
FlatTable header alternative color not changing according theme 

### ISSUE THREAD

**Issue by ibsenjg** [Sage/carbon#5136]
### Current behaviour

Hi,

The Flat Table component has the ability to change their base colors with the colorTheme property, also the FlatTableHeader alternativeBgColor should be affected by this change and match the theme.

### Expected behaviour

the FlatTableHeader alternativeBgColor should be affected by the colorTheme change and match the theme colors

### CodeSandbox or Storybook URL

https://codesandbox.io/s/modest-shaw-n4hxlv

### Carbon Version

106.2.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
@harpalsingh we discussed removing the `alternativeBgColor` prop from the child components of `FlatTable` and just have `FlatTable` control the colours. Is there are requirement in DS to have finer control over the colours of the individual headers?

**Comment by harpalsingh** [comment]
It seems we did not provide the correct value for the Light header variant, so will provide that using the same logic as dark header. @Parsium will discuss that with you, we allow body cells to override background color of a cell as neeeded, I think with need to keep it more restricted with headers though. I think we can fix this bug and then further explore with DS team.

**Comment by Parsium** [comment]
The linked PR seems to have fixed this issue, will close as completed 👍🏼
