### ISSUE TITLE
PopoverContainer always opens to the right side

### ISSUE THREAD

**Issue by kb-sage** [Sage/carbon#5141]
### Current behaviour

Component is opened in a way that extending size of the page

### Expected behaviour

Component should be opened in a way which **does not** extend size of the page

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sharp-pike-yqjteo

### JIRA Ticket (Sage Only)

SBS-33426

### Carbon Version

106.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5175
