### ISSUE TITLE
[PopoverContainer ] Differences between PopoverContainer component and types 

### ISSUE THREAD

**Issue by michalgarnczarski** [Sage/carbon#5152]
### Current behaviour

In PopoverContainer  props `renderOpenComponent` and `renderCloseComponent` expected `PopoverContainerProps.renderCloseComponent?: React.ReactNode | Node` as prop type.  With caused type error and forced to cast to any. 

### Expected behaviour

To be consisted with [story book description](https://carbon.sage.com/?path=/docs/popover-container--default-story) and [implementation](https://github.com/Sage/carbon/blob/c8d70201dc19e5bb27395686e66ddc6b81fc3379/src/components/popover-container/popover-container.component.js#L69) this should be a render props function. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/hungry-cloud-3opd74?file=/src/index.tsx

### JIRA Ticket (Sage Only)

SBS-33979

### Suggested Solution

Based on [implementatnion](https://github.com/Sage/carbon/blob/c8d70201dc19e5bb27395686e66ddc6b81fc3379/src/components/popover-container/popover-container.component.js#L69) create correct interface in [types file](https://github.com/Sage/carbon/blob/c8d70201dc19e5bb27395686e66ddc6b81fc3379/src/components/popover-container/popover-container.d.ts#L6), same to `renderCloseComponentProps` prop. 

### Carbon Version

106.3.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5172
