### ISSUE TITLE
[Heading] Type error, render function return Object not a JSX.Element 

### ISSUE THREAD

**Issue by michalgarnczarski** [Sage/carbon#5154]
### Current behaviour

When I try using `<Heading>` component in TypeScript project I got type error 
```log
 'Heading' cannot be used as a JSX component.
  Its instance type 'Heading' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'Object' is not assignable to type 'ReactNode'.
        The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?ts(2786)
```
Its caused by wrong type declaration like below: 
```
  /**
   * @method render
   * @return {Object} JSX
   */
  render() {
```

```    
/**
     * @method render
     * @return {Object} JSX
     */
    render(): Object;
```

### Expected behaviour

Type of render function should be `JSX.Element` 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/determined-water-osdg55?file=/src/index.tsx   not able to reproduce type

### JIRA Ticket (Sage Only)

SBS-33979

### Suggested Solution

Fix render function return type to `JSX.Element` 

### Carbon Version

106.4.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows, Linux

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5170
