### ISSUE TITLE
PopoverContainer overlay Sidebar when we open Sidebar when PopoverContainer is still opened

### ISSUE THREAD

**Issue by wkustrzykSage** [Sage/carbon#5158]
### Current behaviour

When the user opens `PopoverContainer` first and then opens `Sidebar` while `PopoverContainer` is still opened causing a problem that `PopoverContainer` overlaying the `Sidebar`

### Expected behaviour

PopoverContainer should be close when the user clicks outside the container.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/bold-andras-iz70fc?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-33782

### Suggested Solution

PopoverContaner should be close when the user clicks outside the container, to avoid similar problems in future

### Carbon Version

106.0.1

### Design Tokens Version

2.21.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5184
