### ISSUE TITLE
Previous pagination link doesn't meet contrast requirements

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#5170]
### Current behaviour

According to wcag contrast checker previous link has 2.1 contrast which is not enough:

![image](https://user-images.githubusercontent.com/75613789/170042413-b7aa4207-1c93-492e-a491-e7880526a4dd.png)

### Expected behaviour

Contrast should at least 2.65.

### CodeSandbox or Storybook URL

https://carbon.sage.com/iframe.html?id=flat-table--paginated&args=&viewMode=story

### JIRA Ticket (Sage Only)

SBS-33960

### Carbon Version

106.6.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mboo** [comment]
Any news on this one?

**Comment by nicktitchmarsh** [comment]
@ljemmo Looks like another instance where we should check which token is being applied to the Pagination here.

**Comment by ljemmo** [comment]
@nicktitchmarsh this is a bigger piece of work that needs addressing across all our disabled states on buttons, links etc. Something that we are aware of. I think you can close this issue as once we update the disabled text token on our end, you will automatically get the new accessible colour in pagination.

@ingridzillinger FYI.

**Comment by clairedenning** [comment]
Hi, disabled states do NOT have to have that level of colour contrast. The guidance is to avoid using disabled states when possible. In my opinion, if we start to increase the contrast on disabled components to make them visually accessible, they will actually look enabled, which I'm sure is not the desired outcome :)

**Comment by edleeks87** [comment]
Based on @clairedenning's comment we are going to close this issue
