### ISSUE TITLE
[FlatTableHeader] - Border and background color are the same

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#5175]
### Current behaviour

Steps to reproduce:

1. Compose a `FlatTable` with the prop `colorTheme="light"`
2. Add at least two header rows
3. Apply  `colspan` attribute to `FlatTableHeader`component

See:
![image](https://user-images.githubusercontent.com/11317965/170284160-d83aa5f4-f23f-46aa-b7c1-45edf9e4b0d1.png)

### Expected behaviour

The border between the header cells can be distinguished by having a different color.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/adoring-poitras-k3frj4?file=/src/index.js

### Suggested Solution

The horizontal border between the header rows is a different color than the background.

### Carbon Version

106.6.6

### Design Tokens Version

2.25.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5198
