### ISSUE TITLE
Wrong capitalization in months in Spanish

### ISSUE THREAD

**Issue by BertaLarre** [Sage/carbon#5181]
### Desired behaviour

The following date component used in the Spanish version of Sage Intacct Manufacturing should have the initial letters of the months capitalized. 

### Current behaviour

Currently, the months start with lowercase:
<img width="118" alt="Wrong initial capitalization in Spanish" src="https://user-images.githubusercontent.com/36276659/170672583-c116a283-80b2-4f80-9ff6-94f0ace58238.PNG">

### Suggested Solution

In Spanish we should say “Abril 2022” but “3 de abril de 2022” (depending on the use case).

Where is the content in Spanish coming from?  This component should be updated so that months start with capital letters in Spanish.

Please reach out to me if you need further clarification: berta.larre@sage.com.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
[This](https://github.com/Sage/carbon/blob/8d8ab92399874fe0f696811bcd877942eb470c1a/src/components/date/__internal__/date-picker/date-picker.component.js#L29) comes from the built in locales supplied by `date-fns` so it's weird that some are capitalised whilst others aren't.

I don't think they're likely to fix this anytime soon but we can fix it by either updating the function or via CSS:

- CSS:
```
.DayPicker-Caption {
    display: table-caption;
    height: 1.5rem;
    text-align: center;

    > div::first-letter {
      text-transform: capitalize;
    }
  }
  ```

- JS:
```
const monthsLong = Array.from({ length: 12 }).map((_, i) => {
      const month = localize.month(i);

      return month[0].toUpperCase() + month.slice(1);
    });
```


![image](https://user-images.githubusercontent.com/44157880/171158923-aa8ef397-8e3d-4552-ba4c-3714dd3103c4.png)

**Comment by Parsium** [comment]
FE-5197
