### ISSUE TITLE
[Help] tooltip exists after changing to docs from canvas page

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5183]
### Current behaviour

<img width="723" alt="Screenshot 2022-05-27 at 12 21 04" src="https://user-images.githubusercontent.com/88449494/170691005-3f0a940c-385f-413b-ad49-5be1f487dfd8.png">

### Expected behaviour

Tooltip should not exist after changing to docs from canvas page.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/help--with-tooltip-color-overrides

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
closing as it is a known issue to do with storybook not re-rendering when switching between docs and canvas tabs 

duplicates #5016
