### ISSUE TITLE
Hide the content inside the bounds of the multi-select component

### ISSUE THREAD

**Issue by anuarbolatov** [Sage/carbon#5192]
### Current behaviour

The pill with long text overlaps the dropdown icon and extends outside the bounds of the box of the multi-select component.

### Expected behaviour

The part of the pill with long text extending outside the multi-select component's boundaries should be cropped/hidden.
The dropdown icon should float above the content.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select-multiselect--default-story

### Suggested Solution

Add truncation if the text exceeds the maximum amount of allowed characters.

### Carbon Version

77.13.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Anything else we should know?
![image](https://user-images.githubusercontent.com/44157880/172131462-0583d499-add4-4852-ac70-69a755249e72.png)

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5207

**Comment by harpalsingh** [comment]
@DipperTheDan As suggested we should wrap into an ellipsis (most of the code exists to do this but its missing a few specific fixes), but I would also be useful to allow a none-ellipsis version if needed.

![Screenshot 2022-06-08 at 13 12 42](https://user-images.githubusercontent.com/2411024/172613462-2d14603e-069f-4aa7-a669-3a1f94b9b5b6.png)

![Screenshot 2022-06-08 at 13 13 05](https://user-images.githubusercontent.com/2411024/172613487-9674f223-bdcb-4673-91fa-6c69b98db2c5.png)
