### ISSUE TITLE
Type declaration missing

### ISSUE THREAD

**Issue by clbor** [Sage/carbon#5206]
### Current behaviour

I face of some issues with the Carbon release 106.6.7 (106.6.6 is fine)
When I run the npm run lint command to check the eslint rules, several similar errors for different components are returned.

For example:
```
error TS7016: Could not find a declaration file for module 'carbon-react/lib/components/box'. '/home/clbor/sbc.accountants.clientmanagement.ui/node_modules/carbon-react/lib/components/box/index.js' implicitly has an 'any' type.
```

Below all the concerned components with the same kind of error, maybe there are others...

```
carbon-react/lib/components/box
carbon-react/lib/components/button
carbon-react/lib/components/link
carbon-react/lib/components/hr
carbon-react/lib/components/badge
carbon-react/lib/components/action-popover
carbon-react/lib/style/themes
carbon-react/lib/components/carbon-provider
carbon-react/lib/components/link/link.component
carbon-react/lib/components/alert
carbon-react/lib/components/navigation-bar
carbon-react/lib/components/button/button.component
```

### Expected behaviour

No error raised by lint

### CodeSandbox or Storybook URL

No code sandbox

### Carbon Version

106.6.7

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5204
