### ISSUE TITLE
Sticky column with wrapper component is not working properly 

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#5208]
### Current behaviour

When we use custom wrapper components for the cells the sticky functionality is not working properly and we always have 1 column sticky even there are more cols before

![image](https://user-images.githubusercontent.com/84023810/172572353-46c3c11a-3890-414b-945b-73d2d433863b.png)

### Expected behaviour

Should work as here: https://carbon.sage.com/?path=/docs/flat-table--with-custom-horizontal-border-color#with-row-headers

![image](https://user-images.githubusercontent.com/84023810/172572388-1f0f3edd-50d8-4ffc-a3fd-9cca757b274f.png)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/quirky-satoshi-rtge9t?file=/src/index.js

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5208
