### ISSUE TITLE
Cannot remove default padding from sidebar

### ISSUE THREAD

**Issue by WojciechMichalowski** [Sage/carbon#5210]
### Current behaviour

sidebar have default padding

![Zrzut ekranu 2022-06-8 o 13 26 26](https://user-images.githubusercontent.com/102224763/172605699-04455e2d-5f2e-49b1-9bae-7047ca826be3.png)

### Expected behaviour

padding should be configured

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/sidebar--default-story

### Carbon Version

77.13.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
duplicates #4494
