### ISSUE TITLE
Filterable Select- scroll dissapear when select dropdown opened

### ISSUE THREAD

**Issue by wkustrzykSage** [Sage/carbon#5216]
### Current behaviour

When User clicks on filterable select and options list reveals then page scroll disappears, and the property `overflow: hidden` is added to the `body` tag 

### Expected behaviour

When user open Select list, scroll on main page should not dissapear

### CodeSandbox or Storybook URL

https://codesandbox.io/s/clever-sinoussi-g6p0j8?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-35948

### Carbon Version

106.4.1

### Design Tokens Version

2.25.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Hi @wkustrzykSage this is the intended behaviour, scroll is blocked when a select is open. Is this behaviour something that is causing you issues?

https://github.com/Sage/carbon/pull/4461

**Comment by mkrds** [comment]
@tempertemper @harpalsingh  Hey guys what do you think about it? Maybe we should leave an option to enable the scroll if someone really wants it to be working?

**Comment by wkustrzykSage** [comment]
Issue closed because it's desired behaviour of Filterable select component
