### ISSUE TITLE
Change background color for FlatTableCell

### ISSUE THREAD

**Issue by WojciechMichalowski** [Sage/carbon#5219]
### Desired behaviour

FlatTableCell should have prop background-color

### Current behaviour

FlatTableCell don't have prop background-color

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Your designers should be creating designs inline with what the Design System shows as usage for the FlatTable component. Looking at the screenshot from the attached PR, the subRows being rendered are not currently possible without using the expandable row pattern. If this is required your designer should consult with DS to see if this should be a standard pattern across Sage products

**Comment by edleeks87** [comment]
@ljemmo any thoughts

**Comment by ljemmo** [comment]
So we deliberately suggested the gray colour for child rows within a table accordion. This was to make the child rows have the affordance that these gray rows were 'underneath' the parent row.

Based on the[ screenshot here ](https://github.com/Sage/sbc.accounting.accounts.ui/pull/141) i'm unsure if we would want to support this from a DS perspective. @WojciechMichalowski  please can you get your designer to reach out to us and explain the rationale so we can review properly.

**Comment by nicktitchmarsh** [comment]
I'm going to close this issue, it can be reopened if there are any recommendations from DS regarding this
