### ISSUE TITLE
[Modal] - Right padding is added for no reason

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#5220]
### Current behaviour

Given a page with scrollbar
When navigating to a page without scrollbar
And open a `Sidebar`
Then right padding is added to the `<body>` HTML tag

### Expected behaviour

Given a page with scrollbar
When navigating to a page without scrollbar
And open a `Sidebar`
Then no right padding is added to the `<body>` HTML tag

### CodeSandbox or Storybook URL

https://codesandbox.io/s/epic-elbakyan-06zsuw?file=/src/index.js

### Carbon Version

106.7.0

### Design Tokens Version

2.30.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

In General settings, scrollbar should be always enabled.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5216
