### ISSUE TITLE
Disable selected options of Multi Select component 

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#5223]
### Current behaviour

Selected options of the list are not disabled

### Expected behaviour

Set a disabled look and feel for the selected items on the list

<img width="286" alt="image" src="https://user-images.githubusercontent.com/84023810/173375905-c988c4c9-e0f4-4780-8f3c-bea9570be396.png">

### CodeSandbox or Storybook URL

https://codesandbox.io/s/great-glitter-4l9ph3?file=/src/index.js

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
This looks like a duplicate of https://github.com/Sage/carbon/issues/5123 
We can take a look in this weeks triage.

**Comment by nicktitchmarsh** [comment]
Closed as duplicate
