### ISSUE TITLE
Loader in destructive version of confirm is not correct

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#5226]
### Current behaviour

Loader is barely visible in destructive version of the confirm.
![image](https://user-images.githubusercontent.com/75613789/173504056-872307db-1a4b-46dc-97d8-998fd1fb790a.png)

### Expected behaviour

It should be visible as in the destructive button with `isInsideButton` prop:
![image](https://user-images.githubusercontent.com/75613789/173504232-5548041d-ec18-4c6a-b3f1-6c5a01bd3366.png)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/zen-davinci-bhj756

### JIRA Ticket (Sage Only)

SBS-36145

### Suggested Solution

Loader should have `isInsideButton` prop in the destructive version of the confirm.

### Carbon Version

107.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5215
