### ISSUE TITLE
InputWidth is not working in Textbox for "carbon-react": "106.6.5", 

### ISSUE THREAD

**Issue by jayingale5727** [Sage/carbon#5234]
### Current behaviour

Hi Team,

The inputwidth property is not supported in "carbon-react": "106.6.5" when using the new validation.

### Expected behaviour

The Width of Textbox should be change with inputWidth property when using the new validation.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/withered-sun-vglx64?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-33224

### Carbon Version

106.6.5

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
Hi @harpalsingh, I don't think we had a requirement for this previously but we have a team asking for the new validation message to be 100% width of a Form but have the input width a different size. Do you know if this is something coming in the near future or will it be new designs?

**Comment by ljemmo** [comment]
@DipperTheDan I've seen a few requests for this. It would be a variation/prop needed where can specify a fixed width override on the input field only where. By default though, the field width should be 100% the width of the wrapper that contains the label, hint text and error message. 

See attached a similar solution that i've just added for date picker in our figma library.
https://user-images.githubusercontent.com/98600534/176719964-11d239ef-b22d-45a0-8ce2-f6c066e597d4.mov

On our end, i'll add a ticket for us to add to our figma library. However, does this unblock you for now?

**Comment by Parsium** [comment]
Awesome thanks for the update @ljemmo, we'll create a ticket for this on our backlog? Please could share the DSY ticket number for your work so we can link it?
