### ISSUE TITLE
Add error prop to the Search component

### ISSUE THREAD

**Issue by harsh096** [Sage/carbon#5236]
### Desired behaviour

We have a requirement to show error on `Search` component (Image attached) when user tries to search with less than 2 characters.

![image](https://user-images.githubusercontent.com/28267834/174071307-4bb78361-c4e6-4cf9-b94a-36a5d35ed58d.png)

### Current behaviour

Seems like there are no error props for Search component as of now like we have for [Textbox](https://carbon.sage.com/?path=/docs/textbox--validations-string-new-design) and [Multiselect](https://carbon.sage.com/?path=/docs/select-multiselect--validations-string-new-design) which lets us add custom error text and also turns border to red color.

### Anything else we should know?

Desired functionality is implemented already for [Textbox](https://carbon.sage.com/?path=/docs/textbox--validations-string-new-design) and [Multiselect](https://carbon.sage.com/?path=/docs/select-multiselect--validations-string-new-design) components which lets us add custom error text and also turns border to red color.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@ljemmo are DS ok with us enabling the textbox error styling on search?

**Comment by ljemmo** [comment]
@nicktitchmarsh Yes, happy for you to enable this. Can we make sure that the red error border is visible on to the left of the green search button though?

Also, can we make sure this error doesn't appear after 1 key press. Rather it should appear after enter is hit or the green button is selected.

**Comment by nicktitchmarsh** [comment]
FE-5292

@ljemmo we would supply the props for consuming apps to control. How the validation is triggered is down to implementing teams
