### ISSUE TITLE
CheckboxGroup component - groupName prop doesn't work

### ISSUE THREAD

**Issue by DianeGit22** [Sage/carbon#5247]
### Current behaviour

In Storybook the CheckboxGroup component has a groupName prop which specifies the name prop to be applied to each checkbox in the group.

Currently the groupName prop has no effect on the checkbox names so it is not working. However Robin did raise the point that there is little sense in having a groupName prop for checkboxGroup as all checkboxes can be checked/unchecked independently.  So perhaps it would be better to remove the prop rather than fix it?  

### Expected behaviour

Either fix the issue so that the groupName prop applies the name to all checkboxes in the checkboxGroup or remove support for the groupName prop for this component. 

### CodeSandbox or Storybook URL

https://carbon.sbc-ui.com/?path=/docs/checkbox--checkbox-group

### Carbon Version

107.1.7

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-5223
