### ISSUE TITLE
Controlled Multiselect not working as expected in Carbon v106.6.5

### ISSUE THREAD

**Issue by harsh096** [Sage/carbon#5259]
### Current behaviour

I was trying to use `Multiselect ` component and had a requirement of limiting the number pills that can be selected to 10.
So for this, I used `controlled Multiselect`
But seems like its not behaving as it should....with `v106.6.5` it is allowing to select more number of pills than the condition I applied even when the state variable which is mapped to value prop of Multiselect does not gets updated with more data than applied condition, but still the component displays all of the selected pills in UI irrespective of the condition.
[Sandbox](https://codesandbox.io/s/multi-select-demo-forked-om3joo?file=/src/MultiSelectDemo.jsx)

### Expected behaviour

It should not allow to select more number of pills than the condition applied on the state variable which is mapped to value prop of Multiselect.
[Sandbox](https://codesandbox.io/s/multi-select-demo-carbonv76-1-3-forked-6skzl4?file=/src/index.js)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/multi-select-demo-forked-om3joo?file=/src/MultiSelectDemo.jsx

### Carbon Version

106.6.5

### Design Tokens Version

2.25.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

Working as expected in lower versions of Carbon.
Sandbox for v76.1.3 attached in expected behavior.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5228

**Comment by nicktitchmarsh** [comment]
We have a ticket to implement disabling of select Options FE-5165, this could then be set to disable all options when you reach your limit of selected pills. We will also be actioning an RFC that is due to remove the support for uncontrolled components, this would also solve this issue but will not be done for quite some time. We will aim to implement FE-5165 in the mean time that would provide an interim solution.
