### ISSUE TITLE
Filterable select : align columns in multiple columns

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#5263]
### Current behaviour

In a filterable select with multiple columns, the header and the body are not aligned

![image](https://user-images.githubusercontent.com/16415182/176397394-cd8a8f4b-82a9-4022-9004-43d56499ab24.png)

### Expected behaviour

The columns must be aligned

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select-filterable--with-multiple-columns

### Carbon Version

108.0.0 (version used on carbon.sage.com at time of raising issue)

### Design Tokens Version

2.24.0 (version used on carbon.sage.com at time of raising issue)

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5238
