### ISSUE TITLE
Badge - counter is not visible in canvas mode

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5265]
### Current behaviour

<img width="799" alt="Screenshot 2022-06-29 at 12 26 50" src="https://user-images.githubusercontent.com/88449494/176426142-860c0492-4d9e-4739-9b0a-2aa9e7a0275a.png">

### Expected behaviour

Badge counter should be visible 

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/badge--with-3-digits&globals=theme:mint

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5231
