### ISSUE TITLE
Item with submenu doesn't fire onClick

### ISSUE THREAD

**Issue by maspychaj-sage** [Sage/carbon#5270]
### Current behaviour

OnClick on menu item is not fired when submenu prop exists. Try to click transactions item and check console.

### Expected behaviour

OnClick on menu item is should be fired always.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/condescending-pond-ebt2gb

### Carbon Version

108.0.0

### What browsers are you seeing the problem on?

Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Duplicated by #5313 and fixed by https://github.com/Sage/carbon/pull/5315
