### ISSUE TITLE
[Button] Page is getting stuck for button test component and observing lots of icons

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5273]
### Current behaviour

Steps to reproduce:

1) go to VS code
2) checkout master
3) run npm start
4) it will navigated to the http://localhost:9001
5) go to button component and select test 
6) try to click on default story after that click on next one
7) the page will get stuck

![Screenshot 2022-06-30 at 11 04 33](https://user-images.githubusercontent.com/88449494/176651926-70aed6c4-8b8c-450f-b2c7-c8dd987b0918.png)

### Expected behaviour

Page should work accordingly.

### CodeSandbox or Storybook URL

http://localhost:9001/?path=/docs/button-test--primary-buttons-icons-before

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5229
