### ISSUE TITLE
[Button] observing a layout issue - button bottom focus is invisible after minimising the story book page

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5274]
### Current behaviour

Steps to reproduce:
1) go to https://carbon.sage.com
2) select button component
3) select primary/icon in canvas mode
4) minimise the storybook page
<img width="642" alt="Screenshot 2022-06-30 at 11 27 52" src="https://user-images.githubusercontent.com/88449494/176655598-19b61380-6c37-4c3d-b503-6ea7340a4da6.png">

Uploading Screen Recording 2022-06-30 at 11.22.37.mov…

### Expected behaviour

Button focus should be visible, add m={2} to each button.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/button--primary-icon

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5231
