### ISSUE TITLE
[FlatTable] console error found in expandable--truncated-cell-content

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#5276]
### Current behaviour

![Screenshot 2022-06-30 at 13 05 36](https://user-images.githubusercontent.com/88449494/176676299-25d6fec9-286e-405c-a26c-6f0d46e52992.png)

### Expected behaviour

No console error should occur.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/flat-table-expandable--truncated-cell-content

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5231
