### ISSUE TITLE
Focus not displayed in full screen dialog

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#5278]
### Current behaviour

When you have lots of fields in your form in a dialog full screen, you don't see what is focus when using tab key on firefox. It's working better on chrome as focus component is displayed upper.

### Expected behaviour

See focused component when use tab key on firefox

### CodeSandbox or Storybook URL

https://codesandbox.io/s/serene-swanson-cchn5d?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-37114

### Carbon Version

108.0.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5236
