### ISSUE TITLE
Types: Button forwardRef prop missing React.RefObject<HTMLButtonElement> type

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#5280]
### Current behaviour

When forwarding an immutable ref to Button's forwardRef prop, defined as
```Typescript
    const myRef = useRef<HTMLButtonElement>(null);
```
the following error is logged in the console:

``Warning: Failed prop type: Invalid prop `forwardRef` supplied to `Button`, expected one of type [function].``

defined here: https://github.com/Sage/carbon/blob/master/src/components/button/button.component.tsx#L38..L41

### Expected behaviour

Passing an immutable ref to Button's forwardRed prop does not result in a type error.

### CodeSandbox or Storybook URL

n/a

### Suggested Solution

Add `React.RefObject<HTMLButtonElement>` to the union type and possibly remove `React.MutableRefObject<HTMLButtonElement | null>` as mutable refs shouldn't need be used for DOM manipulation.

### Carbon Version

109.1.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @johnb-sage, we are aware about this issue and it is currently in review #5266

**Comment by johnb-sage** [comment]
Thanks @Parsium.

**Comment by Parsium** [comment]
Duplicate issue of #5246
