### ISSUE TITLE
Focus issue with AnchorNavigation

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#5283]
### Current behaviour

When AnchorNavigation has focus, if you press Tab, focus is kept on AnchorNavigation.
Introduced in 107.1.6

### Expected behaviour

When press Tab, focus should be done on the next component (textbox in exemple)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/headless-framework-y54bn8?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-37111

### Carbon Version

109.1.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5234
