### ISSUE TITLE
FlatTable / PopoverContainer - Axe Violation - Ensures landmarks are unique

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#5286]
### Current behaviour

FlatTable with PopoverContainer has an axe violation, landmarks should have a unique role or role/label/title (i.e. accessible name) combination.

![image](https://user-images.githubusercontent.com/38658070/177346560-4880d7f4-fd76-4e44-9e54-1b2cf940dde2.png)
https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=AxeChrome

### Expected behaviour

No accessibility violations should occur.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/quizzical-fire-j3m2y0?file=/src/index.js:7745-7761

### Carbon Version

109.0.0

### Design Tokens Version

2.25.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5249
