### ISSUE TITLE
Regression: Unnecessary component type validations break existing component logic in AccordionGroup

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#5288]
### Current behaviour

At a number of places, components started validating the type of their children which breaks our application, for example `AccordionGroups` only accept `Accordion`.
<img width="581" alt="image" src="https://user-images.githubusercontent.com/4557844/177731402-37791380-4113-4f67-bf7d-cd45e8f731a3.png">

For example with accordions we have an intermediate component between the AccordionGroup and the Accordion component that assembles the content of the Accordion and decides whether certain accordions should be rendered at all. This component returns an Accordion at the end but the validations still don't accept it.

### Expected behaviour

These validations are removed or degraded into warnings.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/blissful-bhaskara-k8rt5t?file=/src/index.js

### Suggested Solution

These validations are removed as they don't add much value but makes things much more complicated 

### Carbon Version

109

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

This is causing a number of regression issues for us and we are unable upgrade to the latest version.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5239

**Comment by blaky** [comment]
@mkrds Can you please see my response above?

**Comment by mkrds** [comment]
@blaky Hey Bence, sorry for the delay, could you provide me an example which can't be solved with the workaround that I've  proposed?

**Comment by markryd** [comment]
@mkrds your example in codesandbox with logic in a function that returns Accordions has the same error.

![image](https://user-images.githubusercontent.com/481153/188532380-a47bc77c-4425-4d61-9a68-312b16c42adf.png)

**Comment by nicktitchmarsh** [comment]
This appears to be fixed in the latest Carbon. @markryd or @blaky. Are you able to confirm?
