### ISSUE TITLE
MultiSelect - Axe Violation - Elements must only use allowed ARIA attributes

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#5290]
### Current behaviour

MultiSelect component has an axe violation when we open it, ensures ARIA attributes are allowed for an element's role.
![image](https://user-images.githubusercontent.com/38658070/177745058-9203844e-9592-484c-9175-6e29053a88eb.png)
![image](https://user-images.githubusercontent.com/38658070/177745139-eb6c9b0a-557f-4693-a543-9e7a0f46cf30.png)
![image](https://user-images.githubusercontent.com/38658070/177745214-e248a204-330f-45a4-9256-f99f1d9b25ae.png)

### Expected behaviour

No accessibility violations should occur.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select-multiselect--default-story

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-4671

**Comment by Parsium** [comment]
FE-5247

**Comment by nuria1110** [comment]
Closing as this issue was addressed as part of [v111.0.3](https://github.com/Sage/carbon/releases/tag/v111.0.3) of carbon.
