### ISSUE TITLE
Regression: Unnecessary component type validations break existing component logic for ActionPopover

### ISSUE THREAD

**Issue by DipperTheDan** [Sage/carbon#5291]
### Current behaviour

 In a number of places, components started validating the type of their children which breaks our application, ActionPopover accepts only an ActionPopoverItem as a direct child for example.

### Expected behaviour

These validations are removed or degraded into warnings.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/funny-dawn-eod2k5?file=/src/index.js

### Suggested Solution

These validations are removed as they don't add much value but makes things much more complicated or a workaround documented.

### Carbon Version

109.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5240

**Comment by mkrds** [comment]
Can be easily solved by abstracting the logic to a function instead of a component
https://codesandbox.io/s/mutable-star-36d9q7?file=/src/index.js
