### ISSUE TITLE
Pages content padding can not be removed

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#5302]
### Current behaviour

Pages component have by default some padding that we can not remove it and this limit us a lot on the UI we want to implement

![image](https://user-images.githubusercontent.com/84023810/178457232-81fbb182-1829-4d26-acf8-6089233efc3a.png)

### Expected behaviour

The consumer should define the UI , paddings , styles and Pages component should be responsible for the functionality

### CodeSandbox or Storybook URL

https://codesandbox.io/s/fast-snowflake-yfe056?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-37838

### Carbon Version

101.0.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5245
