### ISSUE TITLE
[Confirm] - Confirm component doesn't center correctly on 320px width screen

### ISSUE THREAD

**Issue by michalgarnczarski** [Sage/carbon#5306]
### Current behaviour

Confirm component doesn't center correctly on 320px width screen
![image](https://user-images.githubusercontent.com/104442068/178718062-5b3de2fb-3b1b-4083-a809-cc06d5cc02ed.png)
![image](https://user-images.githubusercontent.com/104442068/178718174-f1708554-af16-4420-8d2d-ae8e08e826a4.png)

### Expected behaviour

Confirm dialog should be centered as below.
![image](https://user-images.githubusercontent.com/104442068/178718260-6782980d-bfa4-4eb2-b999-3ed6d72ee886.png)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/vigilant-pascal-h17qn0?resolutionWidth=320&resolutionHeight=675

### JIRA Ticket (Sage Only)

SBS-37443

### Suggested Solution

Correct calculate left position of confirm dialog. 

### Carbon Version

109.1.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Confirm has not be designed for mobile yet. There is a UX taskforce to identify and adapt components for usage on small screens. Unfortunately we cannot provide a fix until we have direction on how to address this. In the mean time you could potentially use DialogFullScreen. Rough example here [Sandbox](https://codesandbox.io/s/rough-moon-zs5f3c?file=/src/index.js )
