### ISSUE TITLE
PopoverContainer closes when clicking inside of it

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#5322]
### Current behaviour

The PopoverContainer closes wen a click event occurs inside the popover, the functionality regressed when this PR was merged https://github.com/Sage/carbon/pull/5262

### Expected behaviour

It should remain open and only close when the click occurs outside of the container

### CodeSandbox or Storybook URL

https://codesandbox.io/s/keen-sammet-zuw4wk?file=/src/App.js

### Suggested Solution

It looks like we just need to add the `popoverContentNodeRef` to the `useClickAwayListener` refs array argument
  
```
  useClickAwayListener([ref, popoverContentNodeRef], handleClickAway, "mousedown");
```

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

There also seems to be an issue with using Selects in `PopoverContainer` where it closes the container when an Option is clicked. The linked gif has the above suggested fix applied

![select in popover](https://user-images.githubusercontent.com/44157880/180008951-8cb67740-646c-467c-9a4c-1cf26bf54d5c.gif)

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-5282
