### ISSUE TITLE
GridContainer has lost support for React Fragments

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon#5325]
### Current behaviour

Due to recently added child validation in a GridContainer, it's not longer possible to use a react fragment to group together a bunch of GridItems for conditional rendering.

### Expected behaviour

Would expect react fragments to be fully supported as this will lead to unconventional and/or repetitive code to work around. 

We could for example, return an array from a function but this adds (often) unnecessary abstraction and requires we then give each item a unique key which bloats things even more. 

Please note, this also break HoC's. As a matter of policy, we wrap all Carbon components and even the most simple wrapper that returns only an instance of a Carbon Grid Item, will fail this invariant check unless you add a static property "displayName='GridItem'.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/grid-item-wtih-fragment-rih927?file=/src/index.js

### Carbon Version

109.3.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-5283
