### ISSUE TITLE
DateInput - allowEmptyValue and empty value prop yields console warning

### ISSUE THREAD

**Issue by damianOfKyan** [Sage/carbon#5333]
### Current behaviour

When using DateInput with `allowEmptyValue` prop and `value` prop set to blank string ie:

```
<DateInput
      allowEmptyValue
      onChange={(e) => hangleOnChange(e.target.value)}
      onBlur={(e) => hangleOnBlur(e.target.value)}
      value=""
      minDate={"2022-07-26"}
    />
```

There is console warning:
> Warning: Failed prop type: Invalid prop `selectedDays` of type `String` supplied to `ForwardRef`, expected instance of `Date`.

![image](https://user-images.githubusercontent.com/47245766/180814509-4d319c26-f16b-426b-a200-733c0e830040.png)

### Expected behaviour

there should be no warning.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/carbon-date-picker-allowempty-empty-value-warning-5o239g?file=/src/index.js

### Carbon Version

109.3.3

### Design Tokens Version

2.21.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Hey @damianOfKyan the component needs to be controlled so I'm guessing it will have just been receiving the same empty string, although I can't recreate it for some reason. I've updated the sandbox and still don't see any errors so I'm closing this. I'll leave this open for now, but can you provide some repro steps for us to investigate please?

https://codesandbox.io/s/carbon-date-picker-min-date-bug-forked-0iql5q?file=/src/index.js

**Comment by nicktitchmarsh** [comment]
FE-5289
