### ISSUE TITLE
Error message in textarea has wrong contrast when used with Dialog component

### ISSUE THREAD

**Issue by dawidzarzycki** [Sage/carbon#5337]
### Current behaviour

axe devtools shows that the contrast is not good enough for the error message.
Correct value should be 4.5 and for now we have 4.49

![image](https://user-images.githubusercontent.com/19231884/181464887-ab164db5-a93a-4af6-8364-136416606623.png)
![image](https://user-images.githubusercontent.com/19231884/181464986-f4755068-32fe-4aac-a618-bb2f80614356.png)

axe devtolols won't highlight the contrast for error message when it is used in codesandbox, but if you use "inspect element" you will see that the contrast is 4.49

### Expected behaviour

Expecting to have passed the color contrast accessibility

### CodeSandbox or Storybook URL

https://codesandbox.io/s/tender-chihiro-pubm6l?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-38747

### Carbon Version

110.1.1

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@ljemmo it looks like there is a colour token contrast issue. Please could you direct us as to how we should fix this?

**Comment by ljemmo** [comment]
@nicktitchmarsh Claire and I have gone through our reds and tweaked accordingly. This PR should fix this: https://github.com/Sage/design-tokens/pull/214

Are you using the token 'colors.semantic.negative.500' for error text? If yes, then i think you can close this issue as you will get the latest colour once that token PR gets merged.

**Comment by mkrds** [comment]
FE-5304

**Comment by nicktitchmarsh** [comment]
This component does already use --colorsSemanticNegative500 so I don't think we need to make a change here

**Comment by nicktitchmarsh** [comment]
@dawidzarzycki you should be able to update the design tokens package on your project to fix this issue

**Comment by dawidzarzycki** [comment]
@nicktitchmarsh I think it is not working as expected with the latest carbon and design-tokens
![image](https://user-images.githubusercontent.com/19231884/186688278-8c588eea-f6df-451a-84ef-09d877176c70.png)

**Comment by nicktitchmarsh** [comment]
This was fixed in design-tokens 2.41
