### ISSUE TITLE
Select component cuts off option text when it wraps onto a new line

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#5341]
### Current behaviour

Select component cuts off option text when it wraps onto a new line

![image](https://user-images.githubusercontent.com/77396222/182152429-97bcf1fa-05b5-4538-aff7-45bf217f4afd.png)

### Expected behaviour

Select component should display option text when it wraps onto a new line without cutting it off.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/select-options-height-resize-uy2shp?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-38045

### Carbon Version

109.1.2

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5288
