### ISSUE TITLE
Focus does not remain within open dialog when Shift + tab is used

### ISSUE THREAD

**Issue by szeyingyau** [Sage/carbon#5342]
### Current behaviour

Focus does not remain within open dialog when Shift + tab on keyboard is used

### Expected behaviour

Focus remains within open dialog when Shift + tab on keyboard is used

### CodeSandbox or Storybook URL

https://carbon.sage.com/v/109.1.2/index.html?path=/story/dialog--default-story

### JIRA Ticket (Sage Only)

SBS-39486

### Carbon Version

109.1.2

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5287
