### ISSUE TITLE
[Button] - Invalid prop `forwardRef` supplied 

### ISSUE THREAD

**Issue by wkustrzykSage** [Sage/carbon#5343]
### Current behaviour

I've got an error in the console about invalid `forwardRef` supplied to `Button`  

`index.js:27   Warning: Failed prop type: Invalid prop `forwardRef` supplied to `Button`, expected one of type [function].`

### Expected behaviour

Match the `forwardRef` type of `Button` and `renderOpenComponent` method's `ref` prop type. Another solution could be wrapping Button component in `forwardRef` method instead put `forwardRef` prop

### CodeSandbox or Storybook URL

https://codesandbox.io/s/cocky-antonelli-skjggv?file=/src/index.js:1039-1058

### Carbon Version

109.5.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
We currently deprecated the forwardRef prop for Button components, we will be removing it in the future. https://github.com/Sage/carbon/pull/5266

If you use the ref prop instead this should function correctly https://codesandbox.io/s/recursing-carlos-3ow3wh
