### ISSUE TITLE
Add position support to Box

### ISSUE THREAD

**Issue by jamime** [Sage/carbon#5345]
### Desired behaviour

Add support for all positioning props.
e.g.
```jsx
<Box position="fixed"/>
```

### Current behaviour

Unable to position a box fixed position.

### Suggested Solution

https://styled-system.com/api/#position

### CodeSandbox or Storybook URL

https://codesandbox.io/s/admiring-cookies-yhcu3s

### Anything else we should know?

Discussed with carbon team. Agreed to implement.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5285
