### ISSUE TITLE
Select is not center well if render changed after open dropdown

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#5351]
### Current behaviour

When i open my select, if dropdown is displayed and something appears after, my component is not align well if i want my components aligned.

### Expected behaviour

I should not have difference when i display something after my dropdown is opened.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/confident-shape-448hys?file=/src/index.js

### Carbon Version

109.5.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-5303
