### ISSUE TITLE
[Textbox] `maxLength` console error for textbox

### ISSUE THREAD

**Issue by wkustrzykSage** [Sage/carbon#5355]
### Current behaviour

When the user set `characterLimit` property than on the console we can see the error of Input component `maxLength` prop:
 
![image](https://user-images.githubusercontent.com/102224821/182885050-31d018ec-6c64-430c-9e99-10b96ae91362.png)

### Expected behaviour

Set correct type of `maxLength` argument calculated inside `Textbox` component

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nostalgic-proskuriakova-5s6dlq?file=/src/index.js

### Carbon Version

109.3.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-5301
