### ISSUE TITLE
Loading not displayed when open Filterable Select

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#5357]
### Current behaviour

When we pass isLoading props to load asynchronus data i don't have loader displayed.
Reproduced on storybook if you click on reset button.

### Expected behaviour

I should have a loader when open filterable select with async data.

### CodeSandbox or Storybook URL

https://carbon.sage.com/storybook?path=/docs/select-filterable--with-is-loading-prop

### Carbon Version

109.7.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
FE-5300

**Comment by robinzigmond** [comment]
hi @maduv - this looks to have been fixed in version 110.2.1 (this release was to fix a different bug on Select but it seems that the underlying cause was the same). I am therefore closing this issue, please feel free to raise again if you think this hasn't been addressed.
