### ISSUE TITLE
Duplicated import PropTypes

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#5376]
### Current behaviour

When I try to start the application i get the error : 
<img width="569" alt="Capture d’écran 2022-08-10 à 14 02 44 1" src="https://user-images.githubusercontent.com/17086956/184143110-15f738b2-04d4-4f9d-9b5b-14c0c91abc2a.png">

Duplicated import PropTypes from "prop-types"; 

### Expected behaviour

We should have  one import PropTypes from "prop-types"; in modal.component.js

### CodeSandbox or Storybook URL

Not reproduced in the CodeSandbox

### Carbon Version

v110.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5309
