### ISSUE TITLE
Change chevron icon to caret icon - FlatTable component

### ISSUE THREAD

**Issue by ibsenjg** [Sage/carbon#5377]
### Desired behaviour

Hello, I want to choose the variant for IconType in [Expandable Flat Table](https://carbon.sage.com/storybook?path=/docs/flat-table-expandable--default-story) as you do for [Accordion](https://carbon.sage.com/storybook?path=/docs/accordion--default-story) to use the "Caret" icon instead "Chevron" for all expandable elements within the table.

### Current behaviour

the Icon’s type is hardcoded as chevron_down_thick when using the expandable rows functionality

### Suggested Solution

Could we extend or create a new property for FlatTable to change this IconType variant?

### CodeSandbox or Storybook URL

https://codesandbox.io/s/serene-sara-5rtfmj

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@ljemmo would you mind take a look at this and saying whether it's something we should support please?

**Comment by ljemmo** [comment]
@edleeks87 for me to comment, i'd have to see the design to understand why this was requested. Ideally we'd want to keep this component as simple as possible and include a minimum variety of icons.

@ibsenjg please can you share the design spec that prompted this request?

**Comment by ibsenjg** [comment]
Hello @ljemmo @edleeks87 this is a feature request from @danielr-sage to use caret instead chevrons for Report Table. Can i paste Figma designs here?

**Comment by edleeks87** [comment]
@ibsenjg please don't post the designs here. If @danielr-sage reaches out to Luke on slack or teams he can review the request and designs there

**Comment by Parsium** [comment]
Hi @danielr-sage @ljemmo, was a decision made regarding this request? 😄

**Comment by danielr-sage** [comment]
@Parsium Not yet. I'm working to present this together with other related updates to the design system team. It may take a few weeks. If you prefer, we can close this ticket and open a new one once it's investigated properly approved. Thanks

**Comment by Parsium** [comment]
Upon discussion with @danielr-sage, this has been proposed to the Design System team for consideration. @ibsenjg in case this is blocking your work please could you feed this back to your designer? I would recommend sticking with the chevron icons for now until we receive confirmation from the Design System team whether they would to introduce this or not.
