### ISSUE TITLE
TextEditor: error typescript definition for TextEditorState

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#5388]
### Current behaviour

If we use: 
```
import TextEditor, {
  TextEditorState as EditorState
} from "carbon-react/lib/components/text-editor";
```
when we try to use `EditorState` we got this error: `Cannot read properties of undefined (reading 'createEmpty')`.

If we use: 
`import { TextEditorState } from "carbon-react/lib/components/text-editor/text-editor.component";`
we got this issue:
`Cannot find module 'carbon-react/lib/components/text-editor/text-editor.component' or its corresponding type declarations.ts(2307)`

### Expected behaviour

Use TextEditorState without using the declaration:
`declare module "carbon-react/lib/components/text-editor/text-editor.component";`

### CodeSandbox or Storybook URL

https://codesandbox.io/s/blazing-bird-9sflk0?file=/src/index.tsx

### Carbon Version

110.0.3

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5325

**Comment by nuria1110** [comment]
Closing as we believe this issue is resolved, please re-open if you believe this not to be the case.
