### ISSUE TITLE
Sidebar remains open when click onto Docs in Storybook

### ISSUE THREAD

**Issue by ZhuoyuJin** [Sage/carbon#5391]
### Current behaviour

Repo step: 
1. Navigate to sidebar or other modal related components like Dialog or DialogFullScreen
2. Click on "Open Sidebar" then sidebar opens to the right
3. Click on "Docs" on the top of the Storybook, where the main page navigate to docs, but with the sidebar remains open on the right
4. Same behaviour as Dialog/DialogFullScreen

https://user-images.githubusercontent.com/72838192/185077675-68405480-09ea-4e18-82a8-a0a47b6729d5.mp4

### Expected behaviour

When the page navigate to docs, we expect the sidebar disappears from the right

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/sidebar--default-story

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Fairly certain this is a known issue with storybook where switching between `canvas` and `docs` tabs actually just sets a `hidden="true"` on the root div rather than re-rendering etc

![image](https://user-images.githubusercontent.com/44157880/185596674-1ef95ef0-c051-45fa-815c-09c816ea3cdc.png)
