### ISSUE TITLE
Sidebar custom content padding

### ISSUE THREAD

**Issue by rawlmp** [Sage/carbon#5393]
### Desired behaviour

Ability to set the content padding inside the Sidebar.

This way we can get rid of the default padding in the body of the sidebar, and we can put full width elements inside without the need of using negative margins.

### Current behaviour

We are not able to overwrite the predefined padding.

### Suggested Solution

SBS-40388

### CodeSandbox or Storybook URL

Impossible to reproduce a new feature

### Anything else we should know?

We have a Figma resource created by SD. I can't paste here any reference to it.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
https://github.com/Sage/carbon/issues/4494
