### ISSUE TITLE
Sidebar to accept sticky content

### ISSUE THREAD

**Issue by rawlmp** [Sage/carbon#5395]
### Desired behaviour

We need the possibility to attach a sticky content (ouside header) in order to keep it fixed in the sidebar.

Maybe a slot (fixedContent) will be nice.

### Current behaviour

All the content is in the same slot and scrollable when the content height exceeds the Sidebar height.

### Suggested Solution

SBS-40450

### Anything else we should know?

We have a Figma resource created by SD. I can't paste here any reference to it.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @harpalsingh @ljemmo, we have checked the figma designs related to the above ticket, it seems like a lot of thought has been put into this to address some common issues. Is this something that has been officially approved by UX to introduce into DS?

**Comment by ljemmo** [comment]
@rawlmp Can you share the figma so that i can review?

**Comment by edleeks87** [comment]
It is already possible to pass in `Box` components which support the `position` interface and therefore can be made sticky. I'm not sure we should add a specific prop as a compositional approach will allow implementing teams to be flexible

**Comment by Parsium** [comment]
Hi @rawlmp, does the codesandbox @edleeks87 had shared help your issue? :)

**Comment by Parsium** [comment]
Hi @rawlmp, do you have any updates on this?

**Comment by edleeks87** [comment]
Hi @rawlmp did you get a chance to investigate this? I believe we have an issue with inputs and sticky content so if you're happy with it I'd like to close this issue in favour of https://github.com/Sage/carbon/issues/5572

**Comment by edleeks87** [comment]
Closing in favour of #5572, please re-open if needed
