### ISSUE TITLE
Use shadows in some components for new designs

### ISSUE THREAD

**Issue by rawlmp** [Sage/carbon#5396]
### Desired behaviour

In the new design system, there are values for different box shadows, we need the possibility to use them in, for example, the Box component if we want to replicate the designs with those shadows near the header of the sidebar.

### Current behaviour

Shadows need to be added with CSS

### Suggested Solution

SBS-40451

### Anything else we should know?

We have a Figma resource created by SD. I can't paste here any reference to it.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @ljemmo @harpalsingh, do we want to allow the ability to add box shadows generally? Or should we be reserving them for particular use cases?

**Comment by ljemmo** [comment]
@Parsium i would need to see the design in question that prompted this request. Please could someone share? My gut feel would be to reserve them for particular cases in order to drive consistency.

**Comment by Parsium** [comment]
Hi @ljemmo, I remember there has been numerous discussions regarding MTD responsive work both here on github and elsewhere. May I ask if you happened to receive the designs for this or if you still need them?

**Comment by ljemmo** [comment]
@Parsium I've seen the design for this. It looks like they are wanting to apply specific shadows to a stacked box underneath the sidebar header. To achieve this, perhaps we just need a prop on box that allows selection of our shadow tokens? The dev in question can just select the token that best suits them.

**Comment by nicktitchmarsh** [comment]
https://github.com/Sage/carbon/pull/5608 has fixed this
