### ISSUE TITLE
Issue while displaying error in Multiselect component

### ISSUE THREAD

**Issue by harsh096** [Sage/carbon#5401]
### Current behaviour

I have to show the error when no. of selected pills exceeds a certain number. When the dropdown is open and we try to select more pills than that number, border turns red but error text does not show up until I click outside the dropdown and it closes. Similarly when the pills are deleted, error goes away but the space where it was being displayed, remains as such until I click outside the dropdown

### Expected behaviour

Error should be displayed when the error condition is true without any need of clicking outside the dropdown.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/multi-select-demo-forked-8v9789?file=/src/MultiSelectDemo.jsx

### Carbon Version

110.1.1

### Design Tokens Version

2.38.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

Slack conversation can be found [here](https://sageone.slack.com/archives/C0D6DD3N2/p1660897863123719).

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5324
