### ISSUE TITLE
The link doesn’t work for a “flat table with expandable options”

### ISSUE THREAD

**Issue by andrei-marincas** [Sage/carbon#5402]
### Current behaviour

The link doesn’t work for a “flat table with expandable options”

![2022-08-22 12_57_21-](https://user-images.githubusercontent.com/100773040/185894450-5df59c0c-9cd5-4cd1-88ff-1254129a2dad.jpg)

### Expected behaviour

The link must work for a “flat table with expandable options”

### CodeSandbox or Storybook URL

https://codesandbox.io/s/wonderful-dewdney-y2wm59?file=/src/index.js

### Carbon Version

110.1.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
It appears to be when the table row has focus, the link component does not work as expected.

**Comment by Parsium** [comment]
FE-5323
