### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by whomwah** [Sage/carbon#5408]
### Current behaviour

I’m just currently looking at updating some of the dependencies in lib that uses `carbon-react`. After updating some of the issues by bumping dependency versions etc the app started to fail to build giving me `Error: Cannot find module 'chalk'`:

```
> carbon-react@109.2.2 postinstall /s1_payroll_ui/node_modules/carbon-react
> node ./scripts/check_carbon_version.js && node ./scripts/check_rfcs.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'chalk'
```

Looking into it further to understand why. I can see that when you install `carbon-react` there is a `postinstall` command that gets run https://github.com/Sage/carbon/blob/v109.2.2/package.json#L30. So I looked at https://github.com/Sage/carbon/blob/v109.2.2/scripts/check_carbon_version.js#L4 as this gets run first and can see that this is where `chalk` is required. I then looked at the `package.json` and see that `chalk` is in `devDependencies` https://github.com/Sage/carbon/blob/v109.2.2/package.json#L113. So it looks like this error I’m seeing is because `chalk` has not been installed by the library and is relying on it being installed as a dependency of another lib that has been installed before `carbon-react`?

### Expected behaviour

I would expect `chalk` to be installed as part of the library and not to rely on it being available through another dependency.

### CodeSandbox or Storybook URL

n/a

### Suggested Solution

I think the fix is to move `chalk` into the `dependencies` section of the `package.json` file.

### Carbon Version

109.2.2

### Design Tokens Version

0.0.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

Linux

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5320
