### ISSUE TITLE
Typography variant "b" does not truncate.

### ISSUE THREAD

**Issue by Joel-Stratton** [Sage/carbon#5410]
### Current behaviour

Currently when using Typography variant "b" and having truncate set to true, the text does not get truncated and instead runs off screen.   

### Expected behaviour

Text should get truncated like when using other variants.

### CodeSandbox or Storybook URL

https://lx52by.csb.app/

### Carbon Version

106.7.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5338

**Comment by nineteen88** [comment]
This isn't a bug exactly but an issue with implementation whereby inline elements inside of block elements won't work with the `truncate` prop. Additional information will be added to Storybook including an example (see https://github.com/Sage/carbon/pull/5448/)
