### ISSUE TITLE
ListItem to inherit font styles from List

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#5413]
### Desired behaviour

`ListItem` inherits font styles from `List`. To apply a font variant to all list items, the variant prop may be set on `List` alone.

```javascript
<List variant="big">
	<ListItem>item 1</ListItem>
	<ListItem>item 2</ListItem>
	<ListItem>item 3</ListItem>
</List>
```

### Current behaviour

Currently, `ListItem` does not inherit font styles from `List`. To apply a font variant to all list items, each list item must have the variant set.

```javascript
<List>
	<ListItem variant="big">item 1</ListItem>
	<ListItem variant="big">item 2</ListItem>
	<ListItem variant="big">item 3</ListItem>
</List>
```

### CodeSandbox or Storybook URL

https://codesandbox.io/s/list-9tee68

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5336
