### ISSUE TITLE
Multi Select onChange is called twice when a list item is selected, also when object set as value it cannot be edited

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#5418]
### Current behaviour

When an item is selected from the Multi Select option list, two `onChange` callbacks are made.

Also, when an object is set as a value the options cannot be edited.

### Expected behaviour

Only one `onChange` callback should be made when an option is selected.

When an object is set as a value, it should be possible to delete or add more options.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select-multiselect--with-object-as-value

### JIRA Ticket (Sage Only)

FE-5332

### Suggested Solution

The `onChange` callback twice issue looks to be because `onChange` and `updateValue` are both called in the `onSelectOption` function.

The object as value issue looks to be caused by the `onSelectOption` function too, so both issues seem related to this.

### Carbon Version

110.1.1

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
I've fixed the issue with onChange callback being called twice however I was not able to reproduce the second issue with MultiSelect becoming uneditable
