### ISSUE TITLE
Box having a border prop

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#5422]
### Desired behaviour

Having a prop available to add a border to `Box` components

### Current behaviour

The only way to achieve this is using a `FlatTable` with one column, which has `horizontalBorderSize`.

### Suggested Solution

`<Box bb="1px">Content<Box>` or
`<Box bb="small">Content<Box>`

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5335

**Comment by nicktitchmarsh** [comment]
@ljemmo are we ok with opening up these props? This might mean people can circumvent the DS approved looks of components and start creating their own with Box

**Comment by ljemmo** [comment]
@nicktitchmarsh could this be achieved with the HR component? This way we can restrict the colour of the divider used?

**Comment by Parsium** [comment]
After these concerns back to @MarcServat, they have spoken with their designer and decided not to go forward with the design that requires this change, so I will close this and FE-5335
