### ISSUE TITLE
Update Box component to have a gap prop

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#5434]
### Desired behaviour

Box component to have a prop which enables customisation of the gap property in CSS. See info: https://css-tricks.com/almanac/properties/g/gap/

### Current behaviour

Box has no prop which allows customisation of the gap property in CSS.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5357
