### ISSUE TITLE
PopoverContainer renderOpenComponent bug

### ISSUE THREAD

**Issue by vincentfodor** [Sage/carbon#5441]
### Current behaviour

When an open component is given with `renderOpenComponent` the `PopoverContainer` renders at the wrong position. It seems like the `PopoverContainer` is rendered at the end of the document.

❌ **With open component:**
![image](https://user-images.githubusercontent.com/30438094/188095615-e3ac06b2-aea8-4f1e-bfea-d3891d36d009.png)

✔ **No open component:**
![image](https://user-images.githubusercontent.com/30438094/188095775-9201f0d9-fe41-4d70-ae11-0d8f60551420.png)

### Expected behaviour

The expected behaviour is that the PopoverContainer will be rendered under/over the open component

### CodeSandbox or Storybook URL

https://codesandbox.io/s/zen-morse-md57q1?file=/src/index.js

### Carbon Version

110.2.1

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5356 has been raised
