### ISSUE TITLE
Add "Active" Variant to the tile component.

### ISSUE THREAD

**Issue by jordanware** [Sage/carbon#5444]
### Desired behaviour

Add a variant to the tile component for when it is shown within an Active state within the UI. The active state should use the same tokens as the tile select active variant. 

**Border token:**
colors.action.major.025

**Background token:**
colors.action.major.500

### Current behaviour

Currently the tile only has one state/variant with a white background colour.

### Suggested Solution

Add an active variant to allow us to achieve desired designs.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@ljemmo are these tokens ok to use here or would you prefer different tokens?

**Comment by nicktitchmarsh** [comment]
FE-5355 raised

**Comment by ljemmo** [comment]
@nicktitchmarsh yes, these tokens are the ones discussed on a call with jordan the other day. 👍
