### ISSUE TITLE
Select: Infinite loading 

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#5446]
### Current behaviour

The 'infinite loading' loads only the first page. It depends on the zoom of the browser and the resolution of the screen.

On Mac:
It does not work for me when the browser is zoomed to 110% and the resolution done by the Liquid Retina XDR screen

On PC:
It does not work when the browser is zoomed to 110% and the resolution 1920*1080 (take care, it's working on mac with this resolution)

https://user-images.githubusercontent.com/17121053/188460344-5a0c65f1-3a6a-48ad-a34f-5fbc1257b300.mov

sandbox:
https://codesandbox.io/s/magical-lichterman-ds84f2

### Expected behaviour

The 'infinite loading' loads all pages without depending of the resolution (screen) and the zoom (browser).

### CodeSandbox or Storybook URL

https://codesandbox.io/s/magical-lichterman-ds84f2

### JIRA Ticket (Sage Only)

SBS-41292

### Suggested Solution

no

### Carbon Version

109.x

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
This appears to have been fixed on a previous release. Here is it working in the latest version of Carbon: https://codesandbox.io/s/muddy-violet-6iezoh
