### ISSUE TITLE
Update the CONTRIBUTING.md guide with GPG key verification instructions

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#5452]
### Current behaviour

There is no instruction in the `CONTRIBUTING.MD` guide to set up GPG key verification.

Also, the `getting-started` link to the `getting-started.stories.mdx` from the `CONTRIBUTING.MD` guide does not work.

### Expected behaviour

If a dev already has their environment set up and just needs to add Carbon to their project they will likely not consult the `dev-environment-setup.md` and miss the instruction to add GPG key verification. This should be added to the `CONTRIBUTING.MD` guide, or at least direct the reader to that section in the `dev-environment-setup.md` doc.

The link text `getting-started` should link to the correct `getting-started.stories.mdx` doc.

### CodeSandbox or Storybook URL

https://github.com/Sage/carbon/blob/master/CONTRIBUTING.md

### JIRA Ticket (Sage Only)

FE-5358

### Suggested Solution

Update the docs

### Carbon Version

110.3.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5358
