### ISSUE TITLE
Grey hint text for individual checkboxes

### ISSUE THREAD

**Issue by Isabelle-whi** [Sage/carbon#5453]
### Desired behaviour

Individual checkboxes to have grey hint text like other fields
![Screenshot 2022-09-07 at 14 23 39](https://user-images.githubusercontent.com/56259062/188889395-a3b70c49-8618-4dce-87c5-8425461b6de9.png)

### Current behaviour

Individual checkboxes have black hint text.
![Screenshot 2022-09-07 at 14 23 43](https://user-images.githubusercontent.com/56259062/188889493-754ec740-21b2-4797-bcae-597b3e2b1c17.png)

### Suggested Solution

Change fieldHelp colour for individual text boxes.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by ljemmo** [comment]
@DipperTheDan Hint text should use the token 'colors.utility.yin.055'. Please can you check this is the case?

**Comment by Parsium** [comment]
FE-5400
