### ISSUE TITLE
The content is overlapped by the header

### ISSUE THREAD

**Issue by EstebanGoldMuros** [Sage/carbon#5459]
### Current behaviour

The report header is overlapped by the drill down.

### Expected behaviour

The report header must remain in front.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/flat-table-header-objfyh

### JIRA Ticket (Sage Only)

SBS-36717

### Carbon Version

110.3.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by EstebanGoldMuros** [comment]
This problem 
![image](https://user-images.githubusercontent.com/108718201/190078429-a8d44e73-80b7-4af4-8c76-94dc566f86fa.png)

**Comment by nicktitchmarsh** [comment]
FE-5377
