### ISSUE TITLE
Preferred XMLHttpRequest Module (remove superagent)

### ISSUE THREAD

**Issue by andrewjtait** [Sage/carbon#546]
We are looking to move away from using `jQuery.ajax`, and instead are looking at preferred modules to handle this instead.

Possibilities:
- https://github.com/mzabriskie/axios
- https://github.com/visionmedia/superagent

On the back of this, we could even create a Service class which can help create reusable endpoints and can take care of some of the boilerplate required in making requests.

For example (just a rough sketch), a customer service which has GET requests already set up:

```
CustomerService.getCustomer(3)
  .done((response) => {
    ...
  })
  .fail((response) => {
    ...
  });
```

**Comment by edleeks87** [comment]
We are looking to move away from providing specific data-fetching and allowing developers the flexibility to choose their own
