### ISSUE TITLE
MenuItem doesn't accept 'rel' as a prop 

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#5464]
### Current behaviour

MenuItem doesn't accept a rel prop (or do anything to set this attribute on the underlying anchor element)

### Expected behaviour

MenuItem should do something to set the rel attribute on the underlying anchor tag.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/charming-williams-r97bkk?file=/src/index.js

### Carbon Version

110.1.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5366
