### ISSUE TITLE
Message Component has inconsistent render across browsers

### ISSUE THREAD

**Issue by damianOfKyan** [Sage/carbon#5466]
### Current behaviour

There is blank gap between div holding the icon and border outline of message component, this gap is inconsistent across browsers and seems to disappear and re-appear on different UI zoom values.

Note: if I recall correctly, there was no gap in older versions so it could be some global style change that affected this component, otherwise it might be purely down to browser.

As tested in Firefox, Chrome and Edge, the Firefox seems to be ok while Chrome and Edge have issue
https://carbon.sage.com/?path=/story/message--default-story

at 100%:
![image](https://user-images.githubusercontent.com/47245766/189628496-b190ca66-08c2-4957-81eb-5ac01b54f711.png)

zoom-ed in 1 time:
![image](https://user-images.githubusercontent.com/47245766/189628597-cdbffa10-6a9a-4293-9be6-f53859441a80.png)

zoom-ed in 2 times:
![image](https://user-images.githubusercontent.com/47245766/189628649-9b390dcf-6507-4dac-a080-353a8b6b8067.png)

zoom-ed in 3 times:
![image](https://user-images.githubusercontent.com/47245766/189628682-9ba9d288-4276-49fe-b211-81ece275abf8.png)

zoom-ed in 4 times:
![image](https://user-images.githubusercontent.com/47245766/189628724-df511ec3-c83f-4ff5-ae4b-a27b108489ce.png)

zoom-ed in 5 times:
![image](https://user-images.githubusercontent.com/47245766/189628774-9467b6a7-f915-444c-96e0-a62f79823e76.png)

### Expected behaviour

I would expect consistent behaviour across browsers and at various sizez/zoom settings.
My guess is there should not be any blank gap between icon div and border outline.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/message--default-story

### Carbon Version

v110.6.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

you guys rock! #legends

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5364

**Comment by DipperTheDan** [comment]
Closing this issue as this is no longer a problem since the rounded corners work was completed. The code changes completed when doing this piece of work accidentally resolved this bug.
