### ISSUE TITLE
MenuItem component to take iconAlign prop when there is an external link 

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#5468]
### Desired behaviour

There is an 'iconAlign' prop available to pass to the MenuItem component when there is an external link. This will allow us to position the icon to the right of the text. 

### Current behaviour

There is no 'iconAlign' prop available to pass to the MenuItem component. This means that when dealing with external links in Menus we can't use the 'icon' prop as this positions the icon to the left of the text, when it should be to the right.

### Suggested Solution

iconAlign prop as available in the Link component. 

Here: https://carbon.sage.com/?path=/docs/link--with-icon-align

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
@ljemmo would you be able to run this past the DS team please and let us know if you want this feature or not? Thanks 😄

**Comment by ljemmo** [comment]
@niamhmadden24 please could you share the proposed design via teams with Claire Denning and myself so we can review.

**Comment by Parsium** [comment]
Hi @niamhmadden24, are you able to share the design with Claire and Luke please? :)

**Comment by niamhmadden24** [comment]
I'm so sorry. I didn't see these comments @ljemmo @Parsium. I'll share the info via teams now.

**Comment by ljemmo** [comment]
@niamhmadden24 and @Parsium - Just reviewed and happy for us to go ahead with niamh's proposal from a DS perspective. They basically just wanting to enable left or right alignment of icons within child items. Currently we appear to only be able to pass in left-aligned icons.

**Comment by davidsmallman** [comment]
Hi @ljemmo @Parsium do we have a FE Jira ticket for this yet please?

**Comment by ljemmo** [comment]
@davidsmallman from a DS perspective, we're happy for this to go ahead. Do you want to create a ticket on their backlog with technical requirements or a member of the FEET team can? I believe usually the FEET team like to create their own tickets so that all the correct A/C points are added based on the original bug.

**Comment by davidsmallman** [comment]
Thanks @ljemmo, appreciate it. Would be great if someone from FEET could and I'll link it to the corresponding Jira bug.

**Comment by edleeks87** [comment]
FE-5500
