### ISSUE TITLE
Add / Clarify Image component behaviour

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#5469]
### Desired behaviour

As requested: raising a GitHub request for the following two changes:
- alt prop will be clarified to always be provided
- ability to set aria-hidden

> Ah I see and thanks 
[@Robin Zigmond](https://sageone.slack.com/team/UUADCMQHH), perhaps to prevent the abuse of passing of null alt strings, we could add a new prop to Image such as decorative which would automatically handle cases like this.
Please could you add this as an enhancement on our github repo 
[@Paul](https://sageone.slack.com/team/ULVLHRX2Q)
?

### Current behaviour

An error is given if alt prop is empty string and there is no way to set aria hidden

### Suggested Solution

n/a

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5362
