### ISSUE TITLE
MultiActionButton: we cannot use the keyboard to launch a button action

### ISSUE THREAD

**Issue by jerlau** [Sage/carbon#5472]
### Current behaviour

Open the MultiActionButton component with arrow down.
Select one of the item with arrow down or arrow up
<Enter> on the keyboard or <Space> on the keyboard
result:
The action link to the button is not launch
The MultiActionButton component is not closed (we see the list of buttons)

### Expected behaviour

Open the MultiActionButton component with arrow down.
Select one of the item with arrow down or arrow up
<Enter> on the keyboard or <Space> on the keyboard

Expected:
The action kinked to the button is launched
The list of buttons is closed.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/multi-action-button--default-story

### JIRA Ticket (Sage Only)

SBS-41940

### Carbon Version

110.7.0

### Design Tokens Version

2.21.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5372
