### ISSUE TITLE
Button Toggle Group cannot apply width adjustment

### ISSUE THREAD

**Issue by wkustrzykSage** [Sage/carbon#5490]
### Current behaviour

As a developer, I cannot set the width of the Buttons inside the ToggleButtonGroup component. It's also not possible to set ToggleButton Group to be full width. and set position to center if neededcentre

### Expected behaviour

As a developer, I want to be able to set the width of the ToggleButton  Inside ToggleButtonGroup and the possibility to set the position of buttons without adding extra ugly hacks 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/zen-morse-4kpu2w?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-41388

### Carbon Version

110.1.1

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
@ljemmo what are your thoughts on this? Is this something we should provide in Carbon?

**Comment by Parsium** [comment]
We do have this already on our backlog, but we'll block this for now

**Comment by ljemmo** [comment]
@Parsium i never received a design to review I'm afraid. We definitely need a decision log whether we can share screenshots and context imo.

**Comment by Parsium** [comment]
Brilliant thanks for letting us know @ljemmo, I'll unblock FE-5493 👍🏼
