### ISSUE TITLE
Allow input label to exceed length of input box on single line

### ISSUE THREAD

**Issue by scottsmith93** [Sage/carbon#5494]
### Desired behaviour

Allow a text label to be longer than the text box, without the label wrapping over multiple lines.

### Current behaviour

When attempting to make an input a certain size width, the input label is wrapping over multiple lines if it is longer than the box. While this is sometimes unavoidable in certain situations, I would not expect this to happen when the design is not in a stressed state.

It is forcing me to make some inputs exceedingly and unacceptably wide. This breaks good user experience practice of appropriately sized text boxes, to match the users expectation of data required.

I believe this is only an issue when using inputs with the label above. There seems a prop can be used to give the desired outcome when using in line labels.

### Suggested Solution

Allow the input width to be set without the label wrapping. As the design shrinks, if the overall label does fit the width of the container, then I would expect this to naturally wrap.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-5383
