### ISSUE TITLE
Resolve Typescript error when using unique key name for validationStatusOverride prop in Tabs

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#5496]
### Current behaviour

Typescript errors for `validationStatusOverride` prop when using unique key name. See details -

```
Type '{ uniqueKey: { error: false; }; } | {}' is not assignable to type '{ id?: { error?: boolean | undefined; warning?: boolean | undefined; info?: boolean | undefined; } | undefined; } | undefined'.
  Type '{ uniqueKey: { error: false; }; }' is not assignable to type '{ id?: { error?: boolean | undefined; warning?: boolean | undefined; info?: boolean | undefined; } | undefined; }'.
    Object literal may only specify known properties, and 'uniqueKey' does not exist in type '{ id?: { error?: boolean | undefined; warning?: boolean | undefined; info?: boolean | undefined; } | undefined; }'.ts(2322)
tabs.d.ts(36, 3): The expected type comes from property 'validationStatusOverride' which is declared here on type 'IntrinsicAttributes & TabsProps'
```

### Expected behaviour

Typescript should not error when using unique key name for `validationStatusOverride` prop.

### CodeSandbox or Storybook URL

N/A

### JIRA Ticket (Sage Only)

SBS-42471

### Suggested Solution

Updating Typescript definition for `validationStatusOverride` prop as follows should resolve the error -

```
validationStatusOverride?: {
    [id?: string] : {
      error?: boolean;
      warning?: boolean;
      info?: boolean;
    };
  };
```

### Carbon Version

109.1.2

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5379
