### ISSUE TITLE
hidden prop doesn't exist in Image component

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#5501]
### Current behaviour

hidden prop doesn't exist in Image component.

Error message : Cannot assign type '{ size: string; src: string; hidden: true; }' to type 'IntrinsicAttributes & StyledImageProps'.
  Property 'hidden' does not exist on type 'IntrinsicAttributes & StyledImageProps

No problem on the actual version we are using 110.3.0

### Expected behaviour

hidden prop should exists in Image component.

### CodeSandbox or Storybook URL

Not reproduced in the CodeSandbox

### Carbon Version

110.10.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-5381
