### ISSUE TITLE
Trouble with focus on Safari web browser

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#5511]
### Current behaviour

For exemple with Toggle buttons, they never have focus with tab

### Expected behaviour

They should have focus.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/heuristic-wind-0wl8gy?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-31220

### Suggested Solution

My ticket on project has raised that with some component.
So i think it should be checked with all the component. I don't think it's just a problem with toggle.

### Carbon Version

110.11.1

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by jamime** [comment]
You need to press `⌥ (option) + Tab` in Safari by default. You can change this in preferences. 

![image](https://user-images.githubusercontent.com/2328042/193550230-e5e92071-f0aa-4391-ba94-1db8819a55e5.png)

**Comment by maduv** [comment]
Oh, i did not know this tip ! Thanks for this answer. We can close the ticket.

**Comment by Parsium** [comment]
Hi @maduv, thanks for letting us know! I will close this
