### ISSUE TITLE
DialogSizes no longer exported

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#5516]
### Current behaviour

Previously: DialogSizes was accessible by MFEs to import and use as a type.
in v111.0.0 this is no longer the case

### Expected behaviour

DialogSizes capable of being imported as a type into consuming code

### CodeSandbox or Storybook URL

n/a

### JIRA Ticket (Sage Only)

SBS-43091

### Suggested Solution

node_modules/carbon-react/lib/components/dialog/dialog.component.d.ts

```Typescript
- declare type DialogSizes = "auto" | "extra-small" | "small" | "medium-small" | "medium" | "medium-large" | "large" | "extra-large";
+ export declare type DialogSizes = "auto" | "extra-small" | "small" | "medium-small" | "medium" | "medium-large" | "large" | "extra-large";
```

### Carbon Version

v111.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5390
