### ISSUE TITLE
Incorrect Padding in Online Payslips Pod

### ISSUE THREAD

**Issue by Smithasage** [Sage/carbon#5523]
### Current behaviour

When online payslips has been set up the padding in the pod on the summary screen is incorrect.
Padding in the Online payslips pod is incorrect and should align as per Auto/enrolment pensions Pod.

### Expected behaviour

The padding for Online Payslips and Status to align with Auto Enrolment/Pensions in the Pod 

### CodeSandbox or Storybook URL

https://carbon.sage.com/v/109.2.2/index.html?path=/docs/pod--default-story

### JIRA Ticket (Sage Only)

SKPU-7767

### Carbon Version

110.1.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows, Linux

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@Smithasage we're not able to do anything with this, we have no reproducible example or steps, the link you have included has no context and doesn't display an issue as far as I can tell and your description of the issue relates specifically to the project you work on. Please amend this issue to include a generic description of the issue and a reproducible (ideally codesandbox) example or we will have to close the this as we have no way of investigating

**Comment by Smithasage** [comment]
@edleeks87  sure I will provide the reproducible codesandbox example.

**Comment by edleeks87** [comment]
I'm going to close this, if you manage to reproduce the issue in a sandbox please feel free to re-open and we'll investigate
