### ISSUE TITLE
Button as a link focus color

### ISSUE THREAD

**Issue by satheeshkumarp-sage** [Sage/carbon#5526]
### Current behaviour

Button as a link focus color is light gold color

### Expected behaviour

on focus color should be Jade green.

### CodeSandbox or Storybook URL

https://carbon.sage.com/v/109.2.2/index.html?path=/docs/button--as-a-link

### JIRA Ticket (Sage Only)

SKPU-7765

### Carbon Version

109.2.2

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
The link you have provided does not reproduce the issue, I have checked the behaviour and to the best of my knowledge it works correctly. If you can provide a reproducible (ideally codesandbox) example that shows this is a carbon issue please re-open 👍 

https://codesandbox.io/s/intelligent-danilo-f4e4k9
