### ISSUE TITLE
Tab changes focus when typing in Textbox

### ISSUE THREAD

**Issue by vincentfodor** [Sage/carbon#5527]
### Current behaviour

When typing in a `Textbox` inside of a `Tab` the first `Tab` of the `Tabs`-Component will be focused
(See codesandbox: Select Tab 2 > Type in Textbox)

### Expected behaviour

The current selected `Tab` should stay focused

### CodeSandbox or Storybook URL

https://codesandbox.io/s/smoosh-bush-yvug80?file=/src/index.js

### Carbon Version

111.0.3

### Design Tokens Version

2.42.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5399

**Comment by edleeks87** [comment]
@vincentfodor thanks for raising this we'll look to get a fix released asap, if you need a workaround you can use the `onTabChange` and `selectedTabId` props to control the selected `Tab`.

https://codesandbox.io/s/zealous-roman-me7skc

**Comment by vincentfodor** [comment]
Thanks @edleeks87 for the workaround!

**Comment by Chris3y** [comment]
@edleeks87 We encountered this and assumed it was intentional :) Part of the "no longer supporting uncontrolled components" etc

Was a simple fix in our wrapper but will remove that if you guys address it.
