### ISSUE TITLE
DateInput calendar pulled to the bottom of the screen

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#5532]
### Current behaviour

When opening the Date Input calendar, it seems to be appended to the bottom of the DOM (similar to https://github.com/Sage/carbon/issues/5465) as opposed to the location of the input. Storybooks looks fine, for what it's worth, and it looks ok in CodeSandbox, too.

### Expected behaviour

The calendar opens where it should.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/infallible-driscoll-40yngp?file=/src/index.js

### Carbon Version

111.0.3

### Design Tokens Version

2.3.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
@mkrds @damienrobson-sage did we get anywhere with being able to reproduce this issue? Should we raise an issue on our backlog for it?

**Comment by damienrobson-sage** [comment]
@robinzigmond sorry, I mean to close this. All sorted via update to a newer version - probably just a caching issue 👍
