### ISSUE TITLE
Select component not working when displaying as floating filter on sage-grid component 

### ISSUE THREAD

**Issue by lamilsage** [Sage/carbon#5537]
### Current behaviour

When displaying select component on sagegrid floating filter, popover is not displayed.

The following error is displayed on console :
Warning: Failed prop type: The prop `reference.current` is marked as required in `Popover`, but its value is `undefined`.

### Expected behaviour

Popover should be correctly display and no error should be displayed on console

### CodeSandbox or Storybook URL

https://codesandbox.io/s/great-wing-4dv00g?file=/src/App.js

### Carbon Version

111.0.0

### Design Tokens Version

2.44

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5406
