### ISSUE TITLE
Allow to set the label and icon on opposite sides in fullWidth button

### ISSUE THREAD

**Issue by KonradWroblewski** [Sage/carbon#5547]
### Desired behaviour

I would like to be able to set an icon and label in a button with "fullWidth" enabled on opposite sides.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/112560351/195278936-a13d29b2-df96-4be2-b87b-312a5d7f126d.png">

### Current behaviour

Currently it is not possible to set the icon and label on opposite sides in button.
If we set fullWidth to true, the button with the icon looks like this:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/112560351/195280049-11905baf-11c2-490b-8785-e0a7e206bf51.png">

### Suggested Solution

Just add a new property that will set margin-left / margin-right (depending on the position of the icon) icon to "auto". This is just one of the possible solutions.

`
 span[data-component="icon"] {
  margin-left:  'auto'
}
`

`
              <Button
                buttonType="primary"
                iconType="caret_down"
                iconPosition="after"
                fullWidth={isSmallScreen}
                spaceBetween={true} // <== new property to set it
               >
                text
              </Button>
`

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
@ljemmo @harpalsingh is this something we should support in Carbon?

**Comment by harpalsingh** [comment]
@robinzigmond this seems more like a pattern for a select menu not a button, the only button we use the caret like that is the multi-action button, so its "similar" to a select in a a way but this doesnt feel like a button requirement. Will also wait for @ljemmo  feedback from a DS perspective. 

@KonradWroblewski Mind sharing where this requirement is coming from pls

**Comment by ljemmo** [comment]
@KonradWroblewski Similar to Harpal's comment, please can you DM us on teams or slack with the original design request so we can better understand the requirement.

**Comment by Parsium** [comment]
Hi @KonradWroblewski @harpalsingh, do you reach a verdict with this one?

**Comment by KonradWroblewski** [comment]
Hi. I'm truly sorry for that long response time.

This requirement was related do this [TASK](This requirement was related do this TASK) and there is a [FIGMA](https://www.figma.com/file/OaRN1Gi6SrZkRuG9O2NRBV/branch/lImxBljPUO4Pyadu6lia8i/MTD-ITSA---Tier-1---Responsive-Web---Phase-1-Development-UI?node-id=10081%3A133798) (You need to move to mobile version)

**Comment by Parsium** [comment]
Hi @ljemmo, what do you think about the referenced figma designs?

**Comment by ljemmo** [comment]
@Parsium i've chatted with Lisa who is currently rebuilding this component in figma. She's supporting the proposed solution from @KonradWroblewski and we're happy to go ahead with his spec.

**Comment by Parsium** [comment]
Awesome thanks for letting us know @ljemmo, do you want us to wait until this rebuilding work is complete and the Design System docs have been updated before we add this feature in?

**Comment by ljemmo** [comment]
@Parsium she's more refactoring the component to reduce file memory so i think you can go ahead with the implementation of this feature request.

**Comment by Parsium** [comment]
Thanks @ljemmo, have added this to our backlog as **FE-5517.**

Given @harpalsingh's earlier comment it might be worth discussing if we want this styling to be standard for other components like `Menu` too, from a consistency point of view?
