### ISSUE TITLE
Alert and Dialog components right margin overflow on small screens.

### ISSUE THREAD

**Issue by phil9690** [Sage/carbon#5549]
### Current behaviour

When Alert and Dialog components are rendered within a viewport that is smaller than an Ipad, they get pushed up against the right edge of the screen and eventually overflow without any horizontal scroll.

### Expected behaviour

The components width should resize according to the size of the viewports, while maintaining margin on all four sides.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/morning-frost-bhuqfe?file=/src/index.js

### Carbon Version

110.1.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-5496
