### ISSUE TITLE
Error message is split by error icon

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#555]
An error message or warning message is split by the error/warning icon. The icon would be better positioned in the leftmost position followed by the text rather than splitting it.

![error_icon_splitting_error_message_2](https://cloud.githubusercontent.com/assets/12828099/15862595/12ea079c-2cc8-11e6-9e72-137812344b80.png)

**Comment by andrewjtait** [comment]
This has since been resolved https://github.com/Sage/carbon/pull/1130
