### ISSUE TITLE
Multi Action Button should not expand header

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#556]
When hovering over a multi action button the box will expand to fit its children content.

![multiaction](https://cloud.githubusercontent.com/assets/5382335/15888768/2e5a09f8-2d60-11e6-965c-5bd01b6c8a51.gif)

Instead of expanding on hover the title should stay at the same fixed width which allows users to click on neighbouring UI as shown in the example below.

![screen shot 2016-06-08 at 10 03 58](https://cloud.githubusercontent.com/assets/5382335/15888807/57c1a38c-2d60-11e6-9ba9-d95e7c1a0ac9.png)

**Comment by andrewjtait** [comment]
has this been fixed? it looks like the behaviour described https://carbon.sage.com/components/multi-action-button
