### ISSUE TITLE
Disabled Date Input dates show an active border when clicked

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#5567]
### Current behaviour

As the title suggests, clicking a disabled date in the calendar highlights it with an orange border. Clicking the blank space when `fixedWeeks`, `enableOutsideDaysClick` and `showOutsideDays` are set to false also shows the border
<img width="360" alt="Screenshot 2022-10-20 at 09 24 41" src="https://user-images.githubusercontent.com/55696743/196898149-6f5873c1-5092-4e64-bf8d-72d41a67dbc7.png">
<img width="357" alt="Screenshot 2022-10-20 at 09 29 50" src="https://user-images.githubusercontent.com/55696743/196898152-11d9916d-0e47-4069-90ed-71c277e9e3ab.png">

### Expected behaviour

Nothing is highlighted.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/clever-rosalind-m9yh1u?file=/src/index.js

### Carbon Version

111.4.0

### Design Tokens Version

2.3.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5504

**Comment by tempertemper** [comment]
The date picker should definitely be keyboard accessible. Although the user can type the date, offering the button based functionality to pointer/touch users but nobody else is a bit of a tease. And, of course, it fails [2.2.1 Keyboard](https://www.w3.org/TR/WCAG21/#keyboard).

Tabbing into the pop-up could be a short term fix, but some other accessibility issues were identified and Ashley Korsman worked on an accessible redesign, taking into account keyboard behaviour, etc., etc.

@ljemmo, I'll message you to arrange a catch-up with you and Ash on this.

**Comment by nicktitchmarsh** [comment]
@tempertemper more specifically what about navigation over the disabled dates? Do we think that users would expect to be able to arrow key over disabled dates and highlight them? In which case the mouse behaviour would also allow highlighting even if the element isn't interactable?

**Comment by tempertemper** [comment]
@nicktitchmarsh The disabled dates shouldn't be focusable as they're not interactive. Disabled buttons don't (or shouldn't) be in the tab index (or accessible via arrow key in a grid, like in this case).

**Comment by damienrobson-sage** [comment]
@nicktitchmarsh @tempertemper did anything ever come out of this? I've tried in the latest Carbon and it's still an issue, as shown.

<img width="285" alt="Screenshot 2024-05-24 at 09 35 57" src="https://github.com/Sage/carbon/assets/55696743/63f61f92-9c8a-4a42-a325-dd9c0a97eb21">
