### ISSUE TITLE
Multiple Sticky table header rows are not sticky

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#5576]
### Current behaviour

Given a FlatTable with sticky headers
When the headers are updated to nested headers
Then the header rows below the first are not sticky

### Expected behaviour

The header rows below the first remain sticky when updated.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/table-headers-oh5trr?file=/src/Table.tsx

### Carbon Version

111.8.0

### Design Tokens Version

2.48.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @MarcServat, we have a PR open at the moment that will address issue #5577, so this will be fixed once this is merged.

**Comment by edleeks87** [comment]
The linked PR is not related to this issue (see sandbox), I'll raise a ticket for this now

https://codesandbox.io/s/table-headers-forked-4eq7cg

**Comment by edleeks87** [comment]
FE-5514

**Comment by edleeks87** [comment]
I've ended up fixing it in the PR @Parsium linked as it was a trivial fix
