### ISSUE TITLE
Allow for ActionPopover to be focusable

### ISSUE THREAD

**Issue by ernon66** [Sage/carbon#5589]
### Desired behaviour

I would like to be able to set focus on ActionPopover or ActionPopoverMenuButton by passing a ref to it and calling ref.current?.focus()

### Current behaviour

For both of the components there is no ref property, wrapping in div and setting a ref or an id does not work either.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5528
