### ISSUE TITLE
Resolve arrow key navigation when MenuItem component is used with a wrapper component

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#5592]
### Current behaviour

When `MenuItem` component is used with a wrapper component, unable to navigate using arrow keys as it throws `RangeError: Maximum call stack size exceeded error`. 

### Expected behaviour

When `MenuItem` component is used with a wrapper component, able to navigate using arrow keys without any issues. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/menu-item-call-stack-exceeded-uyyiv5

### Suggested Solution

Resolve recursive `handleKeyDown` call here - https://github.com/Sage/carbon/blob/master/src/components/menu/__internal__/submenu/submenu.component.js#L246-L249

### Carbon Version

110.1.1

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5526
