### ISSUE TITLE
Could we have greater flexibility in the menu for nesting additional component types?

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon#5606]
### Desired behaviour

We have a requirement to include an image inside a menuitem for display only. (This is not something a user would select/click on).

![menu_example](https://user-images.githubusercontent.com/13569218/201345351-8bf7f529-351a-4386-a228-e3caa5c0142c.jpg)

So we used the MenuSegmentTitle component and inserted a Box but the console protests that this component is only expected to receive strings.

![image](https://user-images.githubusercontent.com/13569218/201345404-45acac8e-f33b-42de-a049-da6c91c2f67b.png)

Can you advise either an alternative approach or loosen child restrictions?

### Current behaviour

See above

### Suggested Solution

See above

### CodeSandbox or Storybook URL

https://codesandbox.io/s/carbon-menu-new-u3f8hb?file=/src/index.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@Chris3y I have raised https://github.com/Sage/design-system/issues/11 for DS to address this request. I will close this Carbon issue as the work will come through DS
