### ISSUE TITLE
Error - ActionPopover only accepts children of type `ActionPopoverItem`

### ISSUE THREAD

**Issue by SAHesse** [Sage/carbon#5609]
### Current behaviour

Actionpopover gives the error if the Actionpopoveritem is defined in another typescript file.

### Expected behaviour

We have defined Actionpopover item in separate typescript file and call it under <Actionpopver> tag. unfortunately it gives error that ActionPopover only accepts children of type `ActionPopoverItem`. I have created the one small example in codesandbox. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/k2se45

### Carbon Version

110.0.3

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Hi @SAHesse , We are currently working on a solution to allow custom components to be used inside some of our components. We use cloneElement in some cases and expect certain props to be passed down. FE-5284 is in review at the moment. Once this has been completed we can discuss the solution with you.

**Comment by nicktitchmarsh** [comment]
#5288 we believe is the same issue

**Comment by edleeks87** [comment]
The current recommended approach is to use functions or hooks to wrap Carbon components.

https://codesandbox.io/s/carbon-quickstart-forked-5v568f?file=/src/index.tsx

**Comment by nicktitchmarsh** [comment]
@SAHesse does the above example help you for now? We are working on FE-5284 as a general ticket for component wrapping

**Comment by SAHesse** [comment]
@nicktitchmarsh yes that was very helpful. Great to hear that you are working on the component wrapping
