### ISSUE TITLE
Menu: when using keyboard to navigate icons change theirs colors in dark and black theme 

### ISSUE THREAD

**Issue by dawidzarzycki** [Sage/carbon#5613]
### Current behaviour

When using keyboard to navigate icons change theirs colors in dark and black theme 

https://user-images.githubusercontent.com/19231884/201961469-d93decdf-dd7d-44f7-bcd7-ef90f5aaf227.mov

### Expected behaviour

Icons don't change their colors

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/menu--default-story

### JIRA Ticket (Sage Only)

SBS-45506

### Carbon Version

v111.9.1 (latest)

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5686 was raised as duplicate so I have closed original ticket
