### ISSUE TITLE
MenuFullscreen not exported in typescript definition file

### ISSUE THREAD

**Issue by stripeyjumper** [Sage/carbon#5617]
### Current behaviour

The file [components/menu/index.d.ts](https://github.com/Sage/carbon/blob/c4598081b13561059478494e48913c8e75239f75/src/components/menu/index.d.ts) does not export `MenuFullscreen`.

### Expected behaviour

`MenuFullscreen` should be exported in the typescript definition file

### CodeSandbox or Storybook URL

N/A

### Carbon Version

111.8.2

### Design Tokens Version

2.48.0

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

Other

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-4806 should address this issue, I have tagged this issue there
