### ISSUE TITLE
Flat table with sticky footer accessibility issue

### ISSUE THREAD

**Issue by Arkalex** [Sage/carbon#5632]
### Current behaviour

Running an accessibility audit with axe, it shows an accessibility issue on the table footer with pagination (also happening in Carbon documentation).

![Captura de Pantalla 2022-11-23 a las 8 43 53](https://user-images.githubusercontent.com/58083671/203494311-76fa214f-6ef9-4ff5-83bb-2f3b4eefb05d.png)

### Expected behaviour

Running axe shouldn't show any accessibility issues

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/flat-table--with-sticky-footer-inside-of-larger-div

### JIRA Ticket (Sage Only)

SBS-46683

### Carbon Version

111.12.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by mkrds** [comment]
Duplicate https://github.com/Sage/carbon/issues/5284
