### ISSUE TITLE
Date range error, accessibility issue

### ISSUE THREAD

**Issue by Arkalex** [Sage/carbon#5633]
### Current behaviour

When there's an error in a Date Range input and I run an accessibility audit with axe, it shows an accessibility issue (also happening in Carbon documentation).

![Captura de Pantalla 2022-11-23 a las 9 15 01](https://user-images.githubusercontent.com/58083671/203498750-ddafdd49-2a10-409f-a5ce-73f815362048.png)

### Expected behaviour

Running axe shouldn't show any accessibility issues

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/date-range--validations-string-component

### JIRA Ticket (Sage Only)

SBS-46691

### Carbon Version

111.12.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Relates to same issue described in #5594 and #5498

**Comment by Arkalex** [comment]
> Relates to same issue described in https://github.com/Sage/carbon/issues/5594 and https://github.com/Sage/carbon/issues/5498

Totally right, I can close this one then
