### ISSUE TITLE
Textbox component: the left padding of the prefix has disappeared

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#5646]
### Current behaviour

Since the 111.8.4 version, the left padding of the prefix has disappeared on the Texbox component.

### Expected behaviour

Have a left padding for the prefix on a Textbox component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/exciting-danny-qt3v71

### JIRA Ticket (Sage Only)

SBS-46888

### Carbon Version

111.8.4

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by JohnOxleySage** [comment]
We're also seeing this issue when upgrading from version 111.0.0 to version 111.4.1 of Carbon.

**Comment by mkrds** [comment]
FE-5565
