### ISSUE TITLE
Decoupling of icon component's `fontSize` and `bgSize` properties

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#5658]
### Desired behaviour

I would like to independently set the size of the icon and the background shape size, but they are coupled. 

### Current behaviour

If the fontSize is set to any value other than `small`, than the `bgSize` is automatically set to the same value

### Suggested Solution

This is controlled in `src/components/icon/icon.style.ts`'s `adjustIconBgSize` function. It seems like an undocumented feature, with not much explanation on why it is done so. 

Could this be removed? If you are okey with this change, I am happy to file a PR.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@harpalsingh @ljemmo thoughts on this?

**Comment by blaky** [comment]
Hi @edleeks87  @ljemmo ,
Thanks for coming back to me. We wanted to implement the following spec we get from our UX team:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/4557844/205076230-dcc1d968-8879-4701-94bf-9e8032ba5456.png">

To get this, I would need to set the icon `fontSize` to `medium `and the the `bgSize` to `large`.

**Comment by ljemmo** [comment]
@blaky are you using the icons from our foundations file? If yes, they should be 20px so perhaps this issue is not needed?

**Comment by Parsium** [comment]
Hi @blaky, were you able to take a look at Luke's comment above? :)
