### ISSUE TITLE
Validations doesn't allow custom component wrappers in ButtonBar

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#5669]
### Current behaviour

If I render a `Button` (or more buttons) in a `ButtonBar` using an intermediate wrapper component, then the library throws an  error:

```
Invariant Violation
ButtonBar accepts only `Button` or `IconButton` elements.
```

### Expected behaviour

When I render a `Button` component in a `ButtonBar` using an intermediate wrapper component, it should render just fine. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elegant-grothendieck-j1u89d

### Suggested Solution

Remove this validation from the application as it doesn't add much value, or turn it into a warning.

### Carbon Version

111.3.0

### Design Tokens Version

irrelevant

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

It is implemented in src/components/button-bar/button-bar.component.tsx:28

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
From our standpoint we feel this error is valid because we are populating the children of `ButtonBar` with props that will only work on them. We've decided not to support the use of wrappers because it would overcomplicate the component. Can you explain why you are using a wrapper here? Thanks

**Comment by blaky** [comment]
Hi @tomdavies73 
We wrap a number of buttons into other components that add some logic on the top of the basic button or HOC (for example Redux's connect) so the button can be automatically updated as the global state changes. These buttons are used at a number of places, sometimes in button bars, sometimes on their own. This restriction means that we would need to completely rewrite these components if we wish to render them into a ButtonBar, this restriction is not acceptable if we want to write reusable pieces of code.

**Comment by edleeks87** [comment]
IMO we don't need an `invariant` here, this component can easily use context to pass the needed props to the children which would also support the above implementation. I also notice we're using `element.type` instead of cloning which will mean any `ref`s passed to a child will not be preserved.

**Comment by edleeks87** [comment]
FE-5577
