### ISSUE TITLE
Make `MultiActionButton` accept `fullWidth` prop

### ISSUE THREAD

**Issue by bartkowalczyk** [Sage/carbon#5672]
### Desired behaviour

I would love the `MultiActionButton` to accept the `fullWidth` prop similarly to how a regular `Button` does, so it can span the whole available space eg on mobile views.

### Current behaviour

Currently the `MultiActionButton` itself does not accept the `fullWidth` prop and it is only available on the descendant `Button`s which roll down as options. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
We'll be adding `customWidth` support as part of FE-5517 and DS feel there's not much value in having this prop and `fullWidth` as you can achieve the same layout by passing `customWidth="100%"` etc. I've linked this issue to the ticket mentioned and we'll ensure the functionality required is tested as part of the work on it
