### ISSUE TITLE
Pager - disable free-text page number navigation

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#5674]
### Desired behaviour

The ability to type in the desired page number should be optional (i.e. input containing current page can be disabled)

### Current behaviour

The Pager allows you to navigate to pages which may not necessarily exist for the use case implemented. Further explanation from Slack discussion on the matter:

`We make our first call without tokens, which is interpreted by the database as "get page 1". If there are more records than the page size you've asked for, you'll get a token back for the next X records. Page two would then return a token to get you the previous set of results (and another, separate token if there are records beyond the ones shown - we work with a previousToken and nextToken approach). These tokens control Carbon's navigation buttons, but asking the database for "page 2" couldn't work as we have know way of knowing what the token for page 2's records would be - it's all calculated server-side.`

### Suggested Solution

Allow me to pass a prop to the pager that disables the input and replaces it with a simple text label (`Page X of Y`)

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@ljemmo Damien is suggesting we should create a prop which if true disables the input on a pager. Do you feel this is something we should support?

**Comment by tomdavies73** [comment]
Hi @clairedenning would you be able to have a look at this please, Damien is suggesting a prop to disable the pager input and replace it with a text label. Do you feel this is something we could support? Thanks

**Comment by clairedenning** [comment]
Hi @tomdavies73. In Figma, the text input part of the pagination component behaves exactly as a text input component, and so it has a read only state. Would that work for you, rather than replacing the text input component with a label?
![image](https://user-images.githubusercontent.com/49988488/212044526-6b84bb53-432f-460c-802a-83b676df5cb8.png)

**Comment by tomdavies73** [comment]
@clairedenning that is a great point, a read-only attribute would achieve the same result and would require a lot less changes. I believe If we were to implement this it would be with the use of a prop, when present and truthy would remove the "Page" and "of 10" labels either side of the text input and leave one read-only text input which has a value of "Page X of Y". What do you think?

**Comment by Parsium** [comment]
Hi @damienrobson-sage, would making the number input read-only or disabled fix your issue? Or is this being flagged as a problem accessibility-wise or such?

**Comment by damienrobson-sage** [comment]
@Parsium I think read-only would look better, but either should work in the first instance

**Comment by ljemmo** [comment]
Yeah lets go with readonly as disabled doesn't pass contrast checkers. The above looks good to me. 👍

**Comment by Parsium** [comment]
Cheers guys 👍🏼 Let's do this then, I'll raise this as a ticket

**Comment by Parsium** [comment]
@ljemmo @clairedenning would you be able to update the DS zeroheight docs for the Pagination component to include this use case?

**Comment by Parsium** [comment]
FE-5658

**Comment by ljemmo** [comment]
@Parsium i'll create a ticket on our backlog for this, thanks!
