### ISSUE TITLE
RadioButtonGroup margin attribute is not set

### ISSUE THREAD

**Issue by andreiamar** [Sage/carbon#5681]
### Current behaviour

Setting margin bottom for a RadioButtonGroup component does not work.

### Expected behaviour

I would like to be able to set margin bottom to 0 to respect the design.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/keen-sky-80105i?file=/src/App.tsx

### Carbon Version

111.16.0

### Design Tokens Version

2.45

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5583
