### ISSUE TITLE
TextEditor: on a Dialog component, you cannot access the body via the keyboard

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#5685]
### Current behaviour

When you edit a comment and use the keyboard to move through the edit dialogue you cannot access the body of the text. Focus moves from the title field to the Bold text.

### Expected behaviour

The expected behaviour is that there is a yellow frame around the text edit box and the cursor appears before the first character in the body text box.  

### CodeSandbox or Storybook URL

https://codesandbox.io/s/gifted-tree-s6wzy7

### JIRA Ticket (Sage Only)

SBS-41698

### Carbon Version

111.16.0

### Design Tokens Version

2.48.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5582
