### ISSUE TITLE
A NumeralDate in a Tab component causes looping renderings

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#5692]
### Current behaviour

Since carbon version 111.19.0, if a NumeralDate is in a Tab component, rendering never stops.

### Expected behaviour

A NumeralDate in a Tab component must not cause looping renders.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nifty-chandrasekhar-oux82z

### JIRA Ticket (Sage Only)

[SBS-44009](https://jira.sage.com/browse/SBS-44009)

### Carbon Version

111.19.0

### Design Tokens Version

2.48.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5585
