### ISSUE TITLE
The `Image` component with empty `alt` prop

### ISSUE THREAD

**Issue by oo1john-serv** [Sage/carbon#5698]
### Desired behaviour

I would love `Image` to accept empty `alt` prop to be able to follow WAI recommendation for decorative images https://www.w3.org/WAI/tutorials/images/decorative/

### Current behaviour

Currently the `Image` throw an error `Error: Uncaught [Invariant Violation: Please provide an 'alt' string when rendering the 'Image' component as an 'img' element.]`

### Suggested Solution

Allow `Image` component to accept the empty `alt=""` prop.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/serverless-hill-xmmbu1?file=/src/index.js

### Anything else we should know?

The root cause reside on `Image` component: https://github.com/Sage/carbon/blob/master/src/components/image/image.component.tsx#L11-L14

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by grabkowski** [comment]
FE-5590

**Comment by Parsium** [comment]
Hi @oo1john-serv 👋🏼 We have recently released [Carbon v114.12.0](https://github.com/Sage/carbon/releases/tag/v114.12.0) which should address this issue for you. Let us know if you have any further problems 👍🏼
