### ISSUE TITLE
TileSelectGroup - without description prop renders an empty paragraph 

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#5699]
### Current behaviour

Given a TileSelectGroup
When no description prop is passed
Then an empty paragraph is rendered adding a blank space at the top of the component. 

### Expected behaviour

Given a TileSelectGroup
When no description prop is passed
Then the first tile is rendered without a blank space at the top. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elastic-julien-8qqh78?file=/src/index.js

### Carbon Version

111.22.0

### Design Tokens Version

2.64.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@MarcServat would you be able to provide a screenshot of the issue, as we cannot see the current behaviour described in the provided code sandbox? Thanks

**Comment by tomdavies73** [comment]
FE-5597
