### ISSUE TITLE
Badge component should support static informative display

### ISSUE THREAD

**Issue by przemyslawzalewski** [Sage/carbon#5706]
### Desired behaviour

Quite often the `Badge` component is used for plain informative display purposes and is not intended to be interacted with. To achieve that, the `Badge` component (by default?) should support only the display of the counter, not capture focus, and don't show the clear button.

### Current behaviour

However, it still shows the "X" button on hover and the badge is capturing the focus and does not support any option to turn off that behavior.

https://user-images.githubusercontent.com/30114244/208888908-cbcd0f92-b31f-4323-bab1-4c71c6ad2480.mov

### Suggested Solution

The simplest solution would be to turn off the "Clear button" display and interactivity in case the (optional) `onClick` handler is not present:

<img width="1021" alt="Zrzut ekranu 2022-12-21 o 11 57 51" src="https://user-images.githubusercontent.com/30114244/208889376-b72ae88a-d40e-4d08-9663-82f53b42d28b.png">

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@clairedenning do you have any thoughts on this? @przemyslawzalewski is suggesting we have a read-only version of the Badge component e.g no focus and no close button. So just info and a counter, is this something we could support? We do have the Pill component for just displaying info, but this does lack a counter functionality. Thanks

**Comment by edleeks87** [comment]
https://codesandbox.io/s/jovial-galois-iiwv38?file=/src/index.js illustrates the issue

**Comment by Parsium** [comment]
Hi @clairedenning @laiasage, would one of you be able to look at this proposed design pattern for us please? :)

**Comment by clairedenning** [comment]
@v99rly do you have any thoughts on this? Does a non-dismissible badge need to look different from a dismissible one in its default state?

**Comment by v99rly** [comment]
I don't think it really matters to be honest. From an accessibility point of view a screen reader would it just needs to have a `role` attribute with a value of `status`.

**Comment by Parsium** [comment]
Thanks for this @clairedenning @v99rly 👍🏼 I've now added this onto our backlog

**Comment by Parsium** [comment]
FE-5687
