### ISSUE TITLE
Firefox: Scrollbar-gutter bug

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#5708]
### Current behaviour

Please see ticket for relevant links and screenshots

An unnecessary horizontal scroll bar is created due to the vertical scroll bar being created within `table` as shown below which makes the table size exceed `flat-table-wrapper`.

### Expected behaviour

Like below sandbox example, the vertical scroll bar has to be outside of `table`.
![Screenshot 2022-12-21 at 12 20 53](https://user-images.githubusercontent.com/90848080/208900217-769d7ab8-4665-4341-a92d-e6a72f7a3588.png)

### CodeSandbox or Storybook URL

https://08v0ys.csb.app/

### JIRA Ticket (Sage Only)

SBS-47459

### Suggested Solution

Giving `scrollbar-gutter:stable` CSS attribute to the `Box` component resolves the issue like below.

 It would be great to be able to override that attribute or set this as the default.
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

### Carbon Version

111.12.3 (the bug persists in the 111.22.1)

### Design Tokens Version

2.45.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

I created a sandbox example to reproduce the error using the same components and props but I could not. So I was not able to identify the exact reason for this bug in Firefox. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
FE-5598

**Comment by JoaArias** [comment]
The issue can not reproduce on v3.51.2

**Comment by Parsium** [comment]
Thanks for letting us know @JoaArias 👍🏼 I've double checked the codesandbox and `FlatTable` and I couldn't seem to reproduce this as well using Firefox v121.0, which is the latest version as of writing. I'm going to close this ticket as addressed, but feel free to reopen this if the problem comes back 😄
