### ISSUE TITLE
Press escape to dismiss dropdown on sidebar

### ISSUE THREAD

**Issue by victoriadeanton** [Sage/carbon#5716]
### Current behaviour

This is a minor accessibility issue
While navigating in a sidebar, once pressing the escape key to close a drop down list the whole modal is closed instead.

### Expected behaviour

It should close the current dropdown open and not the complete sidebar

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sidebar-with-select-nllhe4

### Carbon Version

111.8.0

### Design Tokens Version

2.45.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5624
