### ISSUE TITLE
FilterableSelect calls onOpen without user interaction

### ISSUE THREAD

**Issue by ernon66** [Sage/carbon#5719]
### Current behaviour

Reproduced on codesandbox.

`FilterableSelect` does not have the same behaviour as `Select` when providing the exact same props.

`onOpen` can be repeatedly called without any user input if some props are modified.

### Expected behaviour

`onOpen` is only called when the user clicks on a `FilterableSelect` component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/lucid-waterfall-8thv8k?file=/src/LoadingSelect.tsx:897-909

### JIRA Ticket (Sage Only)

SBS-47539

### Suggested Solution

quote from @robinzigmond :

"
On initial investigation the cause is this useEffect in FilterableSelect:

```
useEffect(() => {
  if (!isOpen) {
    setFilterText("");
  } else if (onOpen) {
    onOpen();
  }
}, [isOpen, onOpen]);
```
    
In your sandbox example, this actually fires on every render because onOpen (your loadItems) is not memoised in any way. 

I've been attempting to fix this with useCallback but I don't think it's entirely solvable within your example, because the callback in your case updates remainingFailedRequests which is impossible to get rid of as a dependency of getItems and therefore of loadItems.

As you observe, simple Select does not have this problem (because it has no similar useEffect) so we should investigate how we might be able to achieve the desired effect in FilterableSelect without running onOpen every time its dependencies change. 
"

### Carbon Version

111.9.1

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

111.3.0 on codesandbox but happened originally with 111.9.1

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5612
