### ISSUE TITLE
Text in Note overlap with inlineControls

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#5734]
### Current behaviour

With a Note with no title but a long text and inline controls, depending of the width, the text can overlap with the ActionPopover icon

![image](https://user-images.githubusercontent.com/16415182/211034567-9e345916-d732-43b2-a528-3104f11ea1b3.png)

### Expected behaviour

The text never overlap with the icon

### CodeSandbox or Storybook URL

https://codesandbox.io/s/unruffled-smoke-pshbun?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-49055

### Carbon Version

111.22.3

### Design Tokens Version

3.0.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5611
