### ISSUE TITLE
<OptionGroupHeader> causes error in <Select> when using KeyDown

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#5746]
### Current behaviour

 Having `OptionGroupHeader` in `Select`, the scrollbar in the dropdown is not in sync when selecting options with the keyboard arrows. As shown in the sandbox example, the scroll does not continue until the last option.
![Screenshot 2023-01-12 at 11 10 08](https://user-images.githubusercontent.com/90848080/212039315-760bf669-5c9a-484a-8a3a-924d0e0f32b8.png)

### Expected behaviour

 The scroll should reach the last option when using keyboard.
![Screenshot 2023-01-12 at 11 10 22](https://user-images.githubusercontent.com/90848080/212039357-c71a1b5a-4c0a-4991-905f-da3910f68bf1.png)

### CodeSandbox or Storybook URL

https://r57iij.csb.app/

### JIRA Ticket (Sage Only)

SBS-45056

### Suggested Solution

  Please incorporate the pixels taken by `OptionGroupHeader` when auto-scrolling happens.

### Carbon Version

111.12.3

### Design Tokens Version

2.45.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5623

**Comment by JinCoreana** [comment]
Our QA has confirmed that this issue has been resolved. Thank you, Carbon team!
