### ISSUE TITLE
Tabbing/focus trap issues persist with editable AG Grid.

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon#5749]
### Current behaviour

Follow up from:
https://github.com/Sage/carbon/issues/5544

When this issue was originally logged, we re-produced it in a sandbox with minimal code. As far as that goes, the fix worked.

However, AG grid is mostly used for inline editing and if you enable that in the same sandbox, the focus trap causes further issues with tabbing.

I've modified the original sandbox here:
https://codesandbox.io/s/exciting-dew-tz8pml?file=/src/index.js

I've made the cells editable and changed the carbon-react version to an arbitrary one form the past (75.2.5),

If you double-click the cell with "Toyota" in there and press TAB, you can see the correct behaviour, where it will tab to the next editable cell (in edit mode). 

If you then update the carbon version to the one with this fix (113.0.1) and try the above steps, it will no longer tab to the next editable cell. 

### Expected behaviour

Tabbing in AG Grid should still work as expected

### CodeSandbox or Storybook URL

https://codesandbox.io/s/exciting-dew-tz8pml?file=/src/index.js

### Carbon Version

113.0.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5622
