### ISSUE TITLE
`Popover` crashes when embedded within `Sidebar`

### ISSUE THREAD

**Issue by przemyslawzalewski** [Sage/carbon#5753]
### Current behaviour

When the internal `Popover` component (used by `FilterableSelect` for example) is embedded within a `Sidebar`, it can lead to crashes due to the reference to the node not always being present.

Please click "Switch pages" button on the attached reproduction CodeSandbox to experience the crash. Please investigate the console to see the initial `PropTypes` error.

https://user-images.githubusercontent.com/30114244/212655156-585b2bf0-38f5-4f37-91c7-a10a76994ee2.mov

<img width="244" alt="Missing ref" src="https://user-images.githubusercontent.com/30114244/212655206-f74e3b86-cf06-41c6-8316-39d5483bf154.png">

### Expected behaviour

The `Popover` component should never crash, no matter where it is embedded and no console errors should be shown, like:

```
Warning: Failed prop type: The prop `reference.current` is marked as required in `Popover`, but its value is `undefined`.
    at Popover
```

### CodeSandbox or Storybook URL

https://codesandbox.io/s/frosty-paper-n8sqor

### Suggested Solution

The `as` cast seems to be unsafe, it would be better to properly handle the nullability at https://github.com/Sage/carbon/blob/master/src/__internal__/popover/popover.component.tsx#L85

Moreover, all the `ref` access should be investigated for possible nullability and possibly handled via the null-safe property access: https://github.com/Sage/carbon/blob/master/src/__internal__/popover/popover.component.tsx#L52

### Carbon Version

113.0.3

### Design Tokens Version

2.64.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5621

**Comment by mkrds** [comment]
@przemyslawzalewski 
You're right about the `as` type assertion being unsafe, I'll fix it

However I'm not sure I understand the issue you're pointing to about the null-safe property access of the `reference` prop. `React.RefObject<T>` is an object with `current` property being either `null` or `T`
`reference` prop is declared as required meaning that it will always be an object of shape `{ current: T | null }` 

Considering all that the following line seems perfectly fine
`const candidateNode = reference.current?.closest("[role='dialog']")`

**Comment by przemyslawzalewski** [comment]
@mkrds In that case, only the prop types should allow it to be nullable/undefined as we see this warning raised constantly:

> Warning: Failed prop type: The prop `reference.current` is marked as required in `Popover`, but its value is `undefined`.
    at Popover

You are right, the access is `null`-safe so everything is good 👍  This is due to the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) short-circuit behavior:

> If the object accessed or function called using this operator is undefined or null, the expression **short circuits and evaluates to undefined** instead of throwing an error.

<img width="573" alt="Zrzut ekranu 2023-02-3 o 14 49 47" src="https://user-images.githubusercontent.com/30114244/216619433-1a3ed2a1-4f9b-4b6a-aa87-9fe1eb018e50.png">

Thanks for taking look at this issue. The crash is more important for us but great that the warning got your attention as well 🙇

**Comment by mkrds** [comment]
@przemyslawzalewski Sorry for the late reply, you're right about the propTypes being incorrect. Unfortunately this bug is caused by a package that we're using to automatically generate propTypes from the interfaces (typescript-to-proptypes). Problem is that it is no longer maintained and I think we might need to bite the bullet and get rid of the propTypes completely as I don't think it is viable to maintain this package on our own.
