### ISSUE TITLE
nested modals not treating focus correctly after click on non-focusable content

### ISSUE THREAD

**Issue by robinzigmond** [Sage/carbon#5754]
### Current behaviour

On the attached codesandbox:

- open the full-screen dialog
- open the nested dialog
- click on any non-focusable content (in either child dialog or full-screen one - it doesn't mater)

Now focus has been lost to the document body (which is inevitable here), but pressing tab cycles through the focusable elements in the full-screen dialog, and never reaches the nested dialog.

[Note: I have been told that the issue isn't observable to some people. That's not too surprising as it's basically caused by a race condition I believe - but it always seems to "work" for me!]

Note that the exact types of modal component don't seem to matter - the original bug relates to a full-screen dialog opening on top of a sidebar.

### Expected behaviour

Focus should only ever be on elements in the currently "active" dialog and should return there on pressing tab if lost to the body.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/intelligent-gianmarco-7ivt11?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-48145

### Suggested Solution

In `getNextElement` in `focus-trap-utils.js` we check for whether focus is currently on the document body and return the first active element (which the calling code then focuses on). When there are multiple modals open this code is called for each modal and, depending on the order the event handlers fire in, may leave focus in the wrong modal, as has been observed.

I think the fix is to make use of the `TopModalContext` that was introduced for other purposes and return `undefined` from this function if the modal concerned is not the top one.

### Carbon Version

113.0.3

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5620
