### ISSUE TITLE
Tile component rendering empty element when child element is null

### ISSUE THREAD

**Issue by phil9690** [Sage/carbon#5760]
### Current behaviour

When the Tile component is rendered with any JSX child element other than the first that is null, it renders an empty element with a border-top set.

### Expected behaviour

The component should not render anything when a child component is null.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/carbon-tile-test-forked-wcc7rc?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-49777

### Carbon Version

114.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by PaulSumner-Sage** [comment]
SBS-49952 is also related is this can be linked on the FE ticket when picked up

**Comment by edleeks87** [comment]
@phil9690 @PaulSumner-Sage if you need a workaround you should be able to get around this by wraping the children in a fragment

https://codesandbox.io/s/carbon-tile-test-forked-kih72w?file=/src/index.js

**Comment by edleeks87** [comment]
FE-5647

**Comment by edleeks87** [comment]
This isn't something we can fix with the current implementation of `Tile`. We plan to refactor the component to export the internal elements we currently render internally to allow implementation teams to compose the layout they want themselves in FE-5681

**Comment by edleeks87** [comment]
I'm going to fix this as part of FE-6180 as it's quite trivial to solve and I'd like to get it released before I make the breaking change to support a compositional approach
