### ISSUE TITLE
Can't set data-role attribute on Tab component

### ISSUE THREAD

**Issue by andreiamar** [Sage/carbon#5762]
### Current behaviour

The Tab component can't have a data-role attribute.

### Expected behaviour

We need to be able to set a `data-role` attribute on the Tab component for user tracking purposes.

### CodeSandbox or Storybook URL

none

### JIRA Ticket (Sage Only)

SBS-49660

### Carbon Version

111.16.0

### Design Tokens Version

2.45.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5648
