### ISSUE TITLE
Buttons used as renderOpenComponent in PopoverContainer don't respect fullWidth prop

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#5784]
### Current behaviour

The open button of a `PopoverContainer` does not take up the entire space available when set to fullWidth within a Box . If I manually set the width of the `popover-container` div to 100%, the button behaves as expected.

![Screenshot 2023-01-25 at 11 17 25](https://user-images.githubusercontent.com/55696743/214852237-39980910-d182-4486-a2d0-e0cfd2b28707.png)

### Expected behaviour

The button uses the spacing correctly, e.g.:

![Screenshot 2023-01-25 at 11 19 43](https://user-images.githubusercontent.com/55696743/214852242-486a14dd-c017-49be-9f15-4ada4349a8f7.png)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/falling-paper-kd9biz?file=/src/index.tsx

### Carbon Version

113.0.1

### Design Tokens Version

2.48.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5661

**Comment by damienrobson-sage** [comment]
@nicktitchmarsh No immediate rush on it as far as I'm aware. It's not blocking any releases, we're of the understanding that it'll be fixed when it's fixed.
