### ISSUE TITLE
Date picker German translations

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#5786]
### Current behaviour

The German abbreviated translations in the Date Picker calendar are three characters long

### Expected behaviour

The German abbreviated translations in the Date Picker calendar should only be two characters long

### CodeSandbox or Storybook URL

https://carbon.sage.com/iframe.html?id=date-input--locale-override-example-implementation&viewMode=docs&args=#locale-override

### Suggested Solution

Trim the strings when German (`de`) locale detected

### Carbon Version

latest

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5660
