### ISSUE TITLE
ActionPopover items are not aligned if some items have icons while others don't

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#5801]
### Current behaviour

When an `ActionPopover` menu renders with a mix of items with and without icons then the labels are not aligned.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/4557844/216308744-6dc58ffd-b45f-470b-9d98-b243643b5b6a.png">

### Expected behaviour

When an `ActionPopover` menu renders with a mix of items with and without icons then the labels should be aligned and the icon's space should be preserved on the items without icons.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/affectionate-sound-cqi2fv?file=/src/App.js

### Carbon Version

114.7.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @harpalsingh, we discussed there are two alignment approaches for the item text which DS don't provide some guidance on which is right.

Do we either:
1. Align the text of all items (regardless of icon presence) - in orange in image below
2. Align item text with the other icons - in purple in image below

<img width="251" alt="action-popover-bug" src="https://user-images.githubusercontent.com/18368713/217293546-39b43b79-dd11-46a4-b674-84a5e6ca78d1.png">

What do you think?

**Comment by Parsium** [comment]
@clairedenning @ljemmo would you be able to look at this for us please?

**Comment by ljemmo** [comment]
@Parsium  and @nineteen88 It looks like we're supporting approach 2 in the DS today. Here's a screenshot of the menu in figma. usually we would advise that if using icons, you should use them on all menu items. Or alternatively you should use no icons on all items. However in the edge case that you have a mix, i'd suggest we go for approach 2 for MVP and iterate further if we get feedback to do so. Sound like a plan? Then at least carbon will have parity with the DS.
![Screenshot 2023-03-15 at 10 58 59](https://user-images.githubusercontent.com/98600534/225289571-45aa0070-5284-4050-ae31-c8585c2cdc2f.png)

**Comment by Parsium** [comment]
Awesome thanks for this @ljemmo 👍🏼 In that case we'll raise a ticket to support that second approach

**Comment by Parsium** [comment]
FE-5722
