### ISSUE TITLE
Accessibility issues on DateInput component

### ISSUE THREAD

**Issue by harsh096** [Sage/carbon#5804]
### Current behaviour

Have few Axe Accessibility Issues mentioned in SBS-50673

![image](https://user-images.githubusercontent.com/28267834/216553809-44a0c886-d198-40e2-9dfb-bd73e2b0ac69.png)

### Expected behaviour

Resolved Accessibility Issues

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/date-input--default-story

### JIRA Ticket (Sage Only)

SBS-50673

### Carbon Version

114.2.0

### Design Tokens Version

2.59.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
I've removed a shared video (after making a local copy), whoever raises the jira ticket can message me and I'll provide it

**Comment by Parsium** [comment]
FE-5675
