### ISSUE TITLE
`Link`-button does not set `type="button"` like `Button` and submits forms accidentally

### ISSUE THREAD

**Issue by przemyslawzalewski** [Sage/carbon#5807]
### Current behaviour

A `Link` with an `onClick` handler embedded in a `Form` is causing sudden navigations due to implicit form submissions as the HTML buttons are `type="submit"` by default (weird, I know). However, the `Button` does not behave the same way which ends up in a confusing state (as it sets `type="button"` internally).

This issue can be worked around on the `Form` level to `stopPropagation` within the `onSubmit` handler but the inconsistent behavior already caused hard-to-debug issues for us. This is especially risky when some external component uses a `Link` and suddenly starts to refresh the page when clicked (by triggering the unwanted form submission).

https://user-images.githubusercontent.com/30114244/216636568-fcf507ff-aa88-4ca8-b88a-0682b65b42df.mov

### Expected behaviour

The `Link` component with the `onClick` handler which is rendered as `button` should behave just like `Button` component and set `type="button` by default. Just like `Button`, the `Link` component should support `type` property when rendered as button to support other use cases (optional).

### CodeSandbox or Storybook URL

https://codesandbox.io/s/hungry-sutherland-kpp62q

### JIRA Ticket (Sage Only)

SBS-51076

### Suggested Solution

When the `Link` is going to be rendered as `button`, please set `type="button"` to match the `Button` default behavior (which in contrast to HTML's default `button` behavior is `type="submit"` implicitly).

### Carbon Version

114.7.1

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5674

**Comment by DipperTheDan** [comment]
Might be worth re-testing this with the latest version of Carbon as [this release v117.7.1](https://github.com/Sage/carbon/releases/tag/v117.7.1) might have fixed this issue.

**Comment by nicktitchmarsh** [comment]
I tested in the codesandbox and it seems to be resolved so I am closing this for now
