### ISSUE TITLE
Icon - cannot use fontSize prop along with bgSize

### ISSUE THREAD

**Issue by sagemihir** [Sage/carbon#5812]
### Current behaviour

In carbon Icon - if fontSize prop is used along with bgSize prop, the design of the icon is disturbed 

### Expected behaviour

Required - The size should maintain 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/carbon-icon-issue-z0jpr6?file=/src/App.js

### JIRA Ticket (Sage Only)

SBS-47530

### Carbon Version

112.0.2

### Design Tokens Version

2.45.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Seems source of the problem is this function here:

```ts
function adjustIconBgSize(fontSize?: FontSize, bgSize?: BgSize) {
  if (fontSize && fontSize !== "small") {
    return iconConfig.backgroundSize[fontSize];
  }

  return bgSize ? iconConfig.backgroundSize[bgSize] : undefined;
}
```

**Comment by Parsium** [comment]
FE-5672
