### ISSUE TITLE
`VerticalMenuItem`'s settable open/close state

### ISSUE THREAD

**Issue by bartkowalczyk** [Sage/carbon#5822]
### Desired behaviour

When using the `VerticalMenu` component as the main app navigation with `VerticalMenuItem`s holding links to app routes and the `active` prop is set according to the url in the browser, I would like to see the nested subitem which holds a link to the currently active page when the app loads, without the need to expand the parent nav item.

### Current behaviour

As of now, when the current route matches the link which is held within a nested `VerticalMenuItem`, this item is hidden from the user until they explicitly expand the collapsible parent.

### Suggested Solution

Allow for passing a prop like `expanded` to the `VerticalMenuItem` which is a parent to other  `VerticalMenuItem`s (or provide a method to programatically set the collapsed/expanded state).

### CodeSandbox or Storybook URL

https://codesandbox.io/s/musing-keldysh-31cyh0?file=/src/App.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@clairedenning @ljemmo would you be able to review this enhancement from a UX/DS perspective? Is this something we should support in Carbon with the new `VerticalMenu` component?

**Comment by ljemmo** [comment]
Seems like a sensible proposal to me. I'd be happy for you to bake this in as default behaviour. 👍

**Comment by sianford** [comment]
FE-5702
