### ISSUE TITLE
Error unannounced in forms

### ISSUE THREAD

**Issue by Arkalex** [Sage/carbon#5828]
### Current behaviour

Error message is not read by VoiceOver when they appear

### Expected behaviour

Error message is read by VoiceOver when they appear

### CodeSandbox or Storybook URL

https://codesandbox.io/s/admiring-dust-jnecnj

### JIRA Ticket (Sage Only)

SBS-48611, SBS-48601

### Carbon Version

114.9.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-5669
