### ISSUE TITLE
Preview component width issue

### ISSUE THREAD

**Issue by andreiamar** [Sage/carbon#5830]
### Current behaviour

When the width is set, the width is set to both the preview element and it's container, the result being:
- when using percentages, the preview element width would be compounded
- when stacking multiple preview components, the border not be full width of the main container

<img width="348" alt="image" src="https://user-images.githubusercontent.com/112492571/218424362-7539f3c6-abb3-4b5a-a7ab-be6471e22b5c.png">

### Expected behaviour

I'm expecting that when the width is set and multiple elements stacked, the border acting as a divider is not affected by this value.

Also when using percentages, the width should be applied only to the preview element and not it's container. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/interesting-pike-2l7xeo

### JIRA Ticket (Sage Only)

SBS-50426

### Carbon Version

111.16.0

### Design Tokens Version

2.45.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@andreiamar thanks for raising this, would you be able to provide a code sandbox so we can have an example of the incorrect behaviour?

**Comment by Parsium** [comment]
Hi @andreiamar, it seems `Tile` sets a top border on any immediate descendent that is a `div`, which is why in your provided sandbox wrapping the `Preview` component in a `Box` fixes this issue. Looking at the sandbox, the layout seems quite niche, so may I ask if this issue is related to implement a particular design you have been given?

**Comment by sianford** [comment]
@andreiamar can you please clarify the above from @Parsium? Thanks.
