### ISSUE TITLE
Page title set width as inline element

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#5833]
### Current behaviour

Given a Page component
When setting the title prop with an element
Then it takes the width as an inline element

### Expected behaviour

Given a Page component
When setting the title prop with an element
Then it takes the full width as a block element

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elastic-julien-8qqh78?file=/src/index.js

### Carbon Version

114.12.13

### Design Tokens Version

4.8.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by ljemmo** [comment]
@tomdavies73 this isn't something we support currently in the DS. I could potentially see us using this as a kind of 'subheader' underneath the sidebar heading though. - @MarcServat please can you get the designer that you're collaborating with to reach out to us either via the DS extended team meeting or the DS fortnightly drop-in to discuss this proposal further?

**Comment by MarcServat** [comment]
@ljemmo thank you for the reply. The designer has already been notified.

**Comment by Parsium** [comment]
FE-5692

**Comment by nicktitchmarsh** [comment]
This should now be possible with the Title type being changed to Node
