### ISSUE TITLE
VoiceControl does not work with the Select component

### ISSUE THREAD

**Issue by szeyingyau** [Sage/carbon#5834]
### Current behaviour

1. Enable Voice Control on Mac
2. Say the command - "Show numbers"
3. The command does not display a number next to the Select component to be interacted with 

### Expected behaviour

The "Show numbers" command displays a number next to the Select component to be interacted with when VoiceControl is enabled on Mac

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/select--default-story

### Carbon Version

114.12.3

### What browsers are you seeing the problem on?

Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-5683

**Comment by nicktitchmarsh** [comment]
This was a Mac Update issue
