### ISSUE TITLE
enable multiline subtitles for Dialog

### ISSUE THREAD

**Issue by ibsenjg** [Sage/carbon#5844]
### Desired behaviour

Allow Dialog, subtitle prop to change, not to reveice exclusively a string parameter, but considering using an array of strings. render all iff present or not render the wrapper. This way i could show more than one subtitle, separated by line spaces or rows.

### Current behaviour

Dialog subtitle prop allows only string, this means im limited to one line and one message, as string this cannot be splitted or rearranged to be in multiple lines.

### Suggested Solution

Hello team,
There is a property from Dialog component to set subtitle, its a string so only allows one line.
A new design is in the need of having multilines for the subtitles. The way I found to make this happen is to use title property which allows to use a Component, this will do it for now, but the native prop for subtitle should also work similar than title on this regard.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pensive-minsky-v1kupv

### Anything else we should know?

Also note that using a component at title prop is not showing the subtitle, even if present

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5691

**Comment by ibsenjg** [comment]
This suggestion is not suitable, as this subtitle parameter gives aria description for screen readers, changing it will affect negatively to it. We can check this development and arrange some changes alongside design and a11y teams to watch over this without affecting current good practices.
