### ISSUE TITLE
First element isn't focused when clicking then tabbing on a menu

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#5850]
### Current behaviour

When clicking the submenu (to focus it) and then pressing tab the first element in the submenu is skipped.

### Expected behaviour

When clicking the submenu and then tabbing once, the first menu item is focused.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/carbon-menu-items-forked-rvsz51?file=/src/App.js%5D(https://codesandbox.io/s/carbon-menu-items-forked-rvsz51?file=/src/App.js).

### Carbon Version

114.13.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5689

**Comment by edleeks87** [comment]
Apologies I misunderstood the issue and fixed a similar one that I saw when I clicked one of the submenu items, FE-5699 has been raised to address this
