### ISSUE TITLE
Button Minor is not setting padding Y

### ISSUE THREAD

**Issue by Arkalex** [Sage/carbon#5856]
### Current behaviour

I'm trying to set a custom `px` value, but is not working.
When I try to set `py` o `p` is working fine

### Expected behaviour

Prop for setting padding on Y should work fine

### CodeSandbox or Storybook URL

https://codesandbox.io/s/blissful-currying-7e3b3h

### JIRA Ticket (Sage Only)

SBS-51836

### Carbon Version

114.14.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
@ljemmo are these padding props meant to be customisable for Button Minor?

**Comment by ljemmo** [comment]
@sianford padding should be baked in for button minor and not overridable.

**Comment by Parsium** [comment]
Thanks for this @ljemmo, I'll close this issue in that case.
