### ISSUE TITLE
Missing minor button features

### ISSUE THREAD

**Issue by blaky** [Sage/carbon#5858]
### Current behaviour

Minor buttons don't render correctly in ButtonBar component and there is no way of declaring a minor IconButton or a ButtonToggle

Some other components don't render well with minor buttons, but I am not sure if they are supported: SplitButton, MultiActionButton

### Expected behaviour

To be able to render all DLS defined minor buttons scenarios from https://zeroheight.com/2ccf2b601/p/4121af-button-minor/b/03680d page using Carbon components.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/agitated-aryabhata-tqkhdd?file=/src/App.js:323-340

### Carbon Version

114.16.0

### Design Tokens Version

4.13.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
@blaky the ButtonBar component changes were not included in the first stage of Button Minor. The Buttonbar changes will be implemented during the next phase. @ljemmo can you confirm?

**Comment by ljemmo** [comment]
@sianford i believed minor buttons would be delivered in one PR but i'm out of the loop. @nicktitchmarsh should be able to confrim

**Comment by blaky** [comment]
Before reporting, I asked @Parsium if this was a bug or a missing feature. He wasn't sure either, but advised me to report it in any case so it doesn't get forgotten.

**Comment by Parsium** [comment]
FE-5710

**Comment by nineteen88** [comment]
FE-5721 (for Split Button and Multi-Action Button)

**Comment by nicktitchmarsh** [comment]
This is being closed due to withdrawn support for Minor button in the new version of the DS
