### ISSUE TITLE
Package for handling virtual scrolling requires an update on Safari 

### ISSUE THREAD

**Issue by ZhuoyuJin** [Sage/carbon#5872]
### Current behaviour

Please find the issue in the linked codesandbox which relies on the latest carbon release. 
Click on the dropdown arrow, a type error shows on the screen: _`undefined is not an object (evaluating 'entry.borderBoxSize[0]')`_

![Image 28-02-2023 at 11 07](https://user-images.githubusercontent.com/72838192/221837028-c6ade96a-6c25-436b-bded-91290050d6d1.jpg)

### Expected behaviour

No type error exists. As suggestion from Maciek @mkrds, it's cause by the package that we are using to handle virtual scrolling `@tanstack/react-virtual`. This is meant to be fixed in their side already https://github.com/TanStack/virtual/pull/518

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sidebar-with-select-forked-nxszrt?file=/src/index.js 

### Carbon Version

latest

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-5701

**Comment by DipperTheDan** [comment]
Looks like this issue was resolved in [this version of tanstack/virtual](https://github.com/TanStack/virtual/releases/tag/v3.0.0-beta.53)

We are currently on v3.0.0-beta54 since this PR was released https://github.com/Sage/carbon/pull/6020.
