### ISSUE TITLE
Allow Confirm component to have a responsive width without having to rely on media queries

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#5889]
### Desired behaviour

Confirm modal should be responsive without relying on media queries. This is to ensure standardised responsive behaviour when modals are used across different MFEs.

For example, one MFE may set `size="large"` when `useMediaQuery("(min-width: 1260px)")` is true while another may set `size="large"` when `useMediaQuery("(min-width: 1360px))` is true

### Current behaviour

The current approach to display responsive behaviour for the Confirm modal is to rely on media queries. This is recommended in Carbon documentation as well - https://carbon.sage.com/?path=/docs/dialog--responsive

### Suggested Solution

Possibly can be resolved by introducing a `max-width` option

### CodeSandbox or Storybook URL

https://codesandbox.io/s/medium-small-confirm-modal-wv8qgn

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Thanks for raising this @kishanivelupillai-sage 👍🏼 We agree that it is a good idea to standardise this especially given we use predefined sizes for the modal-based components. However, we would need some input from Design System with regards to what standard breakpoints we should be using. We will forward this on to them for you.

**Comment by Parsium** [comment]
Note for DS triage - review for other modal-based components like Dialog as well as Confirm.

**Comment by nicktitchmarsh** [comment]
I am moving this issue to the design-system board. So they can handle the discussion and solution. You can view this issue to keep track of it. I will close this one here. [https://github.com/Sage/design-system/issues/19](https://github.com/Sage/design-system/issues/19)
