### ISSUE TITLE
Select throws Unexpected undefined

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#5905]
### Current behaviour

I have a select with an initial value but the options are loaded when opening the select.

Upon rendering, i got an Unexpected undefined error.

### Expected behaviour

The select should be rendered correctly.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/throbbing-dew-lejnmz?file=/src/App.js

### Carbon Version

114.14.0

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-5718
