### ISSUE TITLE
Voice-over on `Dialog` skips `title`

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#5910]
### Current behaviour

Given I open a `Dialog` that has the default `aria-role`(dialog) + `title` + `subtitle`  with the voice-over on
Then I hear voice-over jumps to the `subtitle` without announcing the `title`. (video attached)

https://user-images.githubusercontent.com/90848080/224061436-2c996c68-f31d-4543-aca5-f1fb70d3cfc6.mov

### Expected behaviour

Given I open a `Dialog` that has the default `aria-role`(dialog) + `title` + `subtitle`  with the voice-over on
Then I hear "`Title`, dialog with x items"
Then I hear "`Subtitle`"

### CodeSandbox or Storybook URL

https://oki0si.csb.app/

### Suggested Solution

I suspect that in certain environments, the `aria-labelledby` attribute may not be synchronised with the `title` attribute of the `Dialog` component, whereas the `aria-describedby` attribute consistently works correctly with the `subtitle` attribute.

When I raised this issue with @robinzigmond, he was unable to reproduce the error. On his PC(with chrome v110), the voice-over announces the `title` correctly. However, I and my teammates(v111) continue to experience this problem, and I am unable to identify the reason.

### Carbon Version

114.14.1

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
Hi @JinCoreana - I have checked the code sandbox and I can't replicate the issue on Chrome v110 or Safari 15.6.1. @tomdavies73 has also tried it on Chrome v111 and can not replicate the issue either. I'm going to close the issue.

**Comment by JinCoreana** [comment]
@nineteen88 Thanks for confirming this. I will investigate which setting of the PCs of mine and my colleague causes this issue and update you.
