### ISSUE TITLE
DateInput component missing type support for `ref` prop

### ISSUE THREAD

**Issue by justin-rankin** [Sage/carbon#5929]
### Current behaviour

Recently the a `ref` prop was added to both `DateRange` and `DateInput` components; however, IDE Intellisense show that DateInput does not find a definition for the `ref` prop.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/79138818/226299502-5035fcf8-301d-4d9b-8e0d-e9cf2724b13a.png">

This can currently only be _"fixed" **temporarily**_ by either:
1. declaring the module - `declare module "carbon-react/lib/components/date";`
2. importing the `.d.ts` file directly - `import type{ DateChangeEvent } from "carbon-react/lib/components/date/date";`

After speaking with @edleeks87 and @robinzigmond , it seems that something is missing from Carbon DateInput's .d.ts file or declaration, and should be included.

### Expected behaviour

Expected behaviour is the ability to use `ref` prop while implementing the `DateInput` component, as i am informed that it already should.

The generated storybook docs should include mention of `ref` also.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/optimistic-leftpad-odqdm7?file=/src/index.tsx

### Carbon Version

116.0.1

### What browsers are you seeing the problem on?

Other

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

Did not select a browser, as this error is seen in / reported by the IDE, pre-compile.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5724
