### ISSUE TITLE
Disabled items in ActionPopover are focusable 

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#5943]
### Current behaviour

Disabled items can be focused

![image](https://user-images.githubusercontent.com/44157880/228280569-5aeb13e5-8251-4637-9c8c-98c736a87285.png)

### Expected behaviour

Disabled items should not be focusable 

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/action-popover--action-popover-component

### Carbon Version

latest

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-5743
