### ISSUE TITLE
Accessible name of input does not match visual label

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#5945]
### Current behaviour

While updating to Carbon v116.2.0, specs to get the `<Select />` component within a form using the `getByRole` query were failing as the name option string was required to be the the visual label text and the value text concatenated. This was noticed in the `react-testing-library` output: ![see attachment](https://user-images.githubusercontent.com/84381483/228305638-9c9c44d3-2e4b-46cb-b3af-6236cb6d21bd.png)

On inspection of the DOM in the browser, the value for the `aria-labelledby` attribute for the `input` element within the `<Select />` component is given the value of the combined `IDs` of the `label` element which holds the label string and the `span` element which holds the value string and so the label text while testing (`screen.getByRole("combobox", { name: "Label text here" })`) is considered to be the string in the label element and in the span element as opposed to the visual label which is not correct. See DOM screenshot: 
![image](https://user-images.githubusercontent.com/84381483/228305950-b358a742-8534-4675-83ca-60f48414b6b4.png)

This also results in the screen reader (VoiceOver) reading the field label including the value (County Please select...).

### Expected behaviour

The accessible name of the input should match the visual label and should not contain the value so while testing, the element can be procured by using the visual label text via the `getByRole` query. Also this will ensure the screen reader reads the label correctly and communicates it to the user.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/silly-tu-8msf5x

### Carbon Version

116.2.0

### What browsers are you seeing the problem on?

Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by kohli-pratik-sage** [comment]
> Hi @kohli-pratik-sage. Could you please provide a codesandbox to demonstrate the issue so that we can inspect what's happening more clearly? Thanks.

Hi @sianford - I have updated the comment above to include a codesandbox url (using the latest Carbon version). The reported issue is visible in screen readers and specs. 

It will be best to see it via the browser so please run a screen reader on the browser output of the codesandbox, tab to the Select component and you will hear the screen reader announce the Select component using the visual label and value text as opposed to just the visual label.

If you would like to see the issue in specs, it will be best if we jump on a call where I can demo it to you locally as there is quite a bit of setup config needed to run specs in the codesandbox template.

**Comment by Parsium** [comment]
FE-5750
