### ISSUE TITLE
FlatTable Sticky Footer - Layout issue - no longer renders at bottom of container

### ISSUE THREAD

**Issue by amieedwards-sage** [Sage/carbon#5955]
### Current behaviour

- Upon updating to carbon `v117.1.0` (from v114.3.0) our existing production UI for the `FlatTable` component with sticky footer has been altered - it is no longer rendering at the bottom of the container/page.

- It’s believed this was broken in v114.10.1 (an unrelated alignment fix for Pager, resulting in some HTML being restructured).

- It is now only rendering one immediate child and has a new `display: grid` property applied to it.

- This situation occurs when the table is nested inside a fixed-height container that is taller than the table itself *and* in scenarios where the footer is designed to be explicitly at the bottom of the container/page.

### Expected behaviour

In our existing production UI the footer was designed and displayed at the bottom of the container. 
The `FlatTable` was rendering two immediate children, using `display:flex` and `space-between` to enable our footer to be rendered at the bottom of the container.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/flattable-mock-up-0ko2g5?file=/src/App.tsx

### JIRA Ticket (Sage Only)

SBS-53642

### Carbon Version

117.1.0

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-5741

**Comment by DipperTheDan** [comment]
Closed as per work release [v119.3.1](https://github.com/Sage/carbon/compare/v119.3.0...v119.3.1)
