### ISSUE TITLE
Safari only: When user clicks on table column headers to reorder, user sees a ghost line of text

### ISSUE THREAD

**Issue by ritxi** [Sage/carbon#5968]
### Current behaviour

https://user-images.githubusercontent.com/145516/231982569-d53eb5b3-bb9c-4582-9a9d-b327dda43a0d.mov

### Expected behaviour

There should not be any ghost texts when user clicks and drags the analysis types to re-order

### CodeSandbox or Storybook URL

https://codesandbox.io/s/zealous-lalande-3cnl2f

### JIRA Ticket (Sage Only)

SKPU-9080

### Carbon Version

117.6.1

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-5760

**Comment by nicktitchmarsh** [comment]
After an investigation we have found that this is a visual issue in older versions of Safari which is not worth fixing given that Safari behaves correctly now. It is also not considered an accessible pattern and will need a complete overhaul too.
