### ISSUE TITLE
FlatTableRow: bgColor prop hasn’t been defined in the d.ts file

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#5979]
### Current behaviour

using the prop gives type warning

### Expected behaviour

no type warning

### CodeSandbox or Storybook URL

None

### Carbon Version

116.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-5763
