### ISSUE TITLE
Cycling focus on a dialog changes the scroll position in the background

### ISSUE THREAD

**Issue by ernon66** [Sage/carbon#5986]
### Current behaviour

In an open dialog, hit tab repeatedly to cycle through the different focusable elements.
When getting back to the first one (the cancel button if there is one for example)
The position of the scrollbar in the background is changed

### Expected behaviour

The position of the scrollbar is not changed

### CodeSandbox or Storybook URL

https://codesandbox.io/s/unruffled-jang-py6lpq

### JIRA Ticket (Sage Only)

SBS-57060

### Carbon Version

latest (117.7.1)

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

Seems to be happening since 116.1.1

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-5771
