### ISSUE TITLE
Focus goes to body when tabbing from Search input with no value and `searchButton` prop set

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#5990]
### Current behaviour

When `Search` has `searchButton` and no value, the button disappears when tabbing from the input meaning focus is placed on document body instead

### Expected behaviour

Focus should move to next focusable element

### CodeSandbox or Storybook URL

https://codesandbox.io/s/distracted-maria-frdmw3

### Suggested Solution

Component needs a design review as to whether the above pattern is what we want. If it is we will need to querySelect focusable elements on the page and move focus programmatically 

### Carbon Version

latest

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @ljemmo @LaiaSage 👋🏼 

The search button here isn't strictly required to be present for the input box to function, but from my understanding of the problem, we need to clarify if we want to display the search button when the input box is empty, as this is what was causing the original technical issue @edleeks87 described.

**Comment by edleeks87** [comment]
FE-6078
