### ISSUE TITLE
Double outline/border when tabbing through FlatTable rows with onClick set

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#5991]
### Current behaviour

When tabbing through table rows that have an onClick prop set there is an additional outline.

![image](https://user-images.githubusercontent.com/44157880/234018438-e48a3fe9-c15d-4852-a11e-0ebd447d9bb0.png)

### Expected behaviour

No additional outline

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/flat-table--with-clickable-rows

### Carbon Version

latest

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
On further investigation it's caused by some user agent styling in chrome

```
:focus-visible {
    outline: -webkit-focus-ring-color auto 1px;
}
```

**Comment by robinzigmond** [comment]
FE-5770
