### ISSUE TITLE
Fixed height on LoaderBar regardless the size

### ISSUE THREAD

**Issue by franip-sage** [Sage/carbon#5999]
### Current behaviour

The `LoaderBar` component in inheriting some values for the `font-size` and `line-height`. This causes the component to be always 17px height, regardless the size you pass (small, medium, or large). The wrapper container is then 17px height, but the animated bar is 4px, 8px, or 16px height depending on the size.

The problem is that when you stack the component below another, a gap is noticeable instead of appearing without separation. 

### Expected behaviour

The component should be the same height as the animated bar.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pensive-orla-kj8x2b

### Carbon Version

118.1.1

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by ashish-khankari** [comment]
could you please assign me this task

**Comment by sianford** [comment]
FE-5882
