### ISSUE TITLE
Allow popover container content to be fixed

### ISSUE THREAD

**Issue by Sage-AlanYoung** [Sage/carbon#6002]
### Desired behaviour

Allow users to set the "transition" style that's applied to the "popover-container-content" when using the PopoverContainer component, or remove/disable it.
![QuickPanelStyle](https://user-images.githubusercontent.com/110925864/236238836-f231f8d7-9b6b-427c-ab2d-d3d03bce67c0.PNG)

### Current behaviour

Popover containers can jump around the screen when scrolling up or down: 

### Suggested Solution

Allow the style to be disabled/overridden if the desire is to have a fixed popover container, which is added here: https://github.com/Sage/carbon/blob/master/src/components/popover-container/popover-container.style.ts#L45

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
To whoever sees this message in triage. Message me for the screenshots and GIFs that were on this ticket.

**Comment by sianford** [comment]
FE-5881
