### ISSUE TITLE
PopoverContainer tab navigation - Accessibility

### ISSUE THREAD

**Issue by victoriadeanton** [Sage/carbon#6008]
### Current behaviour

When opening a PopoverContainer, if the 'X' button is not there, the content of the popover is not reached by tabbing until the last item behind the popover is reach

### Expected behaviour

Open a PopoverContainer and be able to navigate with the tab button inside

### CodeSandbox or Storybook URL

https://codesandbox.io/s/popovercontainer-57efgc

### JIRA Ticket (Sage Only)

SBS-57839

### Carbon Version

117.6.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-5879
