### ISSUE TITLE
Menu component needs accessibility improvements

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6009]
### Current behaviour

JIRA ticket that sparked the discussions:
SBS-47507

### Expected behaviour

Menu component to adjust automatically to available window real estate and to allow for scroll bars / focus shifts by users.

Every menu should work on a 320x256px screen at 200% zoom no matter how many children they have.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/menu--default-story

### Suggested Solution

@robinzigmond Has volunteered to take point on this and explain the issues. Also happy to talk to anyone if there's questions over the requirements.

### Carbon Version

117

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-5878
