### ISSUE TITLE
`Decimal`'s emptyValue does not follow `precision` attribute

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#6012]
### Current behaviour

**Given** `Decimal` component
**When** I set `precision` attribute to 0
**And** I empty the value and blur the input
**Then** I see '0.00' filled in

### Expected behaviour

**Given** `Decimal` component
**When** I set `precision` attribute to 0
**And** I empty the value and blur the input
**Then** I see '0' filled in

### CodeSandbox or Storybook URL

https://codesandbox.io/s/dreamy-sunset-ne2lq6

### JIRA Ticket (Sage Only)

SBS-58568

### Suggested Solution

 Please could you adjust the default emptyValue 0 to adhere to the precision attribute setting or just 0?

### Carbon Version

117.6.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5891
