### ISSUE TITLE
Content string appearing below input field

### ISSUE THREAD

**Issue by louise-crooks** [Sage/carbon#6022]
### Current behaviour

The following line of text appears beneath an input field in the live Accounting Individual free product:
Input contains a character counter 

I've never seen this before. Highlighted on screenshot. 
<img width="954" alt="CarbonInput" src="https://github.com/Sage/carbon/assets/74910059/c08a415d-e2d7-4e2e-9ef3-38ca75d51b33">

### Expected behaviour

The text 'Input contains a character counter' should not be visible in the UI.

### CodeSandbox or Storybook URL

https://app.sbc.sage.com/accounts/banking

### Carbon Version

117.6.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
No this is not a random string, this was an accessibility improvement requested by @tempertemper. Screen readers should announce before an input if there is a character limit, otherwise screen reader user's won't be notified until after the input has been read out.

**Comment by louise-crooks** [comment]
@tempertemper @nicktitchmarsh Yes agree that 2 hint texts are strange and I think it's confusing. We already have the characters remaining underneath the text input box which is a [pattern Gov uses. ](https://design-system.service.gov.uk/components/character-count/) Our character remaining text should be left aligned and underneath the input text box as @ljemmo posted above - it's current;y right aligned in the screenshot I shared so it's not obvious that it relates to the text input.

 Do we need to include the character input in the hint text if we have the remaining characters underneath?

**Comment by louise-crooks** [comment]
@nicktitchmarsh @ljemmo @tempertemper 

So as I see it:

- The character counter under the text input needs to be left-aligned as it's currently right-aligned.
- The 'Input contains a character counter' line needs to be removed. 
- The hint text instruction will be reviewed by content designers to see if we should include a reference to the character count. Any updated content will be managed through Phrase.

Martin - Please let me know if you disagree with this approach.

Nick - do you need me to raise another ticket for the left alignment and the removal of the input string? Or can you reopen this one? 

Thanks

**Comment by ljemmo** [comment]
Reopening this as it looks like we need @tempertemper  to reply to the above from louise. It looks to me like the hint text and character count shouldn't be shown together. Is that your understanding too martin?

As for the alignment of the character counter on text area and text editor, do we want to fix those on other issues / tickets @nicktitchmarsh ?

**Comment by nicktitchmarsh** [comment]
FE-6004
