### ISSUE TITLE
NumeralDate design

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#6024]
### Current behaviour

When I want to horizontally align a Textbox and a NumeralDate, NumeralDate is not aligned

### Expected behaviour

The NumeralDate is correctly aligned with the Textbox.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/empty-morning-lz1j1s?file=/src/App.js

### Carbon Version

118.2.1

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5888
