### ISSUE TITLE
[ Search Icon ] the icon is rendered with wrong styles when used in Menu

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#6030]
### Current behaviour

Check the [storybook](https://carbon.sage.com/?path=/story/menu--scrollable-submenu-with-parent)
Expand 3-rd Menu item
Click into Search input

The Search icon is shown like on screenshot below:
![Screenshot 2023-05-16 at 09 09 36](https://github.com/Sage/carbon/assets/34001198/06c7d444-4400-4fe2-b7ac-3fb9b804dd5f)

### Expected behaviour

It should be rendered with the same styles as for regular Search usage.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/menu--scrollable-submenu-with-parent

### JIRA Ticket (Sage Only)

FE-5886

### Carbon Version

118.3.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
![Same use case in Carbon version 123.2.0](https://github.com/Sage/carbon/assets/18368713/8606437f-57ff-4ff6-b2b8-17f571b2fbe7)

It appears in the latest Carbon version 123.2.0 that the issue has been addressed. The width of the search button has been addressed. Carbon has other discrepancies with the Design System on `Search`, but this could be addressed in a dedicated ticket to resolve them all.
