### ISSUE TITLE
Ensure focus remains on dialog container when opened

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#6039]
### Current behaviour

Focus is on `<body>` tag when dialog is opened

### Expected behaviour

Focus should be on dialog container when dialog is opened

### CodeSandbox or Storybook URL

https://codesandbox.io/s/dialog-focus-behaviour-cwf65m

### JIRA Ticket (Sage Only)

SBS-47556

### Carbon Version

118.3.3

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5984

**Comment by Parsium** [comment]
After further investigation, it seems the container t is being focused correctly when `Dialog` is opened
