### ISSUE TITLE
Action Popover - Gap between icon and menu item in Flat Table story 'paginated with sticky header' has disappeared

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#6045]
### Current behaviour

The menu item in the Action Popover in the second row is missing the gap between the chevron icon and the text "action". This appears to have been broken in v102.20.0. See attached screenshots from v102.19.1 and v102.20.0 for comparison.

![ActionPopover_v102-19-1](https://github.com/Sage/carbon/assets/12828099/1c05b254-d664-4c30-a54b-6bb8a3d361f8)

![ActionPopover_v102-20-0](https://github.com/Sage/carbon/assets/12828099/234b0291-00dd-4d98-8c02-dca1a1bfca17)

### Expected behaviour

There should be a gap between the chevron icon and the menu item text.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/flat-table--paginated-with-sticky-header

### JIRA Ticket (Sage Only)

FE-5896

### Suggested Solution

Add the gap back in.

### Carbon Version

118.3.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5896

**Comment by nicktitchmarsh** [comment]
Checked in latest Carbon, this is fixed
