### ISSUE TITLE
Action Popover - default story, submenu flickers when you hover between the menu item and last submenu item

### ISSUE THREAD

**Issue by sianford** [Sage/carbon#6046]
### Current behaviour

In the last Action Popover in the default story, when you hover between the menu item 'Download CSV' and the second active submenu item 'Sub Menu 2', the submenu flickers. See attached movie.

https://github.com/Sage/carbon/assets/12828099/c08e8cb0-4b1f-4a56-86f6-542d0d980ebf

### Expected behaviour

The submenu should not flicker when the user moves between the menu item and submenu items.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/action-popover--action-popover-component

### JIRA Ticket (Sage Only)

FE-5897

### Carbon Version

118.3.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-5897

**Comment by tomdavies73** [comment]
Closed as this was fixed in version 119.9.0 during the components' alignment with the design system
