### ISSUE TITLE
Allow padding to be configurable for MenuItem component when displayed in a MenuFullscreen component 

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#6058]
### Current behaviour

The `MenuItem` component renders with `padding-y` of 16px when displayed inside `MenuFullscreen` component. This padding value is currently not configurable.

### Expected behaviour

The `MenuItem` component should allow padding values to be configurable when displayed inside `MenuFullscreen` component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/menu-item-padding-16-6b7sn8

### JIRA Ticket (Sage Only)

SBS-59926

### Carbon Version

118.4.0

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5992
