### ISSUE TITLE
MultiActionButton type definition specifies iconType/iconPosition as available props

### ISSUE THREAD

**Issue by clheppell** [Sage/carbon#6059]
### Current behaviour

The `MultiActionButtonProps` interface says that iconType and iconPosition are props on a MultiActionButton but if you set these mothing happens.

Assume that these not working is expected behaviour and they've just been missed from the Omit<SplitButtonProps, blah> in src/components/multi-action-button/multi-action-button.component.tsx.

### Expected behaviour

iconType and iconPosition should not be included in MultiActionButtonProps.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/small-forest-yk15mh?file=/src/App.js:374-382

### Carbon Version

116.2.0

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

We're pulling through your TypeScript type definitions to help power our documentation for Sage 200 Web Amendability. We will work around this by using Omit.

Issue appears in both our current version and latest.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@clheppell thanks for flagging this. Yes accidentally exposed these props that shouldn't be there. Will get these removed. 
FE-5991
