### ISSUE TITLE
Popover container component calls onClose method even if the popover is not opened.

### ISSUE THREAD

**Issue by sage-syfre** [Sage/carbon#6066]
### Current behaviour

onClose is called each time the use click on the page

HandleClickAway calls "onClose" even if the popover isn't opened.
So each time the user click on a page with a popover (not opened) the onClose is called

popover-container.component.tsx
line 210

const handleClickAway = (e: Event) => {
    if (!isControlled) setIsOpenInternal(false);
    if (onClose) onClose(e);  // <<<<<<<<<<<<<<<<<
  };
  const handleClick = useClickAwayListener(handleClickAway, "mousedown");

### Expected behaviour

Call onClose only if the popover was opened.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/popover-container--default

### Carbon Version

118.3.2

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

Obviously there are workarounds in user's code but you can search a while before finding the reason of React refresh.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-5990
