### ISSUE TITLE
Blockquote Component

### ISSUE THREAD

**Issue by AlexKryzh** [Sage/carbon#6072]
### Desired behaviour

Blockquote element that has border to the left. Property of border color can be specified by property. The content can be pass like children.

<img width="1130" alt="image" src="https://github.com/Sage/carbon/assets/2675648/e83ab5c7-a517-4316-be8b-13541b8018c8">

### Current behaviour

In this moment Carbon don't have this type of component.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
I have moved this over to the design system board as this is really a decision for them whether we add this component or not.

**Comment by ljemmo** [comment]
@AlexKryzh this now exists in the new DS - design spec ready if this still needs to be built?
