### ISSUE TITLE
[ Search - search icon ] There are no rounded corners applied to the search (cross) icon on focus

### ISSUE THREAD

**Issue by DlgSHi** [Sage/carbon#6079]
### Current behaviour

1. Open [search](https://carbon.sage.com/?path=/story/search--with-search-button)
2. Provide any text
3. Press Tab to focus the search (cross) icon
4. The corners are sharp
![search_cross_icon_focus](https://github.com/Sage/carbon/assets/34001198/b8196dfb-e4ac-405d-80d5-be7892dc9cd0)

### Expected behaviour

The right corners should be rounded as the input

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/search--with-search-button

### Carbon Version

118.5.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DlgSHi** [comment]
FE-5994

**Comment by nuria1110** [comment]
The Search component is undergoing a redesign (FE-6078), therefore this issue is no longer applicable.
