### ISSUE TITLE
Scroll bar retains position in drop down menus in Firefox

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#6083]
### Current behaviour

Scroll bars retain position in drop down menus in Firefox in between views. 

### Expected behaviour

The position should return to the top of the options in between views. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/trusting-sun-0yr0ji

### Carbon Version

118.4.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-5999
