### ISSUE TITLE
Focus / scroll position jumps to cursor position when editing controlled inputs

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6088]
### Current behaviour

When editing a controlled textArea input that has vertical overflow (scrollbar) scroll position jumps to the cursor unnecessarily.

### Expected behaviour

Scroll position not to be affected when editing an input.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/textarea-focus-59s7gc

### JIRA Ticket (Sage Only)

SBS-52108

### Carbon Version

118.5.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6001
