### ISSUE TITLE
Select component with mutliColumn option, no way to control the list container width

### ISSUE THREAD

**Issue by sage-syfre** [Sage/carbon#6091]
### Desired behaviour

Provide a way to set the select container width.

When the select is used as a cell editor and with the multiColumn option the list container is constraint to the cell's width which in most of the case is far to small.

### Current behaviour

I don't see any way to control the select container width
There is a ref I can pass to the Select but it's the assigned to the input element
The select-list has a containerRef but it's not exposed

### Suggested Solution

add a listMinWidth or a listWidth 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
{{listWidth}} prop can now be used to [override the select list width](https://carbon.sage.com/?path=/story/select--list-width)
