### ISSUE TITLE
Breadcrumbs component - add some props to manage it like the default Navigation Bar

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#6094]
### Desired behaviour

Having the possibility to change the navigationType, position, orientation and offset like for the Navigation Bar.

### Current behaviour

The Breadcrumbs cannot be used with the theme that we want and we cannot fix its position  with another Navigation Bar.

https://github.com/Sage/carbon/assets/38658070/8bf50591-c926-4d37-b5f2-9ea880d3fd4d

### CodeSandbox or Storybook URL

https://codesandbox.io/s/mystifying-albattani-tnwgrx?file=/src/App.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by StylianosKoidakisSage** [comment]
Could not achieve this by Box and Typography props?
