### ISSUE TITLE
`textOverflow` prop on `Typography` can't be used

### ISSUE THREAD

**Issue by clheppell** [Sage/carbon#6098]
### Current behaviour

In plain CSS to to use the `text-overflow` property, you need to set `overflow: hidden` and `white-space: nowrap` which in Carbon can be done by setting the truncate prop, but setting this prop explicity sets `text-overflow` to `ellipsis`, so the value of textOverflow never has any effect.

### Expected behaviour

To be able to specify `textOverflow` alongside the `truncate` prop.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/crimson-flower-f0o3go?file=/src/App.js

### Carbon Version

116.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-6013
