### ISSUE TITLE
Hide menu-divider for empty children within MenuFullscreen component

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#6099]
### Current behaviour

menu-divider is shown for empty children within MenuFullscreen component

### Expected behaviour

menu-divider should not be shown for empty children within MenuFullscreen component

### CodeSandbox or Storybook URL

https://codesandbox.io/s/menu-fullscreen-empty-children-y8e81x?file=/src/App.js:383-520

### JIRA Ticket (Sage Only)

SBS-61391

### Carbon Version

118.5.2

### Design Tokens Version

4.19.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-6011
