### ISSUE TITLE
[ Button ] - Children prop evaluate to falsy 

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#6108]
### Current behaviour

Given a button component
When the `iconType` prop is not passed
And `children` prop is falsy 
Then the children won't be rendered

### Expected behaviour

Given a button component
When the `iconType` prop is not passed
And `children` prop is falsy 
Then the children is rendered

### CodeSandbox or Storybook URL

https://codesandbox.io/s/prod-glitter-ypps3s?file=/src/App.js

### Carbon Version

119.0.1

### Design Tokens Version

4.19.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-6008
