### ISSUE TITLE
`prefix` appears on the right of Decimal and Number

### ISSUE THREAD

**Issue by clheppell** [Sage/carbon#6109]
### Current behaviour

Set the `prefix` prop on Decimal to some value. The text appears on the far right on the input rather than at the start.

### Expected behaviour

The prefix to appear on the left.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/patient-shape-szmsxk?file=/src/App.js

### Carbon Version

116.2.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-6007
