### ISSUE TITLE
DateInput, to many onChange events

### ISSUE THREAD

**Issue by sage-syfre** [Sage/carbon#6123]
### Current behaviour

When the user open the calendar to input a date, and uses the keyboard to set the date directly, the DateInput sends many onChange events, some with an invalid date

For example :
Today is 15 june 2023
The user open the calendar and start editing the date with the keyboard to set the date to 16 June 2020
The fallowing onChange events happened:
15 06 202 (The user used the backspace key, rawValue is null)
15 06 20 (The user used the backspace key, rawValue is 2020-06-15) (why,  rawValue should be null ?!?)
15 06 202 (The user input 2, raw value is null, the calendar is still opened)
15 06 2020 (The user input 0, raw value is 2020-06-15, the calendar is still opened)
16 06 2020 (the user select the 16 and this close the calendar)

The problem with that is that it's not possible to detect when the user ended the selection.

For example if the DateInput is used in a grid cell editor, we want to terminate the cell edition when the user has finished, so that the new value is taken in account by the grid. If we use the onChange event to finish the grid edition (calling stopEdting of the grid api) the value may be incorrect. If we can't call stopEditing, the user need to select and other cell to finish the previous editing and to take the new value in account. 

onBlur and onClick doesn't help.

Note :  It's also possible to finish with an invalid date : 

The current date is 15 June 2023
The user select the DateInput
The DateInput enter edition an open the calendar
The user uses the backspace key to remove the 3, onChange happened with a null rawValue, formattedValue "15/06/202" (french format)
The user clicks outside the DateInput and the calendar
The calendar is closed. 
The only onChange event was with an invalid date.

   

### Expected behaviour

Only one onChange event when the calendar is closed and the selection is finished.
Or alternatively
Add an onClose event when the the calendar is closed and the selection is finished

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/date-input--default-story

### Carbon Version

118.6.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
E-6028

**Comment by edleeks87** [comment]
Hi @sage-syfre, this is how React handles change events unfortunately, it's much more akin to the [onInput of vanilla JS](https://betterprogramming.pub/how-onchange-differs-between-react-and-vanilla-javascript-90b56d6a340a) . I'm not convinced we'll be able to do much about it but you maybe able to use something like add a timeout in the onChange handler ([very rough example](https://codesandbox.io/s/peaceful-wind-ylpykc?file=/src/App.js)). 

With respect to the null values you are seeing, the rawValue is returned as either an iso formatted string or null depending on if the current value in the input can be parsed to a valid date or not. So in the above `15 06 202` is null as it can't be parsed but `15 06 20` is `2020-06-15` as it can be parsed etc.

We'll use the above ticket to investigate if we can do anything on our side and at least give a recommendation if we can't etc.
