### ISSUE TITLE
ID Props applied to Select Options do not carry through, leading to dynamic IDs

### ISSUE THREAD

**Issue by tombarnessage** [Sage/carbon#6126]
### Current behaviour

If I add an ID as a prop to the children of a Select (Option element) That ID is then not present in the devTools. This means certain methods of finding the elements that our (Delta Squad) QA use cannot locate the elements.

### Expected behaviour

Id's supplied as props to the Options of a parent Select element are applied to the component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/distracted-mahavira-k23nr3?file=/src/App.js

### Carbon Version

npm:carbon-react@106.6.8

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tombarnessage** [comment]
> @tombarnessage Is this for testing purposes or do you need to target the options in your app? Would data-selectors be a suitable solution?

This is for automation purposes to select the components via ID to fill in the UI during automated tests.

**Comment by edleeks87** [comment]
FE-6041
