### ISSUE TITLE
BreadCrumb - Crumb onClick is missing type on event

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6133]
### Current behaviour

the onClock of Crumb is typed as `any` currently. Docs on storyboard state:
```
onClick | Function called when the mouse is clicked.((ev: MouseEvent<HTMLButtonElement, MouseEvent> \| KeyboardEvent<HTMLButtonElement> \| KeyboardEvent<...> \| MouseEvent<...>) => void)

```

### Expected behaviour

onClick to be correctlky typed as per documentation

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/breadcrumbs--default-breadcrumbs

### Carbon Version

119.3

### Design Tokens Version

4.17

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6027
