### ISSUE TITLE
Ensure Enter key used on close icon of a Search component used within a MenuItem component only clears search contents

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#6146]
### Current behaviour

When a `Search` component is used within a `MenuItem` with keyboard navigation and the Enter key is pressed on the close icon of the `Search` component, the menu dropdown closes

See carbon storybook - https://carbon.sage.com/?path=/docs/menu--default-story#submenu-with-search

### Expected behaviour

When a `Search` component is used within a `MenuItem` with keyboard navigation and the Enter key is pressed on the close icon of the `Search` component, the menu dropdown remains open and the search contents are cleared.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/submenu-with-search-ls7wnr

### JIRA Ticket (Sage Only)

SBS-62877

### Carbon Version

119.3.2

### Design Tokens Version

4.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6035
