### ISSUE TITLE
Select component does not respond to voice commands

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6157]
### Current behaviour

Select does not respond to "click" voice command for displaying the dropdown / listbox. Only once the listbox is opened via mouse / keyboard may options be "clicked".

### Expected behaviour

Simple Select to behave as per ARIA combobox pattern, which will be compatible with the majority of voice control apps: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select--default

### JIRA Ticket (Sage Only)

SBS-63370

### Carbon Version

119.3.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
hi @johnb-sage ,

Apologies for the long delay before looking into this - but I don't believe there is a problem here.

While as you observe the "click XXX" command does not work on Chrome with MacOS Voice Control, I believe that these MacOS accessibility tools are only really supposed to work with Safari - hopefully @tempertemper can confirm this. And I have testerd with Voice Control on Safari, as well as with Windows Speech Recognition on Chrome, and find the command working as expected.

**Comment by robinzigmond** [comment]
closing after a separate conversation with @tempertemper and @johnb-sage confirming that the above makes this a non-issue
