### ISSUE TITLE
Radio Button Group - Bug with documentation

### ISSUE THREAD

**Issue by DipperTheDan** [Sage/carbon#6172]
### Current behaviour

![radio-button-group-bug](https://github.com/Sage/carbon/assets/56251247/8ea5191d-a1b3-490f-ac00-a71612ce434b)

### Expected behaviour

Selected radio button should not change on hover or change between two different radio button groups.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/radiobutton--default

### Carbon Version

Latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-6057

**Comment by DipperTheDan** [comment]
Fixed as part of the new validation work.
