### ISSUE TITLE
Portrait size changes when initials prop is used

### ISSUE THREAD

**Issue by sagemihir** [Sage/carbon#6191]
### Current behaviour

When an image url is passed to the portrait of size "ML” from the props, the size of the component is 56x56   . But when there is no image url passed and just initials prop is used to show the initials of the user, the size with the same "ML" variant is 54x54 .

### Expected behaviour

The size of the portrait should be same in every case

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/portrait--default

### Carbon Version

118.4.0

### Design Tokens Version

4.17.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Closing this as resolved on external Slack thread

**Comment by tomdavies73** [comment]
FE-6074
