### ISSUE TITLE
Escape key should close the Popover Container

### ISSUE THREAD

**Issue by Sage-AlanYoung** [Sage/carbon#6195]
### Desired behaviour

The escape key doesn't close the container, like it does with the Dialog component. It would be great if it could to make keyboard navigation easier.

### Current behaviour

The escape key does not close the container.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
@ljemmo Hi Luke, would you be able to have a quick look at this? @Sage-AlanYoung is requesting that the escape key should be used to close the container. Is this something we should consider? Obviously, the popover container component is not in the DS, but we still want to make sure its behaviour is consistent with other components which are in the DS. Cheers.

**Comment by ljemmo** [comment]
Hey Tom, you can find the guidance on this component here FYI: https://zeroheight.com/2ccf2b601/p/5722a7-action-popover/b/44980e

It looks like escape should indeed close the container. 👍

**Comment by tomdavies73** [comment]
FE-6072

**Comment by camilledegomme** [comment]
@tomdavies73 or @ljemmo - do you have any update on this request?
