### ISSUE TITLE
Dialog component isn't responsive when the screen width is lower than the default sizes

### ISSUE THREAD

**Issue by amieedwards-sage** [Sage/carbon#6199]
### Current behaviour

We currently have a Dialog component with a size prop set to `auto` (as we need the Dialog to be responsive).
Within our design, when the user hits the ‘Check’ button, the button increases in size when in a loading state. 
This causes the size of the Dialog to jump slightly to accommodate the change in button size and negatively impacts the user experience.

### Expected behaviour

Dialog is responsive when the screen width is reduced lower than the default size.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/brave-estrela-8r8csj?file=/src/App.tsx

### JIRA Ticket (Sage Only)

SBS-64898

### Carbon Version

119.4.0

### Design Tokens Version

4.19.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Thanks for this @amieedwards-sage 👋🏼 Would you be able to share some details about your use case for this pattern here? Currently, we are waiting to receive responsive changes from Design System for all its components so we haven't been able to do a full library review with regards to responsiveness. But we may be able to come up with a temporary solution while DS works on this in the meantime.

**Comment by tomdavies73** [comment]
Hi @amieedwards-sage, has there been any update regarding your use case/designs for the requested pattern?

**Comment by amieedwards-sage** [comment]
Hi @tomdavies73 
I had a meeting with @Parsium to discuss the issue on Friday and have since tried a few things. One of them was adding a `maxWidth` property to the container of the dialog content to 'control' the dynamic content inside - but not sure if this is a suitable fix. Rather than the `Dialog` expanding to accommodate the loader within the button it is now shrinking the input box to fit in the available space.

I'm going to reach out to our UX designer to see if this temporary solution is suitable or if they can suggest any other options?

Hope to update you soon.

**Comment by edleeks87** [comment]
I believe @harpalsingh is looking into some of the options as well so we should have an update/ fix soon

**Comment by nineteen88** [comment]
@harpalsingh @edleeks87  was there any further update on this?

**Comment by edleeks87** [comment]
@nineteen88 no

**Comment by harpalsingh** [comment]
I am looking into this as part of a dialog fix/improvement from UX

**Comment by Parsium** [comment]
Hey @amieedwards-sage 👋🏼 @harpalsingh is doing some responsiveness changes to `Dialog` in #6508. These changes should allow the `Dialog` to scale horizontally a lot better than before:

https://github.com/Sage/carbon/assets/18368713/01c758b3-5f18-4f3b-bb0e-31f5e8b78c71

However, the issue of the resizing `Button` affecting the `Dialog`'s width still remains. Revisiting your codesandbox again, I think setting a minimum width on the content container would be needed, so the `Dialog`'s width doesn't get any smaller than this minimum width. Would this example work for you?:

[Link to codesandbox](https://codesandbox.io/p/sandbox/resizing-dialog-x4x3tp?file=%2Fsrc%2FApp.tsx%3A17%2C20)

**Comment by nicktitchmarsh** [comment]
@amieedwards-sage does this solve the issue for you?
