### ISSUE TITLE
MenuSegmentTitle text may wrap

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6206]
### Current behaviour

Where the MenuSegmentTitle has insufficient space, the text may wrap. 

### Expected behaviour

Segment title text not to wrap, instead causing the parent menu's width to grow to accommodate.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/wrapping-segment-title-j3plk6

### JIRA Ticket (Sage Only)

SBS-65763

### Suggested Solution

An option to prevent text wrapping of the segment title if current wrapping behaviour is intended/required.

### Carbon Version

119.6.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by ljemmo** [comment]
@tomdavies73 so this feels like a scenario where we still need to allow wrapping but allow passing of max and min-widths to the menu parent container. Is this something that we allow today?

**Comment by ljemmo** [comment]
@tomdavies73 the only concern i have for allowing no-wrap is that all our components need to be fully responsive. You can imagine a scenario with no-wrap where a title might pass outside of the viewport. Unless i'm mistaken? A reasonable min-width would be nothing lower than 320px but could be increased if needed by dev.

**Comment by edleeks87** [comment]
FE-6077

**Comment by nicktitchmarsh** [comment]
https://github.com/Sage/carbon/pull/6880 should address this
