### ISSUE TITLE
MultiActionButton: no space between the icon and the label on buttons

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#6214]
### Current behaviour

There is no space between the `Icon` and the label as there is for a `Button` on its own.

### Expected behaviour

To render `Button` components in a `MultiActionButton` in the same way as a single `Button`.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/ancient-shadow-v85zwk?file=/src/App.js

### JIRA Ticket (Sage Only)

SBS-58487

### Carbon Version

116.2.0

### Design Tokens Version

4.22.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6070
