### ISSUE TITLE
Using a Box component with DL results in content disappearing

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#6216]
### Current behaviour

I am using a Definition List and need some sections to be a different background colour. When wrapping the `dt` and`dd` in a `Box` the content of the `dt` and`dd` disappears. 

### Expected behaviour

Wrap `dt` and`dd`  in a Box to change the background colour or add a new prop to `dt` and`dd`  ensure background colour can be changed. 

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nice-lederberg-hkqmky?file=/src/App.js

### Carbon Version

119.6.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by johnb-sage** [comment]
When wrapped in a `Tile`, the `Dl` uses a CSS grid for layout.

**Comment by tomdavies73** [comment]
FE-6071

**Comment by edleeks87** [comment]
Same issue that is causing https://github.com/Sage/carbon/issues/6243
