### ISSUE TITLE
Note content is displayed under inlineControl

### ISSUE THREAD

**Issue by ernon66** [Sage/carbon#6228]
### Current behaviour

When a note is displayed with an inlineControl that has a text
If the note does not have a title and has a long enough content, the content will be displayed under the inline control

### Expected behaviour

The content should not be displayed under the inline control button

### CodeSandbox or Storybook URL

https://codesandbox.io/s/heuristic-jackson-gqk4rd

### JIRA Ticket (Sage Only)

SBS-67131

### Suggested Solution

Probably needs a decision from UX

Issue was already fixed for inline control that does not have a text https://github.com/Sage/carbon/issues/5734, but for now nothing indicates that text should not be added

Suggested solution is to keep a blank space at the top of a note even when there is no title

### Carbon Version

latest (119.9.1)

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6090
