### ISSUE TITLE
Image component - additional attributes for control

### ISSUE THREAD

**Issue by harpalsingh** [Sage/carbon#6232]
### Desired behaviour

The image component provides a lot of flexibility but based on how images might be used a few additional requirements may be needed.

You can apply margins props, we would also request to apply all the padding props.

### Current behaviour

You can not pass any padding props to the image component.

### Suggested Solution

Add the padding props most components use with styled system to the Image component.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/image--default-story

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6089
