### ISSUE TITLE
Unable to compose a `Dl` with exported components

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#6243]
### Current behaviour

When we use an exported component within a `Dl` it doesn't render.

### Expected behaviour

Be able to use exported components to compose a `Dl`

### CodeSandbox or Storybook URL

https://codesandbox.io/s/summary-with-dl-forked-j7kylw?file=/src/App.tsx

### Carbon Version

119.4.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6179
