### ISSUE TITLE
Update Dialog component to allow focus to be reset back to the dialog container

### ISSUE THREAD

**Issue by kishanivelupillai-sage** [Sage/carbon#6250]
### Current behaviour

When either title or subtitle of a dialog are changed because of a state change triggered by the user, then the screenreader will not read out the changed title or subtitle.

### Expected behaviour

When either title or subtitle of a dialog are changed because of a state change triggered by the user, then the screenreader should read out the changed title or subtitle.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/3jmp7w

### Suggested Solution

The recommendation is to allow a consumer of the Dialog component to reset focus back to the dialog container.

### Carbon Version

119.11.0

### Design Tokens Version

4.22.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
@kishanivelupillai-sage @johnb-sage This should be addressed as part of version 120.6.0 😄
