### ISSUE TITLE
Resize Observer warnings in app

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6259]
### Current behaviour

After discussion in Slack: have been asked to raise this issue to look at GlobalHeader/NavigationBar and the usage of ResizeObserver that is potentially causing errors in Sentry.

> I suspect this will relate to the [enhancements Robin added to allow submenus to be scrollable](https://github.com/Sage/carbon/pull/6141) when they exceed the viewport as he used a resize observer as part of that work. Can you raise and issue for this and we’ll look investigate and hopefully fix asap?

Removing/replacing this one component in the app removes warnings.
Removing all content bar an empty GlobalHeader and the error continues.

### Expected behaviour

No resize warnings in GlobalNav

### CodeSandbox or Storybook URL

None possible: errors when running app locally

### Carbon Version

119.6.1

### Design Tokens Version

4.19.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6187

**Comment by aclebson-sage** [comment]
Hi @edleeks87, I'm having a similar issue when using the GlobalHeader component, however, the error I'm getting locally is: _"ResizeObserver loop completed with undelivered notifications."_
