### ISSUE TITLE
Text weight on pill component

### ISSUE THREAD

**Issue by DavidBouffort** [Sage/carbon#6272]
### Current behaviour

![Capture d’écran 2023-08-25 à 15 18 41](https://github.com/Sage/carbon/assets/18547992/4a481742-d2f4-402c-919c-25fc584dddb0)
I saw the weight is 700 on Carbon.

On DS is 500. 
![Capture d’écran 2023-08-25 à 15 20 03](https://github.com/Sage/carbon/assets/18547992/e7fcfc4d-a467-4011-b056-ca9ec9d6aea7)

### Expected behaviour

Could you please define to 500 too?

### CodeSandbox or Storybook URL

no one

### Carbon Version

last

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6190

**Comment by nineteen88** [comment]
Fixed as part of https://github.com/Sage/carbon/pull/6944
