### ISSUE TITLE
onLazyLoading called everytime after click in select

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#6285]
### Current behaviour

onLazyLoading is called everytime when it's defined, after clicking on an option.

### Expected behaviour

onLazyLoading should be called only when we scroll at the bottom of the list.
The code is from storybook.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/peaceful-keller-nfssfn

### Carbon Version

120.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6200

**Comment by StylianosKoidakisSage** [comment]
adding a key with the selected value on the filterable select solve the problem for me.

` key={value?.id}`
