### ISSUE TITLE
Tab-navigation to Next button of `Pager` component triggers `onClick`

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#6289]
### Current behaviour

**Given** `Pager` is rendered
**When** I tab-navigate to `Next` button
**Then** I see the highlight (and I think It triggers pagination `onFocus`)
**When** I press `Enter`
**Then** I see pagination jumps from Page 1 to Page 3

### Expected behaviour

**Given** `Pager` is rendered
**When** I tab-navigate to `Next` button
**Then** I see the highlight without any event being triggered 
**When** I press `Enter`
**Then** I see pagination jumps from Page 1 to Page 2

### CodeSandbox or Storybook URL

https://jdc2vt.csb.app/

### JIRA Ticket (Sage Only)

SBS-66661

### Suggested Solution

Please could you ensure that First, Previous, Next, Last, PageSize dropdown and interactive number input don't trigger pagination `onFocus` without `onClick` or `onChange`.

### Carbon Version

120.1.0

### Design Tokens Version

4.17.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6199

**Comment by Parsium** [comment]
Released part of [version 128.1.2](https://github.com/Sage/carbon/releases/tag/v128.1.2) 🚀
