### ISSUE TITLE
Link: icon misalignment

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#6293]
### Current behaviour

The icon of a Link is not vertically centered with the text.

### Expected behaviour

The icon is vertically centered with the text

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/link--default-story

### Carbon Version

119.10.0

### Design Tokens Version

4.22.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

According to Daniel DIpper, the size of the icon font was increased to 20px in v118.5.0.
We can indeed see the misalignment appearing in v118.5.0 in the storybook.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Looks to be the same issue as #6295 FE-6197 has been raised to cover this I will close this as duplicate

**Comment by gusch** [comment]
I would like to reopen this issue because, as of today, icons are still not aligned with link text : 
![image](https://github.com/Sage/carbon/assets/16415182/1278046a-2062-4430-910f-db301dd21b71)
