### ISSUE TITLE
Link: without text the icon is not well align

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#6295]
### Current behaviour

The icon of a Link don't respect the design of it's container if we don't have a text. I cannot align the icon at the right of the application. For exemple, on the sandbox created, the close icon need to be entirely in the red Box.

### Expected behaviour

That the icon of a link without a text respect the places of it's container to be able to align it with the rest of the application.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nostalgic-nash-vx9d6d?file=/src/App.js

### Carbon Version

120.1.0

### Design Tokens Version

4.23.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

This issue appear in v118.5.0.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Looks like when we increased the Icon font size this wasn't changed. We will change the base styles to accommodate the icon here. Just out of interest is there a reason you aren't using the IconButton component?

**Comment by nicktitchmarsh** [comment]
FE-6197
