### ISSUE TITLE
Padding bottom not good in switch component

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#6303]
### Current behaviour

The Padding bottom is not good in the switch component between the label and the input. 
There is no issue if validationRedesignOptIn is not defined in CarbonProvider. 
We don't have this issue in carbon version 118.4.0 .

### Expected behaviour

We should have the same behaviour as described in the https://carbon.sage.com/?path=/docs/switch--default  

### CodeSandbox or Storybook URL

https://codesandbox.io/s/dry-pine-krlgp9?file=/src/index.js:381-404

### Carbon Version

Latest

### Design Tokens Version

120.1.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6208
