### ISSUE TITLE
Popover Container: control ordering

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#6307]
### Current behaviour

A keyboard-only user can only access the controls in a popover container after tabbing through all other elements on the screen

### Expected behaviour

When opening the filter component, the first control should be the next recipient of focus

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/popover-container--filter

### Carbon Version

119.11.0

### Design Tokens Version

4.23

### What browsers are you seeing the problem on?

Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by alex-j-clark** [comment]
It looks like this occurs when renderCloseComponent is used. If not present then it's included in the tab order correctly.

**Comment by tomdavies73** [comment]
FE-6206
