### ISSUE TITLE
Tabs: borders are misaligned when a tab is in error state

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#6314]
### Current behaviour

![Screenshot 2023-09-13 at 14 43 15](https://github.com/Sage/carbon/assets/55696743/d3a9f26a-f558-4d9e-aeb5-1d476ae12e60)

When using `Tabs` with `borders="on"`, the borders become "unbalanced" if an error is present via Carbon input and the tab is in the middle of other tabs.

### Expected behaviour

The tab borders are the same width

### CodeSandbox or Storybook URL

https://codesandbox.io/s/sad-vaughan-d4kfy2?file=/src/App.js

### Carbon Version

119.11.0

### Design Tokens Version

4.23

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-6221
