### ISSUE TITLE
Focus-Within usage within new Link styling

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6320]
### Current behaviour

119.11.0 introduced new focus sttlying for Link:
https://github.com/Sage/carbon/commit/ae68d8debbfcfa4239096569e738de95773d3d16#diff-4bc76552ffc1900364db75add9c449feb3aedea8878cb1f0255d5816f8c5247fR169

and added focus-within.
This has known issues with jsdom and React Testing Library meaning the UI cannot query role/text of any Link component without opting out of the redesign.

### Expected behaviour

Link styling to use focus or other alternative without known issues with jsdom

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/link--default-story

### Suggested Solution

Link styling to use focus or other alternative without known issues with jsdom

### Carbon Version

119.11.0 and higher

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

Chatted with @Parsium on this matter

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6217
