### ISSUE TITLE
FlatTableCheckBox: ariaLablelledBy not working for a single Id

### ISSUE THREAD

**Issue by alex-j-clark** [Sage/carbon#6323]
### Current behaviour

An ariaLabelledBy value with just a single Id does not work. In this case 'John Doe' does not get picked up:

<img width="625" alt="image" src="https://github.com/Sage/carbon/assets/80039824/8744aa67-3392-4b55-b831-e3cc9d3d4ee4">

If 2 or more ids are specified, then they do, in this case, 'Jane Doe York' is correctly generated:

<img width="619" alt="image" src="https://github.com/Sage/carbon/assets/80039824/875882e8-09c6-4cda-bb7c-3f9ef8a5ef67">

### Expected behaviour

In the first example above, 'John Doe' should be picked up as the aria label.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/solitary-rain-s3qxzh?file=/src/App.js

### Suggested Solution

ariaLabelled by should be able to support a single Id

### Carbon Version

119.11.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
Hi @alex-j-clark,

This appears to work to me. See screenshot of a forked version of your sandbox, on Chrome on Mac, showing Carbon version 119.11.0 (the precise one you mention), where the `aria-labelledby` attribute is present in the DOM with the expected value 
![image](https://github.com/Sage/carbon/assets/25186376/17bf762d-c764-402c-a46d-8ebba4eaee11)

Is there anything else we should know about this?

**Comment by alex-j-clark** [comment]
I can reproduce the issue using the MacOs screen reader, VoiceOver. 

<img width="1105" alt="image" src="https://github.com/Sage/carbon/assets/80039824/19e0b079-7a2c-4d72-9f46-d9243b9a5772">


The other row works fine, with 2 ids.

<img width="1131" alt="image" src="https://github.com/Sage/carbon/assets/80039824/d25c3776-e755-4d60-ba4c-74fefe24ac65">

**Comment by robinzigmond** [comment]
Thanks for the reply - on trying it with VoiceOver just now I can confirm I'm seeing the same behaviour.

This is strange to me, as it has the correct aria-labelledby in the DOM and the accessibility inspector in Chrome is showing me that it has an "accessible name" of John Doe. I can only assume this is a bug or limitation in VoiceOver itself but I will do some more investigation, and raise it as a bug on our backlog if needed.

**Comment by alex-j-clark** [comment]
Thanks - I only have access to VoiceOver, perhaps it is an issue there and it'll work on other screenreaders. The only other thing I can think of is that something else is slightly different between the working and non-working rows, although I can't see anything initially.

**Comment by robinzigmond** [comment]
I have just raised FE-6223 for us to investigate. I don't know whether it's possible for us to fix or if it's simply a VO bug, but I can't find any similar issue with VO referenced anywhere - we will investigate further and let you know what (if anything) we discover.

**Comment by robinzigmond** [comment]
Closing as after discussing with Alex, neither of us is able to reproduce the issue any longer
