### ISSUE TITLE
DatePicker: support closure on ESC press

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#6324]
### Desired behaviour

The DatePicker should close when ESC is pressed

### Current behaviour

The DatePicker can only be closed by clicking outside of the popover, which makes it difficult for keyboard users to close the modal.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/musing-shtern-67p2mk?file=/src/App.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
adding the following to the `handleKeyDown` function in date.component should address this

```
 if (Events.isEscKey(ev)) {
        setOpen(false);
        internalInputRef.current?.focus();
      }
      ```

**Comment by robinzigmond** [comment]
FE-6219
