### ISSUE TITLE
MenuFullScreen doesn't use padding values

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6325]
### Current behaviour

The same Children in a Menu vs MenuFullscreen: py prop is not used in menufullscreen.

### Expected behaviour

padding values to work when provided

### CodeSandbox or Storybook URL

https://codesandbox.io/s/jovial-raman-pssw98?file=/src/App.js

### JIRA Ticket (Sage Only)

SBS-70583

### Carbon Version

120.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
https://github.com/Sage/carbon/blob/bf0dfd06ff4fca3c1a5e8b11410e413b08506647/src/components/menu/menu-item/menu-item.component.tsx#L303 is the line causing it, may well be that we can remove the check for the submenu context (all unit tests pass when removed)
