### ISSUE TITLE
Add the possibility to determinate if an onChange event in FilterableSelect comes from a confirmed choice

### ISSUE THREAD

**Issue by franip-sage** [Sage/carbon#6330]
### Desired behaviour

The current implementation of `FilterableSelect` component emits an `onChange` event in every change detected. So, if a user scrolls through the list of options using the keyboard or if he selects any option pressing the `Enter` key or clicking the option with the mouse the event is fired.

It should be useful having the possibility to know if the event comes from a confirmed selection or not, so we can know if the user has done the final choice. In that example it would be when the `Enter` key is pressed of when the option is clicked via mouse.

### Current behaviour

The current implementation of `FilterableSelect` component emits an `onChange` event in every change of option

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pensive-chihiro-n56txf?file=/src/App.js

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-6233

**Comment by zaineabidi** [comment]
Hello @robinzigmond - do we have an expected delivery timescale for this work so that we can plan the work on the front end accordingly?

**Comment by robinzigmond** [comment]
hi @zaineabidi - I can't give you a specific timescale. The ticket is in our "awaiting development" queue but work hasn't  been started yet. If you have a specific deadline to deliver this by please speak to @nicktitchmarsh so we can prioritise.
