### ISSUE TITLE
`textAlign` attribute for `Typography` component

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#6331]
### Desired behaviour

`Typography` content can be aligned by one prop, `textAlign`

### Current behaviour

Currently, to align `Typography`, it should have Flex-`Box` wrapper.
In the case of wrapping `Typography` with `Link`, this does not work as shown in code-sandbox example

### Suggested Solution

Please could you enable `textAlign` attribute for `Typography` so one prop can do the text alignment? 

### CodeSandbox or Storybook URL

https://28tpvm.csb.app/

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6220
