### ISSUE TITLE
Typography style 'Segment Sub-header' line height issue

### ISSUE THREAD

**Issue by graham-blake** [Sage/carbon#6335]
### Current behaviour

The typography style 'Segment Sub-header' is 16px medium (700) weight text and has 31px line height. Is the line height an oversight or is there a particular reason for the 31px?
![typography-segment-subheader-carbon](https://github.com/Sage/carbon/assets/82100553/69607ff2-06cb-49ed-9aad-5b398c0f7cc5)

### Expected behaviour

The Design System (via Figma) defines the line height to be 24px, which looks about right.
![typography-segment-subheader-design-system](https://github.com/Sage/carbon/assets/82100553/dc73ed5a-c7b2-4831-9a6e-bb47e2e7a3de)

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/typography--variants-story

### Suggested Solution

Note from Daniel Dipper in the Slack Carbon channel:

It looks like the line height value we have is the same value we were given in 2020 when Typography was first created. We followed these specs here. I believe all we require is an updated spec from the DS, so that we can update our component with the new values Typography requires.

### Carbon Version

Latest

### Design Tokens Version

N/A

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

I'm hoping this is an oversight but there may have been a specific reason for the 31px line-height in a particular case in a particular product. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-6232
