### ISSUE TITLE
Focus on link with icon is partially covering icon

### ISSUE THREAD

**Issue by szeyingyau** [Sage/carbon#6353]
### Current behaviour

When the link with an icon is focused, the focus is partially covering the icon 

### Expected behaviour

The focus for a link with an icon should not cover the icon

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/link--with-icon-align

### JIRA Ticket (Sage Only)

SBS-72761

### Carbon Version

120.2.0

### Design Tokens Version

4.23.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
![image](https://github.com/Sage/carbon/assets/18368713/57a0b55b-c628-4933-bb80-6d0562d2fc13)

Note for those in triage, comparing Carbon to the DS, the vertical alignment of the icon is incorrect, causing the black focus underline to cover it.

**Comment by nineteen88** [comment]
I believe this might be fixed by a ticket that @tomdavies73 is currently working on: https://github.com/Sage/carbon/issues/6295. If possible could you confirm that this will resolve it too @tomdavies73 otherwise we will open up a separate issue on our board

**Comment by nineteen88** [comment]
FE-6238
