### ISSUE TITLE
Add select options on the fly keeping/updating id's

### ISSUE THREAD

**Issue by ritxi** [Sage/carbon#6378]
### Current behaviour

When an option is selected, if the list options changes, that refreshes the internally used list items changing their ids.

### Expected behaviour

When adding options to a select I expect to keep previous options with same internal id or updating to the new id

### CodeSandbox or Storybook URL

https://codesandbox.io/s/select-with-on-the-fly-all-option-rw4vl9?file=/src/index.js

### JIRA Ticket (Sage Only)

SKPU-10261

### Suggested Solution

When a select list of options change if the selected value is still on the list that should be updating the internal id reference to keep accessibility compliance.

### Carbon Version

121.0.2

### Design Tokens Version

4.25.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@ritxi, can you give some context about why these options need to be dynamically populated and can't be shown on initial render?

**Comment by Parsium** [comment]
Hi @ritxi 👋🏼 Would you be able to provide some more context regarding your use case?

**Comment by sianford** [comment]
Message sent in Slack to @ritxi requesting more context about their requirements.

**Comment by ritxi** [comment]
Hi guys! This is still an accessibility issue. To reproduce just choose one option(A, B or C) and run axedev tools and you'll see the following error: 
![Captura de pantalla 2024-01-09 a les 8 38 17](https://github.com/Sage/carbon/assets/145516/82b44b4e-0da3-465d-937e-f2eac0da8e0d)

**Comment by nicktitchmarsh** [comment]
Hi @ritxi there is a simple workaround until we fix the ID persistence issue 

`
{optionsList.map((opt) => (
  <Option
    data-role={`option-${opt}`}
    text={opt}
    value={opt}
    key={opt}
    id={opt}
  ></Option>
))}
`

Adding the IDs to each option during your render will ensure they always have the correct ID. I've added a ticket below for us to make this work without any further code. Also as a side note, would you not just want the All option to always be there?

**Comment by ritxi** [comment]
> Hi @ritxi there is a simple workaround until we fix the ID persistence issue
> 
> ` id={opt}`
> 
> Adding the IDs to each option during your render will ensure they always have the correct ID. I've added a ticket below for us to make this work without any further code. Also as a side note, would you not just want the All option to always be there?
> 
> https://codesandbox.io/p/sandbox/select-with-on-the-fly-all-option-forked-74ypdk?file=%2Fsrc%2Findex.js%3A27%2C29

Thanks @nicktitchmarsh, but showing all option after some option is selected was part of the definition.
