### ISSUE TITLE
Multi-Action Button axe failure

### ISSUE THREAD

**Issue by mohitkudi** [Sage/carbon#6383]
### Current behaviour

The multi-action button gives axe issue: "ARIA roles must contain particular children"

### Expected behaviour

No axe errors on multi-action button

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/multi-action-button--default-story

### Suggested Solution

role of `menuitem` should be used instead of `menu-item`.

### Carbon Version

v122.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6249
