### ISSUE TITLE
FilterableSelect openOnFocus Dialog

### ISSUE THREAD

**Issue by gupaz** [Sage/carbon#6384]
### Current behaviour

FilterableSelect openOnFocus doesn't work in Dialog

### Expected behaviour

Filterable select list automaticly opened on Dialog opened

### CodeSandbox or Storybook URL

https://codesandbox.io/s/filterableselect-autofocus-in-dialog-forked-t5mnf8

### JIRA Ticket (Sage Only)

FRTRADS-14762

### Carbon Version

121.2.0

### Design Tokens Version

4.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6262
