### ISSUE TITLE
Scroll position reset to second item in list

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#6399]
### Current behaviour

Selecting drop down > scrolling to bottom of list > clicking off the drop down so it closes > reselect the drop down > the scroll has reset back to the second item in the list.

### Expected behaviour

Reset to the first item in the list. 

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select-filterable--default

### Carbon Version

120.1.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6260
