### ISSUE TITLE
Modal appears behind side bar

### ISSUE THREAD

**Issue by bepud** [Sage/carbon#6402]
### Current behaviour

When a dialog and a sidebar (both coming from 2 different MFEs) are rendered on the load of the application, the dialog appears behind the sidebar.
On our case, as the MFE which open the dialog render faster than the MFE which open the sidebar, the dialog is added on the DOM before the sidebar then it appears behind.

### Expected behaviour

We would expect to see the dialog on the top of the sidebar.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/clever-ully-8xk3dg?file=/src/App.js:0-1331

### Suggested Solution

We would need a way to determine which one is on the top.

### Carbon Version

120.6.1

### Design Tokens Version

4.22.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6259
