### ISSUE TITLE
Toast message cannot be closed when a dialog is opened on top of it

### ISSUE THREAD

**Issue by foxyd-sage** [Sage/carbon#6410]
### Current behaviour

I faced an issue in the [Toast](https://carbon.sage.com/?path=/docs/toast--default) and [Dialog](https://carbon.sage.com/?path=/docs/dialog--other-focusable-containers) component from the Carbon library.
To be exact, the User can’t close the Toast dialogue when opening some other dialogue.
After investigating this bug, I found the property “inert” in the “carbon-portal” class,
which blocks the interaction with the Toast message dialogue.

### Expected behaviour

The user should have the opportunity to close the Toast message, whenever he wants. 
The Toast message shouldn't be blocked if you open the Dialog again.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/kind-poincare-mp6xhl?file=/src/App.js

### JIRA Ticket (Sage Only)

SBS-73513

### Carbon Version

120.1.0

### Design Tokens Version

4.23.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

Steps to reproduce this bug in the [codesandbox](https://codesandbox.io/s/kind-poincare-mp6xhl?file=/src/App.js):

1. Click the **Open First Dialog** button
2. Click the **Save Details** button
3. Close the **DialogFullScreen** that is currently open by clicking the **X** icon in the top right
4. Click the **Open Second Dialog** button
5. Now try closing the currently open **Toast** that has the text **Details saved successfully**

It is not possible to close this currently open **Toast** unless you close the newly opened **Dialog**

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Likely related/similar to https://github.com/Sage/carbon/issues/6402

**Comment by edleeks87** [comment]
FE-6259
