### ISSUE TITLE
Under Firefox, the Select control in-focus UI display is not refreshed on loss of focus if a dialog is opened

### ISSUE THREAD

**Issue by james-burkill** [Sage/carbon#6415]
### Current behaviour

- Set up a page using the carbon select control in such a way that selecting an option launches a dialog.
- Open the page in Firefox
- Select from the dropdown
- Close the resulting dialog
- Move the focus away from the select control

The Select control retains its yellow border as if it were still selected.
![image](https://github.com/Sage/carbon/assets/59570060/246a45b2-1253-47eb-8a14-cc22bb530f9f)

### Expected behaviour

When the select component loses focus, the yellow border indicating focus should not remain in place.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/flamboyant-bhabha-t6t9y5?file=/src/App.js

### JIRA Ticket (Sage Only)

SKPU-10372

### Carbon Version

120.4.0

### Design Tokens Version

4.21.0

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6274
