### ISSUE TITLE
Responsive tile

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#6419]
### Desired behaviour

We want the Tile to be responsive. 
When there is not enough space, the elements inside the Tile should wrap on a new line and a divider should appear between the lines.

### Current behaviour

Currently, the Tile is not responsive and the elements will shrink until they reach theirs min-width and they overflow the Tile.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6269
