### ISSUE TITLE
Cannot scroll table via keyboard when table has focus  (where prop hasStickyHead applies to FlatTable)

### ISSUE THREAD

**Issue by bendyckhoff** [Sage/carbon#6425]
### Current behaviour

When a FlatTable has the prop hasStickyHead the following incorrect behaviour is seen:

When the table has a scrollbar and that table has focus, and the spacebar is pressed, the table is not scrolled (if the page has a scrollbar, this is scrolled instead). 
Additionally the arrow keys do not scroll the table. 

### Expected behaviour

When the table has a scrollbar and that table has focus,  and the spacebar is pressed or the arrow keys are pressed, the table should scroll.

### CodeSandbox or Storybook URL

https://carbon.sage.com/v/123.7.2/iframe.html?viewMode=docs&id=flat-table--with-sticky-head-row-span-and-colspan&args=#with-stickyhead-rowspan-and-colspan

### JIRA Ticket (Sage Only)

SBS-76163

### Carbon Version

123.72

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

This potentially poses a serious accessibility issue for anyone who can only use a keyboard. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6273
