### ISSUE TITLE
MultiActionButton - subtext prop has no effect unless the button is large 

### ISSUE THREAD

**Issue by divyajindel** [Sage/carbon#6433]
### Current behaviour

<img width="1276" alt="Screenshot 2023-11-16 at 22 06 15" src="https://github.com/Sage/carbon/assets/88449494/abd8b327-e382-49f7-8120-dd4550abdab8">

### Expected behaviour

Subtext textArea should be disabled when size is selected as small or medium.

### CodeSandbox or Storybook URL

http://localhost:9001/?path=/story/multi-action-button-test--multi-action-button-story&args=subtext:text

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
Spoke with @divyajindel privately regarding this and we've agreed to close this issue as this behaviour is intentional.
