### ISSUE TITLE
Link focus indicator within Box extends beyond the displayed component

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#6434]
### Current behaviour

When tabbing onto a link, the focus indicator extends to the width of the parent container. Happens in v119.11.0 (my codebase) and the latest version of Carbon (as per Sandbox)

### Expected behaviour

The focus indicator should only wrap the component's children, and ignore the parent

### CodeSandbox or Storybook URL

https://codesandbox.io/s/elastic-ride-2gf3mt?file=/src/App.js

### Carbon Version

119.11.0

### Design Tokens Version

4.23.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-6280
