### ISSUE TITLE
Accessibility issue (contrast)

### ISSUE THREAD

**Issue by DavidBouffort** [Sage/carbon#6436]
### Current behaviour

The contrast of the completed step on a step flow component is not correct when used on a grey background (the green is not good); a serious issue is find with AXE

![Capture d’écran 2023-11-17 à 16 20 34](https://github.com/Sage/carbon/assets/18547992/2c7ea962-1b5c-4820-b8ee-b854fc02d979)

### Expected behaviour

Update the green colour.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/step-sequence--default-story

### Carbon Version

last

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@ljemmo @harpalsingh are you able to advise on the correct colour to use here?

**Comment by ljemmo** [comment]
@DavidBouffort could this problem be solved by simply adjusting the background to white?

**Comment by DavidBouffort** [comment]
@ljemmo Sorry, it's not possible to use a white background here. I talked to Andy this morning and he needs to discuss this point with Claire.

**Comment by ljemmo** [comment]
@DavidBouffort no worries. @clairedenning should have a fix for this ASAP. Carbon will need to update tokens to the latest version once claire has pushed her fix up. @edleeks87 can you help with this?

**Comment by clairedenning** [comment]
@edleeks87 the updated token values have been pushed :)

**Comment by DavidBouffort** [comment]
[heart]         Bouffort, David reacted to your message:
________________________________

**Comment by Parsium** [comment]
Hi @DavidBouffort 👋🏼 We have a ticket in flight to address this. Like @ljemmo mentioned, we have updated the background colour of `Dialog` to white to fit these latest DS changes. Here is the ticket for reference:

FE-6191

**Comment by DavidBouffort** [comment]
Sometimes the step sequence is used on a grey background and in this case, the contrast check is not valid.
So the proposal to use a step sequence on a white background can't work.
The positive green colour must be adapted in this case to be able to have a valid check with our accessibility tool.

**Comment by ljemmo** [comment]
We have pushed a new accessible green that works on the gray bg as well as white. Carbon just need to update to the latest tokens version @DavidBouffort

**Comment by Parsium** [comment]
Thanks Luke 👍🏼 

@DavidBouffort teams should be able to upgrade to the latest version of the `@sage/design-tokens` package already - independently to Carbon. So I would recommend speaking with the product dev teams you work with to upgrade the package.

**Comment by DavidBouffort** [comment]
Thanks all. Great job. :)
