### ISSUE TITLE
NumeralDate allows certain invalid dates

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#6438]
### Current behaviour

The `NumeralDate` component only partly validates an entry. For example, entering `31st February 1924` as a date is accepted but `31st September 1924` is correctly flagged as erroneous

### Expected behaviour

Dates should be correctly validated and accepted/rejected.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/romantic-leaf-p44yf3

### Carbon Version

123.9.1

### Design Tokens Version

4.29.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

CodeSandbox example is from a prototype I'm building for a separate bit of work - it was just easier to link to that one than create a new one

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by robinzigmond** [comment]
FE-6279
