### ISSUE TITLE
Filterable select should trim the value

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#6446]
### Current behaviour

https://carbon.sage.com/?path=/docs/select-filterable--default#default
In the example above if we type `Amber` we see on the list the `Amber` option
If we type through ` Amber` or `Amber ` we do not see the option on the list

### Expected behaviour

I think we should trim that value, or at least trim start and the user can see the `Amber` option

### CodeSandbox or Storybook URL

https://codesandbox.io/s/brave-chatelet-zvlmrq?file=/src/App.js

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6284
