### ISSUE TITLE
TextBox validation messages are limited to input width

### ISSUE THREAD

**Issue by james-burkill** [Sage/carbon#6448]
### Desired behaviour

To be possible to specify a width for the validation message that is independent of the width of the textbox, or otherwise facilitate a means by which the validation message can be wider than the textbox to use the available space.

### Current behaviour

Currently, the validation message is wrapped to the width of the textbox.

![image](https://github.com/Sage/carbon/assets/59570060/fd85e727-b747-4bcd-ab77-7aa95917e6bb)

https://codesandbox.io/s/reverent-hawking-96rwkq?file=/src/App.js

### Suggested Solution

See desired behaviour.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/reverent-hawking-96rwkq?file=/src/App.js

### Anything else we should know?

No.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @james-burkill, this will require some input from the Design System first. 

Looking at their docs, there don't seem to have any guidance around label and validation message width, so I would suggest contacting them via their Teams channel first and asking if labels/validation messages should be constrained to the width of the input box.

**Comment by nicktitchmarsh** [comment]
Your codesandbox shows a `Box` wrapping the input set to 50% width. If you supply the maxWidth prop to the input field instead this will have the desired behaviour.

https://codesandbox.io/p/sandbox/misty-bush-spkyyw?file=%2Fsrc%2FApp.js%3A22%2C1
