### ISSUE TITLE
Select component very slow to select

### ISSUE THREAD

**Issue by james-burkill** [Sage/carbon#6452]
### Desired behaviour

Improved performance with respect to the time it takes to select from a Carbon Select component.

### Current behaviour

When there are 150 options loaded into a Select component, each time a user selects from the list, it takes 3-4 seconds for the selection to complete.  This seems very slow for that volume of data.

See sandbox [example](https://codesandbox.io/p/sandbox/ecstatic-robinson-ppt2k2?file=%2Fsrc%2Findex.js%3A11%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb2hvml0007356iwjbega65%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb2hvml0003356i9npf1vou%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb2hvml0004356i3jn0h4lb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb2hvu8000j356ihr5amod4%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb2hvml0006356it29v0g2t%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb2hvu8000j356ihr5amod4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clpb2hvu8000j356ihr5amod4%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%252C%2522clpb2hvml0003356i9npf1vou%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb2hvmk0002356iredkx81v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A27%257D%255D%257D%255D%252C%2522id%2522%253A%2522clpb2hvml0003356i9npf1vou%2522%252C%2522activeTabId%2522%253A%2522clpb2hvmk0002356iredkx81v%2522%257D%252C%2522clpb2hvml0006356it29v0g2t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb2hvml0005356izxl1922u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpb2hvml0006356it29v0g2t%2522%252C%2522activeTabId%2522%253A%2522clpb2hvml0005356izxl1922u%2522%257D%252C%2522clpb2hvml0004356i3jn0h4lb%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpb2hvml0004356i3jn0h4lb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/ecstatic-robinson-ppt2k2?file=%2Fsrc%2Findex.js%3A11%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb2hvml0007356iwjbega65%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb2hvml0003356i9npf1vou%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb2hvml0004356i3jn0h4lb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb2hvu8000j356ihr5amod4%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb2hvml0006356it29v0g2t%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb2hvu8000j356ihr5amod4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clpb2hvu8000j356ihr5amod4%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%252C%2522clpb2hvml0003356i9npf1vou%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb2hvmk0002356iredkx81v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A27%257D%255D%257D%255D%252C%2522id%2522%253A%2522clpb2hvml0003356i9npf1vou%2522%252C%2522activeTabId%2522%253A%2522clpb2hvmk0002356iredkx81v%2522%257D%252C%2522clpb2hvml0006356it29v0g2t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb2hvml0005356izxl1922u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpb2hvml0006356it29v0g2t%2522%252C%2522activeTabId%2522%253A%2522clpb2hvml0005356izxl1922u%2522%257D%252C%2522clpb2hvml0004356i3jn0h4lb%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpb2hvml0004356i3jn0h4lb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @james-burkill 👋🏼 `Select` does support "virtual scrolling" for cases where they are a large number of options that need to be loaded. This will lazily load them so it shouldn't heavily impact performance. We have an example in our docs here which may be useful to read more:

[Link to virtualisation example](https://carbon.sage.com/?path=/story/select--virtualised)

**Comment by nicktitchmarsh** [comment]
FE-6304 had been raised to investigate the performance issue. James' suggestion might mitigate the problem in the short term.

**Comment by nicktitchmarsh** [comment]
@james-burkill there is a new example with our latest version of Carbon and this doesn't seem to be an issue anymore. Copied your example from previous CodeSandbox https://stackblitz.com/edit/parsium-carbon-starter-qfy7fp?file=src%2FApp.tsx
