### ISSUE TITLE
[Select] Runtime error when navigating with arrows

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#6459]
### Current behaviour

Given a FilterableSelect
When the text introduced have no results in the options
And the arrow down key is pressed
Then the component breaks trying to read the props of the option

### Expected behaviour

Given a FilterableSelect
When the text introduced have no results in the options
And the arrow down key is pressed
Then nothing happens

### CodeSandbox or Storybook URL

https://codesandbox.io/s/filterable-select-wfntgg

### Carbon Version

123.11.2

### Design Tokens Version

4.34.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6290
