### ISSUE TITLE
On next page load of Select infinite scroll, jumps to selected option rather than retaining scroll position

### ISSUE THREAD

**Issue by quinnturner** [Sage/carbon#6461]
### Current behaviour

https://github.com/Sage/carbon/assets/12538019/a69165bc-6b2a-433c-9cc4-af7aa57fd2b4

On the next page load, it goes back to the selected value.

### Expected behaviour

Should retain scroll position

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select--with-infinite-scroll

### Carbon Version

123.11.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6291
