### ISSUE TITLE
FilterableSelect obejct as value and openOnFocus trigger open on click option

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#6462]
### Current behaviour

when we use a FilterableSelect that has as value an object, and we use the prop openOnFocus , if we click an option close and open the menu

### Expected behaviour

should just select and close the menu

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/confident-cherry-cfmlxm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpjx8c3j00073b6hgjzdhv0j%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpjx8c3i00033b6h14o6vzk1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpjx8c3i00043b6hta8fc84f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpjx8c3i00063b6h9i49swh8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B45.34072839435217%252C54.65927160564783%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpjx8c3i00033b6h14o6vzk1%2522%253A%257B%2522id%2522%253A%2522clpjx8c3i00033b6h14o6vzk1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpjx9zqf006w3b6hiusm5njp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A62%252C%2522startColumn%2522%253A70%252C%2522endLineNumber%2522%253A62%252C%2522endColumn%2522%253A70%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpjx9zqf006w3b6hiusm5njp%2522%257D%252C%2522clpjx8c3i00063b6h9i49swh8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpjx8c3i00053b6hxaxtv0c2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpjx8c3i00063b6h9i49swh8%2522%252C%2522activeTabId%2522%253A%2522clpjx8c3i00053b6hxaxtv0c2%2522%257D%252C%2522clpjx8c3i00043b6hta8fc84f%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpjx8c3i00043b6hta8fc84f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6292

**Comment by alex-j-clark** [comment]
Hi - we have just move from Carbon version 119 to 123.11 and are experiencing the same issue now - is there any estimate for when this bug will be fixed? Many thanks.
