### ISSUE TITLE
FilterableSelect disable doesn't disable opening popover or selecting a new value

### ISSUE THREAD

**Issue by quinnturner** [Sage/carbon#6471]
### Current behaviour

https://carbon.sage.com/?path=/docs/select-filterable--default#disabled

1. Click the dropdown
2. (Popover is now open, likely shouldn't be)
3. Click a new value in the popover
4. (Value is updated)

I've tried several combinations of `readOnly`, `disabled`, `event.stopPropagation()` at multiple levels, null callbacks; basically everything. I cannot disable selecting a new value in the current component.

I haven't tried the normal `Select` property to see if there is similar behavior.

### Expected behaviour

1. Preferably, disallow opening the popover
2. At a minimum, disallow selecting a new value in the FilterableSelect popover

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/select-filterable--default#disabled

### Carbon Version

123.11.2

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Broken in `v123.4.4`

**Comment by edleeks87** [comment]
FE-6293
