### ISSUE TITLE
Action Popover makes page scroll to top when in tabular components

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon#6485]
### Current behaviour

We noticed this with an embedded popover in AG Grid but it happens with the Flat Carbon table too (see storybook link)

If you click it, the page will scroll to the very top, if not there already.

Appears to be caused by a sideffect which is focusing the first menu item (indirectly causing the scroll to the top) before it's re-positioned to its anchor element.

https://github.com/Sage/carbon/blob/191c8553fb1d9f8f0f5934dd016502d29aa8f29f/src/components/action-popover/action-popover-item/action-popover-item.component.tsx#L218C15-L218C15

### Expected behaviour

It shouldn't cause that scroll to happen.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/action-popover--action-popover-component#in-flattable-with-highlightable-rows

### Carbon Version

118.2.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6310
