### ISSUE TITLE
Dismissible Box component should have a provision to add data-role to the close Icon

### ISSUE THREAD

**Issue by sagemihir** [Sage/carbon#6487]
### Desired behaviour

Dismissible Box component should have a provision to add data-role to the close Icon

### Current behaviour

There is no provision to add data-role to the close Icon for tracking purposes

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/dismissible-box--default-light-variant

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
For those in triage, looking at the code for the button:

![Screenshot 2023-12-18 at 10 30 16](https://github.com/Sage/carbon/assets/18368713/e3e56704-20da-47d5-978b-ca7158c4c4a4)

I'd suggest we encourage consumers to locate the close button via its ARIA label. With React Testing Library, they should be able to locate it like so:

```ts
const closeButton = screen.getByRole("button", { name: "close-button" });
```

However, we currently [hardcode the ARIA label](https://github.com/Sage/carbon/blob/master/src/components/dismissible-box/dismissible-box.component.tsx#L45) which isn't ideal for localisation, so it would be worth us using a locale translation key here instead.

**Comment by nicktitchmarsh** [comment]
FE-6309

**Comment by Parsium** [comment]
Hi @sagemihir 👋🏼 We have now added the `data-role` to the close icon in the latest release.

An aside to this new data prop, we have also updated the icon so it's `aria-label` can be amended via the translation key `dismissableBox.ariaLabels.close`. If you are using React Testing Library in your tests, this should allow you to alternatively target the close button's aria-label if you wish, like so:

```tsx
it("close button is rendered in 'Target me!' box", () => {
  render(
    <>
      <DismissibleBox onClose={() => {}}>Target me!</DismissibleBox>
      <DismissibleBox onClose={() => {}}>Some other dismissible box</DismissibleBox>
    </>
  );

  const dismissableBox = screen.getByText(/Target me!/);
  const closeButton = within(dismissableBox).getByLabelText("Close");
  expect(closeButton).toBeInTheDocument();
});
```
