### ISSUE TITLE
MenuSegmentTitle

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6488]
### Current behaviour

`MenuSegmentTitle` applies rounding to the last child, which is not correct when the `MenuSegmentTitle` component is not the last item in the menu.

### Expected behaviour

No rounding to occur where other elements follow below `MenuSegmentTitle`.

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/menusegmenttitle-border-radius-4tqhzp

### Carbon Version

124.3.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6307
