### ISSUE TITLE
Pager with page selection on Table footer override click area on pager button

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#6490]
### Current behaviour

When the space between the page selector and `First` button/link is tight we can not click the first button, most of the area of the First button when clicked open the page selector
closed

![image](https://github.com/Sage/carbon/assets/84023810/8e37c522-9106-477e-89ff-22c95de9da90)

### Expected behaviour

The page selector button array should occupy only its space

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/floral-shadow-8zwf4j?file=%2Fsrc%2FApp.js%3A3%2C57

### Carbon Version

latest

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

iOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6307
