### ISSUE TITLE
Escaping date input within a dialog closes the dialog 

### ISSUE THREAD

**Issue by danielthomas2** [Sage/carbon#6505]
### Current behaviour

If you have a date input within a dialog, then open the date picker and hit escape, both the date picker and the dialog are closed. Seems this issue was introduced since v123.4.0, where keyboard navigation within the date picker was supported.
I would expect only the date picker to be closed, and the dialog to close only if I press escape again.

### Expected behaviour

Hitting escape within the date picker should only close the date picker, and not close the dialog as well.

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/practical-tesla-nlx83m?file=%2Fsrc%2Findex.js%3A8%2C1

### Carbon Version

124.4.1

### What browsers are you seeing the problem on?

Microsoft Edge

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6325
