### ISSUE TITLE
Negative margin on  Tabs causing overflow

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6511]
### Current behaviour

Tabs component causing horizontal overflow due to negative margin on the tablist, resulting in a scrollbar appearing regardless of content.

### Expected behaviour

No overflow to occur unless content requires.

### CodeSandbox or Storybook URL

https://codesandbox.io/p/devbox/carbon-quick-start-forked-wdh3zm

### JIRA Ticket (Sage Only)

SBS-70662

### Carbon Version

124.6.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6331
