### ISSUE TITLE
[FilterableSelect] selectConfirmation returns true when no results

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#6518]
### Current behaviour

Given a FilterableSelect
When typing a non existent option
And press enter
Then selectionConfirm property in the event is true

### Expected behaviour

Given a FilterableSelect
When typing a non existent option
And press enter
Then selectionConfirm property in the event should be false

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/filterable-select-xshdvx?file=%2Fsrc%2FApp.tsx%3A13%2C5

### Carbon Version

124.4.1

### Design Tokens Version

4.23.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-6332
