### ISSUE TITLE
Allow overriding the character count translation for Text Editor

### ISSUE THREAD

**Issue by ernon66** [Sage/carbon#6529]
### Desired behaviour

The character count translation for a Text Editor should be customisable like the rest of its content

### Current behaviour

Other content is customisable for Text Editor, but not the character count

### Suggested Solution

I guess the number of characters is an issue but is should be achievable with a {{variable}} in the custom translation content

### Anything else we should know?

JIRA ticket SBS-81959

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by sianford** [comment]
FE-6340

**Comment by Parsium** [comment]
Hi @ernon66 👋🏼 We realised these translation keys were missing in the docs for `TextEditor`. Apologies for this. This has now been corrected 👍🏼
