### ISSUE TITLE
Actionpopover can cause unexpected scroll to top of page when in table. 

### ISSUE THREAD

**Issue by Chris3y** [Sage/carbon#6531]
### Current behaviour

We noticed this with an ActionPopover menu that's embedded into AG Grid but the same issue is observable in the Carbon storybook flat table example (though it's intermittent so you might have to try clicking it a couple of times before you notice a sudden scroll to top. 

When the menu is opened, it will momentarily (and imperceptibly) appear in the top left of the page before it is repositioned/re-attached to its parent component. Because it attempts to focus itself when opening, it is sometimes focusing during this brief moment at the top of the screen, causing a scroll to the top of the page

### Expected behaviour

It shouldn't cause an unexpected scroll to top of the page

### CodeSandbox or Storybook URL

https://carbon.sage.com/iframe.html?viewMode=docs&id=action-popover--action-popover-component#in-flattable-with-highlightable-rows

### Carbon Version

125

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
duplicates [#6485](https://github.com/Sage/carbon/issues/6485)
