### ISSUE TITLE
Broken styling in popover container within menu item

### ISSUE THREAD

**Issue by Sage-AlanYoung** [Sage/carbon#6538]
### Current behaviour

When updating to V125.0.0 https://github.com/Sage/carbon/releases/tag/v125.0.0, the popover container used within a menu item breaks, but it doesn't seem to be related to any of the release notes for this version.

I have a codesandbox example here https://codesandbox.io/p/sandbox/quizzical-gould-n4gzj6 which will hopefully illustrate the issue. If you run it as is (on version 124.6.1) you'll see the popover container working correctly but if you updated to 125.0.0 you'll see the broken behaviour

https://github.com/Sage/carbon/assets/110925864/d735dc8f-d354-4566-a20b-a80ceb9e832b

### Expected behaviour

https://github.com/Sage/carbon/assets/110925864/452187b6-87b7-469d-a685-21ceac5e7bb4

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/quizzical-gould-n4gzj6

### Carbon Version

125.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6343
