### ISSUE TITLE
`FilterableSelect` with Action Button: list scrollbar extends beyond list viewport, covers action button

### ISSUE THREAD

**Issue by justin-rankin** [Sage/carbon#6541]
### Current behaviour

When optional Action Button is present, set by the `listActionButton` prop, the scrollbar of the options list extends to the bottom of the menu, which:

- exceeds height of options list viewport
- covers / is over the action button

![screenshot_20240124_09 23 00](https://github.com/Sage/carbon/assets/79138818/f94266d6-e00a-43d6-8207-1ae6815ad607)

### Expected behaviour

Extents of scrollbar track should match the height of the options list viewport for which it is scrolling.
The bottom of the scrollbar should therefore end at the top of the action button.

### Storybook URL

https://carbon.sage.com/?path=/docs/select-filterable--default

### CodeSandbox URL

https://codesandbox.io/p/sandbox/ecstatic-dew-t5ldc5?file=%2Fsrc%2FApp.js%3A38%2C24

### JIRA Ticket (Sage Only)

SBS-80319

### Suggested Solution

NOTES: 
- Carbon, SD, and UX teams all agree on the expected behaviour
- Figma assets for this component have the correct version

### Carbon Version

125.3.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6348
