### ISSUE TITLE
`Message` component `transparent` mode displays extra paddings

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#6552]
### Current behaviour

As shown in this storybook link, 
https://carbon.sage.com/?path=/docs/message--default#transparent
The text in the `Message` component has excessive padding, resulting in a wide gap between the icon and the text itself.

![Screenshot 2024-01-30 at 08 42 37](https://github.com/Sage/carbon/assets/90848080/fb8f1598-a293-47d7-8f4a-c42309e7038d)

### Expected behaviour

![Screenshot 2024-01-30 at 08 45 45](https://github.com/Sage/carbon/assets/90848080/474c0e4d-4abc-4a82-bd49-fd07b8b380a7)

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/message--default#transparent

### Carbon Version

124.6.0

### Design Tokens Version

4.28.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6347
