### ISSUE TITLE
`FlatTableRowHeader` with `Button` causes extra paddings

### ISSUE THREAD

**Issue by JinCoreana** [Sage/carbon#6561]
### Current behaviour

The default settings cause extra paddings within the cell,

```
      <FlatTableRowHeader stickyAlignment="right">
        <Button>Default</Button>
      </FlatTableRowHeader>
```

<img width="126" alt="Screenshot 2024-02-01 at 11 27 07" src="https://github.com/Sage/carbon/assets/90848080/a3fe3594-50b1-4eb7-a256-8a0a2c3d37f7">

With p={0} attribute, focus outline gets partially hidden
```
      <FlatTableRowHeader p={0} stickyAlignment="right">
        <Button>Padding 0</Button>
      </FlatTableRowHeader>
```
<img width="219" alt="Screenshot 2024-02-01 at 11 28 58" src="https://github.com/Sage/carbon/assets/90848080/1d583eee-4777-496a-a919-23a94bb8c60d">

### Expected behaviour

When a `Button` is placed within a sticky cell, it should not result in additional padding, and the focus outline should be fully visible.
<img width="168" alt="Screenshot 2024-02-01 at 11 29 45" src="https://github.com/Sage/carbon/assets/90848080/a3491425-c73f-4cb8-8801-a636adafae3f">

### CodeSandbox or Storybook URL

https://codesandbox.io/p/sandbox/table-padding-focus-kzm5nr

### JIRA Ticket (Sage Only)

SBS-81079

### Carbon Version

124.6.0

### Design Tokens Version

4.28.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @JinCoreana 👋🏼 The sandbox link you have provided seems to redirect to an error page. Just so we have some more context, please could you recreate your code example using [our new stackblitz template](https://stackblitz.com/fork/github/Parsium/carbon-starter)?

**Comment by JinCoreana** [comment]
> Hi @JinCoreana 👋🏼 The sandbox link you have provided seems to redirect to an error page. Just so we have some more context on the design you are trying to produce, please could you recreate your code example using [our new stackblitz template](https://stackblitz.com/fork/github/Parsium/carbon-starter)?

Hi @Parsium  No problem! here is the new link.
https://stackblitz.com/edit/parsium-carbon-starter-dmv1pi?file=src%2FApp.tsx

**Comment by nicktitchmarsh** [comment]
FE-6373
