### ISSUE TITLE
Button as a link are not being read by screen readers for Safari

### ISSUE THREAD

**Issue by Isabelle-whi** [Sage/carbon#6569]
### Current behaviour

When tabbing through a page a button as a link component is not being read by screen readers in Safari. It is being read as expected in chrome. 

### Expected behaviour

Screen reader to read out  "Button, button text"

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/button--primary-button#button-as-a-link

### Carbon Version

v125.9.3

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @Isabelle-whi 👋🏼 This is the intended behaviour for `Button` as we are [setting a `role="button"` on the button itself](https://carbon.sage.com/?path=/docs/button--button-as-a-link#button-as-a-link). While I appreciate we support rendering `Button` as a link, accessibility-wise this isn't best practice, so if possible would you be able to replace it using our `Link` component instead?

**Comment by Isabelle-whi** [comment]
We have raised the possibility of using a Link instead with the design team but for now it is staying as a button. In chrome it reads out when tabbing through so i had assumed  it was just an issue with safari.

**Comment by nicktitchmarsh** [comment]
@Isabelle-whi We aren't able to reproduce this not reading out the Button text. Could you check your Safari and VoiceOver are up to date please?

**Comment by Isabelle-whi** [comment]
I updated this morning but am still seeing the issue. MacOS: 14.3. Safari: 17.3

**Comment by nicktitchmarsh** [comment]
https://www.tempertemper.net/blog/how-to-use-the-keyboard-to-navigate-on-safari this is a configuration issue and not an issue with Carbon. Confirmed with @Isabelle-whi
