### ISSUE TITLE
Add inputHint prop to Inline inputs

### ISSUE THREAD

**Issue by stephenpowers-sage** [Sage/carbon#6571]
### Desired behaviour

Ability to set inputHint on the Inline inputs component.

### Current behaviour

No inputHint on the Inline inputs component. You could set an inputHint one of the fields within it but the text will wrap around the input and put it out of alignment with the inputs next to it.

### Suggested Solution

Add inputHint prop. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Hi @stephenpowers-sage 👋🏼 Looking at this and the external Slack thread, we felt during triage reviewing the future of the `InlineInputs` component would be best, as having a single label shared between multiple inputs is not great practice for accessibility.

Looking at your design, would you be able to replace `InlineInputs` with our `GroupedCharacter` component instead? This should allow you to group certain characters together with a separator in-between, but there would be one input instead with one associated label.

**Comment by nicktitchmarsh** [comment]
@stephenpowers-sage Are we ok to solve this with a design change rather than a Carbon change?

**Comment by stephenpowers-sage** [comment]
Unfortunately not, using `GroupedCharacter` would have been an ideal solution if we were building new but due to data legacy, we store what should be a single number in the DB as two separate parts. Understand if you prefer not to introduce a feature you'd prefer not to be used just for this one-off use case. At present, I have a bit of hacky Grid, typography and textbox solution that does the job :)

**Comment by Parsium** [comment]
Hi @stephenpowers-sage, yeah I would suggest that you create a custom layout using `Box`, `Grid`, `Typography`, `Textbox`, etc. that would be ideal here. I'll close this for now, but feel free to reopen this if you encounter further problems 👍🏼
