### ISSUE TITLE
`Submenu with search` storybook is broken, padding changed

### ISSUE THREAD

**Issue by amieedwards-sage** [Sage/carbon#6581]
### Description

Updating `carbon` from `123.9.0` to `125.12.1` - has revealed the styling of the nested `Search` element has changed.
Appears this issue was introduced in`125.0.1`
Also visible in Carbon storybook

![Screenshot 2024-02-12 at 16 12 03](https://github.com/Sage/carbon/assets/114926720/7f3b43e4-2222-4a2e-8c0a-4a431b7b2545)

### Reproduction

https://carbon.sage.com/iframe.html?viewMode=docs&id=menu--default-story&args=#submenu-with-search

### JIRA ticket numbers (Sage only)

SBS-84420

### Carbon version

124.0.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

This is currently blocking a `Template UI` update to `125.12.1`

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@amieedwards-sage it looks like we corrected an issue where margin passed into MenuItems wasn't being respected. Please could you confirm if your menu has additional padding added as well? If so this can be removed now. We will correct our Storybook stories

**Comment by nicktitchmarsh** [comment]
FE-6370

**Comment by edleeks87** [comment]
I've addressed this as part of FE-6078 as some of the styling changes will affect how it renders in Menus anyway

**Comment by edleeks87** [comment]
The issue is that the padding is now applied to the main item wrapper when it should be on the Link it renders internally
