### ISSUE TITLE
Select (With Object): First open, the value is not selected

### ISSUE THREAD

**Issue by hegou33** [Sage/carbon#6600]
### Description

The first time that we open the Select, we cannot see the option selected.
By the way, do we really need to use a useRef in this case ?

### Reproduction

https://carbon.sage.com/?path=/docs/select--with-object-as-value

### Steps to reproduce

After loading the page:
- Open the select
- No value are loaded (Normally Green need to be selected)

### Carbon version

126.5.0

### Design tokens version

4.23.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6387

You are right, we will improve our documentation here as the example is not great. Functionally this does work but our example doesn't pass the correct value object.
