### ISSUE TITLE
Tile Bar Component

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#665]
A generic tile bar component might be a nice addition, with a full width background and a set of tiles inside it, like:

<img width="603" alt="screen shot 2016-08-13 at 20 08 59" src="https://cloud.githubusercontent.com/assets/145826/17645043/cf1b709c-6191-11e6-97bf-0182240e27c1.png">

 handling the responsiveness and with unique content allowed

```
<OptionalFullWidthBackground>
  <ResponsiveTileBlock>
    <Tile />
    <Tile />
    <Tile />
  </ResponsiveTileBlock>
</OptionalFullWidthBackground>
```

**Comment by andrewjtait** [comment]
Need to retest that we can potentially achieve this with Pod with new props that have since been added.

**Comment by toni-leigh** [comment]
The screen shot here was a bit misleading, it should have shown the set of tiles rather than just one

However, I think that's something that's more app specific than for Carbon, IMO, apps should be creating their own set of re-usable UI building blocks that are more specific to themselves

**Comment by edleeks87** [comment]
We introduced a Tile component in v9 similar to this but based on the DLS requirements
