### ISSUE TITLE
Form validation summary unresponsive at 320px

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#6658]
### Description

When I am using a small screen the form error validation isn't shown in full. I expect the full text to be visible on the page. 

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-k3ccdw?file=src%2FApp.tsx

### Carbon version

125.12.1

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@harpalsingh are you oaky with us updating the summary to wrap in the above scenario or is there a steer to use a different component/ pattern here?

**Comment by harpalsingh** [comment]
@edleeks87 Makes sense, let me mockup the design with it shown and Ill run it by DS too. I'll add to this issue once ready

**Comment by Parsium** [comment]
Any updates on this @harpalsingh? 😄

**Comment by DipperTheDan** [comment]
@harpalsingh - just tagging you so you know we need a response on this please. Thank you 😄
