### ISSUE TITLE
MenuFullScreen and MenuItem not truncating topic

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6666]
### Description

MenuItems failing to truncate topic when inside a MenuFullScreen parent. works in example Story but not when using MenuFullScreen in our code. demonstrated at desk with @Parsium 

Linked Jira bug is tracking existing issue

### Reproduction

https://carbon.sage.com/?path=/story/menu--truncated-titles-story

### Steps to reproduce

Menu Item with maxWidth prop inside a MenuFullScreen component: width of all children and dialog becomes the width of widest element.

### JIRA ticket numbers (Sage only)

sbs-89600

### Carbon version

130.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@tempertemper before we fix this bug I figured it was worth asking if truncation is still something we should support in MenuItem or should we be looking to wrap the text here instead?

**Comment by Parsium** [comment]
FE-6541

**Comment by camilledegomme** [comment]
@mihai-albu-sage , do you know when this bug will be fixed?
