### ISSUE TITLE
Item remains highlighted in Select dropdown after clearing

### ISSUE THREAD

**Issue by nick-khaustov-sage** [Sage/carbon#6669]
### Description

With a simple controlled select (similar to one in the documentation), after clicking Clear, the input is cleared but the previous item remains highlighted. The expectation is that no item should be highlighted.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-df8xvy?file=src%2FApp.tsx

### Steps to reproduce

Click to open the dropdown - no item is highlighted.
Select an item (for example, Black).
The value in the input now corresponds to the selection
Open the dropdown again - the selected item is highlighted too.
Click Clear button.
The input is cleared.
Open the dropdown again - the previous value is still highlighted 😞.

### Carbon version

131.1.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6431
