### ISSUE TITLE
Checkbox with size `large` allows for flex-shrink reducing spacing between checkbox and label

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6683]
### Description

At small viewport widths, a large checkbox with a sufficiently long label will have reduced spacing between the checkbox and label due to flex-shrink. Most noticeable when focused.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-sh78uy?file=src%2FApp.tsx

### JIRA ticket numbers (Sage only)

SBS-93364

### Carbon version

132.2.1

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6433
