### ISSUE TITLE
Pager component retains focus styling highlight on pagination buttons

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6688]
### Description

![Screenshot 2024-04-18 at 16 25 23](https://github.com/Sage/carbon/assets/53473905/8aeed1f2-6ce0-48ad-9573-82cd0fbb7b65)

going from "next" to "previous" then back to "next" will replicate.
the focus from the previous render of the button will retain the black focus bar under the text

### Reproduction

https://carbon.sage.com/?path=/docs/pager--docs

### Steps to reproduce

going from "next" to "previous" then back to "next" will replicate.
the focus from the previous render of the button will retain the black focus bar under the text

There is a recording attached to the JIRA ticket for further detail calrification

### JIRA ticket numbers (Sage only)

SBS-93920

### Carbon version

130.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-6532
