### ISSUE TITLE
Loader spinner - custom text should be one line and centered

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#6702]
### Description

If i override the label of a Loader Spinner with a long text, it is left align and truncated to take the width of the spinner

![image](https://github.com/Sage/carbon/assets/16415182/7589bc5d-00aa-4aa2-adf9-81105f9f7d2d)

### Suggested solution

The text should be centered on one line.

![image](https://github.com/Sage/carbon/assets/16415182/e8bfac4b-debd-4d36-b8ff-b600c21835e5)

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6539
