### ISSUE TITLE
Text Editor content overflows on small devices 

### ISSUE THREAD

**Issue by IrynaD26** [Sage/carbon#6707]
### Description

We are using `TextEditor` inside the form. When the screen size is 320px, the `TextEditor`  content overflows.

### Reproduction

https://carbon.sage.com/iframe.html?args=&id=text-editor--default&viewMode=story

### Steps to reproduce

1. Open the responsive mode in the browser
2. Make the screen size 320px.
3. Enter characters until you see that text overflows (this is optional. The white background overflows without characters, too).
4. See that the text editor's content overflows.

![image](https://github.com/Sage/carbon/assets/148762678/d7be98c8-14a6-47b5-872d-0ea96e14efba)

### JIRA ticket numbers (Sage only)

SBS-89587

### Carbon version

^133.1.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
FE-6572
