### ISSUE TITLE
MultiActionButton max height / max items for buttons list

### ISSUE THREAD

**Issue by StylianosKoidakisSage** [Sage/carbon#6721]
### Description

some uses of the MultiActionButton component can have many buttons on the lists. Would be nice to provide a solution that we won't show to the user a huge list that would break the UI.

<img width="213" alt="image" src="https://github.com/Sage/carbon/assets/84023810/d3c0eb56-28d2-4934-83ed-b220fdc2faf5">

### Suggested solution

Max height or max items to display would be something useful for may cases

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
@StylianosKoidakisSage Would you mind including a stackblitz of the issue please?

@harpalsingh Is this something that we would like to add. I believe (without seeing the Stackblitz) that the use case makes sense?

**Comment by StylianosKoidakisSage** [comment]
> @StylianosKoidakisSage Would you mind including a stackblitz of the issue please?
> 
> @harpalsingh Is this something that we would like to add. I believe (without seeing the Stackblitz) that the use case makes sense?

what exactly you need? we never use stackblitz before

**Comment by nineteen88** [comment]
> > @StylianosKoidakisSage Would you mind including a stackblitz of the issue please?
> > @harpalsingh Is this something that we would like to add. I believe (without seeing the Stackblitz) that the use case makes sense?
> 
> what exactly you need? we never use stackblitz before

Any issue raised should include a Stackblitz reproduction (if it is reproducible - which this one seems to be). This allows us to see the issue first hand and give us something to test against to ensure we've resolved any problem the issue raiser faced.

This is the template we use to create them: https://stackblitz.com/fork/github/Parsium/carbon-starter

**Comment by nineteen88** [comment]
> The thing is that is not an issue here, only we need new functionality for better UX. I can create a Stackblitz with a big list but i think wont help you

The feature request is effectively a bug and as I mentioned it's so we have a static starting point to test against that we both agree is the primary issue. It saves both the issue raiser and the developer who picks it up a lot of time if both parties start on the same page rather than having to try and replicate every request that is put forward. 

I should also add we need to run this past @harpalsingh as the `better UX` comment is subjective and it's better to show the issue that exists rather than a screenshot

**Comment by StylianosKoidakisSage** [comment]
No problem at all to create a Stackblitz if you think helps. The decision is on your side, i just create the request after the designer request

https://stackblitz.com/edit/parsium-carbon-starter-uuz9yw?file=src%2FApp.tsx

**Comment by harpalsingh** [comment]
Hey @StylianosKoidakisSage I would suggest it might not be the best UX for a user to use a multi-action button with a large list like that, cause we handle things like that already in Selects but its still a problematic pattern. I'll ask @ljemmo if the DS team can be involved into looking into this?

**Comment by StylianosKoidakisSage** [comment]
> Hey @StylianosKoidakisSage I would suggest it might not be the best UX for a user to use a multi-action button with a large list like that, cause we handle things like that already in Selects but its still a problematic pattern. I'll ask @ljemmo if the DS team can be involved into looking into this?

thanks for the answer i will align with our design team

**Comment by ljemmo** [comment]
We're actually currently looking at this component now (in DS). I'll share with Claire and see what max-heights we can suggest to be consumed here. I do agree with Harpal though that we probably shouldn't be encouraging hiding buttons away like this if possible. Based on the screenshot, it looks like @StylianosKoidakisSage is using it for filtering? Usually we would encourage dropdown for that behaviour FYI.
