### ISSUE TITLE
Breadcrumbs component should have a color / backgroundcolor prop

### ISSUE THREAD

**Issue by sagemihir** [Sage/carbon#6724]
### Description

Breadcrumbs component should have a color / backgroundcolor prop for the dark background screens

### Suggested solution

Additional prop for color/background color 

For example:
<img width="696" alt="image" src="https://github.com/Sage/carbon/assets/101108249/15782f02-4a1c-49be-b89b-8cfdbccaa6d5">

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
@ljemmo Breadcrumbs don't have a dark variant like links do but effectively they are just links, right? Should we make changes to Breadcrumbs to follow suit?

**Comment by ljemmo** [comment]
@nineteen88 Makes sense on my side! 

@clairedenning FYI we should probably support on dark breadcrumbs in the fusion DS.

**Comment by clairedenning** [comment]
Can I ask to see an example of somewhere that needs breadcrumbs on a dark bg please? @sagemihir

**Comment by edleeks87** [comment]
I think it would still be good to get some examples of what's wanted here, @sagemihir would you mind sharing them with the carbon and DS teams on slack please? We currently omit certain props from the LinkProps interface before extending them in the CrumbProps interface which we can make changes to to free up support for rendering on dark backgrounds. However, there are other elements rendered as part of this component so we would need to know if they also need styles updated in this scenario

**Comment by sagemihir** [comment]
https://www.figma.com/design/gmNQdGRWOfyR1tVrnU7sz6/SXP-Task-Service---Dev-ready-phase-1?node-id=250-145440&t=5eU54I0zk3IKPIQ6-4

**Comment by emmswalker** [comment]
> Can I ask to see an example of somewhere that needs breadcrumbs on a dark bg please, I'm available on slack or teams? @sagemihir

@clairedenning currently this would be on the onboarding tasks only

https://www.figma.com/design/gmNQdGRWOfyR1tVrnU7sz6/SXP-Task-Service---Dev-ready-phase-1?node-id=239-113650&t=YnCOXOkk7o9Jeg82-0

Let me know if you need to go through anything :)

**Comment by sagemihir** [comment]
@edleeks87 I guess we just need a prop to Breadcrumbs component to have a different color for the darker backgrounds (something like a white or green), exactly how @emmswalker has mentioned in the above comment, currently the breadcrumbs has a green color but for the current page link gets merged into the dark background. Let us know if you need any more inputs 

Thanks

**Comment by emmswalker** [comment]
@clairedenning Can I ask why the breadcrumbs are moving away from the colour we use for actionable elements?

**Comment by clairedenning** [comment]
Hi @emmswalker. Not all actionable elements are green. We tend to keep green for the more prominent actions. Do you have a use-case where black (or white) won't work for you?

**Comment by emmswalker** [comment]
@clairedenning Just wondering if you could share the reasoning behind the change?

**Comment by clairedenning** [comment]
@emmswalker because we want to keep green for more prominent actions :)

**Comment by nicktitchmarsh** [comment]
So just to clarify here @clairedenning, we do need to add dark background support for breadcrumbs and they should be white? or should we follow the Link styling in our current version of the DS?

**Comment by clairedenning** [comment]
I think for the moment you can user the subtle link on dark (ie white link). We will create on-dark variant of breadcrumbs in the new figma library, and that will also address the colour of the slash between each breadcrumb. If you need a token for the slash right now, then replace yin with yang and that should work :)

**Comment by vasfsage** [comment]
We have created an inverse variant of the breadcrumbs: https://www.figma.com/design/Cie8BIDWKj4tEXCVGsen5A/Fusion-Components?m=auto&node-id=85924-10120&t=18tFwWG26Jc6RA9c-1 

This change will be coming with the release of the new design system in the near future.

**Comment by Parsium** [comment]
Thanks everyone 👍🏼  Sounds like we have the requirements to get started. I've raised a ticket on our side now:

**FE-6760**

**Comment by Parsium** [comment]
@clairedenning regarding the new green colour for the selected link, we won't be using this since it's part of the new FusionDS and not the frozen one. For now, we'll add support for a dark background similar to what we have for the Carbon `Link` component and use the existing green colour for the selected link.
