### ISSUE TITLE
Border appearing for buttons within MenuItem 

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6725]
### Description

v129.0.0 introduced a change to button styles where a button rendered within a MenuItem now has a border and additional padding.

https://github.com/Sage/carbon/assets/100130678/326e8ffd-4261-42fe-843f-f19a6871517b

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-wwtgen?file=src%2FApp.tsx

### JIRA ticket numbers (Sage only)

SBS-85541

### Carbon version

134.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6573
