### ISSUE TITLE
Notice Variant Toast gives Axe error on regions

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6729]
### Description

Axe report output:

Issue Description: Error: All page content should be contained by landmarks
Ensures all page content is contained by landmarks -https://dequeuniversity.com/rules/axe/4.8/region?application=AxeChrome

Element Location:
.Hlivg

To solve this issue, you need to…:
Some page content is not contained by landmarks

### Reproduction

https://carbon.sage.com/?path=/story/toast--notice

### JIRA ticket numbers (Sage only)

SBS-95481

### Carbon version

130.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
@tempertemper can we just check whether this is a false positive caused by the use of Portals here?

**Comment by edleeks87** [comment]
@tempertemper any thoughts on the above

**Comment by Parsium** [comment]
After discussing with @tempertemper, we noticed that `Toast` has no semantic meaning, just a <div> with text content. Since `Toast` is designed for status messages or alerts, adding a role of "status" or "alert" should address the semantic issue, which may also resolve the axe violation.

**Comment by Parsium** [comment]
FE-6655
