### ISSUE TITLE
Notice variant Toast breaks Pager buttons when it appears

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#6730]
### Description

Having a Table Pager at the bottom of the page and popping a Notice variant Toast blocks mouse clicks on the existing pager buttons.
Video attached to related JIRA ticket showing behaviour with detailed steps to replicate

### Reproduction

https://carbon.sage.com/?path=/story/toast--notice

### JIRA ticket numbers (Sage only)

SBS-95451

### Carbon version

130.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6576
