### ISSUE TITLE
[PopoverContainer] - Keeps opened when is out of focus

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#6734]
### Description

PopoverContainer keeps opened while loses the focus when contains a select.
I expect that it closes once it loses the focus.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-dxc9dk?file=src%2FApp.tsx

### Steps to reproduce

1. Press tab until the button that opens the PopoverContainer is focused.
2. Press enter
3. Press tab until the focus is out of the Popover 

### Carbon version

134.2.0

### Design tokens version

4.29.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6583

**Comment by sianford** [comment]
Fix implemented in FE-6905.
