### ISSUE TITLE
DialogFullScreen - size of header element

### ISSUE THREAD

**Issue by gusch** [Sage/carbon#6740]
### Description

If I use a StepFlow component in the header of a DialogFullScreen and the title used is very small, the progess indicator can't expand to the whole width.
In a standard Dialog, it takes all the space.
I would like the same behaviour.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-17vmoj?file=src%2FApp.tsx

### Carbon version

133.0.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Potential workaround

```
<Box maxWidth="calc(100vw - 100px)" width="100%">
  <StepFlow
     category="category"
     title="title"
     currentStep={1}
     totalSteps={6}
     showProgressIndicator
  />
</Box>

**Comment by edleeks87** [comment]
FE-6645
