### ISSUE TITLE
Card: focus indicator doesn't wrap full Card when onClick and height props are specifed

### ISSUE THREAD

**Issue by damienrobson-sage** [Sage/carbon#6741]
### Description

Spoke to @edleeks87 who informed me that the `height` prop is not passed to the underlying button when there’s an onClick also set. As shown, this leads to some interesting focus indicator outlines.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-8fzovy?file=src%2FApp.tsx

### Steps to reproduce

Tab onto a Card with `onClick` and `height` props defined

### Carbon version

125.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6584
