### ISSUE TITLE
Screenreader isn't reading ProgressTracker description

### ISSUE THREAD

**Issue by adamfsage** [Sage/carbon#6755]
### Description

I am using the progress tracker component as part of a custom component (see ticket SBS-89576)

The existing aria-labels that are by default on progress tracker shouldn't be there according to external discussion with 
the Accessibility team.

Screenshot below shows issue - screenreader is not reading the text but is instead reading the progress bar itself, which is undesirable

![image](https://github.com/Sage/carbon/assets/155455220/e351bcb0-0b7d-4ee1-92bc-65f66690508d)

Carbon example
<img width="1270" alt="image" src="https://github.com/Sage/carbon/assets/155455220/8161831d-a53c-4316-8cfa-661553fdcc28">

### Reproduction

https://carbon.sage.com/?path=/story/progress-tracker--size-small

### Steps to reproduce

(On carbon) Open Voiceover, select progress tracker component, then CTRL + OPTION + SHIFT + Right arrow key (Mac)

### JIRA ticket numbers (Sage only)

SBS-89576

### Suggested solution

Get rid of default-set aria-labels on component, set component to auto add description text to aria-label, but have that overridden by any custom aria-label set as a prop
### Carbon version

133.1.0 but works on latest storybook

### Design tokens version

4.34.0

### Relevant browsers

Chrome, Safari

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6653
