### ISSUE TITLE
Badge appears under MultiActionButton

### ISSUE THREAD

**Issue by ernon66** [Sage/carbon#6765]
### Description

Hello,

The Badge component interacts differently with a MultiActionButton than it does with a regular Button

With a Button the Badge appears correctly **over** it
With a MultiActionButton the Badge appears **under** it

![image](https://github.com/Sage/carbon/assets/109949759/186097d8-7727-444b-ba30-95bab5c9b3e5)

I think it should always appear over the component

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-2zetxs?file=src%2FApp.tsx

### Steps to reproduce

Use a Badge component with a MultiActionButton

### JIRA ticket numbers (Sage only)

SBS-99460

### Suggested solution

I have not found any workaround

### Carbon version

136.0.3

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Should be a simple fix:

```
<StyledBadgeWrapper>
      {renderCorrectBadge()}
      {children}
    </StyledBadgeWrapper>
```

needs to be

```
<StyledBadgeWrapper>
      {children}
      {renderCorrectBadge()}
    </StyledBadgeWrapper>
```

**Comment by DipperTheDan** [comment]
FE-6665
