### ISSUE TITLE
Progress tracker oversized by 2px when using 100% width

### ISSUE THREAD

**Issue by adamfsage** [Sage/carbon#6779]
### Description

I'm trying to set the progress tracker length property to '100%' so it dynamically sized to the box I'm adding it to, I expect this to look fine however the bar overruns by 2px when I do this:
![image](https://github.com/Sage/carbon/assets/155455220/a0f2c0f9-b27e-48c8-92aa-ce7e6919a746)

Looking at the carbon code it looks like the 1px border isn't being factored in when width is 100%.

### Reproduction

https://carbon.sage.com/?path=/story/progress-tracker--size-small

### Steps to reproduce

Inspect element on the progress bar, and toggle the width: 100% css property to see the length slightly change (2px difference)

### JIRA ticket numbers (Sage only)

SBS-89576

### Suggested solution

Adding box-sizing: border-box would make the border be included in the total width, this will affect the height of the bar however so that may need to be readjusted to correct for this

### Carbon version

135.1.1 but works on latest storybook

### Design tokens version

4.29.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
https://stackblitz.com/edit/parsium-carbon-starter-dcup5t?file=src%2FApp.tsx

**Comment by nicktitchmarsh** [comment]
FE-6672
