### ISSUE TITLE
Appear the green border around the Button by forcing :hover and :focus state

### ISSUE THREAD

**Issue by foxyd-sage** [Sage/carbon#6781]
### Description

The halo appears when to click and hold on Button or when use Tab for focus on the Button and after hover on it.
So the issue appear by forcing :hover and :focus on the same time.

![Screenshot 2024-06-14 at 09 32 03](https://github.com/Sage/carbon/assets/56251247/8a99e129-bc40-42dd-913f-5b3e7ca2eed9)

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-cwybez?file=src%2FApp.tsx

### Steps to reproduce

- Using "Tab" focus on the "Tertiary" button
- Hover on the "Tertiary" button while button has focus state

https://github.com/Sage/carbon/assets/148766647/ceea2d2b-15a2-45ea-ae6d-8be7b7503577

### JIRA ticket numbers (Sage only)

SBS-97305

### Carbon version

130.0.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@foxyd-sage, looking at the usage here. Button was never intended to be a child of the MenuItem component. Can we get on a call to look at the designs you are trying to implement and see if Menu needs to be updates to allow other styling options?

**Comment by foxyd-sage** [comment]
@nicktitchmarsh sure, I'm ready to call, but could we get someone from @Sage/sbc-skellig-squad-dev team, because the change could be in the theirs side ?
I noticed Alan Young about this issue

**Comment by edleeks87** [comment]
FE-6675
