### ISSUE TITLE
Contents of FlatTable visible behind header when inside a Drawer

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#6782]
### Description

I am using a `FlatTable` within a `Drawer` and the contents of the table are visible behind and beyond the table header. 

### Reproduction

https://stackblitz.com/edit/carbon-select-labelinline-f9yvku?file=src%2FApp.tsx

### Carbon version

130.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6674
