### ISSUE TITLE
MenuSegmentTitle Dose not render the correct color for full screen view

### ISSUE THREAD

**Issue by elvis-iacobescu-sage** [Sage/carbon#6789]
### Description

We are rendering dynamically a ScrollableBlock or a menuSegmentTitle. Both have variant="alternate" as a property.
the MenuItem rendered are rendered as children and have  variant="alternate" as a property.

The bug reproduces on small screens when the menu is in full screen.

Expected: the background colors for the menu items in menuSegmentTitle to be gray when the menu is in full-screen View.

Current:   only the title in menuSegmentTitle is gray, and the rest is black.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-viwky9?file=src%2Fmain.tsx

### Steps to reproduce

To reproduce:
open menu. (click the test button)

You will notice that the MenuSegmentTitle items **are not gray** .
if you click the menu item on top of the menuSementTitle you will switch to the scrollable block where the menu items are displayed properly

### JIRA ticket numbers (Sage only)

sbs-36740

### Carbon version

138.2.0

### Relevant browsers

Chrome

### Relevant OSs

Windows

### Additional context

In Stackblits seems that a padding is added for some reason on all li elements. it is not happening in carbon documentation or our application

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
FE-6679

**Comment by edleeks87** [comment]
FYI we're just waiting for a steer from UX/DS on this once we have that the ticket can be refined and pulled into sprint
