### ISSUE TITLE
Controlled MultiSelect component inside PopoverContainer re-renders in bad initial position

### ISSUE THREAD

**Issue by rawlmp** [Sage/carbon#6793]
### Description

We are rendering a controlled MultiSelect inside a PopoverContainer. When you add any option to the MultiSelect it seems it is re-rendered in position 0,0 and looks like flying from top-left screen corner

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-s6xtma?file=src%2FApp.tsx

### Steps to reproduce

Select any option in 2nd Select.

It works well sometimes on remove options but never on adding.

### Carbon version

134.1.0

### Relevant browsers

Chrome, Microsoft Edge, Other

### Relevant OSs

MacOS

### Additional context

- It's still happening in last carbon version 138.0.2

- In previous Carbon version from 134.1.0, (134.0.4) it works fine.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
FE-6678
