### ISSUE TITLE
ButtonToggleGroup: width does not adjust when children components start wrapping

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#6798]
### Description

I have a ButtonToggleGroup with 3 ButtonToggles. When I reduce the screen width, the button toggles start wrapping as expected. However, when the wrapping happens, the ButtonToggleGroup's width does not adjust which results in a blank whitespace as can be replicated in the StackBlitz provided.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-elnjtq?file=src%2FApp.tsx

### Steps to reproduce

Reduce the screen width so the button toggles start wrapping

### Carbon version

134.0.4

### Relevant browsers

Microsoft Edge

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
@ljemmo @harpalsingh , I feel like we should address this as part of a Carbon wide approach to responsiveness. This currently adheres to the DS designs so we need to review those designs
