### ISSUE TITLE
ButtonToggleGroup: button toggles with different text sizes do not wrap uniformly

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#6799]
### Description

Have 3 ButtonToggles with different text sizes and reduce the screen size resulting in the ButtonToggleGroup wrapping. It will be seen the button don't align uniformly as would be expected.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-4fgmqg?file=src%2FApp.tsx,package.json

### Steps to reproduce

Reduce the screen width so the button toggles start wrapping

### Carbon version

134.0.4

### Relevant browsers

Microsoft Edge

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
FE-6677
