### ISSUE TITLE
Bad style on current crumb when navigating insde

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#6808]
### Description

I am navigating in the breadcrumb, i expect to not have the big black bold underligne below my current page.
If i navigate a lot, i can have all my crumbs underligned with bold black underlignes
![image](https://github.com/Sage/carbon/assets/41692955/39658a9e-acf2-47b4-8bb3-877d4d627083)

For me case, i can do a workaround to refresh my whole component to clean the style (using a key on my component)

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-angxru?file=src%2FApp.tsx

### Steps to reproduce

Click on Path 2 for exemple
Click on Add crumb 

### Carbon version

140.1.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6683
