### ISSUE TITLE
Numeral Date does not submit Form on enter key

### ISSUE THREAD

**Issue by allan-sage** [Sage/carbon#6832]
### Description

Inside a form, when focused in Numeral Date field, it doesn't submit on enter key. I have asked in the accessibility channel and they say it should follow the usual field in form behaviour. In the Stackblitz template, I think the numeral date component should follow the behaviour of the textbox component on pressing the enter key when in the field, but it does not.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-u4sifn?file=src%2FApp.tsx

### Steps to reproduce

Focus on Numeral Date field (That is inside a form) and press Enter key

### Suggested solution

Follow standard component behaviour in forms, submit on enter

### Carbon version

138.2.0

### Design tokens version

4.35.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6699
