### ISSUE TITLE
Incorrect behaviour when a `MultiSelect` has multiple options with the same label

### ISSUE THREAD

**Issue by thedannygoodall** [Sage/carbon#6843]
### Description

When a `MultiSelect` contains multiple options in which some of them share identical text, it causes undesired behaviour. See the below video for an example of this. 

https://github.com/user-attachments/assets/1b9e2ed8-f787-43d5-8b07-99ce087e491c

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-elineo?file=src%2FApp.tsx

### Steps to reproduce

1. Create a `MultiSelect` component
2. Add `Option` children to this component, in which at least 2 contain duplicated text, and at least 1 contains non-duplicated text
3. Click the non-duplicated option, then the following 2 duplicated options
4. Try to delete the non-duplicated option

### Carbon version

141.0.1

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6718
