### ISSUE TITLE
[AdvancedColorPicker] - onBlur not being triggered the first time a new color is clicked

### ISSUE THREAD

**Issue by robinzigmond** [Sage/carbon#6850]
### Description

When changing the input value in AdvancedColorPicker by clicking a non-selected color, the onBlur callback should be triggered. But this does not happen the first time a change happens (it does on subsequent ones)

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-bigb4p?file=src%2FApp.tsx

### Steps to reproduce

Open the dialog with the picker in, click a non-red color, and note that there is no output in the console.
Subsequently clicking a new color fires the console message as expected.

### Carbon version

141.0.6

### Design tokens version

4.29.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

Initial investigation suggests the problem is to do with the setting of `isBlurBlocked` in the `handleMouseDown` function (https://stackblitz.com/edit/parsium-carbon-starter-bigb4p?file=src%2FApp.tsx), with the value incorrectly being `true` when the call fails. I do not know why this is happening specifically the first time, or why we are even blocking blur at all.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6707
