### ISSUE TITLE
[BatchSelection] children buttons still active when `hidden` props set

### ISSUE THREAD

**Issue by edleeks87** [Sage/carbon#6858]
### Description

When the `hidden` prop is passed to `BatchSelection` the children buttons are still clickable and have the cursor style indicating so

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-ztamfa?file=src%2FApp.tsx

### Steps to reproduce

Hover/click bottom right corner of red box in above repro

### Suggested solution

Change `opacity: 0` to `visibility: hidden`

### Carbon version

latest

### Design tokens version

4.32

### Relevant browsers

Firefox, Chrome, Safari, Microsoft Edge

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
6727
