### ISSUE TITLE
Allow configuration of minHeight and padding for TextArea component

### ISSUE THREAD

**Issue by harryharford** [Sage/carbon#6860]
### Description

Currently the TextArea component has hardcoded minHeight and padding values https://github.com/Sage/carbon/blob/master/src/components/textarea/textarea.style.ts. 

It is therefore not possible to use this component with only 1 row height, as it does not fit cleanly on a page that also includes TextBox components. 

### Suggested solution

Make the minHeight and padding values configurable and set the current values to defaults. 

### Alternatives

Using TextBox in this case is not suitable as the field needs to expand and needs to support carriage returns. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
Discussed with @ljemmo on slack, agreed that min-height can be configurable with the current set as default. There are plans to add some padding presets in but after discussing with @harryharford I don't think they need that right now so we can probably just update the min-height

**Comment by nicktitchmarsh** [comment]
FE-6726
