### ISSUE TITLE
Allow the width of a select dropdown (e.g. Filterable) to be wider than the original component. 

### ISSUE THREAD

**Issue by harryharford** [Sage/carbon#6861]
### Description

When implementing a select component, in this case Filterable - the length of the text for the options in the dropdown often far exceed the width of the control itself. We need to be able to set the dropdown width to be larger than that of the main select component. 

### Suggested solution

Allow the dropdown width to be configurable and unlock this so that the width can exceed that of the parent control. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Our ticket for rebuild of this component is FE-6311 if you want to link a task
