### ISSUE TITLE
Support overflow and padding props on FlexTileContainer to prevent focus state and shadow appearance being cut off. 

### ISSUE THREAD

**Issue by harryharford** [Sage/carbon#6868]
### Description

When using the FlexTileContainer component, the far left and far right of the container have the focus/shadow appearance cut off for the active field. 

In this specific implementation of the component, the divider elements are not needed, therefore 'overflow: hidden' is unnecessary for our use case. 

### Suggested solution

Allow overflow and padding props for the FlexTileContainer to allow the focus/shadow appearance to display fully without being trimmed. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
I believe space is tight in their layout so padding isn't a guaranteed fix, applying it on the cells would need to be done on every cell to be consistent vs on the container would mean they can just add it on the left and right etc

If we allow overflow to be customised they can avoid the following without needing padding, obviously if they need the divider they would need hidden set but in this scenario they don't

with overflow: hidden set
![image](https://github.com/user-attachments/assets/7f22cd8f-591f-4751-b6a1-bb63d24a6f1f)

with it off
![image](https://github.com/user-attachments/assets/4de12416-23c7-46f6-b1ac-cc3cc95017dd)

**Comment by nineteen88** [comment]
FE-6767
