### ISSUE TITLE
Label and switch vertical alignment do not match for https://carbon.sage.com/?path=/story/switch--with-label-inline

### ISSUE THREAD

**Issue by harryharford** [Sage/carbon#6869]
### Description

When using the switch with labelInline component (or labelInline and reversed), the vertical alignment is off between the label text and the switch itself. 

![image](https://github.com/user-attachments/assets/cb6d9a99-1012-4354-96c3-4f3b92a7eba2)

### Reproduction

https://carbon.sage.com/?path=/story/switch--with-label-inline

### Suggested solution

Adding a height prop resolves this so presumably a height adjustment is all that is needed on the component. 

### Carbon version

v141.2.1

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
The height of the internal slider panel is less than the main wrapper

**Comment by nicktitchmarsh** [comment]
FE-6374 has fixed this and due to be released
