### ISSUE TITLE
MenuItem padding not applied to correct element

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6889]
### Description

When assigning padding values to a clickable MenuItem, this padding is added to the span wrapping the button, which has its own 16px left/right padding.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-rb1szg?file=src%2FApp.tsx

### JIRA ticket numbers (Sage only)

SBS-100370

### Carbon version

141.4.4

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
Will be addressed in FE-6676
