### ISSUE TITLE
Allow date input to setup a custom  formattedValue

### ISSUE THREAD

**Issue by ritxi** [Sage/carbon#6930]
### Description

As a developer using Carbon I want to be able to define a custom `formattedValue` for date-input/date-range. The application I'm working on allows to setup prefered date format. It would be nice to be able pass this format to the date-input/date-range.

### Suggested solution

Add a prop to overide default smart behaviour based on locale.
```jsx
const [state, setState] = useState("04/04/2019");
  const setValue = (ev: DateChangeEvent) => {
    setState(ev.target.value.formattedValue); // 04-04-2019
  };
  return <DateInput label="Date" name="date-input" value={state} onChange={setValue} customFormat="DD-MM-yyyy" />;
```

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nineteen88** [comment]
FE-6797
