### ISSUE TITLE
Number of rows is not being applied to textarea

### ISSUE THREAD

**Issue by niamhmadden24** [Sage/carbon#6961]
### Description

I am adding a number of `rows` to a `textarea` however this is not making the `textarea` bigger

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-7zwgav?file=src%2FApp.tsx

### Carbon version

142.9.1

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
We think there is an issue using Rows and Expandable props together. 

FE-6810
