### ISSUE TITLE
[Loader] ‘Téléhargement’ instead of ‘Téléchargement’ when Reduce animation effects is activated

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#6971]
### Description

When Reduce animation effects is activated, on en french site, the loader component displays the following text ‘Téléhargement’ instead of ‘Téléchargement’.

### Reproduction

https://carbon.sage.com/?path=/docs/loader--docs&globals=locale:fr-FR

### Steps to reproduce

In the system settings, Accessibility menu, activate the ‘Reduce animations’ option.

### JIRA ticket numbers (Sage only)

SBS-109414

### Suggested solution

In the file `fr-fr.ts` file, change the text `Téléhargement` to `Téléchargement`.

### Carbon version

142.11.3

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6822
