### ISSUE TITLE
Select : Unexpected undefined -  Virtualizer - tanstack/react-virtual 

### ISSUE THREAD

**Issue by hagad** [Sage/carbon#6978]
### Description

I'm facing this issue randomly when I try to reach our Select lazy loading component (Which use FilterableSelect select component
It’s a known issue, and I believe it was fixed in https://github.com/TanStack/virtual/releases/tag/v3.6.0  
(https://github.com/tailwindlabs/headlessui/pull/3356)

### Reproduction

This issue is reproduced randomly.

### Suggested solution

Upgrade  @tanstack/react-virtual package 

### Carbon version

Latest

### Design tokens version

120.1.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

<img width="999" alt="Capture d’écran 2024-09-23 à 17 34 30" src="https://github.com/user-attachments/assets/07f1348d-f8b5-45cf-8495-795986e2fb45">

<img width="1038" alt="Capture d’écran 2024-09-23 à 17 34 54" src="https://github.com/user-attachments/assets/4e69b06e-fe1a-41c5-ba8e-133c296777dd">

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6823
