### ISSUE TITLE
Menu component has varying height with wrapping content

### ISSUE THREAD

**Issue by PaulSumner-Sage** [Sage/carbon#7000]
### Description

When a Menu has wrapping / different sized menu items on a smaller viewport the menu bar itself ends up with different heights. This can be seen on the default storyboard when the screen is made smaller

### Reproduction

https://carbon.sage.com/?path=/docs/menu--docs#default

### Steps to reproduce

Can be viewed in default Storyboard on a smaller viewport
https://carbon.sage.com/?path=/docs/menu--docs#default

### JIRA ticket numbers (Sage only)

SBS-110640

### Carbon version

142.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6798
