### ISSUE TITLE
MenuItem children and submenu props when empty string results in unexpected behaviour 

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#7010]
### Description

In the event that either menu item children or submenu props are undefined or empty strings, menu item breaks. 

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-7bebns?file=src%2FApp.tsx

### Steps to reproduce

The provided stackblitz demonstrates both issues. Setting `submenu` as an empty string results in the menu rendering in a bad state. A menu item with no children results in a crash when hovering over the navbar.

### JIRA ticket numbers (Sage only)

SBS-111182

### Carbon version

142.13.5

### Relevant browsers

Chrome, Microsoft Edge

### Relevant OSs

MacOS, Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
The first issue is the correct behaviour for MenuItem as it has an invariant that throws when both `icon` and `children` are [falsy](https://github.com/Sage/carbon/blob/94eb4657115233a08ba59de35abf3e9e2d1fb4fd/src/components/menu/menu-item/menu-item.component.tsx#L124)

The second part will be addressed as part of FE-6798
