### ISSUE TITLE
[Message] - Icon does not provide a text for screen readers 

### ISSUE THREAD

**Issue by MarcServat** [Sage/carbon#7027]
### Description

Given the Message component with an icon
When using screen readers
Then only the text is read
And the icon has no effect whatsoever

### Reproduction

https://carbon.sage.com/?path=/story/message--with-focus

### Steps to reproduce

1. Open the carbon storybook link provided
2. Turn on the voiceover (cmd+F5 for macos)
3. The message text is read, however not the icon.

### Carbon version

142.13.0

### Design tokens version

4.34.0

### Relevant browsers

Chrome, Safari

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6871
