### ISSUE TITLE
Adding margin support to FlexTileCell to ensure Button focus isn't cut off at smallest screen size

### ISSUE THREAD

**Issue by amieedwards-sage** [Sage/carbon#7031]
### Description

When nesting a `<Button>` inside of a `<FlexTileCell>` with a  `<FlexTileDivider>` at a smaller screen size (320px) the focus indicator on the `<Button>` element is being cut off.
This feature request is to be able to align the Button including it's focus inside of the Tile content, without using additional padding. 

![Screenshot 2024-10-23 at 10 25 46](https://github.com/user-attachments/assets/09b6cad0-0a36-4bc9-a90c-a9fcde38088c)

### Suggested solution

Desired output: 
![Screenshot 2024-10-23 at 10 31 14](https://github.com/user-attachments/assets/cdc1f3e2-764e-4bca-b9c7-7a2bd97cf458)

### Demo URL

https://stackblitz.com/edit/parsium-carbon-starter-udg9rc?file=src%2FApp.tsx

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6879
