### ISSUE TITLE
Sidebar content out of screen when max zoom in

### ISSUE THREAD

**Issue by Arkalex** [Sage/carbon#7035]
### Description

When zooming in with a sidebar open, the content is cut off

### Reproduction

https://carbon.sage.com/?path=/docs/sidebar--docs

### Steps to reproduce

1. Open sidebar
2. Zoom in

### JIRA ticket numbers (Sage only)

SBS-112968

### Carbon version

144.0.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6880
