### ISSUE TITLE
Sidebars label tags incorrect element

### ISSUE THREAD

**Issue by hrrcox** [Sage/carbon#7053]
### Description

When using a screen reader, sidebars are read out as 'Sidebar header Close'. This seems to be because the aria-labelledby targets the id on the sidebar header and not the heading itself. I would expect the sidebar only to be labelled by the heading.

### Reproduction

https://carbon.sage.com/?path=/docs/sidebar--docs#with-header

### Steps to reproduce

Open dialog with screen reader

### Suggested solution

Target the sidebar heading rather than the sidebar header

### Carbon version

144.4.0

### Relevant browsers

Chrome, Safari

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6891
