### ISSUE TITLE
Select: aria-describedby does not get added to the combobox input element

### ISSUE THREAD

**Issue by kohli-pratik-sage** [Sage/carbon#7057]
### Description

When using the `aria-describedby` prop provided for the Select component, it does not get applied to the combobox input component, it instead gets applied to the subsequent span element that has the "Please select" placeholder text.

This is a incorrect behaviour as the expectation is for the prop to be applied to the intended component. This is required for a accessibility issue fix.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-uduhy9?file=src%2FApp.tsx

### Steps to reproduce

Inspect the Select component in the StackBlitz environment shared, you will see the aria-label is applied to the combobox input element as expected but the aria-describedby is not.

### Carbon version

142.9.1

### Design tokens version

4.34.0

### Relevant browsers

Microsoft Edge

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-6889
