### ISSUE TITLE
MultiSelect when openOnFocus, the arrow button does not work correctly

### ISSUE THREAD

**Issue by liambellsage** [Sage/carbon#7065]
### Description

Render a MultiSelect in openOnFocus mode. When the dropdown is not rendered, click the arrow button. The dropdown will open and then immediately close

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-gx22m8

### Carbon version

144.5.0

### Relevant browsers

Chrome

### Relevant OSs

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nuria1110** [comment]
FE-6900
