### ISSUE TITLE
The TAB key sequense is lose when it is used in a Popover component with Radio buttons child

### ISSUE THREAD

**Issue by EstebanGoldMuros** [Sage/carbon#7067]
### Description

When I move using the TAB key into a Popover component the navigation jump to the View site information of the browser (side to the URL)

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-igqxxt?file=src%2FApp.tsx

### Steps to reproduce

Press `TAB` key until `With Radio children` button
Press `ENTER`
Press `TAB` key until the last element of the list
Press `TAB` key

### JIRA ticket numbers (Sage only)

SBS-113991

### Carbon version

142.13.5

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nuria1110** [comment]
@tempertemper Checking this is expected behaviour as we believe keyboard navigation within a RadioButtonGroup should be done with arrow keys and Tab should move onto the next focusable element?

**Comment by nuria1110** [comment]
FE-6905
