### ISSUE TITLE
Invalid prop warning, despite it matching docs

### ISSUE THREAD

**Issue by thedannygoodall** [Sage/carbon#7069]
### Description

I am using a `Box` component and the `gridColumn` property. Inside the console in developer tools in a browser, I receive the below warning...

> Warning: Failed prop type: Invalid prop `gridColumn` supplied to `Box`, expected one of type [object].

This is using the same prop that is used inside the Carbon docs...

![Screenshot 2024-11-11 at 10 12 55](https://github.com/user-attachments/assets/e003b2e2-eaab-4ab6-b814-5e1a0a95b2e0)

This below video demonstrates the issue

https://github.com/user-attachments/assets/b152d481-0845-49dc-afb7-8941cc0e7597

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-f4yane?file=src%2FApp.tsx

### Steps to reproduce

1. Create a `Box` component
2. Apply the `gridColumn` property

### Carbon version

144.1.1

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

- This may also apply to other grid related properties on this component, I haven't checked. 
- This also appears when setting the prop to `gridColumn={ '2 / 5' }`

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nuria1110** [comment]
FE-6898
