### ISSUE TITLE
Dialog is re-added to the DOM after opening Vertical Menu

### ISSUE THREAD

**Issue by rawlmp** [Sage/carbon#7073]
### Description

At some point we need to show a modal to prevent navigation before saving changes but the modal shown is colliding with Vertical Menu in mobile devices after clicking a Navigation Item.

It seems the Dialog component is re-added to the DOM after opening Vertical Menu, staying in top and blocking any user action.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-kbwisw?file=src%2FApp.tsx

### Steps to reproduce

Info is provided in the Stackblitz example

### JIRA ticket numbers (Sage only)

SBS-114293

### Carbon version

141.0.8

### Design tokens version

4.34.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6908
