### ISSUE TITLE
Full screen menu component with max-width set has extra top and bottom padding

### ISSUE THREAD

**Issue by szeyingyau** [Sage/carbon#7078]
### Description

When a menu has a href and max-width set onto it, there's extra top and bottom padding added to the menu item

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-lxdwbp?file=src%2FApp.tsx

### JIRA ticket numbers (Sage only)

SBS-115109

### Carbon version

144.0.0

### Design tokens version

4.29.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-6909

**Comment by szeyingyau** [comment]
@nicktitchmarsh this is because we have the `maxWidth` being re-used in both the `Menu` and the `MenuFullScreen` components
