### ISSUE TITLE
Dialog: provide a prop to opt out of the default behaviour of focus returning to the triggering button

### ISSUE THREAD

**Issue by amieedwards-sage** [Sage/carbon#7085]
### Description

I want to be able to override the default focus behaviour of the Dialog on close, to provide a better experience for the user. 

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-8kzldp?file=src%2FApp.tsx

### Steps to reproduce

- Open voiceover
- Navigate to `Open dialog` button and click it
- Close Dialog
- Focus is returned back to the button
- Aria-live section is not read out as expected

### Carbon version

144.9.2

### Design tokens version

4.35.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-7005
