### ISSUE TITLE
Draggable Component Enhancements

### ISSUE THREAD

**Issue by jordanware** [Sage/carbon#7089]
### Description

As a developer using carbon i want the ability to have the draggable icon to the left hand side of the component so that the actions button containing the Move Up, Move Down, Move to Top and Move to Bottom buttons can be aded to the very right hand side. 

### Suggested solution

It appears desired functionality is already possible. Styling changes required.

https://github.com/user-attachments/assets/f694a0e1-c303-4ee2-bc0a-a61bea0263bc

### Additional context

Spoken with Ed on this issue already. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-7003
