### ISSUE TITLE
Sidebar header cannot be 100% width

### ISSUE THREAD

**Issue by liambellsage** [Sage/carbon#7090]
### Description

A recent bug fix in 144.9.1 prevent the sidebar header component from being 100% width when the sidebar also has an onCancel method provided

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-unabsu

### Steps to reproduce

Create a sidebar, add a header component with width:100% and an onCancel method
The header component will not be the width of the sidebar

### Suggested solution

Add width:100% to the div that contains the header

### Carbon version

144.9.2

### Relevant browsers

Chrome

### Relevant OSs

Windows

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by Parsium** [comment]
FE-7008
