### ISSUE TITLE
Custom colour override in Tile highlight variant.

### ISSUE THREAD

**Issue by JohnOxleySage** [Sage/carbon#7092]
### Description

Using the tile component I would like to be able to specify a custom colour for the Tile highlight border. We need this so that we can have enough different colour options so we can correlate a tile to each bar in a bar chart. 

### Suggested solution

Have the highlightVariant colour accept a custom colour rather than just preset strings. 

### Alternatives

Currently we're using Info and Neutral but they're too close in terms of colour so they cannot be differentiated easily. 

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by ljemmo** [comment]
@JohnOxleySage usually we don't encourage tile to have any interactive state such as hover as its meant to be a 'static' component. Whereas card is the component that can be used for interactive journeys. Do you have a design that you can share with me so that i can fully understand the usecase?

**Comment by JohnOxleySage** [comment]
@ljemmo Here's a screenshot of the design we've received:
<img width="838" alt="Screenshot 2024-11-26 at 16 42 43" src="https://github.com/user-attachments/assets/2d06f174-bb67-4b8b-8703-75e2aad42220">
And here's how I've got it looking atm with Info and Neutral:
<img width="469" alt="Screenshot 2024-11-26 at 16 43 46" src="https://github.com/user-attachments/assets/8b095ccb-2476-40d5-8ecd-e5cde1781f25">

**Comment by ljemmo** [comment]
@JohnOxleySage Ah i see, sorry i misunderstood and thought you were wanting to do something with a hover state. Geting my wires crossed with another topic i think.

I do wonder if using a tile border is the correct approach here as the radius looks incorrect based on your original design. Would it be better for carbon to support a keyline or create a new component called 'graph legend' or 'graph key' to achieve your look and feel. @edleeks87  thoughts?

We also have this type of key requested for the Copilot project

**Comment by tomdavies73** [comment]
@ljemmo would this be something that could be added to the design system? Or something we could receive proper designs for first, we would be apprehensive about adding anything to Carbon without a proper source of truth.

I'd also be apprehensive about adding a completely new component for this, I'm sure we'd be able to find away to provide this functionality with one of our current components with the addition of a prop. 

Alternatively, @JohnOxleySage could this design not be achieved with a carbon component that currently exists, opposed to building it for this specific design.

**Comment by ljemmo** [comment]
@tomdavies73 we have on our radar data visualisation components but this would likely be picked up in Q2 or Q3. There is one example of a building block / sub component here which you could build from but i'd recommend waiting until these components become more 'stable': https://www.figma.com/design/l4IeSmZNfAW1Y27OmhBSJW/frozen-theme-fixes?node-id=81150-475684&t=t2ReL9l6GvP0hRXa-4
