### ISSUE TITLE
`backgroundColor` has no effect on DismissibleBox

### ISSUE THREAD

**Issue by nokSage** [Sage/carbon#7108]
### Description

The `backgroundColor` prop has no effect on `DismissibleBox`. It looks like that it is accidentally exposed because normally one would prefer to use the `variant` prop to control the background colour instead.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-2jcuzf?file=src%2FApp.tsx

### Suggested solution

Remove `backgroundColor` from TS props definition and documentation for the `DismissibleBox` component

### Carbon version

144.9.3

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by tomdavies73** [comment]
FE-7016
