### ISSUE TITLE
submenu overflow on Safari

### ISSUE THREAD

**Issue by robinzigmond** [Sage/carbon#7112]
### Description

When a Menu is rendered with a Submenu and various width-related props provided, and the width of the submenu items is greater than that of the parent item, on Chrome (and Firefox) this renders correctly with the submenu the appropriate width 
![image](https://github.com/user-attachments/assets/4e803e49-8592-4b7b-a303-38d6fe7f89dd)

On Safari, the same is rendered only as wide as the parent item, with horizontal overflow:
![image](https://github.com/user-attachments/assets/579a7079-5e81-4e27-8d1e-e5cff16057cb)

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-nqzjqy?file=src%2FApp.tsx%3AL5

### Carbon version

144.9.2

### Relevant browsers

Safari

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
FE-7020
