### ISSUE TITLE
[MultiActionButton] The icons not aligned with the action label

### ISSUE THREAD

**Issue by arvig33** [Sage/carbon#7117]
### Description

Since version 144.9.11, we’ve had problems with the MultiActionButton component. We have icons on the label actions. If the  MultiActionButton label is smaller than the action labels, the icon is displayed above the linked label.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-c192jb

### Carbon version

144.13.0

### Design tokens version

4.35.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by nicktitchmarsh** [comment]
Hi @arvig33, this can be resolved by adding noWrap prop onto the child buttons. Please let us know if this solves your issue.

**Comment by arvig33** [comment]
Hi @nicktitchmarsh, yes that solved the problem.
