### ISSUE TITLE
MultiActionButton is not displaying well when inside an Accordion

### ISSUE THREAD

**Issue by maduv** [Sage/carbon#7134]
### Description

The list of entries in MultiActionButton control is not showing the whole list when it is inside a Accordion.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-b7l4awhr?file=src%2FApp.tsx

### JIRA ticket numbers (Sage only)

SBS-118501

### Carbon version

144.22.1

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-7032
