### ISSUE TITLE
New 'Lato' font has slightly broken field label vertical centring

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#748]
Please see the screen shot:

![screen shot 2016-09-21 at 12 48 57](https://cloud.githubusercontent.com/assets/10499070/18709815/ea1e3af6-7ff9-11e6-82a6-993112580579.png)

The labels on the fields are a few pixels too low

**Comment by andrewjtait** [comment]
UX have completed several sweeps to clean the UI up now with this included.
