### ISSUE TITLE
Investigate covering groups of related elements with feature style specs

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#770]
An example of this is the `Form` component which contains a set of inputs but needs to behave differently due to the state of those inputs.

In particular the display of only one message per form even if there are more than one error / warning. This can be tested at a unit level but not at the Form level.

Should a feature style spec exist, either as part of the form spec or on it's own that tests this sort of functionality?

**Comment by andrewjtait** [comment]
Looking at the Form spec, is this functionality not already covered? For example it tests that a form cannot be submitted with textboxes that have errors, and it tests that the error count is changed with textboxes that have errors etc

**Comment by edleeks87** [comment]
We have introduced these features through a fixtures testbed and cypress regression testing
