### ISSUE TITLE
Language Packs / Multi Language

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#789]
Carbon uses I18n adding the ability for multiple languages however there is no default provided by Carbon even for `en`

We also need to think about defining locales for moment js

**Comment by toni-leigh** [comment]
Comment taken from my linked PR

## Description

* This is the best I can do in 45 mins
* Translations are stored in a separate file inside the component
* This file contains a bit of logic (in the example, there are pluralisations based on data values)
* I18n is used for the locale only
* Tests still pass so the default translations is still falling through correctly (note the way the tests don't rely on I18n itself to pass, they haven't changed for this spike - except for `fdescribe`)

### Technical Problems

* logic in the translations file, ideally this would be reduced to help those translating, who might not be technical, to focus on the task - could this be abstracted so translations inherits from something? Perhaps the I18n could live there and things like pluralisation could be handled at this level?
* mechanism for getting the default - I tried a `switch` but the resulting code was more complex

### Benefits

* Only the translations an app needs are loaded
* Translation files are easier to edit
* There's no need to define simple translations just to use a Carbon based app in a given language - you only need to define translations for your own components
* Translation effort is open source
* Potential to remove I18n dependency (and dependency on gems etc.)
* Simplification of component files

### Drawbacks

* Multiple files to edit for translators
* Possible duplicated logic or re-invention of I18n

**Comment by edleeks87** [comment]
We are proposing to introduce https://i18next.com, and we should also provide default translations as part of this
