### ISSUE TITLE
Generic Validations/Warnings/Notifications

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#852]
The code between validations and warnings is highly duplicated. ⚠️  🔔  

A new system should be created that allows a generic validation/warning/notification to be shown which would be set via a theme or as property which would determine the color, icon and message that it shows on an input. It should also have a flag that stops actions such as submitting a form.

**Comment by ianforster-sage** [comment]
Carbon has Alert, Toast and Flash components in line with the DLS, and the roadmap includes delegation of validation to Formik.
