### ISSUE TITLE
Positioning of icons, tooltips and error messages

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#857]
In the library, css `position` properties, negative values, fixed pixels and javascript calculations are used to position hover messages, icons, errors, warnings and such like

It's suggested that more robust methods of centring and positioning are used, possibly including `flex` in order to avoid problems where a design changes and various different positions need to be changed to in order to accommodate the new designs.

This may also include the abstraction of certain elements into new components.

**Comment by andrewjtait** [comment]
We have started applying flex to elements in the library, seems like we should now close this issue, and raise new issues for any remaining values we find in the future as technical debt.
