### ISSUE TITLE
Handle Content Change should not be called from outside validation class

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#858]
There are now a few use cases where the input validations handle content change is being called externally. I believe this is because the decorated method only get called on a keydown or blur event (this will need to be checked)

Instead we need to check if the content has actually changed in the willReceiveProps lifecycle or similar function

**Comment by ianforster-sage** [comment]
Carbon's form and validation functionality will be replaced with Formik 2.0.
https://github.com/Sage/carbon/blob/master/rfcs/text/formik.md
