### ISSUE TITLE
Message wrapper

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#877]
All three of flash, message and toast follow the same pattern of having an icon on the left, information in the middle and a close button on the right.

In order to position these elements pretty much the same css is used across all three. This is more apparent now I've refactored the css to use `flex`.

Propose a new functional component for wrapping messages and handling the css for the layout. This component might actually cover the message component entirely rendering it un-needed. Then the animation side only of flash and toast can be handled in the components as they are.

**Comment by ianforster-sage** [comment]
These components have now been restyled to follow the latest DLS with CSS-in-JS provided by styled-components
