### ISSUE TITLE
Context & Law Of Demeter

### ISSUE THREAD

**Issue by abramin** [Sage/carbon#890]
Currently components which contain inputs have caused undesired dependencies to appear.
The various input decorators have too much knowledge of components they appear in (e.g. Form, Tabs).  e.g https://github.com/Sage/carbon/blob/master/src/utils/decorators/input-validation/input-validation.js#L257-L265

Ideally the input decorators should have no knowledge of parent components. Instead, they should  interact with a generic context object. The context object (e.g. the form or tab) should handle specific behaviour itself.

**Comment by jamime** [comment]
Closing, this issue is around decorators, a pattern that we're trying to remove in Carbon.
