### ISSUE TITLE
Table calls setState on ActionToolbar

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#906]
ActionToobar holds the total rows and selected rows in its own state. https://github.com/Sage/carbon/blob/master/src/components/action-toolbar/action-toolbar.js#L56

It then has setState called explicitly by its parent component (Table) https://github.com/Sage/carbon/blob/master/src/components/table/table.js#L524

This seems wrong. Where table is calling setState on the actionToolbar it should be calling setState on itself and passing this down to the action toolbar via props.

**Comment by ianforster-sage** [comment]
The ActionToolbar has been rewritten to comply with the DLS.
