### ISSUE TITLE
Carbon content needs to work without content

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#922]
Situations can arise when the body of a `<Content />` item may be blank, perhaps conditionally, and in such cases the component should still render.

We've seen two instances of devs using `<div />` to pad out `<Content />` in order that the title still renders the same as their full components in some consistent interface.

Two options exist: to refactor out the title element or to allow rendering without content.

This real world example demonstrates:

```
<Content
  label={ I18n.t('direct_payment.tan_confirmation.amount') }
  title={ I18n.toCurrency(this.props.amount) }
>
  <div>{ /* Content tag must not be empty, otherwise it is not shown. */}</div>
</Content>
```

**Comment by ianforster-sage** [comment]
Confirmed this behaviour still exists in v14.1.0. Need to investigate further to understand if a fix is required.

**Comment by ianforster-sage** [comment]
@benwilsonsage Please could you review this issue and advise on if/how you would like this to be handled.
