### ISSUE TITLE
Conceptualising BEM as DOM element identifiers

### ISSUE THREAD

**Issue by toni-leigh** [Sage/carbon#923]
Conceptually I see BEM classes as identifiers of a unique type of DOM element that happens to be commonly used for attaching css properties to but shouldn't be seen as just that. As the element doesn't change purpose, i.e. a `Button` will always be a button, a `ContentAddressDetailsPanel` will always be a .... and so on, can the class itself be viewed as (almost) immutable.

I wonder if our best practice ought to reflect this?

Practically, it would mean we could hang all sorts of things off those identifiers and also be sure they would be extremely unlikely to change, which while it may appear to be mixing concerns isn't really, it's just anchoring all the bits associated with a component to a common identifier (a bit like the same foreign key might be used to identify a database item from the perspective of many different app concerns, or a bit like componentising the folder structure in Carbon).

And, it would mean it would be OK to advise adding a class to an HTML element so tests could be hooked in

**Comment by andrewjtait** [comment]
Closing this as we now promote using `data` attributes for element and component identifiers.

**Comment by toni-leigh** [comment]
👍 however, there are some quirks with Enzyme, you need to get the `Component` to get the `props()` whereas the `data-*` tags get the HTML.

To fix this, I've been using the component tag `find(Component)` as an alternative - as Enzyme is tightly tied to React and the component names are as stable as the data-tags within that context, I think this is a viable alternative.
