### ISSUE TITLE
Styling for `:active` and `:visited` in the `Link` component

### ISSUE THREAD

**Issue by toni-sharpe** [Sage/carbon#924]
These seem to be missing, which has led to an over-ride in an app

We should set default styles on these pseudo elements in Carbon

This is mostly for UX reasons, anything that is a link should have a visited state

**Comment by andrewjtait** [comment]
Related to https://github.com/Sage/carbon/issues/334

**Comment by toni-leigh** [comment]
Propose re-opening this @andrewjtait it's related, but different - while I mention the over-rides there's also a UX issue here that should be addressed, the user should be able to see from Carbon which links they've already visited and that funcitonality is not currently handled by Link (it seems only Table has a `:visited` style)

**Comment by andrewjtait** [comment]
Requires some input from UX on designs for this.

**Comment by toni-leigh** [comment]
For UX consideration is that this will be case by case and should probably apply to anything clickable

**Comment by ianforster-sage** [comment]
Link component now complies with DLS styling.
