### ISSUE TITLE
Table calls setState on Row

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#929]
I think there is an issue here on how we are reaching into the row and calling setState on it. In theory setState should be internal to a component and setState would be a private function. If we want to call setState on it we should be doing it through a public API in this case a selectRow and deselectRow that would be present on the row component. This means that if the internal implementation of how a row is selected changes we wouldn't need to change table as well.

However even providing a public API isn't very react. React should work simply by passing props down to its children so in theory Table would track an object or array of selected rows and that would be passed to each child (which it does if you want to track state outside of the table component). This has been done because we wanted a way of having the row selection out the box without the developer having to track the selected state.

There may be some alternate ways of doing this without calling a method and if we must call a method I think this should be done through some kind of context if possible.

**Comment by ianforster-sage** [comment]
fixed in PR #928
