### ISSUE TITLE
Components wrapping other components should use componentXProps

### ISSUE THREAD

**Issue by SeanArmstrong** [Sage/carbon#949]
E.g. `ShowEditPod` contains a `Form` and therefore tries to apply all of the possible form props to the form nested within it. The current implementation means that whenever a new prop is added to form you will have to add it to the pod.

It would be alot better if the ShowEditPod accepted a `formProps` prop that applies to the form. This may include children. The ShowEditPod also contains a `Pod` so it should also have a `podProps`.

**Comment by andrewjtait** [comment]
Passing a hash of props could be dangerous for breaking changes, as it'll be harder for developers to catch these in their applications. I think I'd prefer more control of composition of components, so they can pass full components in if they want to do something custom.

**Comment by ianforster-sage** [comment]
We're now following the principles of atomic design and composition as per Andrew's comment.
